### PR TITLE
Update i2c driver to cpp

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/56)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[libs/base/os_base.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKEYQsBGiclNEmrzav:-KYKEYQsDBNDoCDz1hNU:byg0n1v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/os_base.cpp#L5)):*
> ```cpp
> TakeSemaphore::TakeSemaphore(OSSemaphoreHandle semaphore, OSTaskTimeSpan timeout) : _semaphore(semaphore)
> {
>     if (OS_RESULT_SUCCEEDED(System::TakeSemaphore(this->_semaphore, timeout)))
> ```

what about this: 
```
this->_taken = OS_RESULT_SUCCEEDED(System::TakeSemaphore(this->_semaphore, timeout);
```

---

*[libs/base/Include/base/os.h, line 493 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKEs2D5QtQE5uOORmq:-KYKEs2DA0lQGNR1CNVh:bkve1va) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L493)):*
> ```objc
>  * @code
>  * {
>  * 	TakeSemaphore lock(this->_sem);
> ```

I'd prefer more less specific name in this case. How about just "Lock"?

---

*[libs/base/Include/base/os.h, line 505 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKF4sz6Mn2sQXsCXuG:-KYKF4sz5AuUZgQX2nOL:b-3k9rnd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L505)):*
> ```objc
>  * @endcode
>  */
> class TakeSemaphore
> ```

Provide valid move constructor/assignment operators (it is possible)  or disable them explicitly

---

*[libs/base/Include/base/os.h, line 526 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKHBJL8TGTvoAPsEo3:-KYKHBJL8OZ4PJK84tnn:bhj8zs1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L526)):*
> ```objc
>     bool operator()();
> 
>     TakeSemaphore(const TakeSemaphore&) = delete;
> ```

move to private section.

---

*[libs/base/Include/base/os.h, line 538 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKGRgM0AICe-yNvlVy:-KYKGRgMCnv4lIZvkkzk:b-7q1808) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L538)):*
> ```objc
>  * @brief RTOS queue wrapper
>  */
> template <typename Element, std::size_t Capacity> class Queue
> ```

This class will not work for any complex type. Add static assertion that ensures that no one tries to use non pod/integral types. 

---

*[libs/base/Include/base/os.h, line 553 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKGv1c6QPe7CAxLruH:-KYKGv1c08vrEQyWSg0n:bol9fb1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L553)):*
> ```objc
>      * @return Operation result
>      */
>     OSResult Push(Element* element, OSTaskTimeSpan timeout);
> ```

Prefer const reference instead of pointers. So there is no need to worry about nullptr parameters 

---

*[libs/base/Include/base/os.h, line 560 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKH3LGDTNPGBmZAS8c:-KYKH3LGCYbjog-mw-E1:b-f8uszh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L560)):*
> ```objc
>      * @return Operation result
>      */
>     OSResult PushISR(Element* element);
> ```

Prefer const reference instead of pointers. So there is no need to worry about nullptr parameters

---

*[libs/base/Include/base/os.h, line 568 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKH4Aa3TDp0P9Bs7KB:-KYKH4Aa49b8r2bGJVdS:b37kqcm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L568)):*
> ```objc
>      * @return Operation result
>      */
>     OSResult Pop(Element* element, OSTaskTimeSpan timeout);
> ```

Prefer reference instead of pointers. So there is no need to worry about nullptr parameters

---

*[libs/drivers/i2c/i2c.cpp, line 107 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKIYc229ymQsdLECDG:-KYKIYc29LYZgCf7YxWd:b-y2l38s) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/i2c.cpp#L107)):*
> ```cpp
>     CMU_Clock_TypeDef clock,
>     IRQn_Type irq)
> {
> ```

use initializer list.

---

*[libs/drivers/i2c/i2c.cpp, line 150 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKUT2g4BvsSl9Ow1ag:-KYKUT2gBwEMNtVGtQLT:bkjtsph) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/i2c.cpp#L150)):*
> ```cpp
>     if (status == i2cTransferInProgress)
>     {
>         return;
> ```

shouldn't the 
```
System::EndSwitchingISR();
```
be called here as well?

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKUfVf2rr9cXSWyzOr:-KYKUfVf-a4WNtvbvIvL:bdanow9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/Include/i2c/i2c.h#L1)):*
> ```objc
> #ifndef SRC_DRIVERS_I2C_H_
> ```

I'd separate public interface a.k.a II2cBus & enumerators from the implementation (low level bus, fallback bus etc.)

---

*[src/obc.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKN5kH-x7rXNXiD4hq:-KYKN5kHBA-UWbCjVrBz:bsaac3a) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/src/obc.cpp#L6)):*
> ```cpp
> OBC::OBC()
>     : //
>       Hardware(),
> ```

redundant, default constructor will be called anyway

---

*[unit_tests/I2C/I2CMock.cpp, line 3 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKRqd7--rXrg_JtrP0:-KYKRqd7Ec71YWpXZB-C:bx9w2nc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/unit_tests/I2C/I2CMock.cpp#L3)):*
> ```cpp
> #include "I2CMock.hpp"
> 
> I2CBusMock::I2CBusMock()
> ```

this constructor can be entirely removed

---

*[unit_tests/I2C/I2CMock.hpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKRwr_EE88e3MfpvWc:-KYKRwr_5DfmPXz1slfq:b56spgu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/unit_tests/I2C/I2CMock.hpp#L23)):*
> ```cpp
>             ));
> 
>     decltype(auto) ExpectWriteCommand(const drivers::i2c::I2CAddress address, uint8_t command)
> ```

for consistency reason I would provide also function for read command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[doc/groups.h, line 2 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKWO7a2WbIG_STfCXA:-KYKWO7a5blJB2rdtKvZ:b2x7dcv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/doc/groups.h#L2)):*
> ```objc
> /**
>  * @defgroup perhipheral_drivers Peripheral drivers
> ```

I wouldn't mind more detailed information what this group contains.

---

*[doc/groups.h, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKWTcM-HLf_jQ5EvE5:-KYKWTcM2ix2wGmfHm5Z:b2x7dcv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/doc/groups.h#L8)):*
> ```objc
> 
> /**
>  * @defgroup device_drivers Device drivers
> ```

I wouldn't mind more detailed information what this group contains.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56)*

**Comment by Novakov** [comment]
Review status: 30 of 52 files reviewed at latest revision, 16 unresolved discussions.

---

*[doc/groups.h, line 2 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKWO7a2WbIG_STfCXA:-KYKi9EW3VSLz-EBeiCE:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/doc/groups.h#L2)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I wouldn't mind more detailed information what this group contains.
</blockquote></details>

Done.

---

*[doc/groups.h, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKWTcM-HLf_jQ5EvE5:-KYKi9e_0YRwi4Y0bdW-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/doc/groups.h#L8)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I wouldn't mind more detailed information what this group contains.
</blockquote></details>

Done.

---

*[libs/base/os_base.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKEYQsBGiclNEmrzav:-KYKbHgI1sqBV3MIYSvY:b-q1gbse) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/os_base.cpp#L5)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what about this: 
```
this->_taken = OS_RESULT_SUCCEEDED(System::TakeSemaphore(this->_semaphore, timeout);
```
</blockquote></details>

What I was thinking about when I wrote that if...

---

*[libs/base/Include/base/os.h, line 493 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKEs2D5QtQE5uOORmq:-KYKhLRgEyoq8G8jnRN7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L493)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd prefer more less specific name in this case. How about just "Lock"?
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 505 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKF4sz6Mn2sQXsCXuG:-KYKcBfP5ES7X2lrEgjx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L505)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Provide valid move constructor/assignment operators (it is possible)  or disable them explicitly
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 526 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKHBJL8TGTvoAPsEo3:-KYKcCMC4INMpXxNOo-Y:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L526)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

move to private section.
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 538 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKGRgM0AICe-yNvlVy:-KYKhMi95T97ftZuZmex:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L538)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This class will not work for any complex type. Add static assertion that ensures that no one tries to use non pod/integral types. 
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 553 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKGv1c6QPe7CAxLruH:-KYKflM48MarqgoRvQet:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L553)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Prefer const reference instead of pointers. So there is no need to worry about nullptr parameters 
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 560 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKH3LGDTNPGBmZAS8c:-KYKfluj6pK5e4YBfPvj:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L560)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Prefer const reference instead of pointers. So there is no need to worry about nullptr parameters
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 568 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKH4Aa3TDp0P9Bs7KB:-KYKfma1-_ZOsFcO0f6u:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/base/Include/base/os.h#L568)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Prefer reference instead of pointers. So there is no need to worry about nullptr parameters
</blockquote></details>

Done.

---

*[libs/drivers/i2c/i2c.cpp, line 107 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKIYc229ymQsdLECDG:-KYKg8v99b3czAU57eUK:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/i2c.cpp#L107)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use initializer list.
</blockquote></details>

Done.

---

*[libs/drivers/i2c/i2c.cpp, line 150 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKUT2g4BvsSl9Ow1ag:-KYKgDXW5t6CwcXquDa-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/i2c.cpp#L150)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

shouldn't the 
```
System::EndSwitchingISR();
```
be called here as well?

</blockquote></details>

Done.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKUfVf2rr9cXSWyzOr:-KYS_TxhkkYs7xa5J3QO:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/libs/drivers/i2c/Include/i2c/i2c.h#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd separate public interface a.k.a II2cBus & enumerators from the implementation (low level bus, fallback bus etc.)
</blockquote></details>

Done.

---

*[src/obc.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKN5kH-x7rXNXiD4hq:-KYKgImr1p27tUGs9-S5:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/src/obc.cpp#L6)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

redundant, default constructor will be called anyway
</blockquote></details>

Done.

---

*[unit_tests/I2C/I2CMock.cpp, line 3 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKRqd7--rXrg_JtrP0:-KYKgg6qEFdF6HK9aWYX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/unit_tests/I2C/I2CMock.cpp#L3)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this constructor can be entirely removed
</blockquote></details>

Done.

---

*[unit_tests/I2C/I2CMock.hpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-KYKRwr_EE88e3MfpvWc:-KYKgjV82TVHlBpUhm9q:b-q02w2q) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0e3b6653393c6dde071512fe4eda7c17a61e021/unit_tests/I2C/I2CMock.hpp#L23)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

for consistency reason I would provide also function for read command.
</blockquote></details>

Actually it's not that easy - most read commands will require more that single byte so some complex matcher is requried (like `ElementsAre(someCommand, someAddress)`)  and to be honest I'm not so happy with `ExpectWriteCommand` in it's current form - it's a bit to strict (only one byte) for general use.

I'll think of something better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56)*

**Comment by zaq32** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/56#-:-KYUVcOUXAg484ljRjLO:bnfp4nl)*

**Pull request merged**
