### PR TITLE
C++

### PR DESCRIPTION
**Pull request by Novakov**
* Compile all files as C++ except external libs 
* Comm module updated to be more objective
* Added GSL
* OBC class will be responsible for constructing whole object graph and manage dependencies between them

Known issues:
* all code except unit tests is compiled with `-fno-exeptions`. In case of call unit tests -> lib -> callback -> throw exception, QEmu will be terminated as there is no way to catch that exception

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/49)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r1, 102 of 115 files at r2, 2 of 3 files at r3, 10 of 15 files at r4.
Review status: 77 of 83 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/storage/nand.cpp, line 341 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnIcqrr10q6G2Owmlj:-KWnIcqrr10q6G2Owmlk:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/storage/nand.cpp#L341)):*
> ```cpp
>     WriteProtect(true);
> 
>     return (FlashStatus)status;
> ```

use c++ style cast

---

*[src/commands/state_command.cpp, line 15 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnJIzD6Rp4cytlH380:-KWnJIzD6Rp4cytlH381:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/src/commands/state_command.cpp#L15)):*
> ```cpp
>     int16_t cmd = atoi(args[0]);
> 
>     SetTerminalCommand((TerminalCommand)cmd);
> ```

use c++ style cast

---

*[unit_tests/test.cpp, line 1 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnJSEarzjpMU1xpv1d:-KWnJSEarzjpMU1xpv1e:b-lla5or) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/unit_tests/test.cpp#L1)):*
> ```cpp
> #include <stdio.h>
> ```

use c++ version of this header: cstdio

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by zaq32** [comment]
Reviewed 5 of 115 files at r2, 5 of 15 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/comm.h, line 149 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnNBWJFMpwLs_Xep3z:-KWnN8UiQmD8GJX-IZeJ:b-jrqgf4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/drivers/comm/Include/comm/comm.h#L149)):*
> ```objc
>             {
>                 /**
>                  * @brief Pointer to function that should be called whenever new frame is received.
> ```

out of date

---

*[libs/drivers/comm/Include/comm/comm.h, line 299 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnMULUfdlNRP5IqNKR:-KWnMULUfdlNRP5IqNKS:b-jrqgf4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/drivers/comm/Include/comm/comm.h#L299)):*
> ```objc
>                  *
>                  * @param[in] data Pointer to buffer that contains the frame contents.
>                  * @param[in] length Size of the frame contents in bytes. This value cannot be
> ```

out of date

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by Novakov** [comment]
Review status: 78 of 83 files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/comm.h, line 149 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnNBWJFMpwLs_Xep3z:-KWnNwWtwxo3iPebrLtv:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/drivers/comm/Include/comm/comm.h#L149)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> out of date
</details>
Done.

---

*[libs/drivers/comm/Include/comm/comm.h, line 299 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnMULUfdlNRP5IqNKR:-KWnOajVTJdSmzSK0QZ1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/drivers/comm/Include/comm/comm.h#L299)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> out of date
</details>
Done.

---

*[libs/storage/nand.cpp, line 341 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnIcqrr10q6G2Owmlj:-KWnLwFx1yBcITGkIXB0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/libs/storage/nand.cpp#L341)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use c++ style cast
</details>
Done.

---

*[src/commands/state_command.cpp, line 15 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnJIzD6Rp4cytlH380:-KWnMR1esI7mJ9MMLSCX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/src/commands/state_command.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use c++ style cast
</details>
Done.

---

*[unit_tests/test.cpp, line 1 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWnJSEarzjpMU1xpv1d:-KWnMfJkOPmJB3fDf_e_:b2x4xrh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/571972877a19f12f7417eb199c06d3d55343bebf/unit_tests/test.cpp#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use c++ version of this header: cstdio
</details>
Actually only `gtest/gtest.h` is used. removed rest of them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by zaq32** [comment]
Reviewed 3 of 115 files at r2, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[libs/drivers/comm/Include/comm/comm.h, line 16 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWwYUVfZmrqT9at-fZN:-KWwYUVgZvs_mshtI6_i:b-rna13r) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1eeff165ec376450bda4f0172d6e2695111cb7d/libs/drivers/comm/Include/comm/comm.h#L16)):*
> ```objc
>     namespace devices
>     {
>         namespace comm
> ```

three namespaces that's a bit too much. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by Novakov** [comment]
Review status: 77 of 83 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/Include/comm/comm.h, line 16 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-KWwYUVfZmrqT9at-fZN:-KX6J2GmPoA8OJ6nQJeE:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1eeff165ec376450bda4f0172d6e2695111cb7d/libs/drivers/comm/Include/comm/comm.h#L16)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> three namespaces that's a bit too much. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49)*

**Comment by zaq32** [comment]
:lgtm:

---

Reviewed 3 of 115 files at r2, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/49#-:-KX72CS4rHROAyxDn0aM:bnfp4nl)*

**Pull request merged**
