### PR TITLE
Support backspace in terminal

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/205)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/uart/uart.cpp, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205#-Ko90sxKXs0FzmYAchWB:-Ko90sxKXs0FzmYAchWC:b-b47vat) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2812409c2ab62fe4783caaa8345d79094a617adc/libs/drivers/uart/uart.cpp#L165)):*
> ```cpp
>                         {
>                             this->_buffer--;
>                         }
> ```

consider this:

``` 
if (this->_buffer - this->_bufferBegin > 2)
{
    this->_buffer -= 2;
}
else
{
    --this->_buffer;
}

*this->_buffer = '\0';
break;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/uart/uart.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205#-Ko95A4kiBIo23lusoyd:-Ko95A4kiBIo23lusoye:basge1q) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2812409c2ab62fe4783caaa8345d79094a617adc/libs/drivers/uart/uart.cpp#L15)):*
> ```cpp
>     namespace uart
>     {
>         UART::UART() : _lineEditing(false)
> ```

uninitialized members: 
_buffer
_bufferEnd
_rxChannel
_txChannel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205)*

**Comment by Novakov** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/uart/uart.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205#-Ko95A4kiBIo23lusoyd:-KoCt9UZ6kacV4qBZXJ4:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2812409c2ab62fe4783caaa8345d79094a617adc/libs/drivers/uart/uart.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

uninitialized members: 
_buffer
_bufferEnd
_rxChannel
_txChannel
</blockquote></details>

Done.

---

*[libs/drivers/uart/uart.cpp, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205#-Ko90sxKXs0FzmYAchWB:-KoCt9kqzV5a7q7t-ZDT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2812409c2ab62fe4783caaa8345d79094a617adc/libs/drivers/uart/uart.cpp#L165)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

consider this:

``` 
if (this->_buffer - this->_bufferBegin > 2)
{
    this->_buffer -= 2;
}
else
{
    --this->_buffer;
}

*this->_buffer = '\0';
break;
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/205)*

**Pull request merged**
