### PR TITLE
[TeleComm] Added DisableOverheatSubmode command

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/290)

### CODE REVIEW

**Comment by kfazi** [comment]
[[TC] Disable EPS overheat submode](https://trello.com/c/g4HlUKfr/261-tc-disable-eps-overheat-submode)

**Comment by zaq32** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/Include/mock/eps.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290#-KsxFXNKllaxgoNrYvKb:-KsxFXNKllaxgoNrYvKc:b-4y5vn1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0e2820382d14e1becec205283e8ddc79a82aa55e/unit_tests/base/Include/mock/eps.hpp#L22)):*
>     MOCK_METHOD0(ReadHousekeepingA, Option<devices::eps::hk::ControllerATelemetry>());
> 
>     MOCK_METHOD0(ReadHousekeepingB, Option<devices::eps::hk::ControllerBTelemetry>());
IEPSDriver interface does not have such members.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290)*

**Comment by kfazi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[unit_tests/base/Include/mock/eps.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290#-KsxFXNKllaxgoNrYvKb:-KsxPIYIdNIdM_wtnHRp:biioqwg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0e2820382d14e1becec205283e8ddc79a82aa55e/unit_tests/base/Include/mock/eps.hpp#L22)):*
> struct IEPSDriver : public IEpsTelemetryProvider

It inherits from `IEpsTelemetryProvider`, so it has these members

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290)*

**Comment by zaq32** [comment]
Reviewed 1 of 18 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/290)*

**Pull request merged**
