### PR TITLE
Ucam II unit tests

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/247)

### CODE REVIEW

**Comment by mandrek44** [comment]
[[CAM] Unit tests](https://trello.com/c/MopsW3G1/235-cam-unit-tests)

**Comment by zaq32** [comment]
Reviewed 10 of 17 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/247)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/247)*

**Comment by zaq32** [comment]
[[CAM] Error Counters](https://trello.com/c/ToQt67PO/194-cam-error-counters)

**Pull request merged**
