### PR TITLE
Fixed infinite lock and semaphore leak on Persistent State.

### PR DESCRIPTION
**Pull request by tom4r**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/215)

### CODE REVIEW

**Comment by tom4r** [comment]
Request halted - will be resolved by other solution.

**Comment by zaq32** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/215)*

**Comment by zaq32** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/215)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/215)*

**Pull request merged**
