### PR TITLE
Set RTC time if not correct

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/233)

### CODE REVIEW

**Comment by Novakov** [comment]
[RTC is not reset to valid state](https://trello.com/c/KuVZMKgf/225-rtc-is-not-reset-to-valid-state)

**Comment by zaq32** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/Include/base/writer.h, line 137 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/233#-KqbyaGnYrTf3iRi_H-s:-KqbyaGnYrTf3iRi_H-t:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/86ecc129c56fd777758df6a0751322d54c03d340/libs/base/Include/base/writer.h#L137)):*
> ```objc
>     bool WriteLowerBytesBE(std::uint32_t number, std::uint8_t bytesCount);
> 
>     bool WriteByteBCD(std::uint8_t value);
> ```

undocumented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/233)*

**Comment by Novakov** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/Include/base/writer.h, line 137 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/233#-KqbyaGnYrTf3iRi_H-s:-Kqc0di58HmovA0mdcik:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/86ecc129c56fd777758df6a0751322d54c03d340/libs/base/Include/base/writer.h#L137)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/233)*

**Comment by begreeen** [comment]
Test report:

=> initial state: rtc runs with random values in its registers (year 150)
=> code from this PR uploaded and run:
```
Hello I'm PW-SAT2 OBC
ebug]   Received boot information from bootloader
[Info]    Starting initialization task...
[Info]    Requested runlevel 2
[Info]    [rtc] Integrity flag: 0xD0
[Warning] [rtc] Integrity not guaranteed. Reseting RTC to 0
[Info]    yaffs: yaffs: Mounting /
```
The OBC correctly recognized that RTC contains wrong time.

=> so it set up a time:
```
>rtc get
0-1-1 0:1:3 (946684863 sec since epoch)
```
=> after OBC reboot (rtc supplied all the time):
```
Hello I'm PW-SAT2 OBC
ebug]   Received boot information from bootloader
[Info]    Starting initialization task...
[Info]    Requested runlevel 2
[Info]    [rtc] Integrity flag: 0x48
[Info]    yaffs: yaffs: Mounting /
```
OBC detects proper time and has no doubt about time integrity so it should not set time again
=> as expected, the time is still running, without setting it up again after reboot
```
>rtc get
0-1-1 0:3:39 (946685019 sec since epoch)
```
=> rtc powered down (backup power capacitor discharged intentionally), OBC reboot:
```
>rtc get
0-1-1 0:0:16 (946684816 sec since epoch)
```
the rtc clock integrity is not valid, so OBC detects it and set a time again

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/233)*

**Pull request merged**
