### PR TITLE
Updated sail opening procedure

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/208)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/mission/sail/sail.cpp, line 147 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208#-KommVcHa9B3oRiFe0Kb:-KommVcHa9B3oRiFe0Kc:bxfefwa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9c918248fb3990ecd526992971ecffc28292de8e/libs/mission/sail/sail.cpp#L147)):*
> ```cpp
>             if (step.AfterStepDelay != decltype(step.AfterStepDelay)::zero())
>             {
>                 This->_nextStepAfter = state.Time + step.AfterStepDelay;
> ```

adding anything to max will cause an overflow in this case signed integer overflow (undefined behaviour by standard) In our case it will case This->_nextStepAfter to be negative

---

*[libs/state/Include/state/sail/SailState.hpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208#-KomlOWrIWgSyxluGNMp:-KomlOWrIWgSyxluGNMq:b1lsz1o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9c918248fb3990ecd526992971ecffc28292de8e/libs/state/Include/state/sail/SailState.hpp#L31)):*
> ```cpp
>          * @brief Ctor
>          */
>         SailState() : _currentState(SailOpeningState::Waiting)
> ```

Define class methods outside class definition

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208)*

**Comment by Novakov** [comment]
Review status: 28 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/mission/sail/sail.cpp, line 147 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208#-KommVcHa9B3oRiFe0Kb:-KorIaHsuySK7cWSW4_Q:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9c918248fb3990ecd526992971ecffc28292de8e/libs/mission/sail/sail.cpp#L147)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

adding anything to max will cause an overflow in this case signed integer overflow (undefined behaviour by standard) In our case it will case This->_nextStepAfter to be negative
</blockquote></details>

Done.

---

*[libs/state/Include/state/sail/SailState.hpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208#-KomlOWrIWgSyxluGNMp:-KorFadK7Zc-R5NnziJS:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9c918248fb3990ecd526992971ecffc28292de8e/libs/state/Include/state/sail/SailState.hpp#L31)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Define class methods outside class definition
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208)*

**Comment by zaq32** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/208)*

**Pull request merged**
