### PR TITLE
Documented runlevels design

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/116)

### CODE REVIEW

**Comment by ggajoch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doc/Runlevels.md, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116#-KgzWQqItSrKhG6kgHtk:-KgzWQqJZ5rqlNs4e7pL:b-x5y27g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1d6320c0fd6171c949033ea5e1978ee5e1f8de1e/doc/Runlevels.md#L28)):*
> ```Markdown
> 
> ## How-to: staying on bootloader runlevel
> During startup bootloader checks if pin @ref obc::OBCGPIO::SysClear is low (*TBC*). If not, normal boot procedure is executed up to run level 3. When that pin is low during startup, OBC stays in bootloader for T<sub>boot_timeout</sub> (*TBD*) seconds waiting for commands from terminal. If no command is entered in T<sub>boot\_timeout</sub> than normal boot precedure is performed.
> ```

For now on access port we have only one UART for OBC. We can add GPIO pin to fullfil this requirement but IMO it will be better to wait for UART command (similar mechanism as in bootloader). This method can also reduce fault probability (it is easier to alter pin state than send proper command via UART).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Comment by ggajoch** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Comment by Novakov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Runlevels.md, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116#-KgzWQqItSrKhG6kgHtk:-KiBIDaCsDXKcJNoYeH_:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1d6320c0fd6171c949033ea5e1978ee5e1f8de1e/doc/Runlevels.md#L28)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

For now on access port we have only one UART for OBC. We can add GPIO pin to fullfil this requirement but IMO it will be better to wait for UART command (similar mechanism as in bootloader). This method can also reduce fault probability (it is easier to alter pin state than send proper command via UART).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Comment by ggajoch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doc/Runlevels.md, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116#-KgzWQqItSrKhG6kgHtk:-KiCelE9ZRzREiriplSA:b-eq47e2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1d6320c0fd6171c949033ea5e1978ee5e1f8de1e/doc/Runlevels.md#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Will this pin be necessary on flight model? I understand that is will be helpful to speedup testing, but I don't see a usage for it on flight hardware. Maybe this should be explicitly written here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Comment by zaq32** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doc/Runlevels.md, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116#-KgzWQqItSrKhG6kgHtk:-KiEvuPN4b4dnw375YG3:b-hm8gr5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1d6320c0fd6171c949033ea5e1978ee5e1f8de1e/doc/Runlevels.md#L28)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

Will this pin be necessary on flight model? I understand that is will be helpful to speedup testing, but I don't see a usage for it on flight hardware. Maybe this should be explicitly written here?
</blockquote></details>

This description no longer mentions anything exception uart.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/116)*

**Pull request merged**
