### PR TITLE
Time synchronization update

### PR DESCRIPTION
**Pull request by zaq32**
* Remove time service's serialization ability & replace it with addition to the satellite persistent state.
* Update time synchronization component to make use of persistent state instead of its own in-memory state. As a result time synchronization has been simplified a bit due to it becoming stateless. In addition as a result of this change from now on time lost due to obc being powerred of is now at least partially corrected (50% due to the  mcu time being stopped during this period).
* Introduced time correction configuration. This change provides possibility to adjust time synchronization algorithm in order to make it more resilient to permanent/increasing time measuring errors that may be detected after sattelite launch. It is also possible to disable one of the time sources if it starts to generate too many errors.
* Extend, update persistent state & time synchronization documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/128)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Time] Remove auto saving from TimeProvider](https://trello.com/c/gBCiUIJ3/133-time-remove-auto-saving-from-timeprovider)

**Comment by zaq32** [comment]
[[Time] Time correction should use parametrized weight](https://trello.com/c/JKCVUPpD/151-time-time-correction-should-use-parametrized-weight)

**Comment by zaq32** [comment]
[[Time] Use FRAM to store value of last seen RTC value](https://trello.com/c/7TyINcDS/130-time-use-fram-to-store-value-of-last-seen-rtc-value)

**Comment by Novakov** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/time/time.cpp, line 122 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/128#-KiBlFTv89KpYSn7SU8p:-KiBlFTv89KpYSn7SU8q:b-egvx6q) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/42c5835fbf87d4de7dc66a95c92b6b34aac83b38/libs/mission/time/time.cpp#L122)):*
> ```cpp
>             (deltaMcu * correctionConfiguation.MissionTimeFactor() + deltaRtc * correctionConfiguation.ExternalTimeFactor()) /
>                 correctionConfiguation.Total();
>         auto correctionValue = correctedMissionTime > missionTime ? correctedMissionTime - missionTime : missionTime - correctedMissionTime;
> ```

I like the idea but It should be done as separate pull request - just the suggestion for future

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/128)*

**Comment by Novakov** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/128)*

**Comment by Novakov** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/128)*

**Pull request merged**
