### PR TITLE
Support i2c timeout

### PR DESCRIPTION
**Pull request by Novakov**
DeviceMock has been rewritten almost from scratch, so after this PR gets to master devices must be flashed with new version.

After detecting latched SCL, power cycle is triggered

---

This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/39)

### CODE REVIEW

**Comment by Novakov** [comment]
[[i2c] Support timeout](https://trello.com/c/k35qgiTT/81-i2c-support-timeout)

**Comment by zaq32** [comment]
Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[integration_tests/extensions/SaleaeDump.py, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKFxidOzpx-MU6PIFm:-KVKFxidOzpx-MU6PIFn:b-v1jjis) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/integration_tests/extensions/SaleaeDump.py#L20)):*
> ```Python
>         sleep(1)
>         self._connection.capture_stop()
>         self._connection.save_to_file('D:/captures/%s.logicdata' % test_id)
> ```

this should be build relative path. 

---

*[libs/drivers/i2c/error_handling.c, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHDILdhWGoc2Fxa5U:-KVKHDILdhWGoc2Fxa5V:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L7)):*
> ```C
> #include "i2c.h"
> 
> static inline I2CErrorHandlingBus* Config(I2CBus* inner)
> ```

undocumented

---

*[libs/drivers/i2c/error_handling.c, line 25 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHF_UIAp36ZwPDS6f:-KVKHF_UIAp36ZwPDS6g:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L25)):*
> ```C
> }
> 
> static I2CResult WriteRead(
> ```

undocumented

---

*[libs/drivers/i2c/i2c.c, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHSZW-Xn_MgJDgkCp:-KVKHSZW-Xn_MgJDgkCq:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L10)):*
> ```C
> #include "i2c.h"
> 
> static bool IsSclLatched(const I2CBus* bus)
> ```

undocumented

---

*[libs/drivers/i2c/i2c.c, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHTZ9qIhsYImsYXb7:-KVKHTZ9qIhsYImsYXb8:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L15)):*
> ```C
> }
> 
> static I2CResult ExecuteTransfer(I2CBus* bus, I2C_TransferSeq_TypeDef* seq)
> ```

undocumented

---

*[libs/drivers/i2c/i2c.c, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIXVAeB-qKfq-F6iQ:-KVKIXVAeB-qKfq-F6iR:bfz35q1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L48)):*
> ```C
>         hw->CMD = I2C_CMD_STOP | I2C_CMD_ABORT;
> 
>         while (HAS_FLAG(hw->STATUS, I2C_STATUS_PABORT))
> ```

Can we make sure that this loop will not hang current task indefinitely?

---

*[libs/drivers/i2c/i2c.c, line 69 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHkbLQKErne1GvCsK:-KVKHkbLQKErne1GvCsL:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L69)):*
> ```C
> }
> 
> static I2CResult Write(I2CBus* bus, const I2CAddress address, const uint8_t* data, size_t length)
> ```

undocumented

---

*[libs/drivers/i2c/i2c.c, line 143 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHl7Zmoux_Oyhexqy:-KVKHl7Zmoux_Oyhexqz:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L143)):*
> ```C
> }
> 
> void I2CIRQHandler(I2CBus* bus)
> ```

undocumented

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 84 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIHnhemRZxQhv2oXn:-KVKIHnhemRZxQhv2oXo:b-rscxv7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L84)):*
> ```objc
>         uint16_t SCL;
>         uint16_t SDA;
>     } IO;
> ```

undocumented it also seems to be unused.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 120 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKQ0IzwIZDZk92LwFq:-KVKQ0IzwIZDZk92LwFr:bde126y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L120)):*
> ```objc
>         size_t outLength //
>         );
> } I2CBus;
> ```

This structure is begining to grow out of control. Initially it was intended to be as close as possible to the pure interface.  Maybe we should consider separating state from the interface?

I.e.:
* the field Extra is used only by fallback & error_handling layers,
* fields ResultQueue, Lock & HWInterface are used only by the  actual driver  at the bottom of the stack,

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 176 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIMqgf7wdWxRxWxS0:-KVKIMqgf7wdWxRxWxS1:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L176)):*
> ```objc
> typedef I2CResult (*BusErrorHandler)(I2CBus* bus, I2CResult result, I2CAddress address, void* context);
> 
> typedef struct
> ```

undocumented

---

*[libs/power/CMakeLists.txt, line 3 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIqh2EA1hGrH8oStS:-KVKIlHkVX9lLf9s6T_r:bj71f07) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/power/CMakeLists.txt#L3)):*
> ```CMake
> set(NAME power)
> 
> set(SOURCES
> ```

this looks strange.  
you can also put header files in this list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Comment by Novakov** [comment]
Review status: 36 of 51 files reviewed at latest revision, 12 unresolved discussions.

---

*[integration_tests/extensions/SaleaeDump.py, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKFxidOzpx-MU6PIFm:-KVLj1guWO9sWz3IrSo6:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/integration_tests/extensions/SaleaeDump.py#L20)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this should be build relative path. 
</details>
Done.

---

*[libs/drivers/i2c/error_handling.c, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHDILdhWGoc2Fxa5U:-KVL09rYrrkCabTIK_cW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/drivers/i2c/error_handling.c, line 25 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHF_UIAp36ZwPDS6f:-KVL0Aqf7xh9BZ3eA_LG:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L25)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/drivers/i2c/i2c.c, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHSZW-Xn_MgJDgkCp:-KVL0BcI2r4qgrQsKsJA:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/drivers/i2c/i2c.c, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHTZ9qIhsYImsYXb7:-KVL0CGll03Pnfp6bdGR:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/drivers/i2c/i2c.c, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIXVAeB-qKfq-F6iQ:-KVKdT7E571ovQdogLCN:bgmbzl7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L48)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Can we make sure that this loop will not hang current task indefinitely?
</details>
Not really. ABORT command is handled directly by I2C hardware and should be executed immediately but write to CMD register is not blocking. 

---

*[libs/drivers/i2c/i2c.c, line 69 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHkbLQKErne1GvCsK:-KVL0CrBr4W8cgVGzzU0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L69)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/drivers/i2c/i2c.c, line 143 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHl7Zmoux_Oyhexqy:-KVKnRlXUg4oMuZUbRlM:b-ux1952) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/i2c.c#L143)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Documented in i2c.h

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 84 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIHnhemRZxQhv2oXn:-KVKd4y-GJg-PInqU2zn:b-7kemyc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L84)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented it also seems to be unused.
</details>
Used in `IsSclLatched` function

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 120 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKQ0IzwIZDZk92LwFq:-KVLj30qzn1LKifWLXyt:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L120)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> This structure is begining to grow out of control. Initially it was intended to be as close as possible to the pure interface.  Maybe we should consider separating state from the interface?
> 
> I.e.:
> * the field Extra is used only by fallback & error_handling layers,
> * fields ResultQueue, Lock & HWInterface are used only by the  actual driver  at the bottom of the stack,
</details>
Done.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 176 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIMqgf7wdWxRxWxS0:-KVL0E0AAlwvVVlJSval:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/Include/i2c/i2c.h#L176)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[libs/power/CMakeLists.txt, line 3 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKIqh2EA1hGrH8oStS:-KVL0Ekm4JJSN5yn2xQW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/power/CMakeLists.txt#L3)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this looks strange.  
> you can also put header files in this list.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Comment by zaq32** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/i2c/error_handling.c, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHDILdhWGoc2Fxa5U:-KVLjsD73bUGmDKgO5WG:br7b3dd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L7)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Done.
</details>
this procedure does not have parameter inner

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 76 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVLnXEcvsOqDMjpMXJS:-KVLnXEcvsOqDMjpMXJT:b-qa8f2y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/beaace46e49994b2dcbc56eedfeed830daff1e55/libs/drivers/i2c/Include/i2c/i2c.h#L76)):*
> ```objc
> {
>     /** @brief Arbitrary data needed by driver */
>     void* Extra;
> ```

this field is no longer used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/i2c/error_handling.c, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVKHDILdhWGoc2Fxa5U:-KVOfAF-wMU1Em9A8BGW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dd983d6a2fa7d147fb797b5575da3b44e3afc598/libs/drivers/i2c/error_handling.c#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this procedure does not have parameter inner
</details>
Done.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 76 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-KVLnXEcvsOqDMjpMXJS:-KVOfAtMYyLXlh6XZcyX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/beaace46e49994b2dcbc56eedfeed830daff1e55/libs/drivers/i2c/Include/i2c/i2c.h#L76)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this field is no longer used.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Comment by zaq32** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39#-:-KVOg14bBgPwEKOvOnXQ:bnfp4nl)*

**Comment by zaq32** [comment]
Reviewed 1 of 4 files at r4.
Review status: 49 of 52 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Comment by zaq32** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/39)*

**Pull request merged**
