### PR TITLE
[TeleComm] Refactored DownloadFile command

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/140)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140#-KjSd-025PMkWpYQlSKy:-KjSd-025PMkWpYQlSKz:b-50ahsu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6447d164d2f0af30442686619d7a06577f5f9844/libs/obc/communication/telecommands/file_system.cpp#L39)):*
> ```cpp
>         bool FileSender::SendPart(std::uint32_t seq)
>         {
>             constexpr uint8_t maxFileDataSize = DownlinkFrame::MaxPayloadSize - 2;
> ```

Put this inside `FileSender` class header - so it will be easier to find

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by kfazi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140#-KjSd-025PMkWpYQlSKy:-KjTH5hVOlBvbeHUk-9-:b-eermda) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6447d164d2f0af30442686619d7a06577f5f9844/libs/obc/communication/telecommands/file_system.cpp#L39)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Put this inside `FileSender` class header - so it will be easier to find
</blockquote></details>

But it's used only in this one method. What's the point of putting it into outer scope?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by Novakov** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140#-KjSd-025PMkWpYQlSKy:-KjUjF4hSE-vtL7r_NUz:b-c8u8l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6447d164d2f0af30442686619d7a06577f5f9844/libs/obc/communication/telecommands/file_system.cpp#L39)):*
<details><summary><i>Previously, kfazi wrote…</i></summary><blockquote>

But it's used only in this one method. What's the point of putting it into outer scope?
</blockquote></details>

This value is answer to question 'How much data fits in single frame?' which is perfectly valid question from OPER team. If this value is in class header it will be much easier to find.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by kfazi** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140#-KjSd-025PMkWpYQlSKy:-KjV7tT2cQhmKUYR6cih:bqy67xj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6447d164d2f0af30442686619d7a06577f5f9844/libs/obc/communication/telecommands/file_system.cpp#L39)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

This value is answer to question 'How much data fits in single frame?' which is perfectly valid question from OPER team. If this value is in class header it will be much easier to find.
</blockquote></details>

Fair enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Comment by Novakov** [comment]
Reviewed 3 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/140)*

**Pull request merged**
