### PR TITLE
Uplink frame format

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/67)

### CODE REVIEW

**Comment by Novakov** [comment]
[Implement uplink frame format](https://trello.com/c/54dtqpUq/105-implement-uplink-frame-format)

**Comment by zaq32** [comment]
Reviewed 26 of 27 files at r1.
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/base/reader.h, line 126 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8t1Mkod4SUxFfZtJR:-Ka8t1Mkod4SUxFfZtJS:b4sgbpg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/base/Include/base/reader.h#L126)):*
> ```objc
>      * @return Span for remaining part of buffer
>      */
>     gsl::span<const uint8_t> Remaining();
> ```

There is already equivalent of this: ReadArray method. 

---

*[libs/telecommand_handling/uplink.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8vNqSlQsXSvj58CHt:-Ka8vNqSlQsXSvj58CHu:b2i9tjy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/telecommand_handling/uplink.cpp#L23)):*
> if (frame.size() < 5)
>     {
>         return DecodeTelecommandResult::Failure(DecodeTelecommandFailureReason::MalformedFrame);
>     }
This can be done a posteriori by verifying the reader status and is much more failure resistant to the future changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by zaq32** [comment]
Reviewed 1 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by Novakov** [comment]
Review status: 20 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/reader.h, line 126 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8t1Mkod4SUxFfZtJR:-KaIOWOULkrPvZ9X5RdI:bxb9e4q) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/base/Include/base/reader.h#L126)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

There is already equivalent of this: ReadArray method. 
</blockquote></details>

Sort-of equivalent - it needs size of data to read. What I need is reading everything up to the end of buffer so they are similar but not the same

---

*[libs/telecommand_handling/uplink.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8vNqSlQsXSvj58CHt:-KaIU36oy4xWC897PBQM:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/telecommand_handling/uplink.cpp#L23)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> if (frame.size() < 5)
>     {
>         return DecodeTelecommandResult::Failure(DecodeTelecommandFailureReason::MalformedFrame);
>     }
This can be done a posteriori by verifying the reader status and is much more failure resistant to the future changes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/Include/base/reader.h, line 126 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8t1Mkod4SUxFfZtJR:-KaJMC2_rOyBiXJdnXNP:b-d4hsz0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/base/Include/base/reader.h#L126)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Sort-of equivalent - it needs size of data to read. What I need is reading everything up to the end of buffer so they are similar but not the same
</blockquote></details>

And you can get the size by calling the RemainingSize() procedure. Why add (and maintain) function when it can be easily replicated by using already existing interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/base/Include/base/reader.h, line 126 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8t1Mkod4SUxFfZtJR:-KaJMxvHL0hZ1fA59lRK:bonyp0n) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/base/Include/base/reader.h#L126)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

And you can get the size by calling the RemainingSize() procedure. Why add (and maintain) function when it can be easily replicated by using already existing interface?
</blockquote></details>

It's our code and I would like to have interface that serves our needs: `Remaining()` is a lot more readable than `ReadArray(RemainingSize()`.

In case of such small functions I think that we just spent more time discussing it than we will ever spent on maintaining it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by zaq32** [comment]
Reviewed 5 of 6 files at r3.
Review status: 23 of 24 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by zaq32** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by Novakov** [comment]
Review status: 20 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/Include/base/reader.h, line 126 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67#-Ka8t1Mkod4SUxFfZtJR:-KaSZgjwFAzjendcvw58:bhdwwdg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a87bb85e3644c7d651071bd7701cf6c7b3ae41c9/libs/base/Include/base/reader.h#L126)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's our code and I would like to have interface that serves our needs: `Remaining()` is a lot more readable than `ReadArray(RemainingSize()`.

In case of such small functions I think that we just spent more time discussing it than we will ever spent on maintaining it. 
</blockquote></details>

Changed to `ReadToArray`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/67)*

**Pull request merged**
