### PR TITLE
Telecommand for setting boot slots

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/181)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/communication/telecommands/boot_settings.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/181#-KmSy8LOG9d62obtu1Ax:-KmSy8LOG9d62obtu1Ay:b3rjwut) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4f25ed91a65ab362e9da01a194bdbfc424244b36/libs/obc/communication/telecommands/boot_settings.cpp#L24)):*
> ```cpp
>             auto failsafeBootSlots = r.ReadByte();
> 
>             if (!r.Status())
> ```

verify whether the bootSlots & failSafeBootSlots are valid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/181)*

**Comment by Novakov** [comment]
Review status: 18 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/boot_settings.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/181#-KmSy8LOG9d62obtu1Ax:-KmppG3t2FYU0c3GhhML:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4f25ed91a65ab362e9da01a194bdbfc424244b36/libs/obc/communication/telecommands/boot_settings.cpp#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

verify whether the bootSlots & failSafeBootSlots are valid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/181)*

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/181)*

**Comment by Novakov** [comment]
[[TC] Set boot slots](https://trello.com/c/gKN2NjXx/197-tc-set-boot-slots)

**Pull request merged**
