### PR TITLE
Telecommand: abort experiment

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/134)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] Abort experiment](https://trello.com/c/vTChB6FM/148-tc-abort-experiment)

**Comment by zaq32** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/base/Include/traits.hpp, line 137 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWY-hCTDzXmwjSCIOS:-KiWY-hCTDzXmwjSCIOT:b-xeam34) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/base/Include/traits.hpp#L137)):*
> ```cpp
>  * @brief Compile time traits for values
>  */
> template <typename ValueType> struct ValuesTrait
> ```

By convention single type should provide only one operation and name of the type should be related to the operation.

---

*[libs/experiments/experiments.cpp, line 119 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWXHGPqgQeiqTNZBfa:-KiWXHGQ-cGOtPOqH0fc:b-754s8e) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/experiments/experiments.cpp#L119)):*
> ```cpp
>         do
>         {
>             if (this->_event.IsSet(Event::AbortRequest))
> ```

use `Wait()` with timeout set to 0 and auto reset set to true

---

*[libs/obc/communication/Include/obc/communication.h, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWYFsuRuMNWINrNjCH:-KiWYFsuRuMNWINrNjCI:b90pg0v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L30)):*
> ```objc
>      * @tparam Telecommands Types of telecommands
>      */
>     template <typename... Telecommands> class TelecommandsHolder final
> ```

This type is independent of obc specific logic. Move it to the obc independent library

---

*[libs/obc/communication/Include/obc/communication.h, line 68 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWVkYiDDxUb0f2Dcw_:-KiWVkYiDDxUb0f2Dcwa:bki92sb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L68)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         /** @brief Telecommand instances */
>         std::tuple<Telecommands...> _telecommands;
>         /** @brief Pointers to telecommands */
>         std::array<telecommunication::uplink::IHandleTeleCommand*, sizeof...(Telecommands)> _pointers;
</details>
Class fields should be defined at the end

---

*[libs/obc/communication/Include/obc/communication.h, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWVg0zUUPUSwZO4ZRc:-KiWVg0zUUPUSwZO4ZRd:b3kre) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L72)):*
> ```objc
>         /**
>          * @brief
>          * @return
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/obc/communication/Include/obc/communication.h, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWYFsuRuMNWINrNjCH:-KiWbRnm7BDzLQAFsRg9:b-w81a1w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L30)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This type is independent of obc specific logic. Move it to the obc independent library
</blockquote></details>

It is dependent as it checks if suppiled  types are valid telecommands. Stripping it from telecommands specifics won't give us any good

---

*[libs/obc/communication/Include/obc/communication.h, line 68 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWVkYiDDxUb0f2Dcw_:-KiWcPI-Ko7XbHAypimg:b-69u9fr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L68)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         /** @brief Telecommand instances */
>         std::tuple<Telecommands...> _telecommands;
>         /** @brief Pointers to telecommands */
>         std::array<telecommunication::uplink::IHandleTeleCommand*, sizeof...(Telecommands)> _pointers;
Class fields should be defined at the end
</blockquote></details>

Yeah but my intention was to keep static assert stuff together (and putting it at the beginning of the class will 'hide' purpose of whole class) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/base/Include/traits.hpp, line 137 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWY-hCTDzXmwjSCIOS:-Kia3ni8m0kGMKpBDU_A:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/base/Include/traits.hpp#L137)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

By convention single type should provide only one operation and name of the type should be related to the operation.
</blockquote></details>

Done.

---

*[libs/experiments/experiments.cpp, line 119 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWXHGPqgQeiqTNZBfa:-Kia4wTRTidN8nfsx34U:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/experiments/experiments.cpp#L119)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use `Wait()` with timeout set to 0 and auto reset set to true
</blockquote></details>

Done.

---

*[libs/obc/communication/Include/obc/communication.h, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134#-KiWVg0zUUPUSwZO4ZRc:-Kia3WLPX7LfVnh5f0_D:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23f81621884ad26019118e4d05c3e9daf9f41133/libs/obc/communication/Include/obc/communication.h#L72)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/134)*

**Pull request merged**
