### PR TITLE
Extend telemetry acquisition with software boot time information

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/168)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platforms/DevBoard/Include/mcu.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168#-Kl_7g91sWEWPnmFKJg8:-Kl_7g927c5ARTEzXc4w:bosdtoo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9623fabf0ef4fbead0f8c9020bb72458fc580c32/platforms/DevBoard/Include/mcu.h#L4)):*
> ```objc
> #define PLATFORMS_DEVBOARD_INCLUDE_MCU_H_
> 
> #include "efm32gg990f1024.h"
> ```

You should be including `em_device.h`

---

*[platforms/FlightModel/Include/mcu.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168#-Kl_7tpCKB1_OYKcSRz8:-Kl_7tpCKB1_OYKcSRz9:bosdtoo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9623fabf0ef4fbead0f8c9020bb72458fc580c32/platforms/FlightModel/Include/mcu.h#L4)):*
> ```objc
> #define PLATFORMS_FLIGHTMODEL_INCLUDE_MCU_H_
> 
> #include "efm32gg280f1024.h"
> ```

You should be including `em_device.h`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168)*

**Comment by zaq32** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[platforms/DevBoard/Include/mcu.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168#-Kl_7g91sWEWPnmFKJg8:-Kl_ECN0lDfMQLfhf_wc:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9623fabf0ef4fbead0f8c9020bb72458fc580c32/platforms/DevBoard/Include/mcu.h#L4)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You should be including `em_device.h`
</blockquote></details>

Fixed

---

*[platforms/FlightModel/Include/mcu.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168#-Kl_7tpCKB1_OYKcSRz8:-Kl_EDfLknTjrhOPOfhI:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9623fabf0ef4fbead0f8c9020bb72458fc580c32/platforms/FlightModel/Include/mcu.h#L4)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You should be including `em_device.h`
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/168)*

**Comment by Novakov** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Pull request merged**
