### PR TITLE
Refactor OBC API used in Python tests

### PR DESCRIPTION
**Pull request by Novakov**
Separated `OBC`class into base class which handles power control and command interface. All actual commands were moved to separate classes added as mixins to `OBC`.

Also few decorators have been defined to simplify creating command (format as attribute, base64 encoding/decoding of parameters)

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/46)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 7 of 11 files at r1.
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/obc/CommandFormatter.py, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46#-KW02llXhnHwJFFiZXak:-KW02llXhnHwJFFiZXal:b53n46w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/73685a9fdef4d2c6d1f18358da512db55251dbbb/integration_tests/obc/CommandFormatter.py#L10)):*
> ```Python
>             return b64encode(value).rstrip('=')
> 
>         return super(CommandFormatter, self).convert_field(value, conversion)
> ```

I'd prefer composition instead of inheritance especially in case of standard utilities.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Comment by Novakov** [comment]
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/obc/CommandFormatter.py, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46#-KW02llXhnHwJFFiZXak:-KW3vYOnvCghfxIq_d0u:bxwhewa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/73685a9fdef4d2c6d1f18358da512db55251dbbb/integration_tests/obc/CommandFormatter.py#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> I'd prefer composition instead of inheritance especially in case of standard utilities.
</details>
`Formatter` is standard Python class that handles formating values. The only way to support more conversion is to subclass it. Unfortunately there is no interface-only base class 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Comment by zaq32** [comment]
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/obc/CommandFormatter.py, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46#-KW02llXhnHwJFFiZXak:-KW3zTNNnNtM4sjcxZFh:b-ko46qj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/73685a9fdef4d2c6d1f18358da512db55251dbbb/integration_tests/obc/CommandFormatter.py#L10)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> `Formatter` is standard Python class that handles formating values. The only way to support more conversion is to subclass it. Unfortunately there is no interface-only base class 
</details>
What about plain old aggregation/composition? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Comment by Novakov** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/obc/CommandFormatter.py, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46#-KW02llXhnHwJFFiZXak:-KWCFXLAZGNS5vV83CUB:b-9umcvj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/73685a9fdef4d2c6d1f18358da512db55251dbbb/integration_tests/obc/CommandFormatter.py#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> What about plain old aggregation/composition? 
</details>
I've improved it a bit. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Comment by zaq32** [comment]
Reviewed 1 of 3 files at r2.
Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Comment by zaq32** [comment]
Reviewed 3 of 11 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/46)*

**Pull request merged**
