### PR TITLE
Use lueart over DMA + better terminal handling

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/32)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 19 of 19 files at r1.
Review status: 12 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/drivers/leuart/Include/leuart/leuart.h, line 7 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxMyLXyNV5y72Bcgxx:-KPxMyLXyNV5y72Bcgxy:bmp2djn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/libs/drivers/leuart/Include/leuart/leuart.h#L7)):*
> ```objc
> #include "line_io.h"
> 
> void LeuartLineIOInit(LineIO* io);
> ```

Missing documentation.

---

*[platforms/DevBoard/Include/FreeRTOSConfig.h, line 85 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxNFbEf5Qwh6YnchDL:-KPxNFbEf5Qwh6YnchDM:bmp2djn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/platforms/DevBoard/Include/FreeRTOSConfig.h#L85)):*
> ```objc
>  *----------------------------------------------------------*/
> 
> extern void assertFailed(const char* source, const char* file, uint16_t line);
> ```

Missing documentation.

---

*[platforms/DevBoard/Include/FreeRTOSConfig.h, line 87 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxNL13v-pOlb2Bm1KN:-KPxNL13v-pOlb2Bm1KO:b-k32afa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/platforms/DevBoard/Include/FreeRTOSConfig.h#L87)):*
> ```objc
> extern void assertFailed(const char* source, const char* file, uint16_t line);
> 
> #define configASSERT(x)                                                                                                                    \
> ```

Provide empty version for release builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by Novakov** [comment]
Review status: 8 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/drivers/leuart/Include/leuart/leuart.h, line 7 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxMyLXyNV5y72Bcgxx:-KQoim7oa9zn9geqvZ8v:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/libs/drivers/leuart/Include/leuart/leuart.h#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Missing documentation.
</details>
Done.

---

*[platforms/DevBoard/Include/FreeRTOSConfig.h, line 85 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxNFbEf5Qwh6YnchDL:-KQoinKndKM9xx9VDHJo:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/platforms/DevBoard/Include/FreeRTOSConfig.h#L85)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Missing documentation.
</details>
Done.

---

*[platforms/DevBoard/Include/FreeRTOSConfig.h, line 87 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KPxNL13v-pOlb2Bm1KN:-KQoincdm04UZ1NwsENu:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/89a090e770348581293c752baccc4abb5834cd69/platforms/DevBoard/Include/FreeRTOSConfig.h#L87)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Provide empty version for release builds.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by decu69** [comment]
Reviewed 1 of 19 files at r1, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[platforms/DevBoard/Include/io_map.h, line 16 \[r3\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KQvK4UqzKpe5MMRmjYm:-KQvK4UqzKpe5MMRmjYn:bd0ljmi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b989ab5a1dc10f935fb45a48e8d0b95aa682d69d/platforms/DevBoard/Include/io_map.h#L16)):*
> ```objc
> #define LEUART0_RX 5
> #define LEUART0_LOCATION LEUART_ROUTE_LOCATION_LOC0
> #define LEUART0_BAUDRATE 2400
> ```

is there any reason for changing this baudrate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by zaq32** [comment]
Reviewed 6 of 13 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by decu69** [comment]
Reviewed 3 of 19 files at r1, 4 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[platforms/DevBoard/Include/io_map.h, line 16 \[r3\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-KQvK4UqzKpe5MMRmjYm:-KQw0dub9fldBBBEy6rS:bbzkj6d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b989ab5a1dc10f935fb45a48e8d0b95aa682d69d/platforms/DevBoard/Include/io_map.h#L16)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> is there any reason for changing this baudrate?
</details>
9600 does not work. Possibly as a result of error in clock generation. See EFM32GG Reference Manual, page 500, table 19.2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32)*

**Comment by zaq32** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/32#-:-KR2VYYyMQUiwMjEPnP1:bnfp4nl)*

**Pull request merged**
