### PR TITLE
[TC][purge_photo] Add command to reset state of the photo service.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/272)

### CODE REVIEW

**Comment by zaq32** [comment]
[[TC] Purge PhotoService](https://trello.com/c/umrK40IY/244-tc-purge-photoservice)

**Comment by Novakov** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/tests/test_telecommands_photo.py, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272#-Ks4gEq_GPP3rHhc6xjv:-Ks4gEq_GPP3rHhc6xjw:bb7hquh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b24b6accd52cfeba7d301ac812c121d8a0785295/integration_tests/tests/test_telecommands_photo.py#L50)):*
> ```Python
>         self._start()
> 
>         sail_opening = TestEvent()
> ```

huh?

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp, line 43 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272#-Ks4gQ-oFCmCoMhWYoCG:-Ks4gQ-oFCmCoMhWYoCH:btb5h3l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b24b6accd52cfeba7d301ac812c121d8a0785295/libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp#L43)):*
> ```cpp
> 
>         /**
>          * @brief Take photo telecommand
> ```

Not really...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272)*

**Comment by zaq32** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/tests/test_telecommands_photo.py, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272#-Ks4gEq_GPP3rHhc6xjv:-Ks4ofNWzW2zJ10G9Cnb:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b24b6accd52cfeba7d301ac812c121d8a0785295/integration_tests/tests/test_telecommands_photo.py#L50)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp, line 43 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272#-Ks4gQ-oFCmCoMhWYoCG:-Ks4ofnOegiGHnkWbHI3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b24b6accd52cfeba7d301ac812c121d8a0785295/libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp#L43)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Not really...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/272)*

**Pull request merged**
