### PR TITLE
[TeleComm] Added RemoveFile command

### PR DESCRIPTION
**Pull request by kfazi**
I had to increase stack size for `CommTask` from 2kB to 4kB because of failing integration tests.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/130)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 132 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KiEtBDkkCQwltJfl-H7:-KiEtBDkkCQwltJfl-H8:bq09ntk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dcde242bce62a8e1f2a0eeeba9cad64ef4295e19/libs/obc/communication/telecommands/file_system.cpp#L132)):*
> ```cpp
>             {
>                 LOG(LOG_LEVEL_ERROR, "Unable to open requested file");
>                 DownlinkFrame errorResponse(DownlinkAPID::FileNotFound, 0);
> ```

Sending simple "succeeded" response won't do.  Due to the nature of the gs <-> obc communication we will not wait for the obc to respond to one TC before sending another.  threfore if a response is sent back it has to be constructed in such way that it is possible to map it to the specific request out of many that has been sent.  The very least include original tc apid  in response frame. 

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KiEuSv64bEpN_aBLU9P:-KiEuSv64bEpN_aBLU9Q:b-v581y7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dcde242bce62a8e1f2a0eeeba9cad64ef4295e19/libs/telecommunication/include/telecommunication/downlink.h#L28)):*
> ```objc
>             Success = 0x0,         //!< Success frame
>             Pong = 0x01,           //!< Pong
>             FileNotFound = 0x2,    //!< Error frame: file not found
> ```

There should be one apid assigned to be a response for purely operational commands. If we assign every possible error its own apid we will soon run out of apids for experiments. Remeber that apids are only 6bit values. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by zaq32** [comment]
Reviewed 8 of 11 files at r3.
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by zaq32** [comment]
Reviewed 2 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by Novakov** [comment]
Reviewed 11 of 14 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjSMAtmCZszxjF5Pnfp:-KjSMAtmCZszxjF5Pnfq:bj3hv9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3b65bd15d05d2de51358916eea7e3f22766dc8c1/libs/obc/communication/telecommands/file_system.cpp#L39)):*
> ```cpp
>         bool FileSender::SendPart(std::uint32_t seq)
>         {
>             auto maxFileDataSize = DownlinkFrame::MaxPayloadSize - 2;
> ```

constexpr in `FileSender` class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by kfazi** [comment]
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 132 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KiEtBDkkCQwltJfl-H7:-KjSae8zBHaeAi10SQGr:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dcde242bce62a8e1f2a0eeeba9cad64ef4295e19/libs/obc/communication/telecommands/file_system.cpp#L132)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Sending simple "succeeded" response won't do.  Due to the nature of the gs <-> obc communication we will not wait for the obc to respond to one TC before sending another.  threfore if a response is sent back it has to be constructed in such way that it is possible to map it to the specific request out of many that has been sent.  The very least include original tc apid  in response frame. 
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 39 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjSMAtmCZszxjF5Pnfp:-KjSaMYzAXjc9-6b5hvt:b-3ul6ij) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3b65bd15d05d2de51358916eea7e3f22766dc8c1/libs/obc/communication/telecommands/file_system.cpp#L39)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

constexpr in `FileSender` class
</blockquote></details>

This issue came from pull request #140 and it is corrected there as well

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KiEuSv64bEpN_aBLU9P:-KjSagwopOC0mMgcFKXX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dcde242bce62a8e1f2a0eeeba9cad64ef4295e19/libs/telecommunication/include/telecommunication/downlink.h#L28)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

There should be one apid assigned to be a response for purely operational commands. If we assign every possible error its own apid we will soon run out of apids for experiments. Remeber that apids are only 6bit values. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by zaq32** [comment]
Reviewed 4 of 14 files at r1, 10 of 14 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 119 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTsXFfTbieOwJNPOoO:-KjTsXFfTbieOwJNPOoP:bnrn2lq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/file_system.cpp#L119)):*
> ```cpp
>             auto correlationId = r.ReadByte();
>             auto pathLength = r.ReadByte();
>             auto pathSpan = r.ReadArray(pathLength);
> ```

missing verification of reader status after the last read operation.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 120 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTs_1R7gZoHci05KsY:-KjTs_1R7gZoHci05KsZ:bj0ijfk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/file_system.cpp#L120)):*
> ```cpp
>             auto pathLength = r.ReadByte();
>             auto pathSpan = r.ReadArray(pathLength);
>             auto path = reinterpret_cast<const char*>(pathSpan.data());
> ```

missing verification that path is null terminated.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp, line 66 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTs5lfcrKfU5y6S3mG:-KjTs5lfcrKfU5y6S3mH:b-z0d6bs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp#L66)):*
> - Array of 32-bit LE - Sequence numbers of parts that will be send·
this line is not supposed to be here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by kfazi** [comment]
Review status: 12 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 119 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTsXFfTbieOwJNPOoO:-KjUY4vTM_r6gM4a2MT-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/file_system.cpp#L119)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing verification of reader status after the last read operation.
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 120 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTs_1R7gZoHci05KsY:-KjUY6bv9tERT_qX_Eie:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/file_system.cpp#L120)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing verification that path is null terminated.
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp, line 66 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130#-KjTs5lfcrKfU5y6S3mG:-KjUY9Zkqy35zNHeH_rd:b-7ljcya) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0a3e99cf4a2daae86123fab4d3089b5fcb73ccd/libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp#L66)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> - Array of 32-bit LE - Sequence numbers of parts that will be send·
this line is not supposed to be here
</blockquote></details>

Why not? This allows to download files in chunks.
And this line corresponds to DownloadFileTelecommand, which I'm refactoring in PR #140 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by zaq32** [comment]
Reviewed 1 of 14 files at r4, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Comment by Novakov** [comment]
Reviewed 1 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/130)*

**Pull request merged**
