### PR TITLE
Experiment leop

### PR DESCRIPTION
**Pull request by tom4r**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/232)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Experiment] LEOP](https://trello.com/c/0tGcuogi/199-experiment-leop)

**Comment by Novakov** [comment]
Reviewed 26 of 26 files at r1.
Review status: 24 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[integration_tests/tests/test_experiment_leop.py, line 29 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc7OJAdHWd1pEdGnzE:-Kqc7OJAdHWd1pEdGnzF:bm92qri) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/integration_tests/tests/test_experiment_leop.py#L29)):*
> ```Python
> 
>     @runlevel(2)
>     def test_should_perform_experiment(self):
> ```

Use `@clear_state()`

---

*[libs/experiments/fs/ExperimentFile.cpp, line 130 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc1A749sPleTBM8TC_:-Kqc1A749sPleTBM8TCa:b-yw5axm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/ExperimentFile.cpp#L130)):*
> ```cpp
>     if (_time != nullptr)
>     {
>         const auto& timestamp = _time->GetCurrentTime();
> ```

I don't think that using reference here is valid

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc2HvoSVl-87FRqbRw:-Kqc2HvoSVl-87FRqbRx:b-hr7m65) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L41)):*
> ```cpp
>           public:
>             /** @brief Data packet length.  */
>             static constexpr uint16_t PacketLength = 232;
> ```

Add static_assert somewhere to validate that this size matches size of payload in downlink frame.
Also each frame with part of file contains correlation ID, so there is 231 bytes for data

---

*[libs/mission/leop/leop.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc31OOI6AIUnXUNo3B:-Kqc31OOI6AIUnXUNo3C:ba9cxpl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/mission/leop/leop.cpp#L15)):*
> ```cpp
>     namespace leop
>     {
>         LEOPTask::LEOPTask(::experiments::ExperimentController& experimentController) : _experimentController(experimentController)
> ```

Use interface `IExperimentController` here 

---

*[libs/mission/leop/Include/mission/leop_task.hpp, line 53 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc3E-9FQCL8EQGPmhT:-Kqc3E-9FQCL8EQGPmhU:b-hk7jw7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/mission/leop/Include/mission/leop_task.hpp#L53)):*
> ```cpp
> 
>             /** @brief Flag indicating whether experiment is enabled */
>             std::atomic<bool> _isEnabled{true};
> ```

Change name of this field to something more meaningful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by Novakov** [comment]
Review status: 24 of 26 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqdMw3bcvDPVlAja402:-KqdMw3bcvDPVlAja403:b-cb2i9n) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L37)):*
> ```cpp
>          * until the end - padding data (0xFF)
>          */
>         class ExperimentFile
> ```

There is a resource leak in this class. If it's destroyed without calling `Close` there underlying file handle will never be closed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by zaq32** [comment]
Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 130 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc1A749sPleTBM8TC_:-KqhKOt91QBU0XMbk8c1:b2n05dv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/ExperimentFile.cpp#L130)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't think that using reference here is valid
</blockquote></details>

Its not an error here. 

---

*[libs/experiments/fs/ExperimentFile.cpp, line 45 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhKgNcCDTUl8Kf49Ym:-KqhKgNdbhZvMql4Bxho:b-x46sn8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L45)):*
>             _writer.WriteByte(num(pid));
>             _writer.WriteArray(data);
the length of data may be larger than frame free space limit. Either use `WriteBiggerThanFrame` method or recheck the space size again

---

*[libs/experiments/fs/ExperimentFile.cpp, line 66 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhLiLAYN0pKVANznP8:-KqhLiLAYN0pKVANznP9:bwkv7xk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L66)):*
>         uint32_t length = _writer.RemainingSize() - PIDSize;
>         if (length > dataRemaining)
>             length = dataRemaining;

`const auto length = std::min(dataRemaining, writer.RemainingSize() - PIDSize);`

---

*[libs/experiments/fs/ExperimentFile.cpp, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhLOf_p-w-d5iuWgVX:-KqhLOf_p-w-d5iuWgVY:b-trziof) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L68)):*
> ```cpp
>             length = dataRemaining;
> 
>         auto&& subpart = data.subspan(offset, length);
> ```

why not simply `auto subpart`?

---

*[libs/experiments/fs/ExperimentFile.cpp, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhMvBrg_5ICggUujsC:-KqhMvBrg_5ICggUujsD:b-wjicg3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L118)):*
> for (int i = 1; i < freeSpace; ++i)
>     {
>         _writer.WriteByte(0xFF);
>     }
consider extending writer with `bool Fill(std::uint8_t byte)` method

---

*[libs/experiments/fs/ExperimentFile.cpp, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhN1hEC3Lp8nWNroBT:-KqhN1hEC3Lp8nWNroBU:b-5clpaq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L118)):*
> ```cpp
>     for (int i = 1; i < freeSpace; ++i)
>     {
>         _writer.WriteByte(0xFF);
> ```

use PID::Padding instead of hardcoded value

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqdMw3bcvDPVlAja402:-KqhJrMwkRcU5BeOVelD:bvsfuq6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L37)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

There is a resource leak in this class. If it's destroyed without calling `Close` there underlying file handle will never be closed
</blockquote></details>

the services::fs::File class is responsible for closing underlying file handle, 

However if this class is destroyed without calling `close` the last opened frame will be lost.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 60 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhNGRmBV_W6KSvFEJQ:-KqhNGRmBV_W6KSvFEJR:b-3gun2l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L60)):*
> ```cpp
>             /**
>              * @brief Default constrctor
>              * @param time Optional time provider. If set, each packet automatically has timestamp.
> ```

has -> have a 

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 111 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhNStJkILqA4OKRKus:-KqhNStJkILqA4OKRKut:b-bwcy0c) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L111)):*
> FillBufferWithPadding();
>             void InitializePacket();
> 
>             OSResu
methods should be declared before fields.

---

*[libs/experiments/leop/leop.cpp, line 61 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhQ3iN6MdMNoT9XjO-:-KqhQ3iN6MdMNoT9XjO0:bjxl85s) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/leop/leop.cpp#L61)):*
> ```cpp
>             }
> 
>             return IterationResult::WaitForNextCycle;
> ```

i do not think that > 10 delays are acceptable here. Although this experiment is not fully defined it does says something like this:
```
Start gyroscopes acquisition with high sample rate
```
https://team.pw-sat.pl/w/oper/mission_plan/

---

*[libs/mission/leop/leop.cpp, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhPBCLEi2h_PBEF-3V:-KqhPBCLEi2h_PBEF-3W:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/mission/leop/leop.cpp#L9)):*
> ```cpp
> #include "system.h"
> 
> using namespace std::chrono_literals;
> ```

unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by Novakov** [comment]
Reviewed 1 of 2 files at r3, 25 of 25 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[integration_tests/tests/test_experiment_leop.py, line 77 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsK_wFCV-G3W5_BiAO:-KqsK_wFCV-G3W5_BiAP:b-ljwtlg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/integration_tests/tests/test_experiment_leop.py#L77)):*
> ```Python
> 
>         # wait until all mission descriptors will be processed
>         sleep(20)
> ```

whoa... that's really not nice

---

*[src/checks/checks.cpp, line 7 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsLQzAHx6s2OYZl8an:-KqsLQzAHx6s2OYZl8ao:bsouykj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/src/checks/checks.cpp#L7)):*
> ```cpp
> {
>     static_assert(experiments::fs::ExperimentFile::PacketLength == telecommunication::downlink::DownlinkFrame::MaxPayloadSize,
>         "Packet Length is not equal to downlink frame size");
> ```

Downloading file uses `CorrelatedDownlinkFrame` which has one byte less space than `DownlinkFrame`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[libs/mission/leop/leop.cpp, line 58 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsNrJqLLlZQjN6ithq:-KqsNrJqLLlZQjN6ithr:bqwk3x0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/libs/mission/leop/leop.cpp#L58)):*
> ```cpp
> 
>             return This->_isStartAllowed && isTimeForStart;
>         }
> ```

You can just wait for `currentTime >= 1min`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by tom4r** [comment]
Review status: 39 of 41 files reviewed at latest revision, 18 unresolved discussions.

---

*[integration_tests/tests/test_experiment_leop.py, line 29 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc7OJAdHWd1pEdGnzE:-KqrqPFwe3uyXF5MHlJ1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/integration_tests/tests/test_experiment_leop.py#L29)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Use `@clear_state()`
</blockquote></details>

Done.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 130 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc1A749sPleTBM8TC_:-KqrrA4oiJgd7DFA5Cpg:bo71wb2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/ExperimentFile.cpp#L130)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Its not an error here. 
</blockquote></details>

I removed the reference.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 45 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhKgNcCDTUl8Kf49Ym:-KqrqUC5SYiLpMZZvwdE:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L45)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>             _writer.WriteByte(num(pid));
>             _writer.WriteArray(data);
the length of data may be larger than frame free space limit. Either use `WriteBiggerThanFrame` method or recheck the space size again


</blockquote></details>

Fixed.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 66 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhLiLAYN0pKVANznP8:-KqrqXx2jUZ3TK-2Ssng:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L66)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         uint32_t length = _writer.RemainingSize() - PIDSize;
>         if (length > dataRemaining)
>             length = dataRemaining;

`const auto length = std::min(dataRemaining, writer.RemainingSize() - PIDSize);`
</blockquote></details>

Done.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhLOf_p-w-d5iuWgVX:-KqrqbBeg3yO98Sp-Ck6:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L68)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why not simply `auto subpart`?
</blockquote></details>

Fixed.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhMvBrg_5ICggUujsC:-KqrqczCaobUkh2F7Czc:bkm9xou) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L118)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> for (int i = 1; i < freeSpace; ++i)
>     {
>         _writer.WriteByte(0xFF);
>     }
consider extending writer with `bool Fill(std::uint8_t byte)` method
</blockquote></details>

Added Fill to Writer.

---

*[libs/experiments/fs/ExperimentFile.cpp, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhN1hEC3Lp8nWNroBT:-KqrqgdPD9u9cHL4ilhI:bnrrrtu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/ExperimentFile.cpp#L118)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use PID::Padding instead of hardcoded value
</blockquote></details>

Added PaddingData Constexpr.

This and PID is not exactly the same by design. PID should be easily expanded to 16 bits and here should be always 0xFF.
I created manual file explaining the concepts behind that file format.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqdMw3bcvDPVlAja402:-KqrrGyNjcRrhaGdbm8r:b-pfvi7f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

the services::fs::File class is responsible for closing underlying file handle, 

However if this class is destroyed without calling `close` the last opened frame will be lost.
</blockquote></details>

Added desctuctor that closes file and saves last frame if it has any real data.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc2HvoSVl-87FRqbRw:-KqrrPqFG5qkvMckuNHv:bqmjwcz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L41)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add static_assert somewhere to validate that this size matches size of payload in downlink frame.
Also each frame with part of file contains correlation ID, so there is 231 bytes for data
</blockquote></details>

Added.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 60 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhNGRmBV_W6KSvFEJQ:-KqsmFmxUhHDed9UtKXK:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L60)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

has -> have a 
</blockquote></details>

Fixed.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 111 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhNStJkILqA4OKRKus:-KqrrmAgTTX3lsHH2SvG:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L111)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> FillBufferWithPadding();
>             void InitializePacket();
> 
>             OSResu
methods should be declared before fields.
</blockquote></details>

Fixed.

---

*[libs/experiments/leop/leop.cpp, line 61 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhQ3iN6MdMNoT9XjO-:-KqrrpqY0M42kgoa4l65:bt7sx8w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/experiments/leop/leop.cpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

i do not think that > 10 delays are acceptable here. Although this experiment is not fully defined it does says something like this:
```
Start gyroscopes acquisition with high sample rate
```
https://team.pw-sat.pl/w/oper/mission_plan/
</blockquote></details>

Fixed.
The high sample rate is now defined as 1Hz.

---

*[libs/mission/leop/leop.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc31OOI6AIUnXUNo3B:-Kqrs4CJyWzdrLpe3fan:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/mission/leop/leop.cpp#L15)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Use interface `IExperimentController` here 
</blockquote></details>

Fixed.

---

*[libs/mission/leop/leop.cpp, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqhPBCLEi2h_PBEF-3V:-Kqrs1ADr42gNQ0xERCE:ba3dfob) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/488141e1ac0f2c73feaa6bc09b1a6747b50692b0/libs/mission/leop/leop.cpp#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Removed

---

*[libs/mission/leop/Include/mission/leop_task.hpp, line 53 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-Kqc3E-9FQCL8EQGPmhT:-Kqrs7ur3HGxaiNJAEHh:b2dfaoj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e5136d6d6a6e99eaeee323828754142ae89b5a1b/libs/mission/leop/Include/mission/leop_task.hpp#L53)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Change name of this field to something more meaningful
</blockquote></details>

Field renamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r3, 23 of 25 files at r4, 1 of 2 files at r5.
Review status: 40 of 41 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[unit_tests/others/base/WriterTest.cpp, line 277 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqvABwlfrk-4XkxVPws:-KqvABwlfrk-4XkxVPwt:b8lkb8b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d493ef110543a4ae826faa537b431f4f6af10183/unit_tests/others/base/WriterTest.cpp#L277)):*
> ```cpp
>     }
> 
>     TEST(WriterTest, TestFill)
> ```

you may want to test Fill on empty/full buffer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by zaq32** [comment]
Reviewed 1 of 25 files at r4.
Review status: 40 of 41 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by Novakov** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by tom4r** [comment]
Review status: 30 of 41 files reviewed at latest revision, 4 unresolved discussions.

---

*[integration_tests/tests/test_experiment_leop.py, line 77 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsK_wFCV-G3W5_BiAO:-KqyUxOmo5DFxChakY5Q:b7slvph) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/integration_tests/tests/test_experiment_leop.py#L77)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

whoa... that's really not nice
</blockquote></details>

Ugly code removed.

---

*[libs/mission/leop/leop.cpp, line 58 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsNrJqLLlZQjN6ithq:-KqyUXg74LIz0s-eGCsv:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/libs/mission/leop/leop.cpp#L58)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can just wait for `currentTime >= 1min`
</blockquote></details>

Done.

---

*[src/checks/checks.cpp, line 7 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqsLQzAHx6s2OYZl8an:-KqyUmPizJLELIPrnXwM:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/69f919df55aab207fae902755a28ecfdcbb90b00/src/checks/checks.cpp#L7)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Downloading file uses `CorrelatedDownlinkFrame` which has one byte less space than `DownlinkFrame`
</blockquote></details>

Fixed.

---

*[unit_tests/others/base/WriterTest.cpp, line 277 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232#-KqvABwlfrk-4XkxVPws:-KqyUuSvYRI5-3KA8tbz:b-wj4ea6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d493ef110543a4ae826faa537b431f4f6af10183/unit_tests/others/base/WriterTest.cpp#L277)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

you may want to test Fill on empty/full buffer.
</blockquote></details>

Tests added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by Novakov** [comment]
Reviewed 14 of 14 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Comment by zaq32** [comment]
Reviewed 5 of 14 files at r6, 6 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/232)*

**Pull request merged**
