### PR TITLE
Renamed UART to UART_1, added pinout for UART_0, refactored Uart drive

### PR DESCRIPTION
**Pull request by mandrek44**
... to support different ports

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/217)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217)*

**Comment by Novakov** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/uart/Include/uart/uart.hpp, line 284 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217#-Kpzy65vXqQkpwjz7Pzf:-Kpzy65vXqQkpwjz7Pzg:b-3vs56t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c91b30ba272eec462d5f556398ecfedf7fa5a67e/libs/drivers/uart/Include/uart/uart.hpp#L284)):*
> ```cpp
>                 this);
> 
>             _event.WaitAll(Event::TransferRXFinished, true, InfiniteTimeout);
> ```

It maybe worth putting some timeout here as it is possible to loose some of incoming bytes.

---

*[libs/obc/hardware/hardware.cpp, line 65 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217#-KpzyNdHC1vUI0kyTe9i:-KpzyNdHC1vUI0kyTe9j:bydehtm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c91b30ba272eec462d5f556398ecfedf7fa5a67e/libs/obc/hardware/hardware.cpp#L65)):*
> ```cpp
>     this->I2C.Initialize();
> 
> #ifndef USE_LEUART
> ```

I guess we ca remove usage of that not defined define :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217)*

**Comment by mandrek44** [comment]
Review status: 10 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/uart/Include/uart/uart.hpp, line 284 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217#-Kpzy65vXqQkpwjz7Pzf:-Kq9BfzRGGFHj0zJmycc:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c91b30ba272eec462d5f556398ecfedf7fa5a67e/libs/drivers/uart/Include/uart/uart.hpp#L284)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It maybe worth putting some timeout here as it is possible to loose some of incoming bytes.
</blockquote></details>

Done.

---

*[libs/obc/hardware/hardware.cpp, line 65 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217#-KpzyNdHC1vUI0kyTe9i:-Kq9BgvWH0obmOeQ8hvn:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c91b30ba272eec462d5f556398ecfedf7fa5a67e/libs/obc/hardware/hardware.cpp#L65)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I guess we ca remove usage of that not defined define :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217)*

**Comment by zaq32** [comment]
Reviewed 4 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/217)*

**Pull request merged**
