### PR TITLE
Wait for COMM bootup

### PR DESCRIPTION
**Pull request by ggajoch**
After hardware reset of COMM delay is necessary - hardware reset performs power cycle of COMMs module and it takes some time to initialise.

2017-10-20-014716_1920x1200_scrot

Moved resetting COMM to `OBCCommunication::InitializeRunlevel1`.

[NCR#13](https://team.pw-sat.pl/w/ncr/ncr13/)

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/367)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 233 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367#-Kwtxn22bNcSIS3V8lPm:-Kwtxn22bNcSIS3V8lPn:bhvp9vr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94d53cefb034a3d5676ab0b73bd498859e4d4541/libs/drivers/comm/comm.cpp#L233)):*
> ```cpp
> {
>     auto result = this->SendCommand(Address::Receiver, num(ReceiverCommand::HardReset), resultAggregator);
>     System::SleepTask(2000ms);
> ```

You just made builds longer by few minutes...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367)*

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367)*

**Comment by ggajoch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 233 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367#-Kwtxn22bNcSIS3V8lPm:-Kwu3t5y7h6vrfMHrNgu:b9n12wt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94d53cefb034a3d5676ab0b73bd498859e4d4541/libs/drivers/comm/comm.cpp#L233)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You just made builds longer by few minutes...
</blockquote></details>

Other possibility to get away with this is simply not resetting the TRxVU, assuming that after power cycle it will be in clean state. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 233 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367#-Kwtxn22bNcSIS3V8lPm:-KwxtgqgFRojU3_mkQq1:b-4v73yu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94d53cefb034a3d5676ab0b73bd498859e4d4541/libs/drivers/comm/comm.cpp#L233)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

Other possibility to get away with this is simply not resetting the TRxVU, assuming that after power cycle it will be in clean state. 
</blockquote></details>

That's also valid option

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367)*

**Comment by Novakov** [comment]
Reviewed 1 of 12 files at r2, 4 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/367)*

**Pull request merged**
