### PR TITLE
Experiment file cleanup

### PR DESCRIPTION
**Pull request by tom4r**
And parser enhancements

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/285)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[integration_tests/devices/suns.py, line 69 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqs-hd2IOr5juDkvES:-Ksqs-hd2IOr5juDkvET:b-qj2kzj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/devices/suns.py#L69)):*
> ```Python
>             self.gpio_interrupt_low()
> 
>         t = Timer(0.1, finish)
> ```

It would be nice to get configurable callback delay

---

*[integration_tests/experiment_file/camera.py, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-KsqrPQLdIfw06VGEKb3:-KsqrPQLdIfw06VGEKb4:b-b6sdpu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/camera.py#L6)):*
> ```Python
> from parsing import byte
> 
> CameraSyncCount = pid(0x37) >> count(byte, 1)
> ```

Count is not needed here

---

*[integration_tests/experiment_file/payload.py, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqrk7brN4wnXViUyqm:-Ksqrk7brN4wnXViUyqn:bbi1zyn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/payload.py#L66)):*
> ```Python
>         while len(parsers) > 0:
>             parser = parsers.pop()
>             parser.parse()
> ```

It would be nice to move this code to some utitily function - is it few places already

---

*[integration_tests/experiment_file/payload.py, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqrb7hQyJMoGJJXCji:-Ksqrb7hQyJMoGJJXCjj:b-b6sdpu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/payload.py#L72)):*
> ```Python
>         return Value.failure(index, 'Decode failed')
> 
> PayloadObcTelemetry = pid(0x36) >> count(PayloadParser, 1)
> ```

Count is not needed here

---

*[unit_tests/properties/Experiments/SunSDataPointTest.cpp, line 139 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqssgp5uR-YPtgplb9:-Ksqssgp5uR-YPtgplbA:bka9q29) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/unit_tests/properties/Experiments/SunSDataPointTest.cpp#L139)):*
> ```cpp
> 
>         w.WriteByte(num(ExperimentFile::PID::ExperimentalSunSPrimary));
>         w.WriteByte(point.ExperimentalSunS.whoami);
> ```

Constant is better is this test 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285)*

**Comment by tom4r** [comment]
[[Experiment File] Extend parser and cleanup](https://trello.com/c/bBeRpEum/253-experiment-file-extend-parser-and-cleanup)

**Comment by tom4r** [comment]
Review status: 23 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[integration_tests/devices/suns.py, line 69 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqs-hd2IOr5juDkvES:-Ksr94vEYY0s9Q0j69Op:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/devices/suns.py#L69)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be nice to get configurable callback delay
</blockquote></details>

Done

---

*[integration_tests/experiment_file/camera.py, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-KsqrPQLdIfw06VGEKb3:-Ksr6XrmcfQyqLzx27sv:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/camera.py#L6)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Count is not needed here
</blockquote></details>

Fixed

---

*[integration_tests/experiment_file/payload.py, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqrk7brN4wnXViUyqm:-Ksr9AkUxklNhOVXfdhf:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/payload.py#L66)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be nice to move this code to some utitily function - is it few places already
</blockquote></details>

Done

---

*[integration_tests/experiment_file/payload.py, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqrb7hQyJMoGJJXCji:-Ksr9DKcK-vFBd8Yytpl:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/integration_tests/experiment_file/payload.py#L72)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Count is not needed here
</blockquote></details>

Fixed

---

*[unit_tests/properties/Experiments/SunSDataPointTest.cpp, line 139 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285#-Ksqssgp5uR-YPtgplb9:-Ksr9ICaCuT38HGhHCOF:bwvyox4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bae7becd778199c5d017fd81496707d6b5eaf038/unit_tests/properties/Experiments/SunSDataPointTest.cpp#L139)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Constant is better is this test 
</blockquote></details>

Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/285)*

**Pull request merged**
