### PR TITLE
Telecommand: copy boot slots

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/306)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] Copy boot slot](https://trello.com/c/8gshKaZe/264-tc-copy-boot-slot)

**Comment by zaq32** [comment]
Reviewed 4 of 11 files at r1, 15 of 17 files at r2.
Review status: 19 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306)*

**Comment by zaq32** [comment]
Reviewed 2 of 17 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/experiments/program/program_exp.cpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4gnE8Ti1_CeLwQPup:-Ku4gnE8Ti1_CeLwQPuq:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L37)):*
> ```cpp
>         }
> 
>         static inline DownlinkFrame WriteProgramError(std::uint8_t errorCode, std::uint8_t entry, std::uint32_t offset)
> ```

unused

---

*[libs/experiments/program/program_exp.cpp, line 49 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4goAFYYTPkaswRX84:-Ku4goAGXQ7hhI_4KZMf:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L49)):*
> ```cpp
>         }
> 
>         static inline DownlinkFrame FinalizeEntryWriteError(std::uint8_t errorCode, std::uint8_t entry)
> ```

unused

---

*[libs/experiments/program/program_exp.cpp, line 61 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4goaNwzMONcNfui_o:-Ku4goaNwzMONcNfui_p:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L61)):*
> ```cpp
>         }
> 
>         static inline DownlinkFrame FinalizeEntryCRCError(std::uint8_t entry, std::uint16_t actualCrc)
> ```

unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306)*

**Comment by Novakov** [comment]
Review status: 20 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/program/program_exp.cpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4gnE8Ti1_CeLwQPup:-Ku5K4TuojY3pcYWo8L9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

---

*[libs/experiments/program/program_exp.cpp, line 49 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4goAFYYTPkaswRX84:-Ku5K3RKTP4kL8_Xv3n1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L49)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

---

*[libs/experiments/program/program_exp.cpp, line 61 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306#-Ku4goaNwzMONcNfui_o:-Ku5K3g4PhO8K4zrdYwD:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54a04ecec75a630dff88e083cee07e71fac74b03/libs/experiments/program/program_exp.cpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/306)*

**Pull request merged**
