### PR TITLE
No more COMM beacon

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/312)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 267 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuL9vnDNhWKKaJMhjaE:-KuL9vnDNhWKKaJMhjaF:b-kvmc15) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/src/main.cpp#L267)):*
> ```cpp
>         }
> 
>         Main.Hardware.CommDriver.SendFrame(frame.Frame());
> ```

there is no point to send frame if it could not be constructed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Comment by zaq32** [comment]
Reviewed 2 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Comment by zaq32** [comment]
Reviewed 3 of 7 files at r1, 9 of 13 files at r2.
Review status: 12 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 54 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrZQ_3OX4J3EdIDIG:-KuLrZQ_3OX4J3EdIDIH:b-nngqc3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/libs/mission/beacon/BeaconUpdate.cpp#L54)):*
> ```cpp
>     {
>         auto This = static_cast<BeaconUpdate*>(param);
>         //        auto&& timeDifference = state.Time - This->lastBeaconUpdate;
> ```

remove this no longer used code

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 56 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrbNJjNcUmM7J1wQc:-KuLrbNKaJcjQzQ6LpYA:b-nngqc3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/libs/mission/beacon/BeaconUpdate.cpp#L56)):*
> ```cpp
>         //        auto&& timeDifference = state.Time - This->lastBeaconUpdate;
>         return state.AntennaState.IsDeployed() && This->_beaconTaskHandle != nullptr; // && //
>         //            (timeDifference >= BeaconUpdateInterval || timeDifference < std::chrono::milliseconds::zero());
> ```

remove this no longer used code

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 87 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrcahImixnZYl3jzP:-KuLrcahImixnZYl3jzQ:b-nngqc3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/libs/mission/beacon/BeaconUpdate.cpp#L87)):*
> ```cpp
>         //        {
>         //            LOGF(LOG_LEVEL_ERROR, "Unable to set beacon at %lu", time);
>         //        }
> ```

remove this no longer used code

---

*[src/main.cpp, line 252 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrnZt1LxwRYx5gvqg:-KuLrnZt1LxwRYx5gvqh:b-iohzju) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/src/main.cpp#L252)):*
> ```cpp
>     auto beaconDelay = 30s;
> 
>     while (1)
> ```

shouldn't beacon sender be used in here?

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 918 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrs-Lh8NSfv6QpIAt:-KuLrs-Lh8NSfv6QpIAu:b-nngqc3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/unit_tests/drivers/Comm/CommTest.cpp#L918)):*
> ```cpp
>         //                EXPECT_THAT(inData, Eq(span<const uint8_t>(expectedBeacon)));
>         //                return I2CResult::OK;
>         //            }));
> ```

remove this no longer used code

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 936 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrsd43Tbosh3NOWPj:-KuLrsd43Tbosh3NOWPk:b-nngqc3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/unit_tests/drivers/Comm/CommTest.cpp#L936)):*
> ```cpp
>         //                EXPECT_THAT(inData, Eq(span<const uint8_t>(expectedBeacon)));
>         //                return I2CResult::OK;
>         //            }));
> ```

remove this no longer used code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Comment by zaq32** [comment]
Reviewed 4 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Comment by Novakov** [comment]
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 918 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrs-Lh8NSfv6QpIAt:-KuNuww0wnum5YY6oSgM:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/unit_tests/drivers/Comm/CommTest.cpp#L918)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

remove this no longer used code
</blockquote></details>

Done.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 936 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312#-KuLrsd43Tbosh3NOWPj:-KuNux95wQNhG0HZHapk:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7193d39914b0ebbe4db6a65a01e56360d43ab3e7/unit_tests/drivers/Comm/CommTest.cpp#L936)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

remove this no longer used code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/312)*

**Pull request merged**
