### PR TITLE
SADS Experiment

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/273)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 27 of 30 files at r1.
Review status: 27 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[integration_tests/obc/experiments.py, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273#-Ks4z_EeZFElM8VPrL5J:-Ks4z_EeZFElM8VPrL5K:bm3datl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f48520769e8420813fbe7ff633887cdb4e494556/integration_tests/obc/experiments.py#L18)):*
> ```Python
>     Fibo = 8
>     Payload = 9,
>     SADS=10
> ```

originally sads were supposed to be available under id equal to 6

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 71 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273#-Ks4zxbn7b8wl_hhhhdb:-Ks4zxbn7b8wl_hhhhdc:b-82lmj4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f48520769e8420813fbe7ff633887cdb4e494556/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L71)):*
> ```cpp
>                 PayloadExperimentMainTelemetry = 0x36,
> 
>                 SADSTemperature = 0x31, // 2 bytes of data
> ```

conflicting id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Comment by mandrek44** [comment]
[[Experiment] SADS](https://trello.com/c/4X58xsJW/243-experiment-sads)

**Comment by mandrek44** [comment]
Review status: 21 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 71 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273#-Ks4zxbn7b8wl_hhhhdb:-Ks5M2ciPAIk9COBPr4L:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f48520769e8420813fbe7ff633887cdb4e494556/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L71)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

conflicting id
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Comment by zaq32** [comment]
Reviewed 2 of 30 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/experiments/sads/sads.cpp, line 141 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273#-KsAgGGvztU5064u_Vse:-KsAgGGvztU5064u_Vsf:b-hkm8j0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53ddd7ec2e84089b1550ff36a7a8ae6cc04675cd/libs/experiments/sads/sads.cpp#L141)):*
> ```cpp
> 
>             this->_photoService.DisableCamera(Camera::Nadir);
>             this->_photoService.DisableCamera(Camera::Wing);
> ```

nadir camera is not used in this experiment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Comment by mandrek44** [comment]
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/experiments/sads/sads.cpp, line 141 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273#-KsAgGGvztU5064u_Vse:-KsFFgZEFXAs8AUtI79u:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53ddd7ec2e84089b1550ff36a7a8ae6cc04675cd/libs/experiments/sads/sads.cpp#L141)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

nadir camera is not used in this experiment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/273)*

**Pull request merged**
