### PR TITLE
[TeleComm] Added SetTime telecommand

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/210)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/time.cpp, line 68 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kownz7yVx3sK-M_O3gX:-Kownz7yVx3sK-M_O3gY:b-ow789a) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b369585bbc836fd408b0359182ff7c253885575b/libs/obc/communication/telecommands/time.cpp#L68)):*
> ```cpp
>         }
> 
>         void SetTimeTelecommand::Handle(devices::comm::ITransmitter& transmitter, gsl::span<const std::uint8_t> parameters)
> ```

From technical standpoint this function is very much correct but there is a conceptual problem here....

And it will surface when time synchronization task will be executed concurrently to this telecommand, which can result in changes done by this telecommand being completely overwritten by time synchronization task while GS would still receive response indicating a success.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210)*

**Comment by zaq32** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/time.cpp, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn5k8Yv-YFXpi46hk6:-Kpn5k8Yv-YFXpi46hk7:b4m7dw7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L97)):*
> ```cpp
>                 response.PayloadWriter().WriteByte(-1);
>                 transmitter.SendFrame(response.Frame());
>                 return;
> ```

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope

---

*[libs/obc/communication/telecommands/time.cpp, line 114 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn60655y4sIpw2_tXc:-Kpn60655y4sIpw2_tXd:b4m7dw7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L114)):*
> ```cpp
>                 response.PayloadWriter().WriteByte(-2);
>                 transmitter.SendFrame(response.Frame());
>                 return;
> ```

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope

---

*[libs/obc/communication/telecommands/time.cpp, line 123 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn60ZyzIwdWnnlVKZb:-Kpn60ZyzIwdWnnlVKZc:b4m7dw7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L123)):*
> ```cpp
>                 response.PayloadWriter().WriteByte(-3);
>                 transmitter.SendFrame(response.Frame());
>                 return;
> ```

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope

---

*[unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp, line 50 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn68LdM7kJlstZo1as:-Kpn68LdM7kJlstZo1at:boh6lum) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp#L50)):*
> ```cpp
>     };
> 
>     SetTimeTelecommandTest::SetTimeTelecommandTest()
> ```

Perhaps some synchronization tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210)*

**Comment by kfazi** [comment]
Review status: 5 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/time.cpp, line 68 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kownz7yVx3sK-M_O3gX:-KrFLvYzdO5zvO8C5-Ya:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b369585bbc836fd408b0359182ff7c253885575b/libs/obc/communication/telecommands/time.cpp#L68)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

From technical standpoint this function is very much correct but there is a conceptual problem here....

And it will surface when time synchronization task will be executed concurrently to this telecommand, which can result in changes done by this telecommand being completely overwritten by time synchronization task while GS would still receive response indicating a success.
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/time.cpp, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn5k8Yv-YFXpi46hk6:-KrFNIm6X5l80s7FX7cm:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L97)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/time.cpp, line 114 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn60655y4sIpw2_tXc:-KrFNJmQIsL7X7bMItaZ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L114)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/time.cpp, line 123 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn60ZyzIwdWnnlVKZb:-KrFNKUCH0xOIid7CxhN:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/libs/obc/communication/telecommands/time.cpp#L123)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Time Synchronization  is still locked in here. Use RAII wrapper (preferably Lock type itself)  to control synchronization  scope
</blockquote></details>

Done.

---

*[unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp, line 50 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210#-Kpn68LdM7kJlstZo1as:-KrFT1gSU_ZumL-3gEYg:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/157a3d4f54c84b7d99a8df2387cd9bd60f3c625a/unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp#L50)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Perhaps some synchronization tests?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210)*

**Comment by zaq32** [comment]
Reviewed 10 of 11 files at r3.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210)*

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/210)*

**Pull request merged**
