### PR TITLE
Erase flash experiment

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/244)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 29 of 34 files at r1.
Review status: 29 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/obc/experiments.py, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrF2urT4Chb6jpEPyIU:-KrF2urT4Chb6jpEPyIV:b-6sqdig) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/integration_tests/obc/experiments.py#L14)):*
> ```Python
>     LEOP = 3
>     SunS = 4
>     EraseFlash = 7
> ```

7 is reserved for Sail

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244)*

**Comment by Novakov** [comment]
[[TC] Experiment - Erase flash](https://trello.com/c/cG4NjQSL/150-tc-experiment-erase-flash)

**Comment by zaq32** [comment]
Reviewed 5 of 34 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/experiments/flash/flash.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrFG-iKB_S03l4u7F5u:-KrFG-iKB_S03l4u7F5v:b-hy1g39) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/libs/experiments/flash/flash.cpp#L38)):*
> ```cpp
>             yaffsfs_Unlock();
> 
>             CorrelatedDownlinkFrame frame(DownlinkAPID::Operation, 0, 0x67);
> ```

hard coded id?

---

*[libs/experiments/flash/Include/experiment/flash/flash.hpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrFGJAXMDEH3vFrRHH7:-KrFGJAXMDEH3vFrRHH8:btnodh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/libs/experiments/flash/Include/experiment/flash/flash.hpp#L47)):*
> ```cpp
> 
>             /** @brief Experiment code */
>             static constexpr experiments::ExperimentCode Code = 0x7;
> ```

7 is reserved for sail experiment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration_tests/obc/experiments.py, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrF2urT4Chb6jpEPyIU:-KrFPlcfefqOhQkV0Egf:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/integration_tests/obc/experiments.py#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

7 is reserved for Sail
</blockquote></details>

Done.

---

*[libs/experiments/flash/flash.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrFG-iKB_S03l4u7F5u:-KrFIJgDo8uMT1CIghs0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/libs/experiments/flash/flash.cpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

hard coded id?
</blockquote></details>

Done.

---

*[libs/experiments/flash/Include/experiment/flash/flash.hpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244#-KrFGJAXMDEH3vFrRHH7:-KrFO4JmW-aPbjW_1iDF:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/94f009e498f8293ccf49dd2fe59b0d71149ce1de/libs/experiments/flash/Include/experiment/flash/flash.hpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

7 is reserved for sail experiment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244)*

**Comment by Novakov** [comment]
[Zweryfikować IDki eksperymentów](https://trello.com/c/bdT6vBmD/232-zweryfikowa%C4%87-idki-eksperyment%C3%B3w)

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/244)*

**Pull request merged**
