### PR TITLE
Extend telemetry with support for memory scrubbing

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/214)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 30 of 33 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[integration_tests/emulator/beacon_parser/scrubbing_telemetry_parser.py, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214#-KpvKZHXof7kmztyp1wj:-KpvKZHXof7kmztyp1wk:b97snqt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76e55525b35ecf3c395beff8f91c965fc8af8d53/integration_tests/emulator/beacon_parser/scrubbing_telemetry_parser.py#L9)):*
> ```Python
> 
>     def get_bit_count(self):
>         return 32 + 32 + 32
> ```

Shouldn't it be `32 + 3 + 3`?

---

*[libs/scrubber/Include/scrubber/ram.hpp, line 77 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214#-Kpuhh0XZ7j9GODhDTHS:-Kpuhh0XZ7j9GODhDTHT:bucf1cz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76e55525b35ecf3c395beff8f91c965fc8af8d53/libs/scrubber/Include/scrubber/ram.hpp#L77)):*
> ```cpp
>         BUS_RegBitWrite(&DMA->CHREQMASKS, 3, 1);
> 
>         std::uint32_t* start = _current;
> ```

In this interrupt handler every microsecond counts. 32-bit reads/writes are atomic so there is no need for explicit atomic. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214)*

**Comment by zaq32** [comment]
Review status: 27 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/emulator/beacon_parser/scrubbing_telemetry_parser.py, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214#-KpvKZHXof7kmztyp1wj:-Kq4TEtIt91dvoN9DoSk:byr4flj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76e55525b35ecf3c395beff8f91c965fc8af8d53/integration_tests/emulator/beacon_parser/scrubbing_telemetry_parser.py#L9)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Shouldn't it be `32 + 3 + 3`?
</blockquote></details>

Right.

---

*[libs/scrubber/Include/scrubber/ram.hpp, line 77 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214#-Kpuhh0XZ7j9GODhDTHS:-Kq4TGFfCoxOoI9BnW0o:b-bw8e14) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76e55525b35ecf3c395beff8f91c965fc8af8d53/libs/scrubber/Include/scrubber/ram.hpp#L77)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

In this interrupt handler every microsecond counts. 32-bit reads/writes are atomic so there is no need for explicit atomic. 
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/214)*

**Pull request merged**
