### PR TITLE
Restructure adcs subsystem.

### PR DESCRIPTION
**Pull request by zaq32**
Restructure of entire adcs subsystem. Features:

* Prepare infrastructure for imtq/custom adcs integrration,
* Enable imtq based detumbling once the initial silent period has passed,
* Introduce adcs subsystem coordinator ensuring that only one adcs algorithm is acrtive at any given time.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/78)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/adcs/AdcsCoordinator.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KbuwbCyhUROWs0X1LQM:-KbuwbCzQGpandqn_fNM:b5kemhb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/adcs/AdcsCoordinator.cpp#L6)):*
> ```cpp
> namespace adcs
> {
>     AdcsCoordinator::AdcsCoordinator(IDetumblingSupport& primaryDetembling, //
> ```

Keep naming consistent. Not `primaryDetumbling` but `builtinDetumbling`

---

*[libs/adcs/Include/adcs/adcs.hpp, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-Kbv1acQuaRmYEiBGF6r:-Kbv1acQuaRmYEiBGF6s:b735jry) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/adcs/Include/adcs/adcs.hpp#L77)):*
> ```cpp
>          */
>         virtual OSResult DisableSunPointing() = 0;
>     };
> ```

Any particular reason why detumbling is separated from sun pointing? From what I can see their interfaces are the same. What about simplifing them to `IAdcsMode`?

---

*[libs/mission/adcs/Include/mission/adcs.hpp, line 82 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KbuydSIee-tr2p_JMwi:-KbuydSJKRS69-HqX0Yk:bs4tzq9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/mission/adcs/Include/mission/adcs.hpp#L82)):*
> ```cpp
>              * @brief This procedure is deployment action entry point.
>              *
>              * This procedure runs the antenna deployment process.
> ```

antenna?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78)*

**Comment by zaq32** [comment]
Review status: 31 of 41 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/adcs/AdcsCoordinator.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KbuwbCyhUROWs0X1LQM:-KcnISWplZHAOYwothYh:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/adcs/AdcsCoordinator.cpp#L6)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Keep naming consistent. Not `primaryDetumbling` but `builtinDetumbling`
</blockquote></details>

Fixed

---

*[libs/adcs/Include/adcs/adcs.hpp, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-Kbv1acQuaRmYEiBGF6r:-KcnIVvP613wrDDMDwF6:b-v4ezus) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/adcs/Include/adcs/adcs.hpp#L77)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Any particular reason why detumbling is separated from sun pointing? From what I can see their interfaces are the same. What about simplifing them to `IAdcsMode`?
</blockquote></details>

The seperation is done to prevent mixup between the algorithms and to allow single class to implement both algorithms which may be usefull in case of our own custom adcs implementation.

---

*[libs/mission/adcs/Include/mission/adcs.hpp, line 82 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KbuydSIee-tr2p_JMwi:-KcnIUy5T1RrO_cg0gXT:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/82b267553aac7a5cdd3cd16e6ade218f783848ea/libs/mission/adcs/Include/mission/adcs.hpp#L82)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

antenna?
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78)*

**Comment by Novakov** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/adcs/Include/adcs/AdcsCoordinator.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KcnJ9LvOLEEk-dyN7dE:-KcnJ9LvOLEEk-dyN7dF:bff7rix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c745de743204bbc3552c5c8237d67f90d2146a0c/libs/adcs/Include/adcs/AdcsCoordinator.hpp#L27)):*
> ```cpp
>          * @param[in] primarySunPointing Reference to the sun pointing algorithm controller module.
>          */
>         AdcsCoordinator(IDetumblingSupport& builtinDetembling_, //
> ```

It is wise to run `make doc` to detect any mismatched documentation...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78)*

**Comment by zaq32** [comment]
Review status: 40 of 41 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/adcs/Include/adcs/AdcsCoordinator.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78#-KcnJ9LvOLEEk-dyN7dE:-KcnMglVBIN26iA71He5:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c745de743204bbc3552c5c8237d67f90d2146a0c/libs/adcs/Include/adcs/AdcsCoordinator.hpp#L27)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It is wise to run `make doc` to detect any mismatched documentation...
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/78)*

**Pull request merged**
