### PR TITLE
Boot settings scrubber

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/203)

### CODE REVIEW

**Comment by Novakov** [comment]
[Scrubbing FRAM](https://trello.com/c/w6piMtzO/137-scrubbing-fram)

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/scrubber/Include/scrubber/boot_settings.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203#-KoAzXpb5VOyeOTb_r4e:-KoAzXpb5VOyeOTb_r4f:b3p1dk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d25f323a759ea2d48dc69a1aff89b270c636618/libs/scrubber/Include/scrubber/boot_settings.hpp#L22)):*
> ```cpp
>          * @param bootSettings Boot settings (used for locking)
>          */
>         BootSettingsScrubber(devices::fm25w::IFM25WDriver& fram, boot::BootSettings& bootSettings)
> ```

do not define constructors inline

---

*[libs/scrubber/Include/scrubber/boot_settings.hpp, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203#-KoAz_uOhd6Vw7-JmdAN:-KoAz_uOhd6Vw7-JmdAO:b-bu1p1g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d25f323a759ea2d48dc69a1aff89b270c636618/libs/scrubber/Include/scrubber/boot_settings.hpp#L34)):*
> ```cpp
>       private:
>         /** @brief Size of scrubbed area */
>         static constexpr std::size_t Size = 16;
> ```

shouldn't this value come from boot settings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/scrubber/Include/scrubber/boot_settings.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203#-KoAzXpb5VOyeOTb_r4e:-KoD2KHW0sHVUQ6Rb80P:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d25f323a759ea2d48dc69a1aff89b270c636618/libs/scrubber/Include/scrubber/boot_settings.hpp#L22)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not define constructors inline
</blockquote></details>

Done.

---

*[libs/scrubber/Include/scrubber/boot_settings.hpp, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203#-KoAz_uOhd6Vw7-JmdAN:-KoD52A9TlColsRvV88d:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d25f323a759ea2d48dc69a1aff89b270c636618/libs/scrubber/Include/scrubber/boot_settings.hpp#L34)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

shouldn't this value come from boot settings?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/203)*

**Pull request merged**
