### PR TITLE
RAM Scrubbing

### PR DESCRIPTION
**Pull request by Novakov**
**IMPORTANT**: Scrubbing handler has hardcoded list of DMA channels in use - when using new one that list must be updated as well

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/160)

### CODE REVIEW

**Comment by Novakov** [comment]
[Scrubing RAM](https://trello.com/c/5aAxPPoH/168-scrubing-ram)

**Comment by zaq32** [comment]
Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/160)*

**Comment by zaq32** [comment]
Reviewed 1 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/160)*

**Comment by zaq32** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/160)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/160)*

**Pull request merged**
