### PR TITLE
SunS experiment

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/242)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Experiment] SunS](https://trello.com/c/ntYMT0ZT/209-experiment-suns)

**Comment by zaq32** [comment]
Reviewed 69 of 69 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/suns/suns.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAqqh5ahWtW1crwRWE:-KrAqqh5ahWtW1crwRWF:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/suns.cpp#L65)):*
> ```cpp
>             this->_remainingSessions = this->_parameters.SamplingSessionsCount();
> 
>             this->_primaryDataSet.Open(this->_fs, this->_primaryFileName, FileOpen::CreateAlways, FileAccess::WriteOnly);
> ```

unhandled error condition

---

*[libs/experiments/suns/suns.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAqtBKbkzOsebNtDyl:-KrAqtBKbkzOsebNtDym:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/suns.cpp#L66)):*
> ```cpp
> 
>             this->_primaryDataSet.Open(this->_fs, this->_primaryFileName, FileOpen::CreateAlways, FileAccess::WriteOnly);
>             this->_secondaryDataSet.Open(this->_fs, this->_secondaryFileName, FileOpen::CreateAlways, FileAccess::WriteOnly);
> ```

unhandled error condition

---

*[libs/experiments/suns/Include/experiment/suns/suns.hpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAr_nhAl31feYsMwoc:-KrAr_nhAl31feYsMwod:bb8i2c6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/Include/experiment/suns/suns.hpp#L32)):*
> ```cpp
>         {
>           public:
>             SunSExperimentParams() = default;
> ```

default constructor is not sufficient for this class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242)*

**Comment by Novakov** [comment]
Review status: 66 of 69 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/suns/suns.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAqqh5ahWtW1crwRWE:-KrAxrynWAV4jS8my_Oo:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/suns.cpp#L65)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/experiments/suns/suns.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAqtBKbkzOsebNtDyl:-KrAxsNVutaJ2FMubs-n:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/suns.cpp#L66)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/experiments/suns/Include/experiment/suns/suns.hpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242#-KrAr_nhAl31feYsMwoc:-KrAvP5pg4RM-bD2QD0E:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/755c9936dbe205d998895ceb9b51509f59e91852/libs/experiments/suns/Include/experiment/suns/suns.hpp#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

default constructor is not sufficient for this class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/242)*

**Pull request merged**
