### PR TITLE
IMTQ LCL + detumbling during LEOP only

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/359)

### CODE REVIEW

**Comment by Novakov** [comment]
[LCL for Imtq](https://trello.com/c/Ww3GAOtE/305-lcl-for-imtq)

**Comment by zaq32** [comment]
Reviewed 32 of 35 files at r1, 4 of 4 files at r2.
Review status: 36 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/adcs/builtin/BuiltinDetumbling.cpp, line 32 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkSBeHsNvpJr0R_RLU:-KwkSBeHsNvpJr0R_RLV:b-qub3ne) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/adcs/builtin/BuiltinDetumbling.cpp#L32)):*
> ```cpp
>     OSResult BuiltinDetumbling::Enable()
>     {
>         powerControl.ImtqPower(true);
> ```

no error handling here?

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 124 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkSV8hC73rjDNYsc2N:-KwkSV8hC73rjDNYsc2O:b-qub3ne) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/adcs/experimental/ExperimentalDetumbling.cpp#L124)):*
> ```cpp
>         }
> 
>         this->powerControl.ImtqPower(true);
> ```

no error handling here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359)*

**Comment by Novakov** [comment]
[Unable to download some chunks from file](https://trello.com/c/QCQRI79u/310-unable-to-download-some-chunks-from-file)

**Comment by Novakov** [comment]
Review status: 36 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/adcs/builtin/BuiltinDetumbling.cpp, line 32 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkSBeHsNvpJr0R_RLU:-KwkeJu0aEA8CQz3JmHz:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/adcs/builtin/BuiltinDetumbling.cpp#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

no error handling here?
</blockquote></details>

Done.

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 124 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkSV8hC73rjDNYsc2N:-KwkeKEL_yBz_d0bz5r0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/adcs/experimental/ExperimentalDetumbling.cpp#L124)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

no error handling here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359)*

**Comment by zaq32** [comment]
Reviewed 3 of 35 files at r1, 4 of 8 files at r3.
Review status: 39 of 43 files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/mission/adcs/adcs.cpp, line 64 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkUfD0hMCbyJlS9trx:-KwkUfD0hMCbyJlS9try:bxbr8vb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/mission/adcs/adcs.cpp#L64)):*
> ```cpp
>             }
> 
>             return true; // !IsDetumblingDisabled(state);
> ```

do not leave commented out code

---

*[libs/mission/adcs/adcs.cpp, line 91 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkV7PpQeXSIw08yNc9:-KwkV7PpQeXSIw08yNcA:bl1who5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/mission/adcs/adcs.cpp#L91)):*
> ```cpp
>             }
> 
>             if (context->coordinator.CurrentMode() == ::adcs::AdcsMode::Stopped)
> ```

or disabled

I wonder if there is even point in checking current adcs controller  mode

---

*[libs/mission/adcs/adcs.cpp, line 116 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwknFYfF7j67C6WrS4k:-KwknFYfF7j67C6WrS4l:b-8zf3nd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/mission/adcs/adcs.cpp#L116)):*
> ```cpp
>             if (!state.PersistentState.Get(adcsState))
>             {
>                 return false;
> ```

in case of errors it is safer to assume that detumbling is disabled

---

*[libs/mission/adcs/Include/mission/adcs.hpp, line 100 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkVoPieJrtmHPO_i90:-KwkVoPieJrtmHPO_i91:b-ggzior) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/26e776bc94a34e766b6796c8b729cd1cc7a0b123/libs/mission/adcs/Include/mission/adcs.hpp#L100)):*
> ```cpp
>             enum class State
>             {
>                 WaitingForStart,
> ```

this is effectively the same as stopped

---

*[libs/obc/communication/telecommands/file_system.cpp, line 35 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359#-KwkmPEqaMutnTIodtMU:-KwkmPEqaMutnTIodtMV:byo0c7g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/909c2bd7d68f1425ca4af20cd638553511107fac/libs/obc/communication/telecommands/file_system.cpp#L35)):*
> ```cpp
>         std::uint32_t FileSender::MaxChunkNumber(std::uint32_t fileSize)
>         {
>             auto n = fileSize / MaxFileDataSize;
> ```

consider this: 
auto n = (fileSize + MaxFileDataSize - 1) / MaxFileDataSize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359)*

**Comment by zaq32** [comment]
Reviewed 4 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/359)*

**Pull request merged**
