### PR TITLE
Fix downlink frame bit ordering

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/176)

### CODE REVIEW

**Comment by Novakov** [comment]
[Fix downlink frame bit ordering](https://trello.com/c/TVZC9inv/182-fix-downlink-frame-bit-ordering)

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/telecommunication/downlink.cpp, line 19 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/176#-Km65umnYYHFz0cOPk4z:-Km65umnYYHFz0cOPk5-:b-8x3kt2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7157aa67154c51a06e35b077089ef70bd2cd32fe/libs/telecommunication/downlink.cpp#L19)):*
> w.WriteWord(seq & 0xFF, 8);
>             w.WriteWord((seq & 0xFF00) >> 8, 8);
>             w.WriteWord((seq & 0xFF0000) >> 16, 2);

why not simply:
`w.WriteDoubleWord(seq, 18);`
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/176)*

**Comment by Novakov** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/telecommunication/downlink.cpp, line 19 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/176#-Km65umnYYHFz0cOPk4z:-Km6M7kR-xQNoLV1Y8Oz:b7o1ryr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7157aa67154c51a06e35b077089ef70bd2cd32fe/libs/telecommunication/downlink.cpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> w.WriteWord(seq & 0xFF, 8);
>             w.WriteWord((seq & 0xFF00) >> 8, 8);
>             w.WriteWord((seq & 0xFF0000) >> 16, 2);

why not simply:
`w.WriteDoubleWord(seq, 18);`
?

</blockquote></details>

Debugging leftover - fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/176)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/176)*

**Pull request merged**
