### PR TITLE
Heap based on FreeRTOS heap4 for unit tests

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/43)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by zaq32** [comment]
Reviewed 1 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[unit_tests/mem.cpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLzQEYlFTRP0sHZ7A:-KVjLzQEYlFTRP0sHZ7B:b-rvslvx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L11)):*
> ```cpp
> }
> 
> void* operator new(std::size_t sz)
> ```

You should also define following overloads of operator new:
```
void* operator new[](std::size_t size);          // for arrays
void* operator new(std::size_t count, const std::nothrow_t& tag);    // non throwing  variant of new operator for single objects
void* operator new[](std::size_t count, const std::nothrow_t& tag);    // non throwing  variant of new operator for arrays
```

---

*[unit_tests/mem.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLsbdzGXEKVPYaf5T:-KVjLsbdzGXEKVPYaf5U:bcme07p) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L13)):*
> ```cpp
> void* operator new(std::size_t sz)
> {
>     return pvPortMalloc(sz);
> ```

in case of allocation failure operator new should throw std::bad_alloc exception.

---

*[unit_tests/mem.cpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjMms-kUBS5w7reJ54:-KVjMms-kUBS5w7reJ55:b68cxch) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L15)):*
> ```cpp
>     return pvPortMalloc(sz);
> }
> void operator delete(void* ptr) noexcept
> ```

you should also define following overloads of delete operator:
```
void operator delete[]( void* ptr );           // for arrays
void operator delete  ( void* ptr, const std::nothrow_t& tag );            // counterpart of non throwing variant of new operator for objects
void operator delete[]( void* ptr, const std::nothrow_t& tag );            // counterpart of non throwing variant of new operator for arrays
```

---

*[unit_tests/mem.cpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjMW38hmx5NTyZDnAJ:-KVjMW38hmx5NTyZDnAK:b-23swht) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L17)):*
> ```cpp
> void operator delete(void* ptr) noexcept
> {
>     vPortFree(ptr);
> ```

operator delete should check if ptr is null and ignore it in such case.

---

*[unit_tests/mem.cpp, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjNMbhXSmpUZ5d3Zdy:-KVjNMbhXSmpUZ5d3Zdz:b-euz50e) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L19)):*
> ```cpp
>     vPortFree(ptr);
> }
> void operator delete(void* ptr, std::size_t alignment) noexcept
> ```

this operator should have corresponding operator new defined:
```
void* operator new  ( std::size_t count, std::align_val_t al);
```

---

*[unit_tests/mem.cpp, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjNY7GXyhCi6imiZWX:-KVjNY7GXyhCi6imiZWY:bvruxoj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L19)):*
> ```cpp
>     vPortFree(ptr);
> }
> void operator delete(void* ptr, std::size_t alignment) noexcept
> ```

Also when you define delete operator that supports non standard alignment you should also define following variants:
```
void* operator new[]( std::size_t count, std::align_val_t al);
void* operator new  ( std::size_t count, std::align_val_t al, const std::nothrow_t&);
void* operator new[]( std::size_t count, std::align_val_t al, const std::nothrow_t&);
void operator delete[]( void* ptr, std::size_t sz, std::align_val_t al);
void operator delete  ( void* ptr, std::align_val_t al, const std::nothrow_t& tag);
void operator delete[]( void* ptr, std::align_val_t al, const std::nothrow_t& tag);
```

---

*[unit_tests/FileSystem/FileSystemTest.cpp, line 77 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLAbjc3UnBpJyWskd:-KVjLAbjc3UnBpJyWske:bklxy2k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/FileSystem/FileSystemTest.cpp#L77)):*
> ```cpp
> {
>     const size_t bufferSize = 10240;
>     auto buffer = new uint8_t[bufferSize];
> ```

This buffer is not freed at all. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[unit_tests/mem.cpp, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjNMbhXSmpUZ5d3Zdy:-KVk7EVofuVrjCcPxENV:b-7mndl7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this operator should have corresponding operator new defined:
> ```
> void* operator new  ( std::size_t count, std::align_val_t al);
> ```
</details>
Actually no, this is sized delete operator from C++14. My mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by Novakov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[unit_tests/mem.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLsbdzGXEKVPYaf5T:-KVkIGl8zqCret71cKjO:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L13)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> in case of allocation failure operator new should throw std::bad_alloc exception.
</details>
Done.

---

*[unit_tests/mem.cpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjMms-kUBS5w7reJ54:-KVkIIinWlfPqbj7MTst:bxn6t3m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> you should also define following overloads of delete operator:
> ```
> void operator delete[]( void* ptr );           // for arrays
> void operator delete  ( void* ptr, const std::nothrow_t& tag );            // counterpart of non throwing variant of new operator for objects
> void operator delete[]( void* ptr, const std::nothrow_t& tag );            // counterpart of non throwing variant of new operator for arrays
> ```
</details>
It is enough to implement minimal versions

---

*[unit_tests/mem.cpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjMW38hmx5NTyZDnAJ:-KVkILrveED6aoUGGWyX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L17)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> operator delete should check if ptr is null and ignore it in such case.
</details>
Done.

---

*[unit_tests/mem.cpp, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjNMbhXSmpUZ5d3Zdy:-KVkINIakacKMEJa8mkt:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Actually no, this is sized delete operator from C++14. My mistake.
</details>
Done.

---

*[unit_tests/mem.cpp, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjNY7GXyhCi6imiZWX:-KVkIOGPH1DZ3XIX5RkI:bxn6t3m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Also when you define delete operator that supports non standard alignment you should also define following variants:
> ```
> void* operator new[]( std::size_t count, std::align_val_t al);
> void* operator new  ( std::size_t count, std::align_val_t al, const std::nothrow_t&);
> void* operator new[]( std::size_t count, std::align_val_t al, const std::nothrow_t&);
> void operator delete[]( void* ptr, std::size_t sz, std::align_val_t al);
> void operator delete  ( void* ptr, std::align_val_t al, const std::nothrow_t& tag);
> void operator delete[]( void* ptr, std::align_val_t al, const std::nothrow_t& tag);
> ```
</details>
It is enough to implement minimal versions

---

*[unit_tests/FileSystem/FileSystemTest.cpp, line 77 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLAbjc3UnBpJyWskd:-KVkIPRogAotExDbnxIj:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/FileSystem/FileSystemTest.cpp#L77)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> This buffer is not freed at all. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by Novakov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[unit_tests/mem.cpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-KVjLzQEYlFTRP0sHZ7A:-KVkIRw-LhBBlv1Vd0nE:bxn6t3m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1e0508c8e1a5287e357025faa9f63f3a5585930/unit_tests/mem.cpp#L11)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> You should also define following overloads of operator new:
> ```
> void* operator new[](std::size_t size);          // for arrays
> void* operator new(std::size_t count, const std::nothrow_t& tag);    // non throwing  variant of new operator for single objects
> void* operator new[](std::size_t count, const std::nothrow_t& tag);    // non throwing  variant of new operator for arrays
> ```
</details>
It is enough to implement minimal versions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43)*

**Comment by zaq32** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/43#-:-KVkJamP0Hwc5Z3ku4BV:bnfp4nl)*

**Pull request merged**
