### PR TITLE
Implemented error counters for Comm

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/167)

### CODE REVIEW

**Comment by Novakov** [comment]
[Error Counters - Comm](https://trello.com/c/Oh78vbkj/185-error-counter---comm)

**Comment by zaq32** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 124 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmgxqPxBveL1k8y39y:-KlmgxqPxBveL1k8y39z:bqnl0jn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/drivers/comm/comm.cpp#L124)):*
> ```cpp
> OSResult CommObject::Initialize()
> {
>     auto result = this->_pollingTaskFlags.Initialize();
> ```

mark as const

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 244 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-Klmjk1FFhyJlEOwcpNn:-Klmjk1FFhyJlEOwcpNo:b-pb2qpj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/drivers/comm/Include/comm/CommDriver.hpp#L244)):*
> ```cpp
>      * @return Operation status, true in case of success, false otherwise.
>      */
>     bool SendCommand(Address address, std::uint8_t command, error_counter::AggregatedErrorCounter& resultAggregator);
> ```

I am curious why propagate error counting logic down the call stack instead of observing the top level operation results?

---

*[libs/error_counter/error_counter.cpp, line 56 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmhiuCgSLN7i-5F_4l:-KlmhiuCgSLN7i-5F_4m:b-yvw48x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/error_counter.cpp#L56)):*
> ```cpp
>     }
> 
>     void AggregatedErrorCounter::Failure()
> ```

define this function inline

---

*[libs/error_counter/error_counter.cpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmhndsfYQL_nHuanyT:-Klmhndt7j4zOV3wR3gR:b-yvw48x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/error_counter.cpp#L61)):*
> ```cpp
>     }
> 
>     bool AggregatedErrorCounter::GetAggregatedResult()
> ```

define this function inline

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 167 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-Klmi09nvQ_X6li2fsHK:-Klmi09nvQ_X6li2fsHL:bqnl0jn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/Include/error_counter/error_counter.hpp#L167)):*
> ```cpp
>          * @return Current aggregated result value
>          */
>         bool GetAggregatedResult();
> ```

mark as const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167)*

**Comment by zaq32** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167)*

**Comment by mandrek44** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 124 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmgxqPxBveL1k8y39y:-Km2_KdzltT69s--205H:baexvg5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/drivers/comm/comm.cpp#L124)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as const
</blockquote></details>

Code was modified meantime - `const` not needed anymore

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 244 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-Klmjk1FFhyJlEOwcpNn:-Km2Wve--tUXvivtfALV:b-sg9c9m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/drivers/comm/Include/comm/CommDriver.hpp#L244)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I am curious why propagate error counting logic down the call stack instead of observing the top level operation results?
</blockquote></details>

I observed that not every `false` is reason for incrementing error counters - i.e. if I2C fails then it's a good reason, but if send data buffer is empty then  we just do nothing. 

---

*[libs/error_counter/error_counter.cpp, line 56 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmhiuCgSLN7i-5F_4l:-Km2_YKRB_hW5peJGYbz:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/error_counter.cpp#L56)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

define this function inline
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-KlmhndsfYQL_nHuanyT:-Km2_YgtrOYLfQl49DJ3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/error_counter.cpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

define this function inline
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 167 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167#-Klmi09nvQ_X6li2fsHK:-Km2_ZWUoG0QuI-l0-z9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2960e4e62f97429790ffd86468350185f8c662e4/libs/error_counter/Include/error_counter/error_counter.hpp#L167)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as const
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/167)*

**Pull request merged**
