### PR TITLE
Fix pin initialization

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/380)

### CODE REVIEW

**Comment by tom4r** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[boot/main.cpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380#-Kz8lQN_eCkjUMTXb7g2:-Kz8lQN_eCkjUMTXb7g3:b-58mdqe) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ba9b18538e7f4378acaf997b85052a5fe672ad54/boot/main.cpp#L41)):*
> ```cpp
>     for (std::uint8_t pin = 0; pin < pinCount; pin++)
>     {
>         //        if (port == io_map::Watchdog::ExternalWatchdogPin::Port && pin == io_map::Watchdog::ExternalWatchdogPin::PinNumber)
> ```

Please remove comment.

---

*[platforms/mcu/EngModel/Include/mcu/io_map.h, line 140 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380#-Kz8m6j4UW_GD52_pbag:-Kz8m6j5iaLb2XJ2ykog:b-8d3mn2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ba9b18538e7f4378acaf997b85052a5fe672ad54/platforms/mcu/EngModel/Include/mcu/io_map.h#L140)):*
> ```objc
>         struct HF
>         {
>             using Pin1 = PinLocation<gpioPortB, 13>;
> ```

Consistency note: In documentation Pin1 has sufix 'P' and Pin2 'N' (Positive / Negative?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380)*

**Comment by Novakov** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[boot/main.cpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380#-Kz8lQN_eCkjUMTXb7g2:-Kz8nKgMThgAsQEQAGnU:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ba9b18538e7f4378acaf997b85052a5fe672ad54/boot/main.cpp#L41)):*
<details><summary><i>Previously, tom4r wrote…</i></summary><blockquote>

Please remove comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380)*

**Comment by tom4r** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380)*

**Comment by zaq32** [comment]
Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/380)*

**Pull request merged**
