### PR TITLE
Flatsat tools

### PR DESCRIPTION
**Pull request by Novakov**
This pull requests adds:
 * Buliding additional platforms on CI builds
 * Basic set of tools for working with OBC on flatsat (flashing, running integration tests)
 * Copying build artifacts to flatsat OBC computer

More tools will come in future

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/211)

### CODE REVIEW

**Comment by Novakov** [comment]
[Tools for working with flatsat](https://trello.com/c/ksjma5FP/200-tools-for-working-with-flatsat)

**Comment by zaq32** [comment]
Reviewed 9 of 9 files at r1, 45 of 45 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flatsat_tools/test.txt, line 1 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAWpb5OHrE9HFRYodM:-KpAWpb5OHrE9HFRYodN:bvk0zwo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/flatsat_tools/test.txt#L1)):*
> ```
> sfsf
> ```

what is the purpose of this?

---

*[libs/boot_settings/Include/boot/fwd.hpp, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAWyHxEQqOkHCG6-lf:-KpAWyHxEQqOkHCG6-lg:bf1an76) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/libs/boot_settings/Include/boot/fwd.hpp#L4)):*
> ```cpp
> #define LIBS_BOOT_SETTINGS_INCLUDE_BOOT_FWD_HPP_
> 
> #include <cstdint>
> ```

size_t is defined in cstddef

---

*[src/obc.h, line 147 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAXEtwGOj7RnOdETTv:-KpAXEtwGOj7RnOdETTw:b32vmt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/src/obc.h#L147)):*
> ```objc
> using ExternalWatchdog = drivers::watchdog::PinWatchdog<io_map::Watchdog::ExternalWatchdogPin>;
> 
> void X4();
> ```

??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211)*

**Comment by Novakov** [comment]
Review status: 49 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/boot_settings/Include/boot/fwd.hpp, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAWyHxEQqOkHCG6-lf:-Kpfbz3cdD2c0KBTqiR4:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/libs/boot_settings/Include/boot/fwd.hpp#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

size_t is defined in cstddef
</blockquote></details>

Done.

---

*[flatsat_tools/test.txt, line 1 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAWpb5OHrE9HFRYodM:-KpfblAGd4FtQEEx_mM9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/flatsat_tools/test.txt#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the purpose of this?
</blockquote></details>

Done.

---

*[src/obc.h, line 147 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211#-KpAXEtwGOj7RnOdETTv:-KpfcHUIoxqH9A58DY1H:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4b7657c5fdefbc5e328e145221e46c118faaa490/src/obc.h#L147)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/211)*

**Pull request merged**
