### PR TITLE
Experiment fibonacci

### PR DESCRIPTION
**Pull request by Novakov**
Infrastrucutre for running experiments + sample experiment fibonacci

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/82)

### CODE REVIEW

**Comment by Novakov** [comment]
[Experiment Fibonacci](https://trello.com/c/B3dnuPix/108-experiment-fibonacci)

**Comment by zaq32** [comment]
Reviewed 37 of 39 files at r1.
Review status: 37 of 39 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/utils.h, line 131 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnJWKGHWhdKjiV8bYS:-KcnJWKGHWhdKjiV8bYT:b-ljcpfj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/base/Include/utils.h#L131)):*
> ```objc
>      * @retval true this is Some empty and other is equal to holded value
>      */
>     bool operator==(const T& other) const
> ```

when adding equality operator also add inequality operator

---

*[libs/base/Include/utils.h, line 149 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnJfUXutd7ZlN22_T_:-KcnJfUXutd7ZlN22_Ta:b-ljcpfj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/base/Include/utils.h#L149)):*
> ```objc
>      * @retval true when both are Some and underlying values are equal
>      */
>     bool operator==(const Option<T>& other) const
> ```

when adding equality operator also add inequality operator

---

*[libs/fs/extension.cpp, line 55 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnLLfI8EABpFjQZrs9:-KcnLLfI8EABpFjQZrsA:b-gvz581) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L55)):*
> ```cpp
> }
> 
> File::File() : _fs(nullptr)
> ```

uninitialized fields: _handle, _valid

---

*[libs/fs/extension.cpp, line 106 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnK10Qr1Ho3hzHXqJV:-KcnK10Qr1Ho3hzHXqJW:b-el4c5i) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L106)):*
> ```cpp
> }
> 
> File& File::operator=(File&& other)
> ```

mark as noexcept

---

*[libs/fs/extension.cpp, line 110 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnKAUmYmugu7RwQeXX:-KcnKAUmYmugu7RwQeXY:b-o7zlr2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L110)):*
> ```cpp
>     std::swap(this->_fs, other._fs);
>     std::swap(this->_handle, other._handle);
>     std::swap(this->_valid, other._valid);
> ```

swapping directly can have unexpected consequence of delayed destruction of resources managed by the assignment target,

The proper way to write this operator (when using swap based variant) looks like this:
```
File& operator=(File&& other) noexcept
{
    File tmp(std::move(other));
    tmp.swap(*this);
    return *this;
}

void File::swap(File& other) noexcept
{
    using std::swap;
    swap(this->_fs, other._fs);
    swap(this->_handle, other.handle);
    swap(this->_valid, other._valid);
}
```

---

*[libs/fs/Include/fs/fs.h, line 235 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnL488k1DMIa5Z3JC9:-KcnL488k1DMIa5Z3JCA:b-j5g1lj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/Include/fs/fs.h#L235)):*
> ```objc
>              * @return Reference to this
>              */
>             File& operator=(File&& other);
> ```

when definint move assignment operator you should also define move constructor.

---

*[src/commands/mission.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnPu_Pm5Oilfgaskgw:-KcnPu_Q6x28a-cQumkE:b-gx8fcy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/src/commands/mission.cpp#L23)):*
> ```cpp
>     UNREFERENCED_PARAMETER(argv);
>     LOG(LOG_LEVEL_INFO, "Received request to resume automatic mission processing.");
>     Mission.Suspend();
> ```

look like copy & paste programming on my part. This should be ```Mission.Resume()```....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by zaq32** [comment]
Reviewed 1 of 39 files at r1.
Review status: 38 of 39 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by zaq32** [comment]
Review status: 38 of 39 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[libs/mission/experiments/experiments.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoMBS96Ovksxcda0bo:-KcoMBS96Ovksxcda0bp:b7linw8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L31)):*
> ```cpp
>             auto inProgress = (System::EventGroupGetBits(this->_event) & Event::InProgress) == Event::InProgress;
>             if (inProgress)
>                 return;
> ```

this can be deceiving as user is not able to detect that another experiment is running and his request has been ignored...

---

*[libs/mission/experiments/experiments.cpp, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoLRFShdiz6pLQ5qYf:-KcoLRFShdiz6pLQ5qYg:b-aou86x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L33)):*
> ```cpp
>                 return;
> 
>             this->_requestedExperiment = Some(experiment);
> ```

as far as I can tell access to this variable should be synchronized as it is modified from at least two tasks:
* mission task
* experiment internal task.

---

*[libs/mission/experiments/experiments.cpp, line 82 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoNc_y_iG-lAwreCnA:-KcoNc_z5G4F3cLWn1CG:b-fg6bt5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L82)):*
> ```cpp
>             auto startResult = experiment.Start();
> 
>             if (startResult != StartResult::Success)
> ```

For the future, there should be a mechanism for propagating the status of the experiment back to the source so it can be saved and included in the full obc telemetry

---

*[libs/mission/experiments/experiments.cpp, line 182 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoL8APaxa-btPcginG:-KcoL8APaxa-btPcginH:bnpwndr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L182)):*
> ```cpp
>             auto This = reinterpret_cast<MissionExperiment*>(param);
> 
>             System::EventGroupSetBits(This->_event, 1 << 2);
> ```

use apropriate constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by zaq32** [comment]
Reviewed 1 of 39 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by Novakov** [comment]
Review status: 10 of 49 files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/base/Include/utils.h, line 131 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnJWKGHWhdKjiV8bYS:-KcsvopJJ0r6bZmIC89z:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/base/Include/utils.h#L131)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

when adding equality operator also add inequality operator
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 149 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnJfUXutd7ZlN22_T_:-Kcsvp6FPzGyG7QW5ITY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/base/Include/utils.h#L149)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

when adding equality operator also add inequality operator
</blockquote></details>

Done.

---

*[libs/fs/extension.cpp, line 55 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnLLfI8EABpFjQZrs9:-Kcsvnkc3ss3Ph_gXEKN:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L55)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

uninitialized fields: _handle, _valid
</blockquote></details>

Done.

---

*[libs/fs/extension.cpp, line 106 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnK10Qr1Ho3hzHXqJV:-Kcsvo5Y1mNFDWw6UmBn:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L106)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as noexcept
</blockquote></details>

Done.

---

*[libs/fs/extension.cpp, line 110 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnKAUmYmugu7RwQeXX:-Kct4a0HoncBKoeL13Ik:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/extension.cpp#L110)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

swapping directly can have unexpected consequence of delayed destruction of resources managed by the assignment target,

The proper way to write this operator (when using swap based variant) looks like this:
```
File& operator=(File&& other) noexcept
{
    File tmp(std::move(other));
    tmp.swap(*this);
    return *this;
}

void File::swap(File& other) noexcept
{
    using std::swap;
    swap(this->_fs, other._fs);
    swap(this->_handle, other.handle);
    swap(this->_valid, other._valid);
}
```
</blockquote></details>

Done.

---

*[libs/fs/Include/fs/fs.h, line 235 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnL488k1DMIa5Z3JC9:-KcsvmhA1VX5ioAg4bwl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/fs/Include/fs/fs.h#L235)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

when definint move assignment operator you should also define move constructor.
</blockquote></details>

Done.

---

*[libs/mission/experiments/experiments.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoMBS96Ovksxcda0bo:-KcxgH9OrNcBJo--bSBp:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L31)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this can be deceiving as user is not able to detect that another experiment is running and his request has been ignored...
</blockquote></details>

Done.

---

*[libs/mission/experiments/experiments.cpp, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoLRFShdiz6pLQ5qYf:-KcxiUy893uhobY67uaI:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L33)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

as far as I can tell access to this variable should be synchronized as it is modified from at least two tasks:
* mission task
* experiment internal task.
</blockquote></details>

Done.

---

*[libs/mission/experiments/experiments.cpp, line 82 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoNc_y_iG-lAwreCnA:-Kd5dz9c1z-7gJ4wOZ0y:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L82)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

For the future, there should be a mechanism for propagating the status of the experiment back to the source so it can be saved and included in the full obc telemetry
</blockquote></details>

Done.

---

*[libs/mission/experiments/experiments.cpp, line 182 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcoL8APaxa-btPcginG:-KcxgR6qlnrASNNZn3pL:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/libs/mission/experiments/experiments.cpp#L182)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use apropriate constant.
</blockquote></details>

Done.

---

*[src/commands/mission.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-KcnPu_Pm5Oilfgaskgw:-KcsvqWfHzVTDGMLkdA0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/74ed3ed58da9bd9d53c86f04835cd95b55fe7fe6/src/commands/mission.cpp#L23)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

look like copy & paste programming on my part. This should be ```Mission.Resume()```....
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by zaq32** [comment]
Reviewed 7 of 13 files at r2, 35 of 37 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/base/Include/utils.h, line 93 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7XibVPzIGR2TNDhlE:-Kd7XibVPzIGR2TNDhlF:b-oy6cm1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L93)):*
> ```objc
>  * @brief Class that can logically contain either a value of type T or no value.
>  */
> template <class T> class Option
> ```

A side note (I'm not going to argue about this).

For classes like this it would be better to implement == and != operator as non member free standing functions. 
To understand why consider this:
```
Option<int> a = 5;
int b  = 5;

const auto r1 = a == b;           // works ok 
const auto r2 = b == a;           // compile time error as ther is no equality operator that with first argument T and second Option<T>
```

---

*[libs/base/Include/utils.h, line 115 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7Yms0uBFlY-iW0UTH:-Kd7Yms0uBFlY-iW0UTI:byegzap) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L115)):*
> ```objc
>      * @return Option instance that holds a value.
>      */
>     static Option<T> Some(T&& value)
> ```

Again side note.

From pure language point of view this signature is less then optimal as it does not allow in-place object construction. 
Something like this wold be preferable:
```
template <typename... Args> Option<T> Some(Args&&... args)
{
    return Option<T>(true, std::forward<Args>(args)...);
}
```

---

*[libs/base/Include/utils.h, line 161 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7XFMy82sCwVzcaRe3:-Kd7XFMy82sCwVzcaRe4:bl2df2g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L161)):*
> f (!this->HasValue)
>         {
>             return false;
>         }
>  
>         return this->Value != other;
how about implementing it like this:
```
bool operator!=(const T& other) const
{
    return !(*this == other);
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by Novakov** [comment]
Review status: 48 of 49 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/base/Include/utils.h, line 93 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7XibVPzIGR2TNDhlE:-Kd8npQk22he5MAE1PWs:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L93)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

A side note (I'm not going to argue about this).

For classes like this it would be better to implement == and != operator as non member free standing functions. 
To understand why consider this:
```
Option<int> a = 5;
int b  = 5;

const auto r1 = a == b;           // works ok 
const auto r2 = b == a;           // compile time error as ther is no equality operator that with first argument T and second Option<T>
```
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 115 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7Yms0uBFlY-iW0UTH:-Kd8q5nSuoxVuWYQuWqG:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L115)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Again side note.

From pure language point of view this signature is less then optimal as it does not allow in-place object construction. 
Something like this wold be preferable:
```
template <typename... Args> Option<T> Some(Args&&... args)
{
    return Option<T>(true, std::forward<Args>(args)...);
}
```
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 161 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd7XFMy82sCwVzcaRe3:-Kd8nqMOqDhz6ShxemyP:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dfdca92b932eb7179710d02d34142ccb5b6e1c43/libs/base/Include/utils.h#L161)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> f (!this->HasValue)
>         {
>             return false;
>         }
>  
>         return this->Value != other;
how about implementing it like this:
```
bool operator!=(const T& other) const
{
    return !(*this == other);
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/base/Include/utils.h, line 109 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mp0p691T1rEZdU3_:-Kd9mp0p691T1rEZdU3a:b6p6ns2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L109)):*
> ```objc
>         return Option<T>(false, T());
>     }
>     //
> ```

remove it

---

*[libs/base/Include/utils.h, line 193 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9nRGxv6CmHFLvS_Cx:-Kd9nRGxv6CmHFLvS_Cy:btmg1hw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L193)):*
> ```objc
>  * @retval true lhs is Some and rhs is equal to holded value
>  */
> template <typename T> bool operator==(const Option<T>& lhs, const T& rhs)
> ```

so we have following variats:
```
operator==(Option<T>, T);
operator==(Option<T>, Option<T>);
```

the one that is still missing is:
operator==(T, Option<T>);
```
```


---

*[libs/base/Include/utils.h, line 211 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mveDw3ZK_Z8zQjKv:-Kd9mveDw3ZK_Z8zQjKw:b-n8kqh3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L211)):*
> ```objc
>  * @retval false lhs is Some and rhs is equal to holded value
>  */
> template <typename T> bool operator!=(const Option<T>& lhs, const T& rhs)
> ```

mark as inline

---

*[libs/base/Include/utils.h, line 245 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mxDNmVt5OyoAUijC:-Kd9mxDNmVt5OyoAUijD:b-n8kqh3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L245)):*
> ```objc
>  * @retval true when both are Some and underlying values are equal
>  */
> template <typename T> bool operator!=(const Option<T>& lhs, const Option<T>& rhs)
> ```

mark as inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/base/Include/utils.h, line 109 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mp0p691T1rEZdU3_:-KdBmHLw0GyGANg6opny:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L109)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

remove it
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 193 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9nRGxv6CmHFLvS_Cx:-KdBm_5gnKp42zvcFmjv:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L193)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

so we have following variats:
```
operator==(Option<T>, T);
operator==(Option<T>, Option<T>);
```

the one that is still missing is:
operator==(T, Option<T>);
```
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 211 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mveDw3ZK_Z8zQjKv:-KdBmoabJhVjkTbBtQw1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L211)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as inline
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 245 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82#-Kd9mxDNmVt5OyoAUijC:-KdBmnqk3fKz0zoxeJlN:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b951e978e53fb39f4425e0a747e5e715327fe515/libs/base/Include/utils.h#L245)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as inline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*
<!-- Sent from Reviewable.io -->

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/82)*

**Pull request merged**
