### PR TITLE
Runlevel

### PR DESCRIPTION
**Pull request by Novakov**
Runlevel implementation:
 * Runlevel 0 - Bootloader
 * Runlevel 1 - OBC running, no autonomous operation (no missiom, comm, telemetry)
 * Runlevel 2 (default) - OBC running, all autonomous actions are performed

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/170)

### CODE REVIEW

**Comment by Novakov** [comment]
[Runlevels](https://trello.com/c/LBO6GHcn/184-runlevels)

**Comment by zaq32** [comment]
Reviewed 60 of 60 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 46 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmbP2MJCV4hb1ezSt1:-KlmbP2MJCV4hb1ezSt2:b325z00) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/comm.cpp#L46)):*
> ```cpp
>     : _error(errors),             //
>       _low(low),                  //
>       _frameHandler(nullptr),     //
> ```

why frame handler is not provided at construction time?

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmX9cGYzhXryRJatu1:-KlmX9cGYzhXryRJatu2:b8ykpqv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L62)):*
> ```cpp
>      * @return Operation result
>      */
>     bool Resume();
> ```

This function should not be public

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 349 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmXEIh-UQv24sRQWzf:-KlmXEIh-UQv24sRQWzg:b-lhandq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L349)):*
> ```cpp
> inline void CommObject::SetFrameHandler(IHandleFrame& handler)
> {
>     this->_frameHandler = &handler;
> ```

data race

---

*[libs/obc/communication/communication.cpp, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmbfqMuGPtsg0NfLJX:-KlmbfqMuGPtsg0NfLJY:bc9sqj1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/obc/communication/communication.cpp#L51)):*
> ```cpp
>         LOG(LOG_LEVEL_ERROR, "Unable to restart comm");
>     }
>     this->Comm.Resume();
> ```

restart automatically resumes 

---

*[src/obc.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmaWCgobK_EX10sMh4:-KlmaWChlysxFTm5pPw7:b3ec79x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/src/obc.cpp#L47)):*
> ```cpp
> }
> 
> OSResult OBC::InitializeRunlevel1()
> ```

what is the point of returning status if almost all of the initialization steps statuses are ignored?

---

*[src/obc.h, line 131 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmY3MVEsSFwHj8iD2-:-KlmY3MVEsSFwHj8iD20:b-1kxyjq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/src/obc.h#L131)):*
> ```objc
>     scrubber::RAMScrubber<io_map::RAMScrubbing::MemoryStart, io_map::RAMScrubbing::MemorySize, io_map::RAMScrubbing::CycleSize>;
> 
> static constexpr std::uint32_t PersistentStateBaseAddress = 4;
> ```

this value should not be exposed to anyone except telemetry storage component

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 869 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYaaRgf0v5qfKMS4C:-KlmYaaRgf0v5qfKMS4D:by5y4wd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L869)):*
> ```cpp
>     }
> 
>     TEST_F(CommTest, TestRestartTaskCreationFailure)
> ```

Write coresponding test for Initialize method

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 876 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYoJgJh0zbL6hGIVn:-KlmYoJgJh0zbL6hGIVo:b34zkzb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L876)):*
> ```cpp
>     }
> 
>     TEST_F(CommTest, TestRestart)
> ```

This test should also verify that comm task is resumed

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 883 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYgE8R6AL0MCs14S2:-KlmYgE8R6AL0MCs14S3:b-pniihg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L883)):*
> ```cpp
>     }
> 
>     TEST_F(CommTest, TestDoubleRestart)
> ```

This test should not be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by Novakov** [comment]
Review status: 52 of 60 files reviewed at latest revision, 9 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 46 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmbP2MJCV4hb1ezSt1:-KlmhxBeqjdZ0vxWEbdK:buudnig) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/comm.cpp#L46)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why frame handler is not provided at construction time?
</blockquote></details>

To provide clear initialization path: first COMM driver is initialized, than communication layer plugs in to receive all incoming frames.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmX9cGYzhXryRJatu1:-Klmhd1x02JnoZjgWhJa:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This function should not be public
</blockquote></details>

Done.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 349 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmXEIh-UQv24sRQWzf:-Klmj0OH7L7mlE0C3mHs:b4si3rb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L349)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

data race
</blockquote></details>

Yes and no:
1. In Cortex-M3 all 32-bit aligned writes are atomic (`_frameHandler` is 32-bit pointer)
2. This value is written only in OBC initialization and before COMM task (which reads this value) is resumed 

---

*[libs/obc/communication/communication.cpp, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmbfqMuGPtsg0NfLJX:-KlmhhZHxEKoaxVwMPC5:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/obc/communication/communication.cpp#L51)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

restart automatically resumes 
</blockquote></details>

Done.

---

*[src/obc.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmaWCgobK_EX10sMh4:-KlmjRq0DgD1Q0RnpXOx:bq8gzxs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/src/obc.cpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the point of returning status if almost all of the initialization steps statuses are ignored?
</blockquote></details>

I'm still thinking about how to approach errors (and what error there can be) during initialization - it easier to leave placeholders for statuses and than remove them than remove them in first place than add them again

---

*[src/obc.h, line 131 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmY3MVEsSFwHj8iD2-:-Klmk3_2Ohued1Ny8oik:bxxmt7y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/src/obc.h#L131)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this value should not be exposed to anyone except telemetry storage component
</blockquote></details>

It is used in two places: persistent store saving/reading (passed as argument to mission ctor) and cleaning persistent state on OBC startup (now inside `obc.cpp`). 

Being here is provides simple answer for question 'Where in FRAM begins OBC state?'

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 869 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYaaRgf0v5qfKMS4C:-Klmm0Q-2yxYCyWRh03z:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L869)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Write coresponding test for Initialize method
</blockquote></details>

Done.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 876 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYoJgJh0zbL6hGIVn:-KlmmFZ_xm-JMllpgJFL:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L876)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This test should also verify that comm task is resumed
</blockquote></details>

Done.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 883 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYgE8R6AL0MCs14S2:-KlmmhrYuiEu68Ag9Nvp:b6zp0sd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L883)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This test should not be removed
</blockquote></details>

Actually no harm is done (beside restarting COMM hardware) if driver is restarted again - `ResumeTask` call for running task is no-op

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by zaq32** [comment]
Reviewed 2 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 349 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmXEIh-UQv24sRQWzf:-KlnFwxAe8CCCoXbonOC:bav22xp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L349)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Yes and no:
1. In Cortex-M3 all 32-bit aligned writes are atomic (`_frameHandler` is 32-bit pointer)
2. This value is written only in OBC initialization and before COMM task (which reads this value) is resumed 
</blockquote></details>

Therefore at least document it so it will not get lost in time.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 883 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYgE8R6AL0MCs14S2:-Klmx7XwYvL5_z0Jr1Pu:be1m6a6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L883)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Actually no harm is done (beside restarting COMM hardware) if driver is restarted again - `ResumeTask` call for running task is no-op
</blockquote></details>

this may cause unexpected behaviour when the comm driver is currently processing received frames 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 349 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmXEIh-UQv24sRQWzf:-KlnUc2QCPNweKlBdozD:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5923da41f8cc04eb54b61220879e61fc0ef5a579/libs/drivers/comm/Include/comm/CommDriver.hpp#L349)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Therefore at least document it so it will not get lost in time.
</blockquote></details>

Done.

---

*[unit_tests/drivers/Comm/CommTest.cpp, line 883 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlmYgE8R6AL0MCs14S2:-KlnWyKIkeL0j61M4Ck9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da3a3587e59c6c86fb469617fac1eb7572670b88/unit_tests/drivers/Comm/CommTest.cpp#L883)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this may cause unexpected behaviour when the comm driver is currently processing received frames 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 612 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlnYTx1tm7LLAwDZJwI:-KlnYTx1tm7LLAwDZJwJ:b-1x012a) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a91be2a04c07bccab6f9616270564d23e70b1132/libs/drivers/comm/comm.cpp#L612)):*
> ```cpp
>             comm->_pollingTaskFlags.Clear(TaskFlagRunning);
>             comm->_pollingTaskFlags.Set(TaskFlagAck);
>             System::SuspendTask(NULL);
> ```

Once the task is resumed the TaskFlagRunning will have invalid state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by Novakov** [comment]
Review status: 59 of 60 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 612 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170#-KlnYTx1tm7LLAwDZJwI:-KlnaB1MO21eqvOLkZFe:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a91be2a04c07bccab6f9616270564d23e70b1132/libs/drivers/comm/comm.cpp#L612)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Once the task is resumed the TaskFlagRunning will have invalid state.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/170)*

**Pull request merged**
