### PR TITLE
Application for testing freeRTOS event groups

### PR DESCRIPTION
**Pull request by zaq32**
* Extract terminal to separate static library.
* Add application for testing free rtos event group behaviour.
* Fix free RTOS config -> max task priority.
* Extract assert procedures to external static library.
* Some minor code fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/36)

### CODE REVIEW

**Comment by zaq32** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GXdDxcdV&#x2F;75-check-pulseall-on-eventgroup"> Check PulseAll on EventGroup</a>

**Comment by Novakov** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/external/FreeRTOS/CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAIbmmWF4jBTm-NlBN:-KRAIbmnvgFPGD0J1pV5:b9bde3w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/libs/external/FreeRTOS/CMakeLists.txt#L18)):*
> ```CMake
> target_include_directories(${NAME} PUBLIC ${CMAKE_CURRENT_LIST_DIR}/Include ${PORT_DIR})
> 
> target_link_libraries(${NAME} platform assert)
> ```

Place each reference in separate line

---

*[src/terminal.h, line 4 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAJ-BrIbpj2c1EAd0j:-KRAJ-BrIbpj2c1EAd0k:b-vnz9y2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/src/terminal.h#L4)):*
> ```objc
> #define OBC_TERMINAL_H
> 
> #pragma once
> ```

Why pragma?

---

*[test/pulse_all/main.c, line 31 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAJtYJ9ZdALR4SUMd3:-KRAJtYJ9ZdALR4SUMd4:b3i55ce) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/test/pulse_all/main.c#L31)):*
> ```C
>     UNREFERENCED_PARAMETER(argc);
>     UNREFERENCED_PARAMETER(argv);
>     System.EventGroupSetBits(GlobalEventGroup, 0x80);
> ```

It would be nice to wrap it as `PulseAll` method of OS and similar method like `WaitForPulseAll` (or any other better name).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/external/FreeRTOS/CMakeLists.txt, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAIbmmWF4jBTm-NlBN:-KRZSvUQk97V3X7Xg8PZ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/libs/external/FreeRTOS/CMakeLists.txt#L18)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Place each reference in separate line
</details>
Done.

---

*[src/terminal.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAJ-BrIbpj2c1EAd0j:-KRZSO_m36UWVc5Afb7A:b-hz4lkz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/src/terminal.h#L4)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Why pragma?
</details>
If it is supported it can speedup processing this particular file, if it is not it does not hurt. 

---

*[test/pulse_all/main.c, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAJtYJ9ZdALR4SUMd3:-KRZSb7G7GqQVlum84WM:b-2fh9gj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/test/pulse_all/main.c#L31)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> It would be nice to wrap it as `PulseAll` method of OS and similar method like `WaitForPulseAll` (or any other better name).
</details>
Pulse all is a concept that can be build on top of the EventGroups, I would go for the element built on top of our very think os abstraction rather than try to make it more robust. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/pulse_all/main.c, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36#-KRAJtYJ9ZdALR4SUMd3:-KRZZujtNRwoNv0tYiih:b-27n8p4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/caf74f7d8a21a36fd428ea74592f7985ac565292/test/pulse_all/main.c#L31)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Pulse all is a concept that can be build on top of the EventGroups, I would go for the element built on top of our very think os abstraction rather than try to make it more robust. 
</details>
It will be fine for me - I would like to just hide that Set/Wait options (Wait especially as there are few parameters and small mistake could have strange effects)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Comment by Novakov** [comment]
Reviewed 7 of 12 files at r3.
Review status: 28 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Comment by Novakov** [comment]
Reviewed 4 of 6 files at r4.
Review status: 30 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Comment by Novakov** [comment]
Reviewed 5 of 12 files at r3, 2 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/36)*

**Pull request closed without merging**
