### PR TITLE
Downlink frame format

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/69)

### CODE REVIEW

**Comment by Novakov** [comment]
[Implement downlink frame format](https://trello.com/c/iXtyRYIy/106-implement-downlink-frame-format)

**Comment by zaq32** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/base/Include/base/writer.h, line 115 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavHCVi-GAsI8fhlvIF:-KavHCVi-GAsI8fhlvIG:b6yvz0m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/base/Include/base/writer.h#L115)):*
> ```objc
>      * @return Span covering used part of buffer
>      */
>     gsl::span<std::uint8_t> UsedSpan();
> ```

I'd prefer calling this function ```Capture()```

---

*[libs/telecommunication/downlink.cpp, line 17 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavG1squrFswUmhDnsm:-KavG1squrFswUmhDnsn:b8p0yne) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/telecommunication/downlink.cpp#L17)):*
> ```cpp
> 
>             uint32_t header = (num(apid) << 18) | (seq & 0x3FFFF);
>             w.WriteLowerBytesBE(header, 3);
> ```

use HeaderSize instead of hard coded value

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavGL1xP4ennyT-oQ3R:-KavGL1xP4ennyT-oQ3S:br4kb37) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/telecommunication/include/telecommunication/downlink.h#L77)):*
> ```objc
>         inline gsl::span<uint8_t> DownlinkFrame::Frame()
>         {
>             return gsl::make_span(this->_frame).subspan(0, HeaderSize + this->_payloadWriter.GetDataLength());
> ```

this seems wrong. Why add Header size to the size stored inside the frame writer? The value stored inside the writer already takes the header size into account (see constructor).
For that matter why not directly return ```this->_payloadWriter.UsedSpan()```?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavGL1xP4ennyT-oQ3R:-KaxIyrOob-QD3F0ley6:b-y5vwap) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/telecommunication/include/telecommunication/downlink.h#L77)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this seems wrong. Why add Header size to the size stored inside the frame writer? The value stored inside the writer already takes the header size into account (see constructor).
For that matter why not directly return ```this->_payloadWriter.UsedSpan()```?
</blockquote></details>

Writer used in ctor to writer header is different writer, payload writer works only on payload part of frame, so the final frame size is header + payload size.

I was thinking about using the same writer for header and payload but in case that we add some method to writer that seeks it to the begining of span than it will overwrite header.  Also if any upper level code asks for current size of written data, it will be fooled by additional 3 bytes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavGL1xP4ennyT-oQ3R:-KaxOGogD6UAIQthVq63:b-p46t91) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/telecommunication/include/telecommunication/downlink.h#L77)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Writer used in ctor to writer header is different writer, payload writer works only on payload part of frame, so the final frame size is header + payload size.

I was thinking about using the same writer for header and payload but in case that we add some method to writer that seeks it to the begining of span than it will overwrite header.  Also if any upper level code asks for current size of written data, it will be fooled by additional 3 bytes
</blockquote></details>

How could I miss the fact that it is different object?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69)*

**Comment by Novakov** [comment]
Review status: 26 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/writer.h, line 115 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavHCVi-GAsI8fhlvIF:-Kb61P6vy9sS5IHwIW4D:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/base/Include/base/writer.h#L115)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd prefer calling this function ```Capture()```
</blockquote></details>

Done.

---

*[libs/telecommunication/downlink.cpp, line 17 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69#-KavG1squrFswUmhDnsm:-Kb60HRMSgRG_A3P7nKf:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/62f7d237b032594bd6f0529ecc5e967de43ba13c/libs/telecommunication/downlink.cpp#L17)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use HeaderSize instead of hard coded value
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69)*

**Comment by zaq32** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/69)*

**Pull request merged**
