### PR TITLE
Initialize all unused pins

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/363)

### CODE REVIEW

**Comment by Novakov** [comment]
[[NCR#050] Init all unused pins](https://trello.com/c/hGPW9ypN/309-ncr050-init-all-unused-pins)

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[boot/main.cpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/363#-KwnTJFBvG-adv5XVEM0:-KwnTJFCr-negvY0Umt5:bxbr8vb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5abfce7ca391cb985b4bbba7d7fb5f3ec0dfddd3/boot/main.cpp#L22)):*
> ```cpp
> static void InitializeAllPins(GPIO_Port_TypeDef port, std::uint8_t pinCount)
> {
>     //    GPIO_Port_TypeDef ports[] = {gpioPortA, gpioPortB, gpioPortC, gpioPortD, gpioPortE, gpioPortF};
> ```

do not leave commented out code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/363)*

**Comment by Novakov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[boot/main.cpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/363#-KwnTJFBvG-adv5XVEM0:-KwnXqQtA0ri5Hy9LvE2:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5abfce7ca391cb985b4bbba7d7fb5f3ec0dfddd3/boot/main.cpp#L22)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not leave commented out code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/363)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/363)*

**Pull request merged**
