### PR TITLE
Tools for running unit tests & python tests from cmdline

### PR DESCRIPTION
**Pull request by Novakov**
Tools:
 * `<build>/tools/unit_tests.cmd <binary> <args>` - running unit tests using QEMU
 * `<build>/tools/pytests.cmd <args>` - running python tests (all required configuration is passed as it should be)

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/153)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153)*

**Comment by zaq32** [comment]
Add some documentation how to use these scripts.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153#-:-Kk_TmYurYy0VVHi30My:b6kljib)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[tools/pytests.cmd.template, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153#-Kk_TtnTbEIaDV4e0F8k:-Kk_TtnTbEIaDV4e0F8l:b-qwsce) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1195c172383cbea1f9be723e95bc7acbd53bb9e3/tools/pytests.cmd.template#L1)):*
> ```
> @echo off
> ```

Add some documentation how to use this scripts.

---

*[tools/unit_tests.cmd.template, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153#-Kk_TvfTE2h-ooRgfW_3:-Kk_TvfTE2h-ooRgfW_4:b952y6g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1195c172383cbea1f9be723e95bc7acbd53bb9e3/tools/unit_tests.cmd.template#L1)):*
> ```
> @echo off
> ```

Add some documentation how to use this scripts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153)*

**Comment by Novakov** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/pytests.cmd.template, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153#-Kk_TtnTbEIaDV4e0F8k:-Kk_YCFGjY4UvM7FBpVp:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1195c172383cbea1f9be723e95bc7acbd53bb9e3/tools/pytests.cmd.template#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Add some documentation how to use this scripts.
</blockquote></details>

Done.

---

*[tools/unit_tests.cmd.template, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153#-Kk_TvfTE2h-ooRgfW_3:-Kk_YCl77HV2kQRV-0b1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1195c172383cbea1f9be723e95bc7acbd53bb9e3/tools/unit_tests.cmd.template#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Add some documentation how to use this scripts.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/153)*

**Pull request merged**
