### PR TITLE
[ADCS] Added experimental detumbling

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/151)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 18 of 32 files at r1, 9 of 11 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/adcs/AdcsCoordinator.cpp, line 105 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmqZ0LpMllK3aVkKXp:-KlmqZ0LpMllK3aVkKXq:b-tsv8gr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/AdcsCoordinator.cpp#L105)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>         if (this->currentMode == AdcsMode::Disabled)
>         {
>             LOG(LOG_LEVEL_TRACE, "[ADCS] Running ADCS loop. No mode enabled");
>             System::SleepTask(std::chrono::seconds(1));
>             return;
>         }
</details>
Disabled adcs is not an exception is normal operational state. this if will needlessly generate one log entry every second as long as adcs is not enabled. 

Also consider suspending this task altogether when adcs is disabled instead of waking it up once every second.

---

*[libs/adcs/builtin/BuiltinDetumbling.cpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmpNiUNnvn-T_Md4_J:-KlmpNiUNnvn-T_Md4_K:b-hn5ksy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/builtin/BuiltinDetumbling.cpp#L26)):*
> ```cpp
>     std::chrono::hertz BuiltinDetumbling::GetFrequency() const
>     {
>         return std::chrono::hertz(1);
> ```

since automatic detumbling can work for longer periods of time perhaps it we could lower its frequency to one iteration every several  (> 30?) seconds?

---

*[libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp, line 19 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-Klmp5EoYASncCmySw-8:-Klmp5EoYASncCmySw-9:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp#L19)):*
> ```cpp
>     {
>       public:
>         BuiltinDetumbling(devices::imtq::IImtqDriver& imtqDriver_);
> ```

undocumented

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-Klmm9ZLjFDpfMALqECe:-Klmm9ZLjFDpfMALqECf:b7enu6f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/ExperimentalDetumbling.cpp#L26)):*
> ```cpp
>         }
> 
>         System::SleepTask(10ms);
> ```

imtq self test takes at least a second and according to manufacturer somewhere around 15 seconds

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 51 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmoZLUSml8INshvKVE:-KlmoZLUSml8INshvKVF:b2bi50r) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/ExperimentalDetumbling.cpp#L51)):*
> ```cpp
>             }
> 
>             switch (step.actualStep)
> ```

since there are issues in imtq firmware that manifest in failures being always reported in its self test using its result to disable some of the coils is probably not a good idea.

---

*[libs/adcs/experimental/Include/adcs/ExperimentalSunPointing.hpp, line 16 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmlYzDRK5SSrZgtElr:-KlmlYzDRK5SSrZgtEls:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/Include/adcs/ExperimentalSunPointing.hpp#L16)):*
> ```cpp
>     {
>       public:
>         ExperimentalSunPointing(devices::imtq::IImtqDriver& imtqDriver_);
> ```

undocumented

---

*[libs/adcs/Include/adcs/AdcsCoordinator.hpp, line 46 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmrTX7nzQ84Lv9Wul9:-KlmrTX7nzQ84Lv9WulA:b-4ozxuq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/Include/adcs/AdcsCoordinator.hpp#L46)):*
>         virtual AdcsMode CurrentMode() const final override;
> 
>         virtual OSResult EnableBuiltinDetumbling() final override;
> 
>         virtual OSResult EnableExperimentalDetumbling() final override;
> 
>         virtual OSResult EnableSunPointing() final override;
> 
>         virtual OSResult Disable() final override;
These methods should be synchronized as they are used by at least telecommands & mission loop 

---

*[libs/base/Include/base/hertz.hpp, line 6 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmlDinfjqrl82HZt2h:-KlmlDio-bnibTCD21Rh:b-ydez5o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/base/Include/base/hertz.hpp#L6)):*
> ```cpp
> #include <chrono>
> 
> namespace std
> ```

c++ standard explicitly forbids injecting anything into std "namespace" 

---

*[libs/obc/adcs/Include/obc/adcs.hpp, line 29 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmsRnD86coVPSPc4GH:-KlmsRnD86coVPSPc4GI:b-bw1gc2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/obc/adcs/Include/obc/adcs.hpp#L29)):*
> ```cpp
>       public:
>         /** ctor. */
>         Adcs(devices::imtq::IImtqDriver& imtqDriver_, services::time::ICurrentTime& currentTime_);
> ```

undocumented arguments

---

*[unit_tests/base/Include/mock/AdcsMocks.hpp, line 41 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmsZ-IWWRiZkqS0vNT:-KlmsZ-J8Z1P_Wg1qjYP:bp33njf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/unit_tests/base/Include/mock/AdcsMocks.hpp#L41)):*
> ```cpp
> };
> 
> struct SunPointingMock : adcs::IAdcsProcessor
> ```

consider:
```typedef DetumblingMock SunpointingMock;```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*
<!-- Sent from Reviewable.io -->

**Comment by zaq32** [comment]
Reviewed 1 of 32 files at r1, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by kfazi** [comment]
Review status: 14 of 36 files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/adcs/AdcsCoordinator.cpp, line 105 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmqZ0LpMllK3aVkKXp:-KnF1cL4TcaVGinveCgM:b2tosml) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/AdcsCoordinator.cpp#L105)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         if (this->currentMode == AdcsMode::Disabled)
>         {
>             LOG(LOG_LEVEL_TRACE, "[ADCS] Running ADCS loop. No mode enabled");
>             System::SleepTask(std::chrono::seconds(1));
>             return;
>         }
Disabled adcs is not an exception is normal operational state. this if will needlessly generate one log entry every second as long as adcs is not enabled. 

Also consider suspending this task altogether when adcs is disabled instead of waking it up once every second.
</blockquote></details>

Fixed. Logging is removed and I added task suspension. I don't know whether task can suspend itself, so I left the sleep there and added suspension to the method that creates this task.

---

*[libs/adcs/builtin/BuiltinDetumbling.cpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmpNiUNnvn-T_Md4_J:-KnF2aaD5j1EqZ5LPd0S:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/builtin/BuiltinDetumbling.cpp#L26)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since automatic detumbling can work for longer periods of time perhaps it we could lower its frequency to one iteration every several  (> 30?) seconds?
</blockquote></details>

Done.

---

*[libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp, line 19 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-Klmp5EoYASncCmySw-8:-KnF2cyNnvjTWPCo46vY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-Klmm9ZLjFDpfMALqECe:-KnF2iNOrshvsg0wHGiJ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/ExperimentalDetumbling.cpp#L26)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

imtq self test takes at least a second and according to manufacturer somewhere around 15 seconds
</blockquote></details>

Done.

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 51 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmoZLUSml8INshvKVE:-KnF2mZVpoQM0QhS2WER:bcdheil) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/ExperimentalDetumbling.cpp#L51)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since there are issues in imtq firmware that manifest in failures being always reported in its self test using its result to disable some of the coils is probably not a good idea.
</blockquote></details>

For now I'm assuming self-test always passes. I'm logging reported errors.

---

*[libs/adcs/experimental/Include/adcs/ExperimentalSunPointing.hpp, line 16 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmlYzDRK5SSrZgtElr:-KnF3Ke7ypv7x3w4f-ZY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/experimental/Include/adcs/ExperimentalSunPointing.hpp#L16)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/adcs/Include/adcs/AdcsCoordinator.hpp, line 46 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmrTX7nzQ84Lv9Wul9:-KnF3MdX1se-PttZkkIJ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/Include/adcs/AdcsCoordinator.hpp#L46)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         virtual AdcsMode CurrentMode() const final override;
> 
>         virtual OSResult EnableBuiltinDetumbling() final override;
> 
>         virtual OSResult EnableExperimentalDetumbling() final override;
> 
>         virtual OSResult EnableSunPointing() final override;
> 
>         virtual OSResult Disable() final override;
These methods should be synchronized as they are used by at least telecommands & mission loop 
</blockquote></details>

Done.

---

*[libs/base/Include/base/hertz.hpp, line 6 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmlDinfjqrl82HZt2h:-KnF3OsBTH44Ni5B07aK:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/base/Include/base/hertz.hpp#L6)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

c++ standard explicitly forbids injecting anything into std "namespace" 
</blockquote></details>

Fixed.

---

*[libs/obc/adcs/Include/obc/adcs.hpp, line 29 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmsRnD86coVPSPc4GH:-KnF3b3Pc89Ht8gZ3a97:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/obc/adcs/Include/obc/adcs.hpp#L29)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented arguments
</blockquote></details>

Done.

---

*[unit_tests/base/Include/mock/AdcsMocks.hpp, line 41 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmsZ-IWWRiZkqS0vNT:-KnF3d7Qz3ovj7NVuXuP:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/unit_tests/base/Include/mock/AdcsMocks.hpp#L41)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

consider:
```typedef DetumblingMock SunpointingMock;```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by zaq32** [comment]
Reviewed 22 of 23 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/adcs/AdcsCoordinator.cpp, line 105 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmqZ0LpMllK3aVkKXp:-KnXzC3q38tt1XoCBTSg:b-fecr3n) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/AdcsCoordinator.cpp#L105)):*
<details><summary><i>Previously, kfazi wrote…</i></summary><blockquote>

Fixed. Logging is removed and I added task suspension. I don't know whether task can suspend itself, so I left the sleep there and added suspension to the method that creates this task.
</blockquote></details>

The task can suspend itself. You can do it like this:
```
System::SuspendTask(nullptr);
```

---

*[libs/adcs/AdcsCoordinator.cpp, line 30 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnXzdxdoWZfR_YzoCL4:-KnXzdxdoWZfR_YzoCL5:b70cvhw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/AdcsCoordinator.cpp#L30)):*
> ```cpp
> 
>         result = System::GiveSemaphore(this->sync);
>         if (!OS_RESULT_SUCCEEDED(result))
> ```

there is also OS_RESULT_FAILED macro

---

*[libs/adcs/AdcsCoordinator.cpp, line 126 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnY-4psVfWFUVNp84lH:-KnY-4psVfWFUVNp84lI:b-y5bwgr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/AdcsCoordinator.cpp#L126)):*
> ```cpp
>     }
> 
>     OSResult AdcsCoordinator::EnableSunPointing()
> ```

The difference between the Enable... methods is single constant value (the AdcsMode value). Merge them together.

---

*[libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp, line 35 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnY-WSp9JINTAROpgqt:-KnY-WSp9JINTAROpgqu:b37dezh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp#L35)):*
> ```cpp
> 
>         /** @brief Algorithm refresh frequency. */
>         static constexpr chrono_extensions::hertz Frequency = chrono_extensions::hertz{0.03};
> ```

since float are costly to use consider using mHz or uHz as frequency unit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by zaq32** [comment]
Reviewed 24 of 24 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 15 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnsdgUPauPGBITzRr7M:-KnsdgUPauPGBITzRr7N:b-q4fjn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1df14d7da46a14ef665056084bf0f3b076c4f3d5/libs/adcs/experimental/ExperimentalDetumbling.cpp#L15)):*
> tryToFixIsisErrors(false)
Shouldn't this value be set to true? We know that imtq built-in self test will report failures no matter what.

---

*[src/commands/imtq.cpp, line 369 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnsctRlMgdIj1qYJh13:-KnsctRlMgdIj1qYJh14:b-sdsaxi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1df14d7da46a14ef665056084bf0f3b076c4f3d5/src/commands/imtq.cpp#L369)):*
> ```cpp
>             return;
>         }
>         std::string fixText(argv[0]);
> ```

do not use heap in production code. Our current memory manager does not support freeing memory blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by kfazi** [comment]
Review status: 25 of 42 files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/adcs/AdcsCoordinator.cpp, line 105 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KlmqZ0LpMllK3aVkKXp:-KoMx9feomDiekhCGNAi:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8fadae2966c9ba625c4c15f7c26a117e1354f8cb/libs/adcs/AdcsCoordinator.cpp#L105)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

The task can suspend itself. You can do it like this:
```
System::SuspendTask(nullptr);
```
</blockquote></details>

Done.

---

*[libs/adcs/AdcsCoordinator.cpp, line 30 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnXzdxdoWZfR_YzoCL4:-KoMx67Nnqdjp3vmZaYP:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/AdcsCoordinator.cpp#L30)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

there is also OS_RESULT_FAILED macro
</blockquote></details>

Done.

---

*[libs/adcs/AdcsCoordinator.cpp, line 126 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnY-4psVfWFUVNp84lH:-KoMx8-RD5rMz1LZqkwY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/AdcsCoordinator.cpp#L126)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

The difference between the Enable... methods is single constant value (the AdcsMode value). Merge them together.
</blockquote></details>

Done.

---

*[libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp, line 35 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnY-WSp9JINTAROpgqt:-KoMxAto432Lfx_ebyON:b-u3841u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/711a494e52a03b92e5679b9b6701d3036baf93ed/libs/adcs/builtin/Include/adcs/BuiltinDetumbling.hpp#L35)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since float are costly to use consider using mHz or uHz as frequency unit.
</blockquote></details>

Experimental detumbling algorithm is using floating point in it's frequency calculations. I changed GetFrequency to GetWait method, which returns milliseconds. Because frequencies are constexpr the wait time should be calculated during build. I would like to leave frequencies as the parameter, because all talks with ADCS guys mention frequencies instead of waiting time

---

*[libs/adcs/experimental/ExperimentalDetumbling.cpp, line 15 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnsdgUPauPGBITzRr7M:-KoMwLpNE3IHLN62gVku:bnpf1zw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1df14d7da46a14ef665056084bf0f3b076c4f3d5/libs/adcs/experimental/ExperimentalDetumbling.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> tryToFixIsisErrors(false)
Shouldn't this value be set to true? We know that imtq built-in self test will report failures no matter what.

</blockquote></details>

I would like to test this implementation on real hardware before we will enable it by default.
The custom self test is written based on the emails from isis where they only give a hint on how it could be done.

---

*[src/commands/imtq.cpp, line 369 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151#-KnsctRlMgdIj1qYJh13:-KoMx4n_hMbEpqMz_h_r:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1df14d7da46a14ef665056084bf0f3b076c4f3d5/src/commands/imtq.cpp#L369)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not use heap in production code. Our current memory manager does not support freeing memory blocks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by zaq32** [comment]
Reviewed 17 of 17 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/151)*

**Pull request merged**
