### PR TITLE
Implemented time correction based on external RTC

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/99)

### CODE REVIEW

**Comment by mandrek44** [comment]
[[Time] Check external RTC](https://trello.com/c/DuFMjQer/98-time-check-external-rtc)

**Comment by Novakov** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenxMu7KAXg0EAfkAML:-KenxMu7KAXg0EAfkAMM:b3kfqvp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L42)):*
> ```cpp
>               * @return Transfer result - I2CResult::OK when read was successful.
>               */
>             virtual OSResult ReadTime(RTCTime& rtcTime);
> ```

Extract interface

---

*[libs/time/timer.cpp, line 100 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnyJ9_SPsDa06dlx_:-KeUnyJ9_SPsDa06dlxa:bqfjq9f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/time/timer.cpp#L100)):*
> ```cpp
> bool TimeProvider::SetCurrentTime(milliseconds duration)
> {
>     if (OS_RESULT_FAILED(System::TakeSemaphore(timerLock, InfiniteTimeout)))
> ```

You can use `Lock` class to take semaphore in a bit safer maner

---

*[src/obc.h, line 96 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnp-AGdTAV6BxmG5d:-KeUnp-BO9cJDgJwg3VY:bk8nzbm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/src/obc.h#L96)):*
> ```objc
> 
>     /** @brief External Real Time Clock.  */
>     devices::rtc::RTCObject rtc;
> ```

I thinks it should go to hardware or time-related part of OBC tree

---

*[unit_tests/MissionPlan/TimeTaskTest.cpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Keny_Zh1zlIhL4qkYUo:-Keny_Zh1zlIhL4qkYUp:b-owcoow) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/unit_tests/MissionPlan/TimeTaskTest.cpp#L50)):*
> ```cpp
> TimeTaskTest::TimeTaskTest()
>     : provider(fileSystemMock),                 //
>       rtc(),                                    //
> ```

No need to call default ctor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by zaq32** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenx-Z_QF6CzubQh18Y:-Kenx-ZaR42QYs5uSIT-:b-ncsi6e) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L34)):*
> ```cpp
>              */
>             RTCObject(drivers::i2c::II2CBus& bus);
>             virtual ~RTCObject(){};
> ```

virtual destructor is useful only when you are planning to be able to destroy object via pointer to the base class. Since we do not destroy our objects at all this seems unused. 

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenxcr_IdD2qOWcSgLD:-Kenxcr_IdD2qOWcSgLE:bfrmwk1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L42)):*
> ```cpp
>               * @return Transfer result - I2CResult::OK when read was successful.
>               */
>             virtual OSResult ReadTime(RTCTime& rtcTime);
> ```

It would be better suited to provide an RTC interface so it can be abstracted away instead of making it overrideable.

---

*[libs/mission/time/time.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenxPI9Uk3FE7TpPGDh:-KenxPI9Uk3FE7TpPGDi:bi560pn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/mission/time/time.cpp#L5)):*
> ```cpp
> #include "state/struct.h"
> 
> #include <iostream>
> ```

we should refrain from using iostream plus this header seems unused.

---

*[libs/mission/time/time.cpp, line 99 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenyw2BtZ6bW5gLUqDx:-Kenyw2BtZ6bW5gLUqDy:bdbquoc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/mission/time/time.cpp#L99)):*
> ```cpp
> 
>         auto correctedMissionTime = lastMissionTime.Value + (deltaMcu + deltaRtc) / 2;
>         auto correctionValue = correctedMissionTime > time.Value ? correctedMissionTime - time.Value : time.Value - correctedMissionTime;
> ```

how about using std::abs?

---

*[unit_tests/mock/RtcMock.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenzJm0YT_8sc2QaXZ1:-KenzJm0YT_8sc2QaXZ2:b-m4j1gj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/unit_tests/mock/RtcMock.hpp#L9)):*
> ```cpp
> #include "rtc/rtc.hpp"
> 
> class RtcMock : public devices::rtc::RTCObject
> ```

why not use google mock instead of manually creating mock object?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by mandrek44** [comment]
Review status: 4 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[libs/mission/time/time.cpp, line 99 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenyw2BtZ6bW5gLUqDx:-Kf1iWblqw9m-i3pHzI-:bi64h3v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/mission/time/time.cpp#L99)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

how about using std::abs?
</blockquote></details>

AFAIK there's not `std::abs` for `duration`. There's http://en.cppreference.com/w/cpp/chrono/duration/abs but available since C++17

---

*[src/obc.h, line 96 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnp-AGdTAV6BxmG5d:-Kf2WT1tuomK7SAv4IVn:b-61x4f6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/src/obc.h#L96)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I thinks it should go to hardware or time-related part of OBC tree
</blockquote></details>

What this branch should contain apart from rtc? 

---

*[unit_tests/mock/RtcMock.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenzJm0YT_8sc2QaXZ1:-Kf20SjKwM4yROOmn_aD:be10ghl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/unit_tests/mock/RtcMock.hpp#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why not use google mock instead of manually creating mock object?
</blockquote></details>

Because now I can write `rtc.AdvanceTime(duration_cast<seconds>(mission::TimeCorrectionPeriod));` which is much more readable than setting up mock object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by mandrek44** [comment]
Review status: 4 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenx-Z_QF6CzubQh18Y:-Kf2WdsmeVunP5qnbtBE:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L34)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

virtual destructor is useful only when you are planning to be able to destroy object via pointer to the base class. Since we do not destroy our objects at all this seems unused. 
</blockquote></details>

Done.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenxMu7KAXg0EAfkAML:-Kf2WeUZTOAQ3oS4ysMT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L42)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Extract interface
</blockquote></details>

Done.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kenxcr_IdD2qOWcSgLD:-Kf2Wet-3zmCUP4kZqVe:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/drivers/rtc/Include/rtc/rtc.hpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

It would be better suited to provide an RTC interface so it can be abstracted away instead of making it overrideable.
</blockquote></details>

Done.

---

*[libs/mission/time/time.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KenxPI9Uk3FE7TpPGDh:-Kf2Wg1ufmIwLHfvZhFx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/mission/time/time.cpp#L5)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

we should refrain from using iostream plus this header seems unused.
</blockquote></details>

Done.

---

*[libs/time/timer.cpp, line 100 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnyJ9_SPsDa06dlx_:-Kf2WgwG_27NAXQNxz6z:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/libs/time/timer.cpp#L100)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can use `Lock` class to take semaphore in a bit safer maner
</blockquote></details>

Done.

---

*[unit_tests/MissionPlan/TimeTaskTest.cpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Keny_Zh1zlIhL4qkYUo:-Kf2WcoycsLnwfOhyUGa:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/unit_tests/MissionPlan/TimeTaskTest.cpp#L50)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

No need to call default ctor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by mandrek44** [comment]
I needed to add the RTC Mock because time correction was disturbing the detumbling integration tests

---

Review status: 4 of 20 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-:-Kf2X-AkyRwoZU5aoMoy:b6e78u3)*

**Comment by Novakov** [comment]
Reviewed 5 of 5 files at r2, 6 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[integration_tests/system/system.py, line 51 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kf8M4_IoWC1SHv10vtG:-Kf8M4_IoWC1SHv10vtH:b-kc2hm2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/930d57a6b8de1d0878b49b2ab790b59c1c9e361e/integration_tests/system/system.py#L51)):*
> ```Python
>         self.sys_bus.add_device(self.primary_antenna)
>         self.payload_bus.add_device(self.backup_antenna)
>         self.sys_bus.add_device(self.rtc)
> ```

RTC will bo on PLD board so I guess it will be connected to payload bus 

---

*[integration_tests/tests/test_time.py, line 37 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kf8MFafva3gC8F69Gxp:-Kf8MFafva3gC8F69Gxq:bb7qx3u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/930d57a6b8de1d0878b49b2ab790b59c1c9e361e/integration_tests/tests/test_time.py#L37)):*
> ```Python
>     #     obc_time_difference_ms = obc_end_time_ms - obc_start_time_ms
>     #
>     #     self.assertAlmostEqual(obc_time_difference_ms, sys_time_difference_ms, places=None, delta=wait_time_accuracy_ms)
> ```

wat?

---

*[src/obc.h, line 96 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnp-AGdTAV6BxmG5d:-Kf8MmYo8vXdOZi65F9G:bad6ufx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/src/obc.h#L96)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

What this branch should contain apart from rtc? 
</blockquote></details>

Maybe time provider. My point is that I would like to avoid big blob of things inside OBC structure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by mandrek44** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[integration_tests/tests/test_time.py, line 37 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kf8MFafva3gC8F69Gxp:-Kf8NVJPsunTGccTM3rx:bx2gmza) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/930d57a6b8de1d0878b49b2ab790b59c1c9e361e/integration_tests/tests/test_time.py#L37)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

wat?
</blockquote></details>

How this got there? ;-) Damn it - this whole file should not be changed in this pull request

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by mandrek44** [comment]
Review status: 18 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[integration_tests/system/system.py, line 51 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-Kf8M4_IoWC1SHv10vtG:-Kf8RPy0eeZNqngxAjE3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/930d57a6b8de1d0878b49b2ab790b59c1c9e361e/integration_tests/system/system.py#L51)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

RTC will bo on PLD board so I guess it will be connected to payload bus 
</blockquote></details>

Done.

---

*[src/obc.h, line 96 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99#-KeUnp-AGdTAV6BxmG5d:-Kf8P50-GoowdUtKMKJt:b-5itcjo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85978ff69338d19047959e328db9d83d0e22c659/src/obc.h#L96)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Maybe time provider. My point is that I would like to avoid big blob of things inside OBC structure
</blockquote></details>

That may be hard to resolve - `Hardware` depends on `TimeProvider`, `RTC` depends on `Hardware`.  I think we'd have redesign the obc structure - i.e. look also at adcs, antenna drivers etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/99)*

**Pull request merged**
