### PR TITLE
Mount 3 external N25Q flashes

### PR DESCRIPTION
**Pull request by Novakov**
Mount 3 external flashes when using N25Q storage

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/85)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/obc/storage/n25q_flash/n25q.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWYH9QEWYMIsDc54kk:-KcWYH9QEWYMIsDc54kl:b-7togat) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/n25q.cpp#L28)):*
> _flashes{
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>           {"/a", pins.Flash1ChipSelect, spi, deviceOperations}, //
>           {"/b", pins.Flash2ChipSelect, spi, deviceOperations}, //
>           {"/c", pins.Flash3ChipSelect, spi, deviceOperations}  //
>       }
</details>
This looks suspicious, flash driver (even high level one) should not have hard coded mount moints for any device.

---

*[libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWXZ6bw2HHTMTWSfja:-KcWXZ6bw2HHTMTWSfjb:bdwc082) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h#L4)):*
> ```objc
> #define LIBS_OBC_STORAGE_N25Q_FLASH_INCLUDE_OBC_STORAGE_N25Q_H_
> 
> #include <array>
> ```

seems unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85)*

**Comment by Novakov** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/obc/storage/n25q_flash/n25q.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWYH9QEWYMIsDc54kk:-Kcd8M60D9beRsBqqKxR:b-q3wweo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/n25q.cpp#L28)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> _flashes{
>           {"/a", pins.Flash1ChipSelect, spi, deviceOperations}, //
>           {"/b", pins.Flash2ChipSelect, spi, deviceOperations}, //
>           {"/c", pins.Flash3ChipSelect, spi, deviceOperations}  //
>       }
This looks suspicious, flash driver (even high level one) should not have hard coded mount moints for any device.
</blockquote></details>

It's not flash driver of any kind - it's part of OBC structure - part that composes everything together

---

*[libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWXZ6bw2HHTMTWSfja:-KcdAutp8yFf2QEctvdA:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

seems unused
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/storage/n25q_flash/n25q.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWYH9QEWYMIsDc54kk:-KcdGu8zuS7U5nwUyGle:b4ltbe1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/n25q.cpp#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's not flash driver of any kind - it's part of OBC structure - part that composes everything together
</blockquote></details>

ok, so why there are 3 MakeDirectory calls in main.cpp with exact same list of directory paths?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/storage/n25q_flash/n25q.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85#-KcWYH9QEWYMIsDc54kk:-KcdHaq7_iTOjwUSK-J-:b-puodwc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf04d4e915e406747e39ab5b15daec470ad39884/libs/obc/storage/n25q_flash/n25q.cpp#L28)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

ok, so why there are 3 MakeDirectory calls in main.cpp with exact same list of directory paths?
</blockquote></details>

If you use development-only STK internal flash you want to mimic directory structure from flight model (N25Q flashes). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/85)*

**Pull request merged**
