### PR TITLE
Added automatic telemetry sending during Sail experiment

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/278)

### CODE REVIEW

**Comment by kfazi** [comment]
[Send automatically output from sail experiment as it progresses](https://trello.com/c/1rO0uRHw/237-send-automatically-output-from-sail-experiment-as-it-progresses)

**Comment by Novakov** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/experiments/sail/sail.cpp, line 335 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsnT_dA4tO0L0qsNHRZ:-KsnT_dA4tO0L0qsNHR_:b-c5n5xt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e020bff947e644d1b9fb0b4c322dadb8860a49f7/libs/experiments/sail/sail.cpp#L335)):*
> ```cpp
>         }
> 
>         void SailExperiment::SendTelemetry(const gsl::span<uint8_t>& data)
> ```

I would say that it's not telemetry, more like 'experiment data'

---

*[libs/experiments/sail/sail.cpp, line 339 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsnTO7fbMQbJxYCtsAX:-KsnTO7fbMQbJxYCtsAY:b-h30yab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e020bff947e644d1b9fb0b4c322dadb8860a49f7/libs/experiments/sail/sail.cpp#L339)):*
> ```cpp
>             LOGF(LOG_LEVEL_INFO, "[exp_sail] Sending telemetry, sequence %lu", telemetrySequence);
> 
>             CorrelatedDownlinkFrame message(DownlinkAPID::Operation, telemetrySequence++, correlationId);
> ```

Data send from sail experiment should have dedicated APID (we've got lots of them) . 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by kfazi** [comment]
Review status: 7 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/experiments/sail/sail.cpp, line 335 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsnT_dA4tO0L0qsNHRZ:-Ksr_kiaod17Vedi-OyL:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e020bff947e644d1b9fb0b4c322dadb8860a49f7/libs/experiments/sail/sail.cpp#L335)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I would say that it's not telemetry, more like 'experiment data'
</blockquote></details>

Done.

---

*[libs/experiments/sail/sail.cpp, line 339 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsnTO7fbMQbJxYCtsAX:-Ksr_mwAV0kehQ1xx0fm:b-iikm9w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e020bff947e644d1b9fb0b4c322dadb8860a49f7/libs/experiments/sail/sail.cpp#L339)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Data send from sail experiment should have dedicated APID (we've got lots of them) . 
</blockquote></details>

Done. Only automatic replies have separate APID, because experiment is started by experiment telecommand which has operation APID

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by zaq32** [comment]
Reviewed 6 of 15 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/base/Include/base/delegate.hpp, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGpd0Rf2DBgA6jYpC:-KsxGpd0Rf2DBgA6jYpD:boxt0ng) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L9)):*
> ```cpp
>  * This object stores pointer to class and it's member.
>  */
> template <typename TReturn, typename... TParams> class Delegate
> ```

define class methods outside class definition

---

*[libs/base/Include/base/delegate.hpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGl9sSfYlMNiz_c_C:-KsxGl9sSfYlMNiz_c_D:b-j5ar9y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L11)):*
> ```cpp
> template <typename TReturn, typename... TParams> class Delegate
> {
>     typedef TReturn (*Type)(void* callee, TParams...);
> ```

this type should be public as it is used in public interface of this class

---

*[libs/base/Include/base/delegate.hpp, line 42 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGgQ5tav_PgTC2zkR:-KsxGgQ5tav_PgTC2zkS:b-hxyh7g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L42)):*
> ```cpp
>     TReturn operator()(TParams... params) const
>     {
>         return (*function)(callee, params...);
> ```

std::move(params)...

---

*[libs/base/Include/base/delegate.hpp, line 53 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGbrixmwD_Utn4lTJ:-KsxGbrixmwD_Utn4lTK:b-hxyh7g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L53)):*
> ```cpp
>     {
>         T* object = static_cast<T*>(callee);
>         return (object->*TMethod)(params...);
> ```

std::move(params)...

---

*[libs/experiments/sail/sail.cpp, line 62 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxI7uWbxKinVDedv-A:-KsxI7uWbxKinVDedv-B:buqve17) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/sail.cpp#L62)):*
> ```cpp
>               _timeProvider(timeProvider),                 //
>               _sailState(sailState),                       //
>               transmitter(transmitter)                     //
> ```

uninitialized: telemetrySequence, correlationId

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIwSqGRnq4ehJgx1o:-KsxIwSqGRnq4ehJgx1p:ba0ot52) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L37)):*
> ```cpp
>              * @param experimentEnd New experiment end time.
>              */
>             virtual void SetExperimentEnd(std::chrono::milliseconds experimentEnd) = 0;
> ```

unused method

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 43 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIxyeXjTm3A9_iTI8:-KsxIxyeXjTm3A9_iTI9:ba0ot52) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L43)):*
> ```cpp
>              * @param nextTelemetryAcquisition Next telemetry acquisition time.
>              */
>             virtual void SetNextTelemetryAcquisition(std::chrono::milliseconds nextTelemetryAcquisition) = 0;
> ```

unused method

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 49 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIyVV8rCw9nPAmmbh:-KsxIyVV8rCw9nPAmmbi:ba0ot52) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L49)):*
> ```cpp
>              * @param nextPhotoTaken Next photo time.
>              */
>             virtual void SetNextPhotoTaken(std::chrono::milliseconds nextPhotoTaken) = 0;
> ```

unused method

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 273 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIMBk9gI80l6pUnWo:-KsxIMBk9gI80l6pUnWp:b2ic3p1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L273)):*
> ```cpp
>             uint32_t telemetrySequence;
> 
>             uint8_t correlationId;
> ```

unused field

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by kfazi** [comment]
Review status: 10 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/base/Include/base/delegate.hpp, line 9 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGpd0Rf2DBgA6jYpC:-KsyGM_T5JRoFumKTSQw:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

define class methods outside class definition
</blockquote></details>

Done.

---

*[libs/base/Include/base/delegate.hpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGl9sSfYlMNiz_c_C:-KsyGNg8F_6353beyu99:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L11)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this type should be public as it is used in public interface of this class
</blockquote></details>

Done.

---

*[libs/base/Include/base/delegate.hpp, line 42 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGgQ5tav_PgTC2zkR:-KsyGOVLm4-8b9qwTW8N:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

std::move(params)...
</blockquote></details>

Done.

---

*[libs/base/Include/base/delegate.hpp, line 53 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGbrixmwD_Utn4lTJ:-KsyGPLrD6saBWLCKgYT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L53)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

std::move(params)...
</blockquote></details>

Done.

---

*[libs/experiments/sail/sail.cpp, line 62 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxI7uWbxKinVDedv-A:-KsyGRUJHtOxKdEaoRxO:bqmttr6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/sail.cpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

uninitialized: telemetrySequence, correlationId
</blockquote></details>

Removed correlationId, initialized telemetrySequence

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIwSqGRnq4ehJgx1o:-KsyGVef70_Z3Py127Eb:ba3dfob) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused method
</blockquote></details>

Removed

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 43 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIxyeXjTm3A9_iTI8:-KsyGXL4hCO-Iw86GUe_:ba3dfob) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L43)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused method
</blockquote></details>

Removed

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 49 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIyVV8rCw9nPAmmbh:-KsyGYibFBI55ETo7NF6:ba3dfob) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L49)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused method
</blockquote></details>

Removed

---

*[libs/experiments/sail/Include/experiment/sail/sail.hpp, line 273 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxIMBk9gI80l6pUnWo:-KsyG_2VebKwXKZ5r-Kx:ba3dfob) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/experiments/sail/Include/experiment/sail/sail.hpp#L273)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused field
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by zaq32** [comment]
Reviewed 6 of 10 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/base/delegate.hpp, line 53 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGbrixmwD_Utn4lTJ:-KtCdTYhYa8bc709Uhgi:bacfjzg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L53)):*
<details><summary><i>Previously, kfazi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

incorrect order of parenthesis and ... operator. This construction will only work for single argument delegates.

---

*[libs/base/Include/base/delegate.hpp, line 62 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KtCdf3c2h3L0sRoR8U5:-KtCdf3c2h3L0sRoR8U6:bg5yh7u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b7f8ef1970286ca00c957ca85cc0f6ce45df8736/libs/base/Include/base/delegate.hpp#L62)):*
> ```cpp
> template <typename TReturn, typename... TParams> inline TReturn Delegate<TReturn, TParams...>::operator()(TParams... params) const
> {
>     return (*function)(callee, std::move(params...));
> ```

incorrect order of parenthesis (')') and '...' operator. This construction will only work for single argument delegates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by kfazi** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/delegate.hpp, line 53 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KsxGbrixmwD_Utn4lTJ:-KtChmvqYuc7r3_fNmUu:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0a8911b82826b0548bf99504fe39492857d2d4d9/libs/base/Include/base/delegate.hpp#L53)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

incorrect order of parenthesis and ... operator. This construction will only work for single argument delegates.
</blockquote></details>

Fixed

---

*[libs/base/Include/base/delegate.hpp, line 62 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278#-KtCdf3c2h3L0sRoR8U5:-KtChkqNH_Ab7Mjnhw3l:b-9xy8on) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b7f8ef1970286ca00c957ca85cc0f6ce45df8736/libs/base/Include/base/delegate.hpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

incorrect order of parenthesis (')') and '...' operator. This construction will only work for single argument delegates.
</blockquote></details>

Right, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/278)*

**Pull request merged**
