### PR TITLE
OBC Emulator

### PR DESCRIPTION
**Pull request by mandrek44**
- emulator (available with `pyconsole` target)
- time-related commands use timedelta
- additional SWO logs

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/206)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 7 of 47 files at r1, 1 of 3 files at r2.
Review status: 8 of 49 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration_tests/devices/comm.py, line 264 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWgR6j4uJ7tlrfIAyU:-KoWgR6j4uJ7tlrfIAyV:b-qvkjp3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/devices/comm.py#L264)):*
>         self.current_beacon = data[3:]
>         self.current_beacon_timestamp = time.localtime()
This should be executed only if the on_set_beacon hook allows it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206)*

**Comment by zaq32** [comment]
Reviewed 13 of 47 files at r1, 2 of 3 files at r2.
Review status: 23 of 49 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/commands/time.cpp, line 22 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWhanZIBU6xeE0BwCX:-KoWhan_Jgefo-H46Ljd:b1xj1dj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/src/commands/time.cpp#L22)):*
> ```cpp
> 
>     char* tail;
>     const auto targetTime = milliseconds(strtoul(argv[0], &tail, 10));
> ```

I hope you've updated all the tests as well 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206)*

**Comment by zaq32** [comment]
Reviewed 19 of 47 files at r1.
Review status: 42 of 49 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[integration_tests/emulator/beacon_parser/controller_a_telemetry_parser.py, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWijEzKyIZLHxJBeM1:-KoWijEzKyIZLHxJBeM2:bsvuvwm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/emulator/beacon_parser/controller_a_telemetry_parser.py#L4)):*
> ```Python
> 
> 
> class ControllerATelemetryParser(Parser):
> ```

The name should indicate that it is part of eps telemetry

---

*[integration_tests/emulator/beacon_parser/controller_b_telemetry_parser.py, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWipviF9th7yrvkkvz:-KoWipviF9th7yrvkkw-:b7drxnq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/emulator/beacon_parser/controller_b_telemetry_parser.py#L4)):*
> ```Python
> 
> 
> class ControllerBTelemetryParser(Parser):
> ```

the name should indicate that it is part of eps telemetry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206)*

**Comment by Novakov** [comment]
Review status: 42 of 49 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[integration_tests/devices/comm.py, line 264 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWgR6j4uJ7tlrfIAyU:-KoWscSDeLBL3DLMZzEZ:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/devices/comm.py#L264)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         self.current_beacon = data[3:]
>         self.current_beacon_timestamp = time.localtime()
This should be executed only if the on_set_beacon hook allows it
</blockquote></details>

Done

---

*[integration_tests/emulator/beacon_parser/controller_a_telemetry_parser.py, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWijEzKyIZLHxJBeM1:-KoWtLvXNy1F8J8Qlamh:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/emulator/beacon_parser/controller_a_telemetry_parser.py#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

The name should indicate that it is part of eps telemetry
</blockquote></details>

Done

---

*[integration_tests/emulator/beacon_parser/controller_b_telemetry_parser.py, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWipviF9th7yrvkkvz:-KoWtNBGCU5tEGg2bLX-:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/integration_tests/emulator/beacon_parser/controller_b_telemetry_parser.py#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

the name should indicate that it is part of eps telemetry
</blockquote></details>

Done

---

*[src/commands/time.cpp, line 22 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206#-KoWhanZIBU6xeE0BwCX:-KoWtWfP3q8jhd8glCQm:b-m2fa92) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ccbc1c91efdeb4a38004bbc4b6b07380089b6363/src/commands/time.cpp#L22)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I hope you've updated all the tests as well 
</blockquote></details>

All OBC time-related commands are now using `timedelta` parameters which are formeted to milliseconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206)*

**Comment by zaq32** [comment]
Reviewed 6 of 49 files at r1, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/206)*

**Pull request merged**
