### PR TITLE
[telecommand] Add command to request build information.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/291)

### CODE REVIEW

**Comment by zaq32** [comment]
[[TC] Send back compile info](https://trello.com/c/2HU5GVs5/262-tc-send-back-compile-info)

**Comment by Novakov** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/obc/communication/telecommands/compile_info.cpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291#-Ksxp8UddMmFIbYQZpG_:-Ksxp8UddMmFIbYQZpGa:bkgh5je) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/11d3cb304fdda509c575d6b0fd7a8dd14beaa207/libs/obc/communication/telecommands/compile_info.cpp#L32)):*
> ```cpp
>                 const std::uint8_t array[] = VERSION;
>                 writer.WriteByte(0);
>                 writer.WriteArray(array);
> ```

It would be nice to have static_assert to verify that `VERSION` will fit into single frame

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/compile_info.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291#-KsxoeaBYenu3Us8B6-7:-KsxoeaBYenu3Us8B6-8:bi66kl8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/11d3cb304fdda509c575d6b0fd7a8dd14beaa207/libs/obc/communication/telecommands/Include/obc/telecommands/compile_info.hpp#L22)):*
> ```cpp
>          *
>          * Parameters:
>          *  - 8-bit - APID that will be used in response
> ```

Not APID but correlation id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291)*

**Comment by zaq32** [comment]
Review status: 7 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/obc/communication/telecommands/compile_info.cpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291#-Ksxp8UddMmFIbYQZpG_:-KsyGOkNK1747Sul1V_G:b769fjl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/11d3cb304fdda509c575d6b0fd7a8dd14beaa207/libs/obc/communication/telecommands/compile_info.cpp#L32)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be nice to have static_assert to verify that `VERSION` will fit into single frame
</blockquote></details>

There were cases that version info was longer then downlink frame payload size. So I have added separate apid for version info and split entire information in two frames

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/compile_info.hpp, line 22 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291#-KsxoeaBYenu3Us8B6-7:-KsyGhoqx7VESiQvLXvp:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/11d3cb304fdda509c575d6b0fd7a8dd14beaa207/libs/obc/communication/telecommands/Include/obc/telecommands/compile_info.hpp#L22)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Not APID but correlation id
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291)*

**Comment by Novakov** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/291)*

**Pull request merged**
