### PR TITLE
Pyconsole improvments

### PR DESCRIPTION
**Pull request by Novakov**
* EPS/COMM watchdog kick time
* Ability to restart OBC with normal boot procedure (upper is still default)
* Script for downloading files from OBC via COMM

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/284)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Emulator] Ostatnie kopnięcie watchodoga COMMa](https://trello.com/c/BEpsEf5x/247-emulator-ostatnie-kopni%C4%99cie-watchodoga-comma)

**Comment by Novakov** [comment]
[[Emulator] Ostatnie kopnięcie watchodoga EPSa](https://trello.com/c/ky5wz8Hl/246-emulator-ostatnie-kopni%C4%99cie-watchodoga-epsa)

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration_tests/telecommand/__init__.py, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/284#-Ksr2hhv8byau0L6DTe2:-Ksr2hhv8byau0L6DTe3:bw8cpe5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/17dc41caafd447eaa7c66fded1d975c463493cd5/integration_tests/telecommand/__init__.py#L41)):*
> ```Python
>     'PerformSailExperiment',
>     'TakePhotoTelecommand',
>     'DeploySolarArrayTelecommand',
> ```

what is the reason?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/284)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration_tests/telecommand/__init__.py, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/284#-Ksr2hhv8byau0L6DTe2:-Ksr3TNnAvcjozza_3Bg:b83hv04) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/17dc41caafd447eaa7c66fded1d975c463493cd5/integration_tests/telecommand/__init__.py#L41)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the reason?
</blockquote></details>

SADS are deployed only as part of experiment.

I believe @mandrek44 added telecommand for deploying SADS only than removed it but entry in `__all__` remained

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/284)*

**Pull request merged**
