### PR TITLE
[Emulator Addons] Simulated frame sending and parsing time.

### PR DESCRIPTION
**Pull request by tom4r**
- Added transmitter simulator. When it is enabled it gets one by one frame from the queue.
- Mission Time and External time is converted to readable string.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/295)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[integration_tests/emulator/comm.py, line 78 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295#-Kt6gdM8A38cc4hdyFyI:-Kt6gdM8A38cc4hdyFyJ:b-vzorj9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cf927ca0409fea0ef5bf8726f57d651b5b626ff2/integration_tests/emulator/comm.py#L78)):*
> ```Python
>     def transmitter_simulator_loop(self):
>         if (not self._is_transmitter_simulated_checkbox.GetValue()) \
>                   or (self._system.transmitter.queue_size() < 1 and not self._last_message_processing_start):
> ```

It's better to split these conditions into few ifs - it will be easier to read 

---

*[integration_tests/emulator/comm.py, line 84 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295#-Kt6hFTPEZ-5Fh7mqvr9:-Kt6hFTPEZ-5Fh7mqvrA:b-5ynam2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cf927ca0409fea0ef5bf8726f57d651b5b626ff2/integration_tests/emulator/comm.py#L84)):*
> ```Python
>         if not self._last_message_processing_start:
>             self._last_message_processing_start = time.time()
>             self._system.comm.get_frame(0.01)
> ```

Handle empty queue exception 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295)*

**Comment by tom4r** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/emulator/comm.py, line 78 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295#-Kt6gdM8A38cc4hdyFyI:-Kt8JjwCALv6d6Rpem8H:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cf927ca0409fea0ef5bf8726f57d651b5b626ff2/integration_tests/emulator/comm.py#L78)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's better to split these conditions into few ifs - it will be easier to read 
</blockquote></details>

Done

---

*[integration_tests/emulator/comm.py, line 84 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295#-Kt6hFTPEZ-5Fh7mqvr9:-Kt8Jly4LsA58g4R1urY:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cf927ca0409fea0ef5bf8726f57d651b5b626ff2/integration_tests/emulator/comm.py#L84)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Handle empty queue exception 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295)*

**Comment by tom4r** [comment]
Additionally changed Beacon frames to be decoded from frames "sent", not set as beacon

**Comment by Novakov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/295)*

**Pull request merged**
