### PR TITLE
Error counters for IMTQ

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/178)

### CODE REVIEW

**Comment by mandrek44** [comment]
[[IMTQ] Error Counters](https://trello.com/c/p8igsEtB/188-imtq-error-counters)

**Comment by zaq32** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/178)*

**Comment by zaq32** [comment]
Reviewed 2 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/178)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/178)*

**Pull request merged**
