### PR TITLE
[TeleComm] Added SetBitrate telecommand

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/289)

### CODE REVIEW

**Comment by kfazi** [comment]
[[TC] Set COMM bitrate](https://trello.com/c/D6JraZC1/260-tc-set-comm-bitrate)

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Comment by zaq32** [comment]
Reviewed 5 of 7 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/response_frames/__init__.py, line 24 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289#-KsxEk2NKJHBmJAtdGAK:-KsxEk2NKJHBmJAtdGAL:bvk0zwo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/654a2469bc088bff7b8d4b84096a1e836c86f303/integration_tests/response_frames/__init__.py#L24)):*
> ```Python
> frame_types += map(lambda t: t[1], inspect.getmembers(set_bitrate, predicate=inspect.isclass))
> frame_types = filter(lambda t: issubclass(t, ResponseFrame) and t != ResponseFrame, frame_types)
> frame_types = reduce(lambda t, x: t + [x] if x not in t else t, frame_types, [])
> ```

what is the purpose of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Comment by zaq32** [comment]
Reviewed 2 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Comment by kfazi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration_tests/response_frames/__init__.py, line 24 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289#-KsxEk2NKJHBmJAtdGAK:-KsxLQLo-QWzkecfcvHD:b-8k3o5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/654a2469bc088bff7b8d4b84096a1e836c86f303/integration_tests/response_frames/__init__.py#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the purpose of this?
</blockquote></details>

This is needed to remove duplicate frame types.
inspect.getmembers() returns inherited classes and for example:
`class SetBitrateSuccessFrame(OperationSuccessFrame)`
will be resolved as both `SetBitrateSuccessFrame` and `OperationSuccessFrame`
what will cause exception in https://github.com/PW-Sat2/PWSat2OBC/blob/654a2469bc088bff7b8d4b84096a1e836c86f303/integration_tests/response_frames/downlink_frame_factory.py#L27

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/289)*

**Pull request merged**
