### PR TITLE
[telemetry] Extend telemetry acquisition of error counters state

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/172)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172#-Klxw9GGEj229FxcFL_d:-Klxw9GGEj229FxcFL_e:b-em1aeh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/56db28d23bd35d64d479612770c8dd9dec7e412a/unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp#L23)):*
> ```cpp
>     TEST(ErrorCountersTest, TestSerialization)
>     {
>         std::uint8_t expected[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa};
> ```

It is not consistent with telemetry definition - there should be 16 values

---

*[unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172#-Klxw8u1BD3LGOKvf_IU:-Klxw8u2PucB7oz6hZng:b-vtqoy1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/56db28d23bd35d64d479612770c8dd9dec7e412a/unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp#L24)):*
> ```cpp
>     {
>         std::uint8_t expected[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa};
>         std::array<std::uint8_t, (ErrorCountingTelemetry::BitSize() + 7) / 8> buffer;
> ```

I don't think `+7` is needed here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172)*

**Comment by zaq32** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172#-Klxw9GGEj229FxcFL_d:-Klxz4emgwWoCjrsLCLv:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/56db28d23bd35d64d479612770c8dd9dec7e412a/unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp#L23)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It is not consistent with telemetry definition - there should be 16 values
</blockquote></details>

Fixed

---

*[unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172#-Klxw8u1BD3LGOKvf_IU:-Klxz6SlMRVJRcc0dfAA:bt3obwx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/56db28d23bd35d64d479612770c8dd9dec7e412a/unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp#L24)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't think `+7` is needed here
</blockquote></details>

Strictly speaking it is not neccessary, but it does not have any negative impact and it is more resistant to future changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/172)*

**Pull request merged**
