### PR TITLE
Align telemetry in file

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/348)

### CODE REVIEW

**Comment by Novakov** [comment]
[[NCR #031] Telemetry at most 230 bytes + save to file at multiply of 230 bytes](https://trello.com/c/aB7lS21C/300-ncr-031-telemetry-at-most-230-bytes-save-to-file-at-multiply-of-230-bytes)

**Comment by zaq32** [comment]
Reviewed 18 of 31 files at r1.
Review status: 18 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Comment by zaq32** [comment]
Reviewed 11 of 31 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[integration_tests/tools/bit_joiner.py, line 1 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgj0A0S1KMp1iNkCF:-KwKgj0A0S1KMp1iNkCG:b6mwlkd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/integration_tests/tools/bit_joiner.py#L1)):*
> ```Python
> def encode(data):
> ```

is this even used?

---

*[libs/drivers/antenna/telemetry.cpp, line 59 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKfoY38AnsCroE1QFY:-KwKfoY38AnsCroE1QFZ:b-1qdsya) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/libs/drivers/antenna/telemetry.cpp#L59)):*
> ```cpp
>         }
> 
>         void AntennaTelemetry::SetBurningStatus(AntennaChannel channel, bool antenna1, bool antenna2, bool antenna3, bool antenna4)
> ```

enum is not guaranteed to not contain values that are not listed in its declaration. Mathematical operations on enums without prior range check should not be done. 

---

*[libs/drivers/antenna/telemetry.cpp, line 75 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKg1kKI2ac2SPspmEI:-KwKg1kKI2ac2SPspmEJ:bdzpkkk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/libs/drivers/antenna/telemetry.cpp#L75)):*
> ```cpp
>         }
> 
>         void AntennaTelemetry::SetTimeReached(AntennaChannel channel, bool antenna1, bool antenna2, bool antenna3, bool antenna4)
> ```

The three above functions are almost the same consider extracting common logic

---

*[unit_tests/drivers/antenna/AntennaTelemetryTest.cpp, line 286 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgMlMpBdDK1oOO9pt:-KwKgMlMpBdDK1oOO9pu:bxbr8vb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/unit_tests/drivers/antenna/AntennaTelemetryTest.cpp#L286)):*
> ```cpp
>     };
> 
>     //    TEST_P(AntennaTelemetryTest, GetDeploymentStatusPositive)
> ```

do not leave commented out code

---

*[unit_tests/drivers/EPS/EpsTelemetryTest.cpp, line 27 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgU0alB1TgVs3xEXZ:-KwKgU0alB1TgVs3xEX_:bb7r2f0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/unit_tests/drivers/EPS/EpsTelemetryTest.cpp#L27)):*
> ```cpp
>             ASSERT_THAT(buffer[i], Eq(expected[i])) << "Mismatch at position " << i;
>         }
>         //        ASSERT_THAT(writer.Status(), Eq(true));
> ```

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[integration_tests/tools/bit_joiner.py, line 1 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgj0A0S1KMp1iNkCF:-KwL4MnTZc4xqbowieEd:bm4d64w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/integration_tests/tools/bit_joiner.py#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

is this even used?
</blockquote></details>

Function - right in the last statement in this file
Script - no, it just for help someone next changing something in the telemetry to ease the pain of bit-level calculations

---

*[libs/drivers/antenna/telemetry.cpp, line 59 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKfoY38AnsCroE1QFY:-KwLMSjnPttxqNBR5Ewo:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/libs/drivers/antenna/telemetry.cpp#L59)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

enum is not guaranteed to not contain values that are not listed in its declaration. Mathematical operations on enums without prior range check should not be done. 
</blockquote></details>

Done.

---

*[libs/drivers/antenna/telemetry.cpp, line 75 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKg1kKI2ac2SPspmEI:-KwLMT9NPIjsUJHwQId5:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/libs/drivers/antenna/telemetry.cpp#L75)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

The three above functions are almost the same consider extracting common logic
</blockquote></details>

Done.

---

*[unit_tests/drivers/antenna/AntennaTelemetryTest.cpp, line 286 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgMlMpBdDK1oOO9pt:-KwL5cqqq1ZKjyCei6vM:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/unit_tests/drivers/antenna/AntennaTelemetryTest.cpp#L286)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not leave commented out code
</blockquote></details>

Done.

---

*[unit_tests/drivers/EPS/EpsTelemetryTest.cpp, line 27 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwKgU0alB1TgVs3xEXZ:-KwL5t6SEqTg2iJDcaMa:b-9xrigv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/106e7fa25656571ac44ec7f185a85ee5031c0850/unit_tests/drivers/EPS/EpsTelemetryTest.cpp#L27)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Debugging leftover. Uncommented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/antenna/telemetry.cpp, line 64 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwLNi_TC0mjV_j3JMSa:-KwLNi_TC0mjV_j3JMSb:bd8u7wu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f9f81880900e553a6a14165e3389ca03b25a4b5d/libs/drivers/antenna/telemetry.cpp#L64)):*
> ```cpp
>             auto idx = 4 * (channel - ANTENNA_FIRST_CHANNEL);
> 
>             if (idx > 4)
> ```

|| idx < 0

---

*[libs/drivers/antenna/Include/antenna/telemetry.hpp, line 338 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwLN_lcARHSPJWS6T7W:-KwLN_lcARHSPJWS6T7X:b-6732qk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f9f81880900e553a6a14165e3389ca03b25a4b5d/libs/drivers/antenna/Include/antenna/telemetry.hpp#L338)):*
> ```cpp
>         inline void AntennaTelemetry::SetActivationTimes(AntennaChannel channel, const ActivationTimes& times)
>         {
>             if (channel <= ANTENNA_BACKUP_CHANNEL && channel >= ANTENNA_FIRST_CHANNEL)
> ```

for conditions like this add static_assert that num(backup_channel) > num(first_channel)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Comment by Novakov** [comment]
Review status: 29 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/antenna/telemetry.cpp, line 64 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwLNi_TC0mjV_j3JMSa:-KwLSgDWcaN_7t-lUGkT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f9f81880900e553a6a14165e3389ca03b25a4b5d/libs/drivers/antenna/telemetry.cpp#L64)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

|| idx < 0
</blockquote></details>

Done.

---

*[libs/drivers/antenna/Include/antenna/telemetry.hpp, line 338 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348#-KwLN_lcARHSPJWS6T7W:-KwLSgjTkr6olTnabHw3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f9f81880900e553a6a14165e3389ca03b25a4b5d/libs/drivers/antenna/Include/antenna/telemetry.hpp#L338)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

for conditions like this add static_assert that num(backup_channel) > num(first_channel)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/348)*

**Pull request merged**
