### PR TITLE
More terminal commands in python

### PR DESCRIPTION
**Pull request by begreeen**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/389)

### CODE REVIEW

**Comment by tom4r** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[integration_tests/obc/flash.py, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6ragK-KRbuoaWjSyx0:-L6ragK-KRbuoaWjSyx1:bopgytx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/flash.py#L4)):*
> ```Python
> import re
> 
> class FLASHMixin(OBCMixin):
> ```

I don't like the uppercase Flash - it is not abbreviation.

---

*[integration_tests/obc/flash.py, line 19 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6reI-SEF3a-v6eDyK1:-L6reI-TruXttpNwlmjD:b-fxincj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/flash.py#L19)):*
> ```Python
>     @decode_return(_parse_testflash)
>     @command("testflash")
>     def test_flash(self, index):
> ```

Is the index argument used?

---

*[integration_tests/obc/imtq.py, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6rd5N9bx3xFSTdT9ph:-L6rd5N9bx3xFSTdT9pi:bhtpap1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/imtq.py#L33)):*
> ```Python
> 
>     @decode_return(_parse_lines_to_array)
>     @command("imtq PerformSelfTest 0")
> ```

Please dehardcode 0

untested example:
    @command("imtq PerformSelfTest {0}")
    def perform_self_test(self, fix=0):

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389)*

**Comment by tom4r** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389)*

**Comment by begreeen** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration_tests/obc/flash.py, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6ragK-KRbuoaWjSyx0:-L83mC6HIfql6VtdFUEy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/flash.py#L4)):*
<details><summary><i>Previously, tom4r wrote…</i></summary><blockquote>

I don't like the uppercase Flash - it is not abbreviation.
</blockquote></details>

Done.

---

*[integration_tests/obc/flash.py, line 19 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6reI-SEF3a-v6eDyK1:-L83m9GAtQlf7z6uhhtC:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/flash.py#L19)):*
<details><summary><i>Previously, tom4r wrote…</i></summary><blockquote>

Is the index argument used?
</blockquote></details>

Done.

---

*[integration_tests/obc/imtq.py, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389#-L6rd5N9bx3xFSTdT9ph:-L83m7u4Gagw8DVrqWhD:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5830b3c6a808ece431b5e19302abaf472b0de826/integration_tests/obc/imtq.py#L33)):*
<details><summary><i>Previously, tom4r wrote…</i></summary><blockquote>

Please dehardcode 0

untested example:
    @command("imtq PerformSelfTest {0}")
    def perform_self_test(self, fix=0):
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389)*

**Comment by tom4r** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389)*

**Comment by Novakov** [comment]
Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/389)*

**Pull request merged**
