### PR TITLE
EPS: remove error code as first byte

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/201)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/eps/eps.cpp, line 201 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201#-Ko3wGlKxxThrtRGm8r4:-Ko3wGlKxxThrtRGm8r5:bj5f3vc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dec97558e0a96f43819a51c79ab0eb647cba3e0a/libs/drivers/eps/eps.cpp#L201)):*
> ```cpp
>             if (controller == Controller::A)
>             {
>                 command[0] = 0x4B;
> ```

can you name this constant?

---

*[libs/drivers/eps/eps.cpp, line 205 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201#-Ko3wL2vChVtA5fFdCE2:-Ko3wL2vChVtA5fFdCE3:bj5f3vc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dec97558e0a96f43819a51c79ab0eb647cba3e0a/libs/drivers/eps/eps.cpp#L205)):*
> ```cpp
>             else
>             {
>                 command[0] = 0x07;
> ```

can you name this constant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/drivers/eps/eps.cpp, line 201 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201#-Ko3wGlKxxThrtRGm8r4:-Ko8KnJZd13wB6SEu6tf:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dec97558e0a96f43819a51c79ab0eb647cba3e0a/libs/drivers/eps/eps.cpp#L201)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

can you name this constant?
</blockquote></details>

Done.

---

*[libs/drivers/eps/eps.cpp, line 205 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201#-Ko3wL2vChVtA5fFdCE2:-Ko8KnYD1w3933RXellR:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dec97558e0a96f43819a51c79ab0eb647cba3e0a/libs/drivers/eps/eps.cpp#L205)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

can you name this constant?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/201)*

**Comment by Novakov** [comment]
[[BUG] EPS driver cannot not read device telemetry](https://trello.com/c/vpuAvyqH/198-bug-eps-driver-cannot-not-read-device-telemetry)

**Pull request merged**
