### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by zaq32**
* Update doxygen configuration file to make it more suitable for c++,
* Fix some doxygen issues,
* Fix typo in the project documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/60)

### CODE REVIEW

**Comment by Novakov** [comment]
Would it be possible to reduce Doxygen verbosity? It's hard to catch warnings in that amount of output

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60#-:-KYrDe-SbNSC_MZ3imER:b8tdyxb)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60#-KYrDwm_FxJ0H-p7H5Xt:-KYrDwm_FxJ0H-p7H5Xu:b-atf57p) (no related file):*
Would it be possible to reduce Doxygen verbosity? It's hard to catch warnings in that amount of output

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60)*

**Comment by zaq32** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60#-KYrDwm_FxJ0H-p7H5Xt:-KYrEpvTDYefkQl87_wH:bh5s1s6) (no related file):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Would it be possible to reduce Doxygen verbosity? It's hard to catch warnings in that amount of output
</blockquote></details>

Take a look now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60#-KYrDwm_FxJ0H-p7H5Xt:-KYyLHh3cTyHTc8ws-6F:b8bj6tk) (no related file):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Take a look now.
</blockquote></details>

Now it is possible to see something :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/60)*

**Pull request merged**
