### PR TITLE
Telecommand: stop antenna deploymen

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/202)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko89an65Na9PdIIqvhO:-Ko89an65Na9PdIIqvhP:b-jsonb9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/mission/antenna/Include/mission/antenna_task.hpp#L61)):*
> ```cpp
>         };
> 
>         class StopAntennaDeploymentTask : public mission::Action, public IDisableAntennaDeployment
> ```

Why to build this task instead of updating antenna configuration stored in persistent state directly from telecommand?

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/antenna.hpp, line 12 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko8AFp07Cx9-jBN10Ek:-Ko8AFp07Cx9-jBN10El:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/obc/communication/telecommands/Include/obc/telecommands/antenna.hpp#L12)):*
> ```cpp
>     namespace telecommands
>     {
>         class StopAntennaDeployment : public telecommunication::uplink::Telecommand<0xA3>
> ```

undocumented

---

*[libs/state/Antenna.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko8AJfS02ib4VLNFm-V:-Ko8AJfS02ib4VLNFm-W:b32vmt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/state/Antenna.cpp#L23)):*
> ```cpp
>         if (!isDeploymentDisabled)
>         {
>             LOG(LOG_LEVEL_INFO, "[TUTUAJ]");
> ```

??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202)*

**Comment by Novakov** [comment]
Review status: 31 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko89an65Na9PdIIqvhO:-Ko8BM5Lr3dd6oyGPwFw:bx9kxok) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/mission/antenna/Include/mission/antenna_task.hpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Why to build this task instead of updating antenna configuration stored in persistent state directly from telecommand?
</blockquote></details>

Mainly to coordinate with end of antenna deployment process, also to avoid any synchronization problems with persistant state

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/antenna.hpp, line 12 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko8AFp07Cx9-jBN10Ek:-Ko8BaPseJtNVaBhaK-A:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/obc/communication/telecommands/Include/obc/telecommands/antenna.hpp#L12)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/state/Antenna.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko8AJfS02ib4VLNFm-V:-Ko8BFO0sjvGXVel24WD:bcgn7bm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/state/Antenna.cpp#L23)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

??
</blockquote></details>

Yep, realised 5 seconds after pushing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko89an65Na9PdIIqvhO:-Ko8Bx_VuFK9hzeo00s4:b4rkjcp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/mission/antenna/Include/mission/antenna_task.hpp#L61)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Mainly to coordinate with end of antenna deployment process, also to avoid any synchronization problems with persistant state
</blockquote></details>

the persistent state will have to be synchronized anyway as there will be more telecommands that need to either read or write it i.e. TimeTelecommand. However such synchronization is progressing very slowly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202#-Ko89an65Na9PdIIqvhO:-Ko8COGCy8RvIX67J-cs:b-t7329d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dfb6d35c6b1f5305a15a06612a4c408875fc410/libs/mission/antenna/Include/mission/antenna_task.hpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

the persistent state will have to be synchronized anyway as there will be more telecommands that need to either read or write it i.e. TimeTelecommand. However such synchronization is progressing very slowly.
</blockquote></details>

That's true but using mission task is simple way of coordinating with antenna deployment and achieving 'Do it when you can' behavior

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/202)*

**Pull request merged**
