### PR TITLE
RFC - Error counters

### PR DESCRIPTION
**Pull request by Novakov**
Draft for error counting mechanism.

ToDo (in this pull request or another):
* Storing current configuration in FRAM
* Telecommands for changing config
* Publishing error counts to global state (for telemetry)
* Integration with all devices

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/98)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 22 of 24 files at r1.
Review status: 22 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Comment by zaq32** [comment]
Reviewed 2 of 24 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 122 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNO8SlqvovO5_b-xpY:-KfNO8SmpLZhUVGpNHcp:bkzkdvz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/drivers/comm/comm.cpp#L122)):*
> ```cpp
> bool CommObject::Reset()
> {
>     return this->SendCommand(Address::Receiver, num(ReceiverCommand::HardReset)) >> this->_error;
> ```

if we are to adopt device error counting then every communication transaction should affect the device's counter.

---

*[libs/error_counter/error_counter.cpp, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNL5t-pUISsZf1FpDn:-KfNL5t-pUISsZf1FpDo:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L7)):*
> ```cpp
>     CounterValue ErrorCounting::Current(Device device) const
>     {
>         Lock l(this->_sync, InfiniteTimeout);
> ```

unhandled error condition

---

*[libs/error_counter/error_counter.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLAxslUPRJ3V7fViN:-KfNLAxslUPRJ3V7fViO:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L15)):*
> ```cpp
>         auto increment = this->_config.Increment(device);
> 
>         Lock l(this->_sync, InfiniteTimeout);
> ```

unhandled error condition

---

*[libs/error_counter/error_counter.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLFeaaoe99oZpqOuP:-KfNLFeaaoe99oZpqOuQ:b-p7nz8i) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L23)):*
> ```cpp
>             if (this->_callback != nullptr)
>             {
>                 this->_callback->LimitReached(device, this->_counters[device]);
> ```

In general case it is rather risky to call externally provided functions while holding a lock.

---

*[libs/error_counter/error_counter.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLT1jkAQqSUYRIZpn:-KfNLT1jkAQqSUYRIZpo:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L30)):*
> ```cpp
>     void ErrorCounting::Handler(IErrorCountingCallback& callback)
>     {
>         Lock l(this->_sync, InfiniteTimeout);
> ```

unhandled error condition

---

*[libs/error_counter/error_counter.cpp, line 36 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLTa7OgGXDa38wxBF:-KfNLTa7OgGXDa38wxBG:b-dbn2m7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L36)):*
> ```cpp
>     void ErrorCounting::Success(Device device)
>     {
>         Lock l(this->_sync, InfiniteTimeout);
> ```

unhandled error condition

---

*[libs/error_counter/error_counter.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLXKOq1SHyrLTGeuI:-KfNLXKOq1SHyrLTGeuJ:bfoymrh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L47)):*
> this->_sync = System::CreateBinarySemaphore(1);
> System::GiveSemaphore(this->_sync);
unhandled error condition

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLe4uHAX2Zz6-KHTJ:-KfNLe4uHAX2Zz6-KHTK:b-y13r1y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
> ```cpp
>      * When error limit (also configurable) is reach, callback is invoked
>      */
>     class ErrorCounting
> ```

I do not like the idea of monotonic counters that can only be increased or reset to zero. Such policy makes this system prone to trigger errors as soon as the requested number of errors or ignore them if one every N communication transactions succeeds. I believe the error counters should be slowly decreased (with zero cut off) in case of the successful communication. This will allow to safely overwrite infrequent problems and will still issue a red flag if errors start appearing in series.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNMsDRCB9E3WAVhrhS:-KfNMsDRCB9E3WAVhrhT:b8fhos0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
> ```cpp
>      * When error limit (also configurable) is reach, callback is invoked
>      */
>     class ErrorCounting
> ```

also consider using interlocks instead of semaphore.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNOSXkP2y-Tgtmo8j:-KfNNOSXkP2y-Tgtmo8k:bqp4jyu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
> ```cpp
>      * When error limit (also configurable) is reach, callback is invoked
>      */
>     class ErrorCounting
> ```

mark as final

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 121 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNLVT0vai4lXh8Y-6:-KfNNLVT0vai4lXh8Y-7:bqp4jyu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L121)):*
> ```cpp
>      * @tparam Device Device ID
>      */
>     template <Device Device> class ErrorCounter
> ```

mark as final

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 143 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNIhLYuML1IX5zpRQ:-KfNNIhLYuML1IX5zpRR:b-a2q8xl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L143)):*
> ```cpp
>     }
> 
>     template <Device Device> std::uint8_t ErrorCounter<Device>::Current() const
> ```

mark as inline 

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNI9ZMMgHkb5wV7wy:-KfNNI9ZMMgHkb5wV7wz:b-a2q8xl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L148)):*
> ```cpp
>     }
> 
>     template <Device Device> void ErrorCounter<Device>::Failure()
> ```

mark as inline 

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 153 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNGrToFwaTVsYFkN8:-KfNNGrToFwaTVsYFkN9:b-a2q8xl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L153)):*
> ```cpp
>     }
> 
>     template <Device Device> void ErrorCounter<Device>::Success()
> ```

mark as inline 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Comment by Novakov** [comment]
Review status: 9 of 25 files reviewed at latest revision, 14 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 122 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNO8SlqvovO5_b-xpY:-KfNQskGVasxIb0x68SL:b-eg81sp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/drivers/comm/comm.cpp#L122)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

if we are to adopt device error counting then every communication transaction should affect the device's counter.
</blockquote></details>

Sure - just before doing that I want to get at least some feedback on the overall idea.

---

*[libs/error_counter/error_counter.cpp, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNL5t-pUISsZf1FpDn:-KfNbRYUS_WloMfgnBw7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLAxslUPRJ3V7fViN:-KfNbS7fiXkEYwuLd5Wq:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 23 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLFeaaoe99oZpqOuP:-KfNbSVK_4WuOPXl8XPP:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L23)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

In general case it is rather risky to call externally provided functions while holding a lock.
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLT1jkAQqSUYRIZpn:-KfNbT0RIEtg07Mh6sN1:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L30)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 36 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLTa7OgGXDa38wxBF:-KfNbTTAUHuCxJnTQBOt:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L36)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unhandled error condition
</blockquote></details>

Done.

---

*[libs/error_counter/error_counter.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLXKOq1SHyrLTGeuI:-KfNbTz5E1Df1uEBGmnr:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/error_counter.cpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> this->_sync = System::CreateBinarySemaphore(1);
> System::GiveSemaphore(this->_sync);
unhandled error condition
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNMsDRCB9E3WAVhrhS:-KfNbV38fCmzJ78Z2KJ5:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

also consider using interlocks instead of semaphore.
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNOSXkP2y-Tgtmo8j:-KfNbZBbWurdNgj3pRTr:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as final
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNLe4uHAX2Zz6-KHTJ:-Kfbyg30DjV6KYxE9vn8:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L62)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I do not like the idea of monotonic counters that can only be increased or reset to zero. Such policy makes this system prone to trigger errors as soon as the requested number of errors or ignore them if one every N communication transactions succeeds. I believe the error counters should be slowly decreased (with zero cut off) in case of the successful communication. This will allow to safely overwrite infrequent problems and will still issue a red flag if errors start appearing in series.
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 121 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNLVT0vai4lXh8Y-6:-KfNbZNkBv_PK_KFaUYv:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L121)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as final
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 143 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNIhLYuML1IX5zpRQ:-KfNbccn81ZwshILwzB3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L143)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as inline 
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNI9ZMMgHkb5wV7wy:-KfNbd-kIQe9fZv2cFyA:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L148)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as inline 
</blockquote></details>

Done.

---

*[libs/error_counter/Include/error_counter/error_counter.hpp, line 153 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfNNGrToFwaTVsYFkN8:-KfNbdO9T7k8KMEThhHg:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eb75d570fade016f3b3ba14d63e9c041e95524f9/libs/error_counter/Include/error_counter/error_counter.hpp#L153)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

mark as inline 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Comment by zaq32** [comment]
Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/traits.hpp, line 105 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfrKYQOPwVxYvWCWiiP:-KfrKYQOPwVxYvWCWiiQ:ba1qz5t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c3c68ab6ed926e9e5b31e776c70b4e2b6f5561b6/libs/base/Include/traits.hpp#L105)):*
> ```cpp
>  * @brief Returns integer type that is wider than given type
>  */
> template <typename T> struct Wider
> ```

when you depend explicitly on template specialization the default version should not be defined.

---

*[libs/error_counter/CMakeLists.txt, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfrM_U-yIuTA7BdQ1Jr:-KfrM_U-yIuTA7BdQ1Js:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c3c68ab6ed926e9e5b31e776c70b4e2b6f5561b6/libs/error_counter/CMakeLists.txt#L10)):*
> ```CMake
> 
> target_link_libraries(${NAME} 
> 	base
> ```

unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Comment by Novakov** [comment]
Review status: 24 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/traits.hpp, line 105 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfrKYQOPwVxYvWCWiiP:-KfrQ6oKinsNV1N-n2o5:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c3c68ab6ed926e9e5b31e776c70b4e2b6f5561b6/libs/base/Include/traits.hpp#L105)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

when you depend explicitly on template specialization the default version should not be defined.
</blockquote></details>

Done

---

*[libs/error_counter/CMakeLists.txt, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98#-KfrM_U-yIuTA7BdQ1Jr:-KfrOQosLLGpUw7CsgrG:b-qmaoyn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c3c68ab6ed926e9e5b31e776c70b4e2b6f5561b6/libs/error_counter/CMakeLists.txt#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unused
</blockquote></details>

`traits.hpp` header from base is used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/98)*

**Pull request merged**
