### PR TITLE
[TC] Add command to obtain current raw copy of the persistent state.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/266)

### CODE REVIEW

**Comment by zaq32** [comment]
[[TC] Dump persistent state](https://trello.com/c/OOs3NfiK/248-tc-dump-persistent-state)

**Comment by Novakov** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[integration_tests/persistent_state/__init__.py, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266#-KruTtJq8HEYQxg66IOv:-KruTtJq8HEYQxg66IOw:b-wm9z51) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c14131d68cb76ec8c5f208022a7ec700b7af2709/integration_tests/persistent_state/__init__.py#L11)):*
> ```Python
> 
> PersistentStateParser = joint(
>     count(AntennaConfiguration, 1),
> ```

No need to use `count` if you want to match single element

---

*[integration_tests/persistent_state/base.py, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266#-KruU-jUr754txCnjU-W:-KruU-jUr754txCnjU-X:bbshswo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c14131d68cb76ec8c5f208022a7ec700b7af2709/integration_tests/persistent_state/base.py#L41)):*
> ```Python
> int16 = packed('<h')
> 
> uint32 = packed('<L')
> ```

As these utils are quite useful you can put it in separate file and use from `persistent_state` and from `experiment_file`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266)*

**Comment by zaq32** [comment]
Review status: 10 of 25 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[integration_tests/persistent_state/__init__.py, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266#-KruTtJq8HEYQxg66IOv:-Krz6kCb1XEw0FHRtofK:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c14131d68cb76ec8c5f208022a7ec700b7af2709/integration_tests/persistent_state/__init__.py#L11)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

No need to use `count` if you want to match single element
</blockquote></details>

Done.

---

*[integration_tests/persistent_state/base.py, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266#-KruU-jUr754txCnjU-W:-Krz6h-SykmUnF1AtKSY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c14131d68cb76ec8c5f208022a7ec700b7af2709/integration_tests/persistent_state/base.py#L41)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

As these utils are quite useful you can put it in separate file and use from `persistent_state` and from `experiment_file`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/266)*

**Pull request merged**
