### PR TITLE
Implemented N25Q Driver with TMR

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/129)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/n25q/n25q.cpp, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiA1jL0c7qhP4YedXPh:-KiA1jL0c7qhP4YedXPi:b-yh00rc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/n25q.cpp#L20)):*
> ```cpp
> using drivers::spi::ISPIInterface;
> using drivers::spi::SPISelectSlave;
> using redundancy::Voter;
> ```

I don't see any usage of this in this file

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiAOlxf1mqbQSW9cXRR:-KiAOlxf1mqbQSW9cXRS:bwclmtu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L148)):*
> ```objc
>              * @param[in] offset Chunk address offset
>              * @param[in] chunk Buffer
>              * @return Operation waiter
> ```

Add remark (and assert) 

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATFYEnL2MHAAR8YBK:-KiATFYEnL2MHAAR8YBL:b81zhnn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L165)):*
> ```objc
>              * Operation can take up to 5ms per page
>              */
>             OperationResult WriteMemory(size_t address, gsl::span<const uint8_t> buffer);
> ```

Writing in chunks will be enough - remove if not needed elsewhere

---

*[src/commands/file_system.cpp, line 330 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATMg-6oEyUpVqTg1Z:-KiATMg-6oEyUpVqTg1_:b-6qlm9a) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/src/commands/file_system.cpp#L330)):*
> ```cpp
>     //
>     //        Main.terminal.NewLine();
>     //    }
> ```

// comments!!!!!!!1111

---

*[unit_tests/base/RedundancyTest.cpp, line 36 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATPc3EiqADwZFzuH1:-KiATPc3EiqADwZFzuH2:b8eg17v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/unit_tests/base/RedundancyTest.cpp#L36)):*
> ```cpp
>     ASSERT_THAT(corrector.Correct(0b0000001, 0b0010000, 0b0010000), Eq(0b0010000));
>     ASSERT_THAT(corrector.Correct(0b0010000, 0b0010001, 0b0000000), Eq(0b0010000));
>     ASSERT_THAT(corrector.Correct(0b1010101, 0b1110000, 0b0010001), Eq(0b1010001));
> ```

At least one test case is missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by zaq32** [comment]
Reviewed 2 of 5 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/redundancy.hpp, line 42 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiExxv8DFqYtvAAKMw7:-KiExxv8DFqYtvAAKMw8:b-6ehhkm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/base/Include/redundancy.hpp#L42)):*
> ```cpp
>      * @tparam T Type used for majority vote. Must implement bitwise & and | operations.
>      */
>     template <typename T> struct BitwiseCorrector
> ```

add static_assert to ensure that T is an integral or enum type. 

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 152 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF-u-MHQ08uA-LcBGB:-KiF-u-MHQ08uA-LcBGC:b8ifvf0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L152)):*
> ```objc
>              * Operation can take up to 5ms
>              */
>             OperationWaiter BeginWriteChunk(size_t address, ptrdiff_t offset, gsl::span<const uint8_t> chunk);
> ```

What is the reason of using the OperationWaiter type as return value? It is not being used to allow caller to wait for operation to complete (it is done internally by the driver) and all the extra information it provides can be returned directly.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 306 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF1Cf82GR9NaykVBB0:-KiF1Cf82GR9NaykVBB1:b-27qznx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L306)):*
> ```objc
>              * @param[in] address Start address
>              * @param[out] outputBuffer Output buffer
>              * @param[in] redundantBuffer1 First buffer used for redundant read
> ```

redundantBuffer1 & redundantBuffer1 are also out parameters

Documentaiton should also specify that all buffers should have the same length. This function should use length of the shortest buffer as data size if they are not equal length.

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2VejA5E7zVxmyM2M:-KiF2VejA5E7zVxmyM2N:b1vvwwy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L39)):*
> ```objc
>          * @tparam TotalSize Total memory size
>          */
>         template <BlockMapping blockMapping, std::size_t ChunkSize, std::size_t TotalSize> class N25QYaffsDevice
> ```

define template methods outside class template definition

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 58 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2mYQZIhcmdP02cTr:-KiF2mYQZIhcmdP02cTs:b-p5mp5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L58)):*
> BlockSize(blockMapping)
This can be done at compile time

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 146 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2DV1cJCLv-08CUub:-KiF2DV1cJCLv-08CUuc:b-pwk1i0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L146)):*
> ```objc
> 
>                 gsl::span<uint8_t> outputBuffer(data, data_len);
>                 gsl::span<uint8_t> redundantBuffer1(This->_redundantReadBuffer1.data(), data_len);
> ```

assuming that data_len <= ChunkSize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by Novakov** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by mandrek44** [comment]
Review status: 9 of 18 files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/base/Include/redundancy.hpp, line 42 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiExxv8DFqYtvAAKMw7:-KiW_BBQwPg-fEvOHlIO:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/base/Include/redundancy.hpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

add static_assert to ensure that T is an integral or enum type. 
</blockquote></details>

Done.

---

*[libs/drivers/n25q/n25q.cpp, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiA1jL0c7qhP4YedXPh:-KiWZnXftSDYzBszeUU0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/n25q.cpp#L20)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't see any usage of this in this file
</blockquote></details>

Done.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiAOlxf1mqbQSW9cXRR:-KiGcP6SmRublfHqCAAg:b7fg40t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L148)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add remark (and assert) 
</blockquote></details>

I'm bit confused - how can I assert the length of the page? Any hint?

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATFYEnL2MHAAR8YBK:-KiWZpEzybuJFSEKWElT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L165)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Writing in chunks will be enough - remove if not needed elsewhere
</blockquote></details>

Done.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 152 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF-u-MHQ08uA-LcBGB:-KiGcoVgrWyt8GLbfxxH:b73o21k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L152)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

What is the reason of using the OperationWaiter type as return value? It is not being used to allow caller to wait for operation to complete (it is done internally by the driver) and all the extra information it provides can be returned directly.
</blockquote></details>

`RedundantN25QDriver::WriteMemory` will call `BeginWritePage` for all 3 chips and then wait for them to report that the operation is finished. As far I as understand it, page is writen first to chip buffer and we have to wait until chip finishes writing it to the flash storage. This allows us to initiate the writing on all 3 chips simultaneously
 

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 306 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF1Cf82GR9NaykVBB0:-KiWZr0HtfnbXI-K8eqe:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L306)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

redundantBuffer1 & redundantBuffer1 are also out parameters

Documentaiton should also specify that all buffers should have the same length. This function should use length of the shortest buffer as data size if they are not equal length.
</blockquote></details>

Done.

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 39 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2VejA5E7zVxmyM2M:-KiWZu1r1GMTfuKxQdV3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L39)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

define template methods outside class template definition
</blockquote></details>

Done.

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 58 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2mYQZIhcmdP02cTr:-KiWZxjsVse8lY8oGT1H:bqzjwox) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L58)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> BlockSize(blockMapping)
This can be done at compile time
</blockquote></details>

Look at the implementation - is this correct way to achieve this?

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 146 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2DV1cJCLv-08CUub:-KiGlGzgx8_hUPPadJTc:bqcdx56) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L146)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

assuming that data_len <= ChunkSize
</blockquote></details>

Yes - I added a check and logging if it's not true

---

*[src/commands/file_system.cpp, line 330 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATMg-6oEyUpVqTg1Z:-KiW_DND51pLoKIyJn7c:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/src/commands/file_system.cpp#L330)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

// comments!!!!!!!1111
</blockquote></details>

Done.

---

*[unit_tests/base/RedundancyTest.cpp, line 36 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiATPc3EiqADwZFzuH1:-KiW_7VE0w5JOtIrofBO:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/unit_tests/base/RedundancyTest.cpp#L36)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

At least one test case is missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by Novakov** [comment]
Reviewed 2 of 5 files at r2, 8 of 10 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiAOlxf1mqbQSW9cXRR:-KieSbsWeJjowug-oMrn:bdxcsr0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L148)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

I'm bit confused - how can I assert the length of the page? Any hint?
</blockquote></details>

It can't be static_assert, so some assert in runtime by calling extern `assertFailed` function (like in EFM/FreeRTOS)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 152 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF-u-MHQ08uA-LcBGB:-Kif_nFNNuFQMtgBXuiV:b-bgil4h) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L152)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

`RedundantN25QDriver::WriteMemory` will call `BeginWritePage` for all 3 chips and then wait for them to report that the operation is finished. As far I as understand it, page is writen first to chip buffer and we have to wait until chip finishes writing it to the flash storage. This allows us to initiate the writing on all 3 chips simultaneously
 
</blockquote></details>

This is what you intended but it is not what actually happens. What happens right now is as follows:

* OperationWaiter is created inside the BeginWritePage function. Lets call this object x. 
* return statement is being executed which will either copy or move (depending on the type & context, most likely move) object x to the outside object. Lets call it y. 
Now object y contains a copy of the state of object x. 
* **Destructor of object x** is called, which calls Wait & it subsequently **waits for write operation to finish**
(several us later)
* Destructor of object x finishes its execution
* BeginWritePage function ends
* user calls Wait on object y which tries to wait for the same operation to finish. 

As you can see current implementation despite being intended as non blocking it is not. This makes every function call in fact fully synchronous. 

---

*[libs/drivers/n25q/Include/n25q/yaffs.h, line 58 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF2mYQZIhcmdP02cTr:-KiexfFSA6_P0Pk2COxr:b2nign6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/yaffs.h#L58)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

Look at the implementation - is this correct way to achieve this?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by mandrek44** [comment]
Review status: 11 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 148 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiAOlxf1mqbQSW9cXRR:-Kil8pCe-nhcLwP7berm:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/af34208577e0f3ba470e327d6b7286f7aa78bee9/libs/drivers/n25q/Include/n25q/n25q.h#L148)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It can't be static_assert, so some assert in runtime by calling extern `assertFailed` function (like in EFM/FreeRTOS)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by mandrek44** [comment]
Review status: 11 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/n25q/Include/n25q/n25q.h, line 152 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129#-KiF-u-MHQ08uA-LcBGB:-Kil9rsp2D2_dr3VcHfL:bz0o0tw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e323c805e391dfebeee82d87ffc85e70fec20cd8/libs/drivers/n25q/Include/n25q/n25q.h#L152)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This is what you intended but it is not what actually happens. What happens right now is as follows:

* OperationWaiter is created inside the BeginWritePage function. Lets call this object x. 
* return statement is being executed which will either copy or move (depending on the type & context, most likely move) object x to the outside object. Lets call it y. 
Now object y contains a copy of the state of object x. 
* **Destructor of object x** is called, which calls Wait & it subsequently **waits for write operation to finish**
(several us later)
* Destructor of object x finishes its execution
* BeginWritePage function ends
* user calls Wait on object y which tries to wait for the same operation to finish. 

As you can see current implementation despite being intended as non blocking it is not. This makes every function call in fact fully synchronous. 
</blockquote></details>

Good point - I changed the `OperationWaiter` to support move semantics, I also added unit tests to make sure everything works as expected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Comment by zaq32** [comment]
Reviewed 7 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/129)*

**Pull request merged**
