### PR TITLE
Update os wrapper to cpp

### PR DESCRIPTION
**Pull request by Novakov**
All function pointers from `OS` structure have been converted to static methods. Their implementions are added at link-time by linking to `free_rtos_wrapper` in `pwsat`. Also unit tests have their own mock-friendly implementations.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/52)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 20 of 22 files at r1.
Review status: 19 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/base/Include/base/os.h, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM71dZi6t6vyNAD6Md:-KXM71dZi6t6vyNAD6Me:b-vyfzdx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L32)):*
> ```objc
>  * @brief Enumerator for all possible operating system error codes.
>  */
> enum OSResult
> ```

in this case enum class would be more apropriate.

---

*[libs/base/Include/base/os.h, line 204 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM7F0qGkg3tg9E9ZNg:-KXM7F0qGkg3tg9E9ZNh:bulmzj6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L204)):*
> ```objc
>     template <typename Param>
>     static OSResult CreateTask(void (*entryPoint)(Param&),
>         Param& param,
> ```

passing task parameter by reference is dangerous as it enforces task creator to ensure that reference parameter object  is alive for unspecified period of time.

---

*[libs/base/Include/base/os.h, line 417 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM9fKl6d-1i_gr276l:-KXM9fKl6d-1i_gr276m:b181vfs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L417)):*
> ```objc
>     OSTaskHandle* taskHandle)
> {
>     auto entryPointPtr = reinterpret_cast<OSTaskProcedure>(entryPoint);
> ```

Converting function pointers is very risky

---

*[libs/base/Include/base/os.h, line 419 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM9YzHnlh9z-szaexF:-KXM9YzHnlh9z-szaexG:blrsfaa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L419)):*
> ```objc
>     auto entryPointPtr = reinterpret_cast<OSTaskProcedure>(entryPoint);
> 
>     return System::CreateTask(entryPointPtr, taskName, stackSize, &param, priority, taskHandle);
> ```

Undefined behaviour: implicit conversion from pointer to reference

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by zaq32** [comment]
Reviewed 2 of 22 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by decu69** [comment]
*[libs/base/Include/base/os.h, line 204 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM7F0qGkg3tg9E9ZNg:-KXMlc-2knNKacS58EKM:b3zblgs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L204)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> passing task parameter by reference is dangerous as it enforces task creator to ensure that reference parameter object  is alive for unspecified period of time.
</details>
how should that be resolved correctly? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by Novakov** [comment]
Review status: 7 of 46 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/base/Include/base/os.h, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM71dZi6t6vyNAD6Md:-KXNLkR1kVN48C15UQ30:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> in this case enum class would be more apropriate.
</details>
Done.

---

*[libs/base/Include/base/os.h, line 204 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM7F0qGkg3tg9E9ZNg:-KXNLlL4zG3tnjUW5C4K:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L204)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> how should that be resolved correctly? 
</details>
Done.

---

*[libs/base/Include/base/os.h, line 417 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM9fKl6d-1i_gr276l:-KXNLhkLaLu12ZTBl2gw:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L417)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Converting function pointers is very risky
</details>
Done.

---

*[libs/base/Include/base/os.h, line 419 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXM9YzHnlh9z-szaexF:-KXNLi9ZAMF4U0vSPMcA:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/76648d4a1ea155bfd294dcf6a7ae6bd47257fac6/libs/base/Include/base/os.h#L419)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Undefined behaviour: implicit conversion from pointer to reference
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by zaq32** [comment]
Reviewed 1 of 22 files at r1, 39 of 39 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/base/Include/utils.h, line 14 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgV9BaOeeNhuaD_-MX:-KXgV9BaOeeNhuaD_-MY:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L14)):*
> ```objc
> }
> 
> constexpr std::size_t operator"" _Bytes(unsigned long long int value)
> ```

undocumented

---

*[libs/base/Include/utils.h, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVBMOiJ5n7mA1MgIP:-KXgVBMPzhaBVAlX0C5N:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L19)):*
> ```objc
> }
> 
> constexpr std::size_t operator"" _KB(unsigned long long int value)
> ```

undocumented

---

*[libs/base/Include/utils.h, line 24 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVBvd9n290unA9GKs:-KXgVBvd9n290unA9GKt:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L24)):*
> ```objc
> }
> 
> constexpr std::size_t operator"" _MB(unsigned long long int value)
> ```

undocumented

---

*[libs/base/Include/base/os.h, line 427 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVXKss6CRbzouRJfY:-KXgVXKss6CRbzouRJfZ:bn4qnu3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L427)):*
> ```objc
> {
>     static_assert(sizeof(Param) < 16, "WTF are you trying to do?");
>     static_assert(StackSize <= UINT16_MAX, "Stack size must be uint16_t number");
> ```

use std::numeric_limits<std::uint16_t>::max() or better yet make stack_size template parameter std::uint_t16 instead of size_t

---

*[libs/base/Include/base/os.h, line 441 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVrFqKi6i6iFN4Qhb:-KXgVrFqKi6i6iFN4Qhc:b-fq1i9g) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L441)):*
> ```objc
>      * @param[in] handler Function that will be executed in new task
>      */
>     Task(const char* name, Param param, HandlerType handler) : _taskName(name), _param(param), _handler(handler), _handle(nullptr)
> ```

In almost all cases constructors should not be defined inline.

---

*[libs/base/Include/base/os.h, line 441 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgWHLhtHu2rdSc0bAt:-KXgWHLhtHu2rdSc0bAu:b-th7lw9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L441)):*
> ```objc
>      * @param[in] handler Function that will be executed in new task
>      */
>     Task(const char* name, Param param, HandlerType handler) : _taskName(name), _param(param), _handler(handler), _handle(nullptr)
> ```

missing std::move on handler & param.

---

*[libs/base/Include/base/os.h, line 449 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgW44aR67Y9e6jUBow:-KXgW44aR67Y9e6jUBox:broht85) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L449)):*
> ```objc
>      * @return Operation status
>      */
>     OSResult Create()
> ```

Prefer defining inline functions outside class definition to make the class interface more concise

---

*[libs/base/Include/base/os.h, line 451 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgZDCCVtBlzJGgX4TN:-KXgZDCCVtBlzJGgX4TO:b5lxt8v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L451)):*
> ```objc
>     OSResult Create()
>     {
>         return System::CreateTask(EntryPoint, this->_taskName, StackSize, static_cast<void*>(this), Priority, &this->_handle);
> ```

As per System::Create task documentation the stack size is specified in words not bytes. This function call will in effect create stack that is two times bigger then intended.

---

*[libs/drivers/leuart/Include/leuart/line_io.h, line 32 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgWqCz1xWfdE0_3NjQ:-KXgWqCz1xWfdE0_3NjR:bwg6ylb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/drivers/leuart/Include/leuart/line_io.h#L32)):*
> ```objc
> 
>     /**
>      * @brief Procedure that print given buffer char-by-char. Useful for non-terminated strings
> ```

Useful for non null terminated strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/base/Include/utils.h, line 14 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgV9BaOeeNhuaD_-MX:-KXkuUl7SFdFOKzTkkBy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 19 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVBMOiJ5n7mA1MgIP:-KXkupLnHMUPiOicOGmh:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/base/Include/utils.h, line 24 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVBvd9n290unA9GKs:-KXkupiu2ya2j5FYhwxF:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/utils.h#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 427 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVXKss6CRbzouRJfY:-KXkvGU1y6BQqwnXgH71:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L427)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use std::numeric_limits<std::uint16_t>::max() or better yet make stack_size template parameter std::uint_t16 instead of size_t
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 441 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgWHLhtHu2rdSc0bAt:-KXkvYf-h4NUZfBdt-V9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L441)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing std::move on handler & param.
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 441 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgVrFqKi6i6iFN4Qhb:-KXkwl7QODUDOU9NvSHZ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L441)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

In almost all cases constructors should not be defined inline.
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 449 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgW44aR67Y9e6jUBow:-KXkwn1zAZsk-2qdZXTy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L449)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Prefer defining inline functions outside class definition to make the class interface more concise
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 451 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgZDCCVtBlzJGgX4TN:-KXkwooWtuR_rqTF5NoK:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/base/Include/base/os.h#L451)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

As per System::Create task documentation the stack size is specified in words not bytes. This function call will in effect create stack that is two times bigger then intended.
</blockquote></details>

Done.

---

*[libs/drivers/leuart/Include/leuart/line_io.h, line 32 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52#-KXgWqCz1xWfdE0_3NjQ:-KXkwvnnNyFfbv6UTcxt:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a0f2abdb35e59c45fc117cb7d9547e999b98177/libs/drivers/leuart/Include/leuart/line_io.h#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Useful for non null terminated strings.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by zaq32** [comment]
Reviewed 1 of 3 files at r3.
Review status: 44 of 46 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Comment by zaq32** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/52)*

**Pull request merged**
