### PR TITLE
Extend telemetry acquisition with antenna telemetry.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/196)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 37 of 37 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/antenna/telemetry.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196#-Ko8QUSK4rsVEAIzLJEa:-Ko8QUSLKKb3gkRwhpWC:boaf4tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/16d479c17a928c381a1924e853ae45d0717f7027/libs/drivers/antenna/telemetry.cpp#L30)):*
> ```cpp
>         ActivationTimes::ActivationTimes()
>         {
>             this->times[0] = this->times[1] = this->times[2] = this->times[3] = 0s;
> ```

You can use `fill` method of `std::array` or call second ctor (like with `ActivationCounts`)

---

*[libs/drivers/antenna/Include/antenna/driver.h, line 145 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196#-Ko8Qv-hFkU3Q_-zVYsf:-Ko8Qv-hFkU3Q_-zVYsg:b-a5odl7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/16d479c17a928c381a1924e853ae45d0717f7027/libs/drivers/antenna/Include/antenna/driver.h#L145)):*
> ```objc
>      * @brief Pointer to the procedure that queries hardware for its current state.
>      * @param[in] driver Current driver instance.
>      * @param[out] telemetry Reference to boject that should be filled with updated antenna telemetry.
> ```

What is `boject`? ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196)*

**Comment by zaq32** [comment]
Review status: 35 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/antenna/telemetry.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196#-Ko8QUSK4rsVEAIzLJEa:-Ko8Z34HrNfTiyh_IhuO:b-7ql1td) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef2191355f18a40b08cb61bc61a65b6e96dbf889/libs/drivers/antenna/telemetry.cpp#L30)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can use `fill` method of `std::array` or call second ctor (like with `ActivationCounts`)
</blockquote></details>

fixed

---

*[libs/drivers/antenna/Include/antenna/driver.h, line 145 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196#-Ko8Qv-hFkU3Q_-zVYsf:-Ko8Z4Z66UN1dAOBlyLz:b-7ql1td) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef2191355f18a40b08cb61bc61a65b6e96dbf889/libs/drivers/antenna/Include/antenna/driver.h#L145)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

What is `boject`? ;)
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/196)*

**Pull request merged**
