### PR TITLE
Refactored camera

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/243)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/drivers/camera/camera.cpp, line 87 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAOtTTUiEq464iWK08:-KrAOtTTUiEq464iWK09:b-q6m0yg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/camera.cpp#L87)):*
> ```cpp
>             CameraCmd::None,                             //
>             i & 0xff,                                    //
>             (uint8_t)(i >> 8),                           //
> ```

Use single 16-bit parameter

---

*[libs/drivers/camera/camera.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAP8MMswpoAqhRfZEU:-KrAP8MMswpoAqhRfZEV:bieqtyz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/camera.cpp#L89)):*
> ```cpp
>             (uint8_t)(i >> 8),                           //
>             buffer.subspan(bufferIndex, dataToTake + 6), //
>             dataToTake + 6);
> ```

You can get length from span size

---

*[libs/drivers/camera/Include/camera/camera.h, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrASzLynfqbwh12nihd:-KrASzLynfqbwh12nihe:bu4lelx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera.h#L42)):*
> ```objc
>              * @return True if initialization succeeded, false otherwise
>              */
>             bool Initialize();
> ```

We need number of sync retries that were neccessary to sync camera

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 198 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATWaK9Bjmb2ufSRTc:-KrATWaK9Bjmb2ufSRTd:bu37zk2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L198)):*
> ```objc
> 
>             /** @brief Initializes the data structure */
>             PictureData() : type(CameraPictureType::Enum::Invalid), dataLength(0)
> ```

Do not define ctors inline

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 207 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATYTTFSQ5KBst80AF:-KrATYTTFSQ5KBst80AG:b5mhor4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L207)):*
> ```objc
>              * @return True if parsed correctly, false if not valid picture data response.
>              */
>             bool Parse(gsl::span<const uint8_t> command)
> ```

Move to .cpp

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATclQjL_cjC8k46nm:-KrATclQjL_cjC8k46nn:b-t2e14s) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L215)):*
> ```objc
> 
>                 dataLength = (((uint32_t)command[3]) | ((uint32_t)command[4] << 8) | ((uint32_t)command[5] << 16));
>                 type = CameraPictureType::GetPictureType(command[2]);
> ```

You can use `Reader` here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by zaq32** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[libs/drivers/camera/command_factory.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAv5B_1mqcnOVICo_X:-KrAv5B_1mqcnOVICo_Y:b-1t5slp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/command_factory.cpp#L6)):*
> ```cpp
> using namespace devices::camera;
> 
> void CommandFactory::BuildAck(Frame cmd, CameraCmd cmdAck, uint8_t packageIdLow, uint8_t packageIdHigh)
> ```

use c++ style casts instead of C style casts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by mandrek44** [comment]
Review status: 20 of 32 files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/drivers/camera/camera.cpp, line 87 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAOtTTUiEq464iWK08:-KrB5TAx_8kWDEaBdIOi:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/camera.cpp#L87)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Use single 16-bit parameter
</blockquote></details>

Done.

---

*[libs/drivers/camera/camera.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAP8MMswpoAqhRfZEU:-KrB5V0zn_2ixBgKnA_C:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/camera.cpp#L89)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can get length from span size
</blockquote></details>

Done.

---

*[libs/drivers/camera/command_factory.cpp, line 6 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrAv5B_1mqcnOVICo_X:-KrB5XWnkjo4JoPHDmn6:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/command_factory.cpp#L6)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use c++ style casts instead of C style casts
</blockquote></details>

Done.

---

*[libs/drivers/camera/Include/camera/camera.h, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrASzLynfqbwh12nihd:-KrB5fsO4dY4OKcCNrQY:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera.h#L42)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

We need number of sync retries that were neccessary to sync camera
</blockquote></details>

Done.

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 198 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATWaK9Bjmb2ufSRTc:-KrB5bP0jfoezBtx0n6V:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L198)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Do not define ctors inline
</blockquote></details>

Done.

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 207 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATYTTFSQ5KBst80AF:-KrB5c3I96pA_dHmGzbC:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L207)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Move to .cpp
</blockquote></details>

Done.

---

*[libs/drivers/camera/Include/camera/camera_types.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrATclQjL_cjC8k46nm:-KrB5dSZc4f7QHBbq0eb:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/9068fab419d2f32feb5c4532a8a51e7ffe3c7d34/libs/drivers/camera/Include/camera/camera_types.h#L215)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can use `Reader` here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by Novakov** [comment]
Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/camera/camera.cpp, line 110 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrC7b2BrJqjk0nmPJiN:-KrC7b2BrJqjk0nmPJiO:b-5qjz0m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/70f2cef2472b592aeffe85a51f49e6cab229a869/libs/drivers/camera/camera.cpp#L110)):*
> ```cpp
> }
> 
> uint8_t Camera::CameraSync(uint8_t& syncCount)
> ```

Why passing reference if you are zero it and return?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by mandrek44** [comment]
Review status: 30 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/camera/camera.cpp, line 110 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243#-KrC7b2BrJqjk0nmPJiN:-KrCT7YHW4B6xZ0XmorH:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/70f2cef2472b592aeffe85a51f49e6cab229a869/libs/drivers/camera/camera.cpp#L110)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Why passing reference if you are zero it and return?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Comment by zaq32** [comment]
Reviewed 16 of 18 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/243)*

**Pull request merged**
