### PR TITLE
Obc persisent state

### PR DESCRIPTION
**Pull request by zaq32**
Add object that contains obc's persisent state & logic related for reading/writing it from dedicated memory.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/112)

### CODE REVIEW

**Comment by zaq32** [comment]
[Prepare infrastructure to handle OBC's persistent state & configuraiton](https://trello.com/c/vC20Ak0W/152-prepare-infrastructure-to-handle-obc-s-persistent-state-configuraiton)

**Comment by Novakov** [comment]
Reviewed 26 of 47 files at r1, 2 of 3 files at r2.
Review status: 26 of 49 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/obc.cpp, line 12 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnB_fpgKnk2Ga0E8B:-KgtnB_fpgKnk2Ga0E8C:b-swjfw7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/src/obc.cpp#L12)):*
> ```cpp
>       Experiments(fs, this->adcs.GetAdcsController(), this->timeProvider), //
>       Communication(this->Fdir, Hardware.I2C.Buses.Bus, fs, Experiments),  //
>       framSpi(Hardware.SPI, Hardware.Pins.Flash1ChipSelect),               //
> ```

FRAM driver is part of hardware and should be put inside `OBCHardware`

---

*[unit_tests/mock/AdcsMocks.hpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnWOs6ZFUJ6LZusE0:-KgtnWOtaL_fiMmTnlLq:b-gwzdih) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L11)):*
> ```cpp
> struct AdcsCoordinatorMock : adcs::IAdcsCoordinator
> {
>     ~AdcsCoordinatorMock();
> ```

Add default ctor

---

*[unit_tests/mock/AdcsMocks.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnYxyWzCsvkRKhlS8:-KgtnYxyWzCsvkRKhlS9:b-gwzdih) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L27)):*
> ```cpp
> {
>     ~DetumblingMock();
> ```

Add default ctor

---

*[unit_tests/mock/AdcsMocks.hpp, line 35 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnZR6nBQBWMm3y-FF:-KgtnZR6nBQBWMm3y-FG:b-gwzdih) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L35)):*
> ```cpp
> struct SunPointingMock : adcs::ISunPointingSupport
> {
>     ~SunPointingMock();
> ```

Add default ctor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Comment by zaq32** [comment]
Review status: 19 of 51 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/obc.cpp, line 12 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnB_fpgKnk2Ga0E8B:-Kgu5vP0MFJ7GIv-bx3r:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/src/obc.cpp#L12)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

FRAM driver is part of hardware and should be put inside `OBCHardware`
</blockquote></details>

Done.

---

*[unit_tests/mock/AdcsMocks.hpp, line 11 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnWOs6ZFUJ6LZusE0:-Kgu5rxLUqwqyNARlDBG:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L11)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add default ctor
</blockquote></details>

Done.

---

*[unit_tests/mock/AdcsMocks.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnYxyWzCsvkRKhlS8:-Kgu5tzF5pDEUhInkTjD:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L27)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add default ctor
</blockquote></details>

Done.

---

*[unit_tests/mock/AdcsMocks.hpp, line 35 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgtnZR6nBQBWMm3y-FF:-Kgu5uOM3U6ioXDlw5wM:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/54e695214388e2865f1427b6806f0caec18318ea/unit_tests/mock/AdcsMocks.hpp#L35)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add default ctor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Comment by Novakov** [comment]
Reviewed 18 of 49 files at r1, 1 of 3 files at r2, 15 of 16 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/mission/state/PersistentStateSave.cpp, line 45 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgyfiyNTedBQl3rZ3MT:-KgyfiyNTedBQl3rZ3MU:bi40w1x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/mission/state/PersistentStateSave.cpp#L45)):*
> ```cpp
>         obc::WritePersistentState(state.PersistentState, this->baseAddress, this->storageAccess);
>     }
> }
> ```

I don't think that it's needed to manage dirty flag of persistant state. Dumping it in each mission loop iteration won't slow it down (it should took about 40ms for whole 32KB)  and FRAM memory can't be damaged by too many writes (well, it can after 85 years of constant writes with 20MHz). in addition more frequent writes will prevent errors (maybe we will be able to skip scrubbing of FRAM)

---

*[libs/state/Include/state/PersistentState.hpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-Kgyi4zyhoYOo--dMDFH:-Kgyi4zyhoYOo--dMDFI:b-1btaap) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/PersistentState.hpp#L26)):*
> ```cpp
>      * @endcode
>      */
>     template <typename... Parts> class PersistentState
> ```

It would be wise to add some static_asserts:
1) that types are unique (git merge may went wrong and one line will get duplicated)
2) total size is smaller that maximum FRAM size (32KB)

---

*[libs/state/Include/state/TimeState.hpp, line 107 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-Kgyj_k4aC2mvaV9yNMG:-Kgyj_k4aC2mvaV9yNMH:bbq0ryh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/TimeState.hpp#L107)):*
> ```cpp
>     inline constexpr std::uint32_t TimeState::Size()
>     {
>         return 2 * sizeof(decltype(std::declval<std::chrono::milliseconds>().count()));
> ```

`count()` is returning value of type `rep` (typedef inside duration), so this can be written as `sizeof(decltype(lastMissionType)::rep) + sizeof(decltype(lastExternalTime)::rep)`

---

*[libs/state/Include/state/antenna/AntennaState.hpp, line 15 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgyibcWLmRsTCcEw7Ne:-KgyibcX1rxVoJaK22ND:b-896nc1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/antenna/AntennaState.hpp#L15)):*
> ```cpp
>     {
>       public:
>         AntennaState();
> ```

Docs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Comment by zaq32** [comment]
Review status: 43 of 52 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/mission/state/PersistentStateSave.cpp, line 45 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgyfiyNTedBQl3rZ3MT:-KhD4QeLhFCvWX6Up0av:b-acuaqk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/mission/state/PersistentStateSave.cpp#L45)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't think that it's needed to manage dirty flag of persistant state. Dumping it in each mission loop iteration won't slow it down (it should took about 40ms for whole 32KB)  and FRAM memory can't be damaged by too many writes (well, it can after 85 years of constant writes with 20MHz). in addition more frequent writes will prevent errors (maybe we will be able to skip scrubbing of FRAM)
</blockquote></details>

I have extended the persistent state definition with customizable policy for state tracking. 

---

*[libs/state/Include/state/PersistentState.hpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-Kgyi4zyhoYOo--dMDFH:-KhD4VzwSveXC6R3uchN:bac2xo4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/PersistentState.hpp#L26)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be wise to add some static_asserts:
1) that types are unique (git merge may went wrong and one line will get duplicated)
2) total size is smaller that maximum FRAM size (32KB)
</blockquote></details>

1- > Done.
2-> Current solution requires enough stack space to serialize entire persistent state. We will hit problems long before persistent state size reaches even 16KB

---

*[libs/state/Include/state/TimeState.hpp, line 107 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-Kgyj_k4aC2mvaV9yNMG:-KhD4hXmFBO2cSIN1GVI:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/TimeState.hpp#L107)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

`count()` is returning value of type `rep` (typedef inside duration), so this can be written as `sizeof(decltype(lastMissionType)::rep) + sizeof(decltype(lastExternalTime)::rep)`
</blockquote></details>

Done

---

*[libs/state/Include/state/antenna/AntennaState.hpp, line 15 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgyibcWLmRsTCcEw7Ne:-KhD4iZL1Wysrpf4evuc:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/antenna/AntennaState.hpp#L15)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Docs?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Comment by Novakov** [comment]
Reviewed 1 of 49 files at r1, 1 of 1 files at r4, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/mission/state/PersistentStateSave.cpp, line 45 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-KgyfiyNTedBQl3rZ3MT:-KhIKyhu1MxKVjIhjXvP:biud8n1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/mission/state/PersistentStateSave.cpp#L45)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I have extended the persistent state definition with customizable policy for state tracking. 
</blockquote></details>

ok, we can go with that solution for now but I don't think it will be necessary

---

*[libs/state/Include/state/PersistentState.hpp, line 26 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112#-Kgyi4zyhoYOo--dMDFH:-KhIJGBx-AaPWfs9NTEI:blnp494) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/089338d142376abc098343954de1aabde493a316/libs/state/Include/state/PersistentState.hpp#L26)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

1- > Done.
2-> Current solution requires enough stack space to serialize entire persistent state. We will hit problems long before persistent state size reaches even 16KB
</blockquote></details>

True but I would add some sanity-check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Comment by Novakov** [comment]
Reviewed 7 of 10 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/112)*

**Pull request merged**
