### PR TITLE
[eps][telemetry] Eps telemetry update.

### PR DESCRIPTION
**Pull request by zaq32**
Temperatures in battery pack in controller A telemetry are now 13 bit.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/269)

### CODE REVIEW

**Comment by zaq32** [comment]
[[EPS] Update telemetry](https://trello.com/c/WJ8FSgGv/250-eps-update-telemetry)

**Comment by Novakov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269#-KrqTMTQ_kXoDQvX43Oh:-KrqTMTQ_kXoDQvX43Oi:bb0fxie) (no related file):*
Waiting for @begreeen to verify

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269)*

**Comment by ggajoch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269#-KrqTMTQ_kXoDQvX43Oh:-KsAUmEBFLK2tlE_ZZlT:b-sxhgex) (no related file):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Waiting for @begreeen to verify
</blockquote></details>

LGTM. Final verification will be performed with connected sensors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269)*

**Comment by ggajoch** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269#-:-KsAV_xFdFcj7ff28yXY:bnfp4nl)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/269)*

**Pull request merged**
