### PR TITLE
Watchdog update

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/177)

### CODE REVIEW

**Comment by Novakov** [comment]
[Watchdogs](https://trello.com/c/pF0DROFw/181-watchdogs)

**Comment by zaq32** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[boot/main.cpp, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAHJblKE33jg0cr-Bm:-KmAHJblKE33jg0cr-Bn:bw0mp2u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/boot/main.cpp#L7)):*
> ```cpp
>   * @version 2.0
>   ******************************************************************************/
> #include <em_rmu.h>
> ```

is this actually needed?

---

*[libs/drivers/watchdog/Include/watchdog/external.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAJKs0gqKmhCJKzOFQ:-KmAJKs0gqKmhCJKzOFR:b-65r8za) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/libs/drivers/watchdog/Include/watchdog/external.hpp#L9)):*
> ```cpp
>          * @ingroup watchdog
>          */
>         class ExternalWatchdog
> ```

how about making this class a template with Pin being its parameter?

---

*[libs/mission/watchdog/Include/mission/watchdog.hpp, line 44 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAJVa4Pw6-8DiSU_0e:-KmAJVa5OBZpv50_7lVy:b7e1h1u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/libs/mission/watchdog/Include/mission/watchdog.hpp#L44)):*
> ```cpp
> 
>         /** @brief EPS driver */
>         devices::eps::EPSDriver& _eps;
> ```

how about making this task capable of kicking anything that implements specific interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Comment by Novakov** [comment]
Review status: 25 of 34 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/mission/watchdog/Include/mission/watchdog.hpp, line 44 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAJVa4Pw6-8DiSU_0e:-KmBkTG0nVr0YPgHkEot:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/libs/mission/watchdog/Include/mission/watchdog.hpp#L44)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

how about making this task capable of kicking anything that implements specific interface?
</blockquote></details>

Done.

---

*[boot/main.cpp, line 7 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAHJblKE33jg0cr-Bm:-KmBdLyek-CVylrzJBxl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/boot/main.cpp#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

is this actually needed?
</blockquote></details>

Done.

---

*[libs/drivers/watchdog/Include/watchdog/external.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177#-KmAJKs0gqKmhCJKzOFQ:-KmBhq7lsh88OTrnkN6b:b-elvpx6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/81f043c1d820487754511894403af7ea3f94fa71/libs/drivers/watchdog/Include/watchdog/external.hpp#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

how about making this class a template with Pin being its parameter?
</blockquote></details>

Nice idea :) Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Comment by zaq32** [comment]
Reviewed 11 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Comment by Novakov** [comment]
[Driver do watchdoga zewnętrznego](https://trello.com/c/yOvdKf14/116-driver-do-watchdoga-zewn%C4%99trznego)

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/177)*

**Pull request merged**
