### PR TITLE
Control antenna LCL during antenna deployment process

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/220)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/mission/antenna/antenna.cpp, line 470 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4GiA-2b29jaxYwjp:-Kpn4GiA-2b29jaxYwjq:b5p6hsd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/antenna.cpp#L470)):*
> ```cpp
>             else
>             {
>                 stateDescriptor.Retry(StepRetryLimit, GetTimeout(step));
> ```

This is a bit tricky. in case of obc being unable to power on the antenna controller half of the deployment procedure will not work at all and it will only generate a lot of false errors and slow down the process. 

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4smsSifnH0VChX3Q:-Kpn4smsSifnH0VChX3R:b-97v8h9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/Include/mission/antenna_state.h#L9)):*
> ```objc
> #include "base/os.h"
> #include "mission/base.hpp"
> #include "power/power.h"
> ```

full IPowerControl interface definition is not needed here

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 21 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4zx1sI9NfebatGdA:-Kpn4zx1sI9NfebatGdB:b-3c1ibv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/Include/mission/antenna_task.hpp#L21)):*
> ```cpp
>          * @ingroup mission_atenna
>          */
>         struct IAntennaTelemetryProvider
> ```

I'd move the definition of this interface to the antenna driver module event if implementation is not done there.

---

*[src/obc.cpp, line 157 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4-qerW3P9cmjORCA:-Kpn4-qerW3P9cmjORCB:b-l7vggf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/src/obc.cpp#L157)):*
> ```cpp
>     }
> 
>     static_cast<mission::antenna::AntennaTask&>(Mission).Initialize();
> ```

Reduntant call. All mission elements are initialized during mission initialization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220)*

**Comment by Novakov** [comment]
Review status: 12 of 32 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/mission/antenna/antenna.cpp, line 470 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4GiA-2b29jaxYwjp:-KpuugWnpQ_6xycu5QiJ:b-f7f6di) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/antenna.cpp#L470)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This is a bit tricky. in case of obc being unable to power on the antenna controller half of the deployment procedure will not work at all and it will only generate a lot of false errors and slow down the process. 
</blockquote></details>

Updates as discussed - check LCL during deployment

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4smsSifnH0VChX3Q:-KppSeDijMYdzNllEwI3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/Include/mission/antenna_state.h#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

full IPowerControl interface definition is not needed here
</blockquote></details>

Done.

---

*[libs/mission/antenna/Include/mission/antenna_task.hpp, line 21 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4zx1sI9NfebatGdA:-KpuG82u_66Hpuq13Iwf:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/libs/mission/antenna/Include/mission/antenna_task.hpp#L21)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd move the definition of this interface to the antenna driver module event if implementation is not done there.
</blockquote></details>

Done.

---

*[src/obc.cpp, line 157 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220#-Kpn4-qerW3P9cmjORCA:-KpuQTK6d65yHD-OWw1c:b-6uals8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/99d1290563e172d6af0c98820a303f1d236a1a20/src/obc.cpp#L157)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Reduntant call. All mission elements are initialized during mission initialization.
</blockquote></details>

They are now :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220)*

**Comment by zaq32** [comment]
Reviewed 21 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/220)*

**Pull request merged**
