### PR TITLE
Update telemetry acquisition mechanism to support new requirements

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/164)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 28 of 28 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/base/BitWriter.cpp, line 86 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/164#-KlXHV9toWmlExhVkKT6:-KlXHV9uaP9vHsGGDuhR:bb7phvt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/87dbe50271bd1c1db624fe3622a2b208bb9bae43/libs/base/BitWriter.cpp#L86)):*
> ```cpp
> 
>     const std::uint32_t bits = length + this->_bitPosition;
>     const std::uint32_t bytes = BitsToByes(bits);
> ```

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/164)*

**Comment by zaq32** [comment]
Review status: 28 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/BitWriter.cpp, line 86 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/164#-KlXHV9toWmlExhVkKT6:-KlXKxr_w7C6mfrcAzG_:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/87dbe50271bd1c1db624fe3622a2b208bb9bae43/libs/base/BitWriter.cpp#L86)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/164)*

**Comment by Novakov** [comment]
Reviewed 1 of 28 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/164)*

**Pull request merged**
