### PR TITLE
BSP from ESL

### PR DESCRIPTION
**Pull request by Novakov**
Import of BSP + bootloader +sample application for CubeComputer from ESL.

Changes required to build & run tests on EM successfully.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/139)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 3 of 95 files at r1, 17 of 77 files at r5.
Review status: 20 of 138 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139)*

**Comment by zaq32** [comment]
Reviewed 60 of 95 files at r1, 1 of 3 files at r2, 5 of 19 files at r3, 53 of 77 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/drivers/uart/uart.cpp, line 15 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTkTA4yHHx7ODgU-aY:-KjTkTA4yHHx7ODgU-aZ:bgz775q) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L15)):*
> ```cpp
> #define DEBUG_UART
> 
> __attribute__((optimize("O3"))) void UART1_RX_IRQHandler()
> ```

we do not put interrupt handlers in driver libraries. put it in main and redirect from there to the driver object.

---

*[libs/drivers/uart/uart.cpp, line 19 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTkHQgSPL3Qf7dgTeG:-KjTkHQgSPL3Qf7dgTeH:b-y9c023) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L19)):*
> ```cpp
> #ifdef DEBUG_UART
>     GPIO->P[gpioPortC].DOUTCLR = 1 << 11;
> //    GPIO_PinOutClear(gpioPortC, 11);
> ```

do not leave commented out code. either remove it or use #if 0

---

*[libs/drivers/uart/uart.cpp, line 115 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTl_D-25JgPUsIKxEH:-KjTl_D-25JgPUsIKxEI:b-yqccv2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L115)):*
> ```cpp
>             This->_event.Clear(Event::LineEndReceived);
> 
>             GPIO_PinOutClear(gpioPortC, 12);
> ```

I'd rather have pins defined in io_map then hardcoded in uart driver

---

*[libs/drivers/uart/Include/uart/uart.h, line 14 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTlpoMqZ-FTU0dwoM0:-KjTlpoMqZ-FTU0dwoM1:bu3gior) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/Include/uart/uart.h#L14)):*
> ```objc
>     namespace uart
>     {
>         class UART
> ```

missing documentation

---

*[platforms/DevBoard/Include/io_map.h, line 21 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTnGaDpVmLhwkNC90U:-KjTnGaDpVmLhwkNC90V:bhlgen4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/platforms/DevBoard/Include/io_map.h#L21)):*
> ```objc
>     using SlaveSelectFlash3 = PinLocation<gpioPortB, 12>;
> 
>     using SlaveSelectFram1 = PinLocation<gpioPortA, 11>;
> ```

This pin is not available on devboard

---

*[src/commands/ping.cpp, line 7 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTp5eg7jzyeR-iiZ9t:-KjTp5eg7jzyeR-iiZ9u:b2nzp9c) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/src/commands/ping.cpp#L7)):*
> #include <em_system.h>
> #include <core_cm3.h>
duplicated below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/drivers/uart/uart.cpp, line 15 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTkTA4yHHx7ODgU-aY:-KjTrzaueO6ZZO7zrZGT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

we do not put interrupt handlers in driver libraries. put it in main and redirect from there to the driver object.
</blockquote></details>

Done.

---

*[libs/drivers/uart/uart.cpp, line 19 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTkHQgSPL3Qf7dgTeG:-KjTr_6aHGWRPvW03Hv-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L19)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not leave commented out code. either remove it or use #if 0
</blockquote></details>

Done.

---

*[libs/drivers/uart/uart.cpp, line 115 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTl_D-25JgPUsIKxEH:-KjTqxzbQCwmQ7ya0t6o:b-mw4lzx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/uart.cpp#L115)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd rather have pins defined in io_map then hardcoded in uart driver
</blockquote></details>

When I will be satisfied with stability of the UART driver I will remove them

---

*[libs/drivers/uart/Include/uart/uart.h, line 14 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTlpoMqZ-FTU0dwoM0:-KjTyUSvG5qtPrTTVPIC:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/libs/drivers/uart/Include/uart/uart.h#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing documentation
</blockquote></details>

Done.

---

*[platforms/DevBoard/Include/io_map.h, line 21 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTnGaDpVmLhwkNC90U:-KjTrYzjJUZisKp0JbMJ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/platforms/DevBoard/Include/io_map.h#L21)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This pin is not available on devboard
</blockquote></details>

Done.

---

*[src/commands/ping.cpp, line 7 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139#-KjTp5eg7jzyeR-iiZ9t:-KjTqf5eoTvgHn-kz8J8:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/53c529169af972d59f380d7feab104feec31264b/src/commands/ping.cpp#L7)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> #include <em_system.h>
> #include <core_cm3.h>
duplicated below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139)*

**Comment by zaq32** [comment]
Reviewed 10 of 10 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/139)*

**Pull request merged**
