### PR TITLE
Added RadFET experiment

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/248)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/experiments/radfet/radfet.cpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRFoqBBkKxAq3oZGGl:-KrRFoqBBkKxAq3oZGGm:bdicaxa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L41)):*
> ```cpp
>         }
> 
>         experiments::StartResult RadFETExperiment::Start()
> ```

this function needs better error handling. Ensure that nothing is left open/enabled/initialized in case of failures. 

---

*[libs/experiments/radfet/radfet.cpp, line 122 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRG81bXeOlcuxyDq97:-KrRG81bXeOlcuxyDq98:b-v6nr28) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L122)):*
> ```cpp
>         }
> 
>         void RadFETExperiment::Stop(experiments::IterationResult /* lastResult */)
> ```

in case of this function early escape may not be the best approach.  It would be better to proceed to the end regardless of errors

---

*[libs/experiments/radfet/radfet.cpp, line 198 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRGZh86YSaBnOv5qCn:-KrRGZh86YSaBnOv5qCo:b-229eru) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L198)):*
> ```cpp
>         }
> 
>         bool RadFETExperiment::SaveEndTelemetry(
> ```

this function differs from the above one with only with one value. Merge those together

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248)*

**Comment by zaq32** [comment]
[[Experiment] RadFET](https://trello.com/c/pFhSAGrl/212-experiment-radfet)

**Comment by kfazi** [comment]
Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/radfet/radfet.cpp, line 41 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRFoqBBkKxAq3oZGGl:-KrRp0gvmEkd4HC4aHnZ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L41)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this function needs better error handling. Ensure that nothing is left open/enabled/initialized in case of failures. 
</blockquote></details>

Done.

---

*[libs/experiments/radfet/radfet.cpp, line 122 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRG81bXeOlcuxyDq97:-KrRp1ngIJ-YYS8lgirC:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L122)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

in case of this function early escape may not be the best approach.  It would be better to proceed to the end regardless of errors
</blockquote></details>

Done.

---

*[libs/experiments/radfet/radfet.cpp, line 198 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248#-KrRGZh86YSaBnOv5qCn:-KrRp2bg5axu3VcEusB8:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f1a598af835795614ce262600c40247af4a699fb/libs/experiments/radfet/radfet.cpp#L198)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this function differs from the above one with only with one value. Merge those together
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/248)*

**Pull request merged**
