### PR TITLE
Bootloader cleanup

### PR DESCRIPTION
**Pull request by Novakov**
Major clean-up to bootloader:

1. Compile as C++
1. Simplify command parsing

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/143)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 57 of 63 files at r1.
Review status: 39 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143)*

**Comment by zaq32** [comment]
Reviewed 6 of 63 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[boot/commands/booting.cpp, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcC429U0L9Ow6y6u6d:-KjcC42A3HfC_q4mI1q1:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/booting.cpp#L11)):*
> ```cpp
> {
>     char debugStr[60] = {0};
>     auto debugLen = sprintf((char*)debugStr, "\n\nBooting to upper half ");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/booting.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcC6W5Q0Rh6UumxjLk:-KjcC6W5Q0Rh6UumxjLl:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/booting.cpp#L24)):*
> ```cpp
>     if (index > BOOT_TABLE_SIZE)
>     {
>         auto debugLen = sprintf((char*)debugStr, "\n\nError: Boot index out of bounds!");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/settings.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcCDpXYzjnZIXFhtvp:-KjcCDpXYzjnZIXFhtvq:b85if3o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/settings.cpp#L14)):*
> ```cpp
>     auto index = USART_Rx(BSP_UART_DEBUG);
> 
>     debugLen = sprintf((char*)debugStr, "%d", index);
> ```

format entire string here

---

*[boot/commands/upload.cpp, line 21 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajYFlkJczX6AxvIym:-KjajYFlkJczX6AxvIyn:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L21)):*
> ```cpp
>     if (index == 0x00)
>     {
>         debugLen = sprintf((char*)debugStr, "\nError: Cant override safe mode program!");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/upload.cpp, line 27 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-Kjajmj75uY_-W1bWnWy:-Kjajmj75uY_-W1bWnWz:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L27)):*
> ```cpp
>     if (index > BOOT_TABLE_SIZE)
>     {
>         debugLen = sprintf((char*)debugStr, "\nError: Boot index out of bounds!");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/upload.cpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajoAPAy33jiUi6Rma:-KjajoAPAy33jiUi6Rmb:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L32)):*
> ```cpp
>     }
> 
>     debugLen = sprintf((char*)debugStr, "\nUpload Binary: ");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/upload.cpp, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajqqubN_8xHp9b-fK:-KjajqqubN_8xHp9b-fL:b60eqfa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L51)):*
> ```cpp
>     BOOT_setValid(index);
> 
>     debugLen = sprintf((char*)debugStr, "\nBoot Description: ");
> ```

Unnecessary. constant string literals like this one can be written directly to the output.

---

*[boot/commands/upload.cpp, line 70 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcBY9gDzNgNZ7Sykxq:-KjcBY9gDzNgNZ7Sykxr:b-43qu9v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L70)):*
> ```cpp
> 
>     // update entry description
>     BOOT_programDescription(index, desc);
> ```

is the desc supposed to be null terminated or fixed size?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143)*

**Comment by Novakov** [comment]
Review status: 40 of 44 files reviewed at latest revision, 8 unresolved discussions.

---

*[boot/commands/booting.cpp, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcC429U0L9Ow6y6u6d:-KjcoO9H-3fK6wuw9OBO:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/booting.cpp#L11)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/booting.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcC6W5Q0Rh6UumxjLk:-KjcoOsAR1Cbu2a4YBkq:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/booting.cpp#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/settings.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcCDpXYzjnZIXFhtvp:-KjcolJjexqkKDAPbnWb:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/settings.cpp#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

format entire string here
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 21 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajYFlkJczX6AxvIym:-KjcpGYzYHXOZMuE-rar:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L21)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 27 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-Kjajmj75uY_-W1bWnWy:-KjcpIhlEao1NeCcLMCB:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L27)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajoAPAy33jiUi6Rma:-KjcpJGxhbwuMZ0L28Pa:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjajqqubN_8xHp9b-fK:-KjcpJtcKJH8piY-oTq3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L51)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unnecessary. constant string literals like this one can be written directly to the output.
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 70 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143#-KjcBY9gDzNgNZ7Sykxq:-KjcpLGUeXF8t4PtaanT:b-6m0yxk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8ac7c7cbd51b48f0e752f927a49418f963d6d382/boot/commands/upload.cpp#L70)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

is the desc supposed to be null terminated or fixed size?
</blockquote></details>

I retained the original structure - description is loaded up to size or new line (whichever is receives first). When displaying it is displayed up to null terminator, new line character or maximum size

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/143)*

**Pull request merged**
