### PR TITLE
Telecommand handling

### PR DESCRIPTION
**Pull request by Novakov**
Simple telecommand handling
* no encoding, no encryption
* just ping command

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/50)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 26 of 36 files at r1.
Review status: 26 of 36 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/system.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEpmZ0M3kLjiTwcs0w:-KXEpmZ0M3kLjiTwcs0x:bh2orxj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L4)):*
> ```objc
> #define SRC_SYSTEM_H_
> 
> #include <stddef.h>
> ```

use cstddef

---

*[libs/base/Include/system.h, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEq4ZuYOz_R-s7QY8q:-KXEq4ZuYOz_R-s7QY8r:b-ouldcq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L49)):*
> ```objc
> size_t RoundToMultiply(size_t value, size_t base);
> 
> template <typename Enum> typename std::underlying_type_t<Enum> num(Enum v)
> ```

incorrect return type it should be 
```
std::underlyingtype<Enum>::type
```

---

*[libs/base/Include/system.h, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqEAEIrGr3NzLuftP:-KXEqEAEIrGr3NzLuftQ:byr4ffv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L51)):*
> ```objc
> template <typename Enum> typename std::underlying_type_t<Enum> num(Enum v)
> {
>     return static_cast<typename std::underlying_type_t<Enum>>(v);
> ```

see above

---

*[libs/drivers/adxrs453/adxrs453.cpp, line 2 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqJBeIIHsjKB7tc09:-KXEqJBeIIHsjKB7tc0A:bh2ovv5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/drivers/adxrs453/adxrs453.cpp#L2)):*
> ```cpp
> #include "adxrs453.h"
> #include <stdint.h>
> ```

use cstdint

---

*[libs/drivers/comm/Include/comm/comm.h, line 151 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqcYEQ5dwPZ9mp403:-KXEqcYEQ5dwPZ9mp404:bh3jand) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/drivers/comm/Include/comm/comm.h#L151)):*
> ```objc
>              *
>              */
>             virtual void HandleFrame(CommFrame& frame) = 0;
> ```

How are you going to send responses without access to ComObject?

---

*[platforms/DevBoard/platform.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqzKAR1FADe9Sci25:-KXEqzKBQK4sxCnELukN:b-8p8kb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/platforms/DevBoard/platform.cpp#L5)):*
> ```cpp
> #include "system.h"
> 
> alignas(4) const uint8_t EncryptionKey[] = {0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00};
> ```

I thought this was supposed to be confidential

---

*[platforms/DevBoard/Include/platform.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXErC8TIpRIe4Rlrnk1:-KXErC8TIpRIe4Rlrnk2:b-is5f44) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/platforms/DevBoard/Include/platform.h#L4)):*
> ```objc
> #define PLATFORMS_DEVBOARD_INCLUDE_PLATFORM_H_
> 
> #include <stdint.h>
> ```

use cstdint header

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by Novakov** [comment]
Review status: 16 of 33 files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/base/Include/system.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEpmZ0M3kLjiTwcs0w:-KXH2B3Aw3w_MR3SVSrg:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use cstddef
</details>
Done.

---

*[libs/base/Include/system.h, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEq4ZuYOz_R-s7QY8q:-KXEz1hnN1wB_fUcrnV1:b-l023sd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L49)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> incorrect return type it should be 
> ```
> std::underlyingtype<Enum>::type
> ```
</details>
Since C++14 it is possible to use shorter version: http://en.cppreference.com/w/cpp/types/underlying_type

---

*[libs/base/Include/system.h, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqEAEIrGr3NzLuftP:-KXH2WHZYvyyx5NjjN4o:byr4ffv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/base/Include/system.h#L51)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> see above
</details>
see above

---

*[libs/drivers/adxrs453/adxrs453.cpp, line 2 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqJBeIIHsjKB7tc09:-KXH2dKq2o29fdueimni:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/drivers/adxrs453/adxrs453.cpp#L2)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use cstdint
</details>
Done.

---

*[libs/drivers/comm/Include/comm/comm.h, line 151 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqcYEQ5dwPZ9mp403:-KXHXhPzaYvtgaLqlOT1:b-jquhb0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/libs/drivers/comm/Include/comm/comm.h#L151)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> How are you going to send responses without access to ComObject?
</details>
I've added dedicated interface used to send frames back. Changing to more elaborate mechanism will be added after implementing downlink protocol

---

*[platforms/DevBoard/platform.cpp, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXEqzKAR1FADe9Sci25:-KXH2fxuTHe444Qhz6n4:b5enx7n) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/platforms/DevBoard/platform.cpp#L5)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> I thought this was supposed to be confidential
</details>
Actually it is not needed (yet). Removed whole file

---

*[platforms/DevBoard/Include/platform.h, line 4 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXErC8TIpRIe4Rlrnk1:-KXH3J_ePL4zRkTna8Ok:b-cmhs2v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0c3fae101a1adbbda26d2c272582a790fd6e9b8f/platforms/DevBoard/Include/platform.h#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use cstdint header
</details>
Removed file as not needed yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by zaq32** [comment]
Reviewed 5 of 36 files at r1, 14 of 15 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[libs/base/utils.cpp, line 3 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMHY5kbInJiGKjveir:-KXMHY5kbInJiGKjveis:b-o8yfmg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/base/utils.cpp#L3)):*
> ```cpp
> #include <stddef.h>
> 
> size_t RoundToMultiply(size_t value, size_t base)
> ```

this function is not used anywhere.

---

*[libs/drivers/adxrs453/adxrs453.cpp, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMA4r26saVkao-z9_n:-KXMA4r26saVkao-z9_o:bs75pfy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/drivers/adxrs453/adxrs453.cpp#L10)):*
> ```cpp
> #include "system.h"
> 
> using namespace std;
> ```

in general using namespace is ok but I would treat it as last resort. Prefer using 'using directives' i.e. 
```
using std::array
```

---

*[libs/drivers/comm/Include/comm/comm.h, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMEYKkPU7sWSEjIEH3:-KXMEYKkPU7sWSEjIEH4:b608273) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/drivers/comm/Include/comm/comm.h#L68)):*
> ```objc
> 
>             /** @brief Frame content. */
>             std::uint8_t Contents[COMM_MAX_FRAME_CONTENTS_SIZE];
> ```

since now we are using c++ it wold there is no need to use this fixed size buffer and copy the frame contents into it every time we get a frame. 
It may be simpler to just use gsl::span instead.

---

*[libs/telecommand_handling/telecommand_handling.cpp, line 3 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMF8pNqpLplxxKbcem:-KXMF8pNqpLplxxKbcen:b-jmepyd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/telecommand_handling.cpp#L3)):*
> ```cpp
> #include <stdalign.h>
> #include <stdint.h>
> #include <em_aes.h>
> ```

unused

---

*[libs/telecommand_handling/telecommand_handling.cpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFCUgbnYNbe33py_4:-KXMFCUgbnYNbe33py_5:buybzna) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/telecommand_handling.cpp#L27)):*
> ```cpp
> void IncomingTelecommandHandler::HandleFrame(ITransmitFrame& transmitter, CommFrame& frame)
> {
>     uint8_t decryptedFrame[DecryptionBufferSize] = {0};
> ```

use std::array instead

---

*[libs/telecommand_handling/uplink.cpp, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMDpUj6dKNWh17qbMF:-KXMDpUj6dKNWh17qbMG:b-620goc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/uplink.cpp#L10)):*
> ```cpp
> DecryptStatus UplinkProtocol::Decrypt(gsl::span<const uint8_t> frame, gsl::span<uint8_t> decrypted, size_t& decryptedDataLength)
> {
>     auto lastCopied = std::copy(frame.cbegin(), frame.cend(), decrypted.begin());
> ```

missing include <algorithm>

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 55 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFTOYk2mHdELv-dRG:-KXMFTOYk2mHdELv-dRH:btnxl53) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L55)):*
> ```objc
>              * @return Operation status
>              */
>             virtual DecryptStatus Decrypt(
> ```

Use more complex return type instead of out parameters. Out parameters may be accidentally left uninitialized return value can't.

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 71 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMB2G2_dVhBWS9fW-X:-KXMB2G2_dVhBWS9fW-Y:b-soksek) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L71)):*
> ```objc
>              * @return Operation status
>              */
>             virtual DecodeFrameStatus Decode(
> ```

Use more complex return type instead of out parameters

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMBXYA2KonShUlPv8b:-KXMBXYA2KonShUlPv8c:b-2irpvv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L97)):*
> ```objc
>          * Incoming frame handler that is capable of decoding them and dispatching telecommands
>          */
>         class IncomingTelecommandHandler : public devices::comm::IHandleFrame
> ```

Consider making this class a template that takes as parameter frame decryptor

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMD7M-_Xuf2uCLfaWR:-KXMD7M-_Xuf2uCLfaWS:b-mz5km6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L97)):*
> ```objc
>          * Incoming frame handler that is capable of decoding them and dispatching telecommands
>          */
>         class IncomingTelecommandHandler : public devices::comm::IHandleFrame
> ```

if you are going to use interfaces mark their implementation as final to make it easier for the optimizer to devirtualize the functions during the optimization

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMBJqr8jDBLB3p_h_v:-KXMBJqr8jDBLB3p_h_w:b-vrpts0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L118)):*
> ```objc
>           private:
>             /** @brief Frame decryption implementation */
>             IDecryptFrame& _decryptFrame;
> ```

In general fields should be the last thing defined in class as they are least interesting from class user point of view

---

*[src/communication.cpp, line 1 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFj1Ig63Vn5UwX4hz:-KXMFj1Ig63Vn5UwX4i-:b-66f65h) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.cpp#L1)):*
> ```cpp
> #include "communication.h"
> ```

The command handlers should be tested as well therefore they cannot be defined in main project.

---

*[src/communication.h, line 5 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMGF_93C4cF6_gThwo:-KXMGF_93C4cF6_gThwp:bphh6ip) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.h#L5)):*
> ```objc
> #include <gsl/span>
> #include "comm/comm.h"
> #include "i2c/i2c.h"
> ```

the only reason this header is needed is to declare the I2CBus type. We should start preparing headers with just forward declarations.

---

*[src/communication.h, line 6 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMG_MRbUe9_L9IQVGF:-KXMG_MRbUe9_L9IQVGG:bp9qecr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.h#L6)):*
> ```objc
> #include "comm/comm.h"
> #include "i2c/i2c.h"
> #include "system.h"
> ```

this header seems to be unused

---

*[unit_tests/TeleCommandHandling/TeleCommandHandlingTest.cpp, line 76 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMGrUo_-pZkdYl4UFP:-KXMGrUo_-pZkdYl4UFQ:byadkoy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/unit_tests/TeleCommandHandling/TeleCommandHandlingTest.cpp#L76)):*
> ```cpp
> 
>     EXPECT_CALL(this->deps, Decrypt(_, _, _))
>         .WillOnce(Invoke([](gsl::span<const uint8_t> frame, gsl::span<uint8_t> decrypted, size_t& decryptedDataLength) {
> ```

This would be much more clear if the Decrypt method used only return value to report the results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by Novakov** [comment]
Review status: 10 of 32 files reviewed at latest revision, 15 unresolved discussions.

---

*[libs/drivers/adxrs453/adxrs453.cpp, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMA4r26saVkao-z9_n:-KXNaSScOeqw4zgyli6C:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/drivers/adxrs453/adxrs453.cpp#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> in general using namespace is ok but I would treat it as last resort. Prefer using 'using directives' i.e. 
> ```
> using std::array
> ```
</details>
Done.

---

*[libs/drivers/comm/Include/comm/comm.h, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMEYKkPU7sWSEjIEH3:-KXSIXLSRHjqpaKWDEuH:b-1ttuv4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/drivers/comm/Include/comm/comm.h#L68)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> since now we are using c++ it wold there is no need to use this fixed size buffer and copy the frame contents into it every time we get a frame. 
> It may be simpler to just use gsl::span instead.
</details>
using `gsl::span` will require changes to comm low-level driver that I'm not so sure (at least now). Currently Method `CommObject::ReceiveFrame` is filling frame object that is passed as reference. Buffer for received data is local, so span will be referencing local variable

Changed that to `std::array`.

---

*[libs/telecommand_handling/telecommand_handling.cpp, line 3 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMF8pNqpLplxxKbcem:-KXNa_VCd9CSeEXQRP1Z:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/telecommand_handling.cpp#L3)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> unused
</details>
Done.

---

*[libs/telecommand_handling/telecommand_handling.cpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFCUgbnYNbe33py_4:-KXSH6kGO2Zkc4FQYg4K:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/telecommand_handling.cpp#L27)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> use std::array instead
</details>
Done.

---

*[libs/telecommand_handling/uplink.cpp, line 10 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMDpUj6dKNWh17qbMF:-KXNaktMHH53pzXuoHH0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/uplink.cpp#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> missing include <algorithm>
</details>
Done.

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 55 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFTOYk2mHdELv-dRG:-KXSbgDdddmvQi2rwJLL:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L55)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Use more complex return type instead of out parameters. Out parameters may be accidentally left uninitialized return value can't.
</details>
Done.

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 71 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMB2G2_dVhBWS9fW-X:-KXSbgiiM8aDcxgzTV9s:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L71)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Use more complex return type instead of out parameters
</details>
Done.

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMD7M-_Xuf2uCLfaWR:-KXNau1kygqTSFdT3_5V:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L97)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> if you are going to use interfaces mark their implementation as final to make it easier for the optimizer to devirtualize the functions during the optimization
</details>
Done.

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 97 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMBXYA2KonShUlPv8b:-KXSO1k3Sj6uiPlVT6xB:b-mcnaqw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L97)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Consider making this class a template that takes as parameter frame decryptor
</details>
Not saying no but I'm not convinced at the moment. It's quick change, maybe I'll try it later

---

*[libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h, line 118 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMBJqr8jDBLB3p_h_v:-KXNayw-TVSIrDDa3elq:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/telecommand_handling/include/telecommand_handling/telecommand_handling.h#L118)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> In general fields should be the last thing defined in class as they are least interesting from class user point of view
</details>
Done.

---

*[src/communication.cpp, line 1 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMFj1Ig63Vn5UwX4hz:-KXSeIvWggs5WxW94K2f:bq2rurs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.cpp#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> The command handlers should be tested as well therefore they cannot be defined in main project.
</details>
They will be tested and will not be defined in main project. For now there's only Ping telecommand but nothing prevents them from being defined anywhere they want.

---

*[src/communication.h, line 5 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMGF_93C4cF6_gThwo:-KXScXusUMQax96dY80o:b5fhua6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.h#L5)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> the only reason this header is needed is to declare the I2CBus type. We should start preparing headers with just forward declarations.
</details>
I2C driver update is coming soon

---

*[src/communication.h, line 6 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMG_MRbUe9_L9IQVGF:-KXNb55zz1Y-6MlcUX0t:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/src/communication.h#L6)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this header seems to be unused
</details>
Done.

---

*[unit_tests/TeleCommandHandling/TeleCommandHandlingTest.cpp, line 76 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMGrUo_-pZkdYl4UFP:-KXSbk_rzWbQMshIRUdu:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/unit_tests/TeleCommandHandling/TeleCommandHandlingTest.cpp#L76)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> This would be much more clear if the Decrypt method used only return value to report the results.
</details>
Done.

---

*[libs/base/utils.cpp, line 3 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50#-KXMHY5kbInJiGKjveir:-KXNY4z4MII-76C447Qr:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d88195ef5c051749b12772a7800cd908275f308/libs/base/utils.cpp#L3)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> this function is not used anywhere.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by Novakov** [comment]
[Telecommands handling](https://trello.com/c/OJax9LOg/84-telecommands-handling)

**Comment by zaq32** [comment]
Reviewed 18 of 24 files at r3.
Review status: 27 of 32 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by zaq32** [comment]
Reviewed 5 of 24 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by zaq32** [comment]
Reviewed 1 of 16 files at r4.
Review status: 18 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Comment by zaq32** [comment]
Reviewed 15 of 16 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/50)*

**Pull request merged**
