### PR TITLE
EPS error counters

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/133)

### CODE REVIEW

**Comment by Novakov** [comment]
[[EPS] Error counters](https://trello.com/c/6gkcmO4Z/159-eps-error-counters)

**Comment by zaq32** [comment]
Reviewed 6 of 18 files at r1.
Review status: 6 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133)*

**Comment by zaq32** [comment]
Reviewed 12 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/traits.hpp, line 167 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133#-KiWZ3_1z14zI_cawS8r:-KiWZ3_1z14zI_cawS8s:b-yd4865) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da9c04a3e7f23d646448c973e55d33d94a412468/libs/base/Include/traits.hpp#L167)):*
> ```cpp
>   public:
>     /** @brief Value indicating whether type is in list */
>     static constexpr bool value = Check<0, List...>();
> ```

put public members before private members

---

*[libs/base/Include/traits.hpp, line 202 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133#-KiWZ8l-9V8fXpD75Z-s:-KiWZ8l-9V8fXpD75Z-t:b-yd4865) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da9c04a3e7f23d646448c973e55d33d94a412468/libs/base/Include/traits.hpp#L202)):*
> ```cpp
>   public:
>     /** @brief Value indicating whether types in template pack are unique */
>     static constexpr bool value = IsUnique<0, Ts...>();
> ```

put public members before private members

---

*[libs/drivers/eps/eps.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133#-KiWZotwl7sTavx_qkOd:-KiWZotwl7sTavx_qkOe:bh6n3hn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da9c04a3e7f23d646448c973e55d33d94a412468/libs/drivers/eps/eps.cpp#L30)):*
> template <error_counter::Device Device>
>         static constexpr I2CResult operator>>(I2CResult result, error_counter::ErrorCounter<Device>& counter)
>         {
>             (result == I2CResult::OK) >> counter;
> 
>             return result;
>         }
> 
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         template <error_counter::Device Device>
>         static constexpr ErrorCode operator>>(ErrorCode result, error_counter::ErrorCounter<Device>& counter)
>         {
>             (result == ErrorCode::NoError) >> counter;
</details>
> 
>             return result;
>         }
Any reason why these cannot be put in the same library as error counting implementation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/drivers/eps/eps.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133#-KiWZotwl7sTavx_qkOd:-KiaS6K6Rv0Wg3QzX-a3:b-u3qpnx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/da9c04a3e7f23d646448c973e55d33d94a412468/libs/drivers/eps/eps.cpp#L30)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> template <error_counter::Device Device>
>         static constexpr I2CResult operator>>(I2CResult result, error_counter::ErrorCounter<Device>& counter)
>         {
>             (result == I2CResult::OK) >> counter;
> 
>             return result;
>         }
> 
>         template <error_counter::Device Device>
>         static constexpr ErrorCode operator>>(ErrorCode result, error_counter::ErrorCounter<Device>& counter)
>         {
>             (result == ErrorCode::NoError) >> counter;
> 
>             return result;
>         }
Any reason why these cannot be put in the same library as error counting implementation?
</blockquote></details>

I2CResult comes from `i2c` library, putting this operator into error counters library will make it dependant on `i2c` - which will be strange. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/133)*

**Pull request merged**
