### PR TITLE
Smart wait

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/44)

### CODE REVIEW

**Comment by decu69** [comment]
*[libs/os/os.c, line 187 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfgdIvjRLb6_rwV2Fk:-KVfgdIvjRLb6_rwV2Fl:b-i1d6fp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/os/os.c#L187)):*
> ```C
>     OSEventBits result = EventGroupWaitForBits((OSEventGroupHandle)handle, 0x80, true, true, timeout);
> 
>     if (result == 0x80)
> ```

shouldnt be moved to some const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[libs/time/timer.c, line 426 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfmAP9as9ORcirY-iJ:-KVfmAP9as9ORcirY-iK:b-gt1h0n) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L426)):*
> ```C
>         }
> 
>         if (TimePointLessThan(time, missionTime))
> ```

dont get that. Documentation says that it should return true when time is achieved. Calling that method suggest something different.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[unit_tests/time/SmartWait.cpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfombz_hPhk33XZgkX:-KVfombz_hPhk33XZgkY:b-cfenfr) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L50)):*
> ```cpp
>         }));
> 
>     auto result = TimeLongDelayUntil(&timeProvider, TimePointBuild(0, 0, 10, 0, 0));
> ```

so it will simulate 10 min delay? (called 10 times adding each time 1 minute?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[unit_tests/time/SmartWait.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfpwyjfSb-UMBV3x0T:-KVfpwyjfSb-UMBV3x0U:bs3ucc4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L30)):*
> ```cpp
> }
> 
> TEST_F(SmartWaitTest, ShouldReturnImmediatelyIfAlreadyAfterDesiredTime)
> ```

how do you know that is that immediately? Second part of the name of the test is not clear for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by zaq32** [comment]
Reviewed 13 of 16 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[libs/time/timer.c, line 141 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjRNGB_o_a6vwxV9PK:-KVjRNGB_o_a6vwxV9PL:b-hs30zh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L141)):*
> ```C
>     }
> 
>     provider->TickNotification = System.CreatePulseAll();
> ```

timer should report initialization failure when this event group could not be created. 

---

*[libs/time/timer.c, line 426 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfmAP9as9ORcirY-iJ:-KVjVaw37EE3zQcEqBj_:b-o42v2f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L426)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> dont get that. Documentation says that it should return true when time is achieved. Calling that method suggest something different.
</details>
yes those parameters seem to be in wrong order

---

*[libs/time/include/time/timer.h, line 112 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjU1pKr5KOlJXqywHP:-KVjU1pKr5KOlJXqywHQ:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/include/time/timer.h#L112)):*
> ```objc
>     OSSemaphoreHandle notificationLock;
> 
>     OSEventGroupHandle TickNotification;
> ```

undocumented

---

*[unit_tests/time/SmartWait.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjVNkYff7YjfBOkgVL:-KVjVNkYff7YjfBOkgVM:b-ehznea) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L38)):*
> ```cpp
> }
> 
> TEST_F(SmartWaitTest, ShouldWaitForPulseAndReturnIfDesiredTimeReached)
> ```

I'd also test what happens when PulseWait returns error/timeout. 

---

*[unit_tests/time/SmartWait.cpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjVH8i8EnUzsthcZoB:-KVjVH8jDqdXqDxdLoAg:bjbewti) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L42)):*
> ```cpp
>     timeProvider.CurrentTime = TimePointToTimeSpan(TimePointBuild(0, 0, 0, 0, 0));
> 
>     EXPECT_CALL(osMock, PulseWait(_, _))
> ```

I'd add verification how many times PulseWait procedure has been called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[libs/os/os.c, line 187 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfgdIvjRLb6_rwV2Fk:-KVkJCqfUXs2JWXmdsn-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/os/os.c#L187)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> shouldnt be moved to some const?
</details>
Done.

---

*[libs/time/timer.c, line 141 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjRNGB_o_a6vwxV9PK:-KVkKhaK8YwvvEyula-w:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L141)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> timer should report initialization failure when this event group could not be created. 
</details>
Done.

---

*[libs/time/timer.c, line 426 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfmAP9as9ORcirY-iJ:-KVkU83f3TPjsZ8qoXWg:b-3l3u19) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L426)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> yes those parameters seem to be in wrong order
</details>
`TimePointLessThan(time, missionTime)` => `time < missionTime`.  Current mission time is *after* desired time, so parameters are in good order

---

*[libs/time/include/time/timer.h, line 112 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjU1pKr5KOlJXqywHP:-KVkUmnkxwKJvDHkkWrr:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/include/time/timer.h#L112)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> undocumented
</details>
Done.

---

*[unit_tests/time/SmartWait.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfpwyjfSb-UMBV3x0T:-KVkWN1o4yNMarhWeGd5:b18l6dz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L30)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> how do you know that is that immediately? Second part of the name of the test is not clear for me.
</details>
I've added another assertion

---

*[unit_tests/time/SmartWait.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjVNkYff7YjfBOkgVL:-KVkXhhT6NAh-KE3ZoZl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> I'd also test what happens when PulseWait returns error/timeout. 
</details>
Done.

---

*[unit_tests/time/SmartWait.cpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVjVH8i8EnUzsthcZoB:-KVkWT5tCnrYflDl3MbJ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> I'd add verification how many times PulseWait procedure has been called.
</details>
Done.

---

*[unit_tests/time/SmartWait.cpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfombz_hPhk33XZgkX:-KVkWU-8sI_9VKjR3H8E:b-81la7d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/unit_tests/time/SmartWait.cpp#L50)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> so it will simulate 10 min delay? (called 10 times adding each time 1 minute?)
</details>
Right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[libs/time/timer.c, line 426 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfmAP9as9ORcirY-iJ:-KVojxqcgLkGWrxn2ceo:bbw68yd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L426)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> `TimePointLessThan(time, missionTime)` => `time < missionTime`.  Current mission time is *after* desired time, so parameters are in good order
</details>
My question was not about the order of parameters but the logic. Documentation says that the whole method TimeLongDelayUntil should return true IF desired time is achieved. This commented IF is something I dont understand why we compare desired time with mission time and we return true from it (as we need to wait to achieve desired time? as next IF checks that?)

So I believe (if I correctly understand, but it seems I do not ;)) that we should check

if desiredTime >= currentTime and then return from that loop (true)? as it would mean we achieved desired time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[libs/os/os.c, line 187 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfgdIvjRLb6_rwV2Fk:-KVomvLgBxhQj7cyX6hg:b-e0bc6w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/os/os.c#L187)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Done.
</details>
fine. btw. this value comes from the system? it is always 0x80?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
*[unit_tests/time/timer.cpp, line 48 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVooFu1kFN4Tst_o-FN:-KVooFu1kFN4Tst_o-FO:bp19cto) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e166ce48a1a7611a1dbcba7e2358aa79f1539eea/unit_tests/time/timer.cpp#L48)):*
> ```cpp
>     ON_CALL(os, GiveSemaphore(_)).WillByDefault(Return(OSResultSuccess));
> 
>     EXPECT_CALL(os, CreatePulseAll()).WillOnce(Return(reinterpret_cast<void*>(3)));
> ```

This doesnt explain much for me. "TimerTest" naming not clear for me. Why here is 3? Maybe we can talk f2f to understand this ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/os/os.c, line 187 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfgdIvjRLb6_rwV2Fk:-KVootdxppGB6VaNsBqe:bw2721d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/os/os.c#L187)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> fine. btw. this value comes from the system? it is always 0x80?
</details>
Just some number with single bit set, is could be 0x08 as well. 

---

*[libs/time/timer.c, line 426 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVfmAP9as9ORcirY-iJ:-KVomGwNkFacz6mjE94i:b2zpytt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93b7853a7126bf6cfbc4eeeecf9efd663fef5ccd/libs/time/timer.c#L426)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> My question was not about the order of parameters but the logic. Documentation says that the whole method TimeLongDelayUntil should return true IF desired time is achieved. This commented IF is something I dont understand why we compare desired time with mission time and we return true from it (as we need to wait to achieve desired time? as next IF checks that?)
> 
> So I believe (if I correctly understand, but it seems I do not ;)) that we should check
> 
> if desiredTime >= currentTime and then return from that loop (true)? as it would mean we achieved desired time?
</details>
`TimeLongDelayUntil` waits until time is achived (e.g. 5 minutes). It is done by checking mission time after each timer tick. 

It is possible that after tick, mission time and desired time are equal (second IF). More likely desired time will be between ticks, so wait will be a little long (up to tick length), so we need to check if mission time is after desired time.


Condition desiredTime >= currentTime, means that currentTime is before desiredTime, exiting in that condition will be cause no wait at all

---

*[unit_tests/time/timer.cpp, line 48 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KVooFu1kFN4Tst_o-FN:-KVooc5E6ezrrNHa4o6j:buewxow) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e166ce48a1a7611a1dbcba7e2358aa79f1539eea/unit_tests/time/timer.cpp#L48)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> This doesnt explain much for me. "TimerTest" naming not clear for me. Why here is 3? Maybe we can talk f2f to understand this ;)
</details>
3 is as good as any other value. Some value must be returned but is has no significance in case of unit testing.

TimerTest is name of test fixture with tests related to keeping track of mission time 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by Novakov** [comment]
[SmartWait](https://trello.com/c/SMjmxnbH/74-smartwait)

**Comment by decu69** [comment]
*[unit_tests/time/SmartWait.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KWJKMJaeZt_gV5BeN1l:-KWJKMJaeZt_gV5BeN1m:ba7n9jy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e166ce48a1a7611a1dbcba7e2358aa79f1539eea/unit_tests/time/SmartWait.cpp#L30)):*
> ```cpp
>     osGuard = InstallProxy(&osMock);
> 
>     EXPECT_CALL(osMock, TakeSemaphore(_, _)).WillRepeatedly(Return(OSResultSuccess));
> ```

why is taking and giving calls here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/time/SmartWait.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44#-KWJKMJaeZt_gV5BeN1l:-KWJKc5lB1avvYMvaj9m:b-1ndekq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e166ce48a1a7611a1dbcba7e2358aa79f1539eea/unit_tests/time/SmartWait.cpp#L30)):*
<details><summary><i>Previously, decu69 wrote…</i></summary>
> why is taking and giving calls here?
</details>
Because timer code is using semaphores but testing failures of these actions are not point of this tests, so it is easier to setup semaphore related functions to return  success

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Comment by decu69** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/44)*

**Pull request merged**
