### PR TITLE
EPS Driver

### PR DESCRIPTION
**Pull request by Novakov**
TODO (next pull request): error counting integration

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/123)

### CODE REVIEW

**Comment by zaq32** [comment]
Most of this code is undocumented

---

Reviewed 35 of 38 files at r1.
Review status: 35 of 38 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/utils.h, line 358 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDA6sz5jpD_SEA4v_V:-KhDA6sz5jpD_SEA4v_W:b-691456) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/base/Include/utils.h#L358)):*
> ```objc
>  * @tparam BitsCount Number of bits used by number
>  */
> template <typename Underlying, std::uint8_t BitsCount> class BitValue
> ```

missing assignment & comparison operators

---

*[libs/drivers/eps/Include/eps/eps.h, line 39 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDBeQrrWnpVSEsK1d7:-KhDBeQrrWnpVSEsK1d8:bs4qjzm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/drivers/eps/Include/eps/eps.h#L39)):*
> ```objc
>         };
> 
>         class EPSDriver
> ```

This class combines low level hardware communication (command reading/parsing & processing) with high level coordination and some knowledge that do not necessarily has to be hardcoded into the driver (like i2c bus assignment). 

Perhaps splitting this driver into smaller parts would not be a bad idea?

---

*[libs/drivers/i2c/Include/i2c/forward.h, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDCHG0-zWbODimbf-m:-KhDCHG0-zWbODimbf-n:b-7khyww) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/drivers/i2c/Include/i2c/forward.h#L8)):*
> ```objc
>     namespace i2c
>     {
>         using I2CAddress = uint8_t;
> ```

missing include: cstdint

---

*[libs/mission/sail/Include/mission/sail.hpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDCWWHU7boQ05upP2D:-KhDCWWHU7boQ05upP2E:bhr4js8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/mission/sail/Include/mission/sail.hpp#L38)):*
> ```cpp
>          *
>          * To support single argument construction.
>          * @param[in] isSailOpened Initial sail deployment state.
> ```

update documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-:-KhDBHlSCzzmOM2rhQ5S:b-hgpnqx)*

**Comment by Novakov** [comment]
Review status: 17 of 38 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/base/Include/utils.h, line 358 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDA6sz5jpD_SEA4v_V:-KhJ4zTH8VFkoxK23iF3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/base/Include/utils.h#L358)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing assignment & comparison operators
</blockquote></details>

Done.

---

*[libs/drivers/eps/Include/eps/eps.h, line 39 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDBeQrrWnpVSEsK1d7:-KhSoYtVQ-5N1zrVQopN:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/drivers/eps/Include/eps/eps.h#L39)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This class combines low level hardware communication (command reading/parsing & processing) with high level coordination and some knowledge that do not necessarily has to be hardcoded into the driver (like i2c bus assignment). 

Perhaps splitting this driver into smaller parts would not be a bad idea?
</blockquote></details>

Done

---

*[libs/drivers/i2c/Include/i2c/forward.h, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDCHG0-zWbODimbf-m:-KhJ5PYsTegI5MYZLKho:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/drivers/i2c/Include/i2c/forward.h#L8)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing include: cstdint
</blockquote></details>

Done.

---

*[libs/mission/sail/Include/mission/sail.hpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhDCWWHU7boQ05upP2D:-KhSjGgAzImStWZqmYFI:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c4159dc0c30ea253bf9e07f967ee3ef49134ab2/libs/mission/sail/Include/mission/sail.hpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

update documentation
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by zaq32** [comment]
Reviewed 19 of 20 files at r2.
Review status: 36 of 38 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/drivers/eps/Include/eps/hk.hpp, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-Kh_qv9Ep-GEhR4nH2Te:-Kh_qv9Ep-GEhR4nH2Tf:bjaf810) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf6df31fb1fadc0458f9fbc69e7512cd185deac2/libs/drivers/eps/Include/eps/hk.hpp#L4)):*
> ```cpp
> #define LIBS_DRIVERS_EPS_INCLUDE_EPS_HK_HPP_
> 
> #include "base/reader.h"
> ```

use only forward declaration header

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by Novakov** [comment]
Review status: 33 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/eps/Include/eps/hk.hpp, line 4 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-Kh_qv9Ep-GEhR4nH2Te:-Khh-yWWz-Hg61UOD_Qx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/bf6df31fb1fadc0458f9fbc69e7512cd185deac2/libs/drivers/eps/Include/eps/hk.hpp#L4)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use only forward declaration header
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by zaq32** [comment]
Reviewed 1 of 38 files at r1, 3 of 4 files at r3.
Review status: 37 of 38 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by zaq32** [comment]
Review status: 37 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/eps/eps.cpp, line 99 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhlvwSxSbi_MdXN6HiK:-KhlvwSxSbi_MdXN6HiL:b8te4e1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c9a5ed781a5f70d5e179c88c6f842062f6a1b0a/libs/drivers/eps/eps.cpp#L99)):*
> ```cpp
>         }
> 
>         bool EPSDriver::PowerCycleB()
> ```

almost exact duplicate of PowerCycleA  try to extract common parts of A & B controllers into dedicated functions/types. 

This aplies to entire driver.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by Novakov** [comment]
[[Driver] EPS](https://trello.com/c/XyDgUrFa/65-driver-eps)

**Comment by Novakov** [comment]
Review status: 34 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/eps/eps.cpp, line 99 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123#-KhlvwSxSbi_MdXN6HiK:-KiBRK8ayg-8gnRrVlk5:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2c9a5ed781a5f70d5e179c88c6f842062f6a1b0a/libs/drivers/eps/eps.cpp#L99)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

almost exact duplicate of PowerCycleA  try to extract common parts of A & B controllers into dedicated functions/types. 

This aplies to entire driver.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/123)*

**Pull request merged**
