### PR TITLE
I2C Read

### PR DESCRIPTION
**Pull request by ggajoch**
Implementation of I2C read command.
Needed for:
  * imtq
  * comm

Tested on imtq branch - works with device mock OOTB.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/79)

### CODE REVIEW

**Comment by ggajoch** [comment]
[I2C Read](https://trello.com/c/1fmcQrtk/112-i2c-read)

**Comment by Novakov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 90 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/79#-KbqMSpzqqkSVtDFLyox:-KbqMSpzqqkSVtDFLyoy:b-aq2wed) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4bc7945b0d8aa06423ae838798618a111fa0bc79/libs/drivers/i2c/Include/i2c/i2c.h#L90)):*
> ```objc
>             virtual I2CResult Write(const I2CAddress address, gsl::span<const uint8_t> inData) = 0;
> 
>             virtual I2CResult Read(const I2CAddress address, gsl::span<uint8_t> outData) = 0;
> ```

Missing documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/79)*

**Comment by ggajoch** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/i2c/Include/i2c/i2c.h, line 90 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/79#-KbqMSpzqqkSVtDFLyox:-KbqR5rv2L0UlWwlWsu9:bb7f2mf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4bc7945b0d8aa06423ae838798618a111fa0bc79/libs/drivers/i2c/Include/i2c/i2c.h#L90)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/79)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/79)*

**Pull request merged**
