### PR TITLE
Added delays for power operations

### PR DESCRIPTION
**Pull request by ggajoch**
Added:
 * `6 s` delay after turning off the camera in photoservice
 * `6 s` between steps in payload commissioning experiment

This should fix [NCR#041](https://team.pw-sat.pl/w/ncr/ncr41/)

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/350)

### CODE REVIEW

**Comment by zaq32** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/power/power_eps/power_eps.cpp, line 121 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350#-Kw3jzZ5C9A449ni0YI1:-Kw3jzZ5C9A449ni0YI2:blnud1o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5330e896ddfd54425227e087e03f83e918aab46d/libs/power/power_eps/power_eps.cpp#L121)):*
> ```cpp
>                 using namespace std::chrono_literals;
>                 auto status = this->_eps.EnableLCL(lcl) == ErrorCode::NoError;
>                 System::SleepTask(500ms);
> ```

in at least half of the use cases this sleep will introduce unnecessary artificial delay that is already taken care of.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350)*

**Comment by Novakov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/power/power_eps/power_eps.cpp, line 121 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350#-Kw3jzZ5C9A449ni0YI1:-Kw5_ffyZt1SSZZByLGQ:b-7wf6gl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5330e896ddfd54425227e087e03f83e918aab46d/libs/power/power_eps/power_eps.cpp#L121)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

1. why do you think that this 500 ms delay will be harmful to the system? do you see any threats that we are not aware of?
2. setting this delay let's say 'globally' was menat to reduce workload needed for this change. 
</blockquote></details>

1. It's just strange 
2. Actually photo service is the only place that lacked necessary delays

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350)*

**Comment by Novakov** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350)*

**Comment by ggajoch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/power/power_eps/power_eps.cpp, line 121 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350#-Kw3jzZ5C9A449ni0YI1:-Kw5ziO73Hb5b2QLVjw0:b-edr0pk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5330e896ddfd54425227e087e03f83e918aab46d/libs/power/power_eps/power_eps.cpp#L121)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

1. It's just strange 
2. Actually photo service is the only place that lacked necessary delays
</blockquote></details>

Done, removed it from here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350)*

**Comment by Novakov** [comment]
[[NCR #041] LCL delay violation](https://trello.com/c/A4BbL3r6/302-ncr-041-lcl-delay-violation)

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/350)*

**Pull request merged**
