### PR TITLE
[NCR #39] Ensure that beacon is sent when antenna deployment is disabled

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/356)

### CODE REVIEW

**Comment by zaq32** [comment]
[[NCR #039] Beacon stopped working](https://trello.com/c/OZZFO6S3/301-ncr-039-beacon-stopped-working)

**Comment by Novakov** [comment]
Reviewed 10 of 16 files at r1, 1 of 3 files at r2.
Review status: 11 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_telecommands_experiments.py, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356#-KwL-ll1PwTeU4GPhuKD:-KwL-ll1PwTeU4GPhuKE:b-djem2r) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77510b2b2c46417db26185c7a8c17542675ef194/integration_tests/tests/test_telecommands_experiments.py#L28)):*
> ```Python
> 
>     @runlevel(2)
>     @clear_state()
> ```

Why? For the Fibo experiment it shoul not matter if state is cleared

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Comment by zaq32** [comment]
Review status: 11 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_telecommands_experiments.py, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356#-KwL-ll1PwTeU4GPhuKD:-KwL6bjjYjcnjvHwnHn6:bish683) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77510b2b2c46417db26185c7a8c17542675ef194/integration_tests/tests/test_telecommands_experiments.py#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Why? For the Fibo experiment it shoul not matter if state is cleared
</blockquote></details>

fibo itself does not depend on the persistent state, however one of the previous test disable antena deployment which causes borg/beacon frames to be sent before fibo response which eventually fails assert that expects fibo response frame

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Comment by Novakov** [comment]
Review status: 11 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_telecommands_experiments.py, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356#-KwL-ll1PwTeU4GPhuKD:-KwL8HbMwmX5T_qzzpYg:b-r5jyvc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77510b2b2c46417db26185c7a8c17542675ef194/integration_tests/tests/test_telecommands_experiments.py#L28)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

fibo itself does not depend on the persistent state, however one of the previous test disable antena deployment which causes borg/beacon frames to be sent before fibo response which eventually fails assert that expects fibo response frame
</blockquote></details>

That's why there is `filter_type` argument in `get_frame` method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Comment by Novakov** [comment]
Reviewed 3 of 16 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Comment by zaq32** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_telecommands_experiments.py, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356#-KwL-ll1PwTeU4GPhuKD:-KwaPz9wIGGcJwC_s1Sw:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77510b2b2c46417db26185c7a8c17542675ef194/integration_tests/tests/test_telecommands_experiments.py#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

That's why there is `filter_type` argument in `get_frame` method
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/356)*

**Pull request merged**
