### PR TITLE
Temperature sensor for EFM

### PR DESCRIPTION
**Pull request by Novakov**
Dead-simple temperatue sensor based on ADC

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/106)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/drivers/temp/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrK623Z6_TzpF2cCdY:-KfrK623Z6_TzpF2cCdZ:b59ewu1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/temp/CMakeLists.txt#L1)):*
> ```CMake
> set(NAME temp)
> ```

we have multiple temperature sensors this library name & location should reflect the fact that this is related to mcu internal sensor

---

*[libs/drivers/temp/efm.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrJYr5VCqDLQQfTJZJ:-KfrJYr5VCqDLQQfTJZK:b-qhs9js) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/temp/efm.cpp#L47)):*
> ```cpp
> 
>         /* Temperature gradient (from datasheet) */
>         std::int8_t t_grad = -6.3 * 10;
> ```

why not just `const std::int8_t t_grad = -63;`?

---

*[libs/obc/hardware/Include/obc/hardware.h, line 125 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrKJg7H6zHUSeMjmBK:-KfrKJg7H6zHUSeMjmBL:bydu9vu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/obc/hardware/Include/obc/hardware.h#L125)):*
> ```objc
> 
>         /** @brief Self-temperature sensor */
>         temp::ADCTemperatureReader Temperature;
> ```

this name should indicate that this is for mcu internal sensor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by Novakov** [comment]
Review status: 2 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/obc/hardware/Include/obc/hardware.h, line 125 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrKJg7H6zHUSeMjmBK:-KfrZbVNSjqFeYaUASN-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/obc/hardware/Include/obc/hardware.h#L125)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this name should indicate that this is for mcu internal sensor
</blockquote></details>

Done.

---

*[libs/drivers/temp/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrK623Z6_TzpF2cCdY:-KfrZA93NlrFNPm0tHMl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/temp/CMakeLists.txt#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

we have multiple temperature sensors this library name & location should reflect the fact that this is related to mcu internal sensor
</blockquote></details>

Done.

---

*[libs/drivers/temp/efm.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrJYr5VCqDLQQfTJZJ:-KfrZB6LQyrIdPBU18mB:bjunh9b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/temp/efm.cpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why not just `const std::int8_t t_grad = -63;`?
</blockquote></details>

-6.3 comes from datasheet. For this type of values I prefer to put them that way as it is easier to look for them (value from datasheet in code and value from code in datasheet - Ctrl+F will work)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by zaq32** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/mcu_temp/efm.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrJYr5VCqDLQQfTJZJ:-Kfrc_3Wx3Vk_zmGOUFx:b-spyn6k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/mcu_temp/efm.cpp#L47)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

-6.3 comes from datasheet. For this type of values I prefer to put them that way as it is easier to look for them (value from datasheet in code and value from code in datasheet - Ctrl+F will work)
</blockquote></details>

ok, but still this should be compile time constant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by Novakov** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/mcu_temp/efm.cpp, line 47 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106#-KfrJYr5VCqDLQQfTJZJ:-KfwyUOaKEYXqOp6kt2s:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02716bf30ce07152366348774164e61969add284/libs/drivers/mcu_temp/efm.cpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

ok, but still this should be compile time constant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by zaq32** [comment]
Reviewed 1 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/106)*

**Pull request merged**
