### PR TITLE
Mission task for beacon management

### PR DESCRIPTION
**Pull request by zaq32**
Setting beacon once the transmitting antennas have been deployed & updating the beacon once every 5 minutes since then. For the moment beacon content is single field that contains current mission time. 

Add some infrastructure for saving fields as downlink frame payload.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/97)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 43 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-kO3_S71PHX5k1xgt:-Ke-kO3aDj-Jo3GELs_F:bwdzk0p) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/mission/beacon/BeaconUpdate.cpp#L43)):*
> ```cpp
>         auto This = static_cast<BeaconUpdate*>(param);
>         return state.Antenna.Deployed && state.AreTransmittingAntennasDeployed() &&
>             ((state.Time - This->lastBeaconUpdate) > BeaconUpdateInterval);
> ```

I think it will be more readable if each condition will be separate, like:
```
if(!state.Antenna.Deployed) return false;
if(..) return false;

return true;
```

But that just my opinion ;)

---

*[libs/state/Include/state/struct.h, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-i2NIrJTEYXgg0NwB:-Ke-i2NIrJTEYXgg0NwC:b-b4hboh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/state/Include/state/struct.h#L62)):*
> ```objc
> inline bool SystemState::AreTransmittingAntennasDeployed() const
> {
>     // TODO verify antennas' ids
> ```

Add trello task for it and link it here

---

*[libs/telecommunication/include/telecommunication/FrameContentWriter.hpp, line 120 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-j-eHKVLhtZXwCxQE:-Ke-j-eIGhTRMqyK4SZ4:b-aq2wed) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/telecommunication/include/telecommunication/FrameContentWriter.hpp#L120)):*
> ```cpp
>             bool WriteFieldId(FieldId fieldId);
> 
>             Writer& writer;
> ```

Missing documentation

---

*[unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp, line 78 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-lXTTPABRCef8WKtk:-Ke-lXTUekQ_6sDd6I_9:b-ymzg1u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp#L78)):*
> ```cpp
>     action.actionProc(state, action.param);
>     EXPECT_THAT(action.condition(state, action.param), Eq(true));
> }
> ```

One test is missing: mission time = 60min && antenna deployed = false

---

*[unit_tests/mock/BeaconControllerMock.hpp, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-icvco5fA6IiIPBaX:-Ke-icvco5fA6IiIPBaY:b3dbx1m) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/mock/BeaconControllerMock.hpp#L11)):*
> ```cpp
> struct BeaconControllerMock : public devices::comm::IBeaconController
> {
>     MOCK_METHOD1(SetBeacon, bool(const devices::comm::Beacon& beacon));
> ```

Define default ctor explicit - to speed up compilation

---

*[unit_tests/telecommunication/FrameContentsWriterTest.cpp, line 17 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-jlOnSVxWHQfAA-Tk:-Ke-jlOo8ieL6LL88ue5:bkyr2ro) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/telecommunication/FrameContentsWriterTest.cpp#L17)):*
> ```cpp
> {
>     ASSERT_TRUE(std::equal(current, current + currentLength, expected, expected + expectedLength));
> }
> ```

You can use `Writer::Capture()` and `Eq` matcher. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by zaq32** [comment]
Review status: 21 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 43 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-kO3_S71PHX5k1xgt:-Ke-yfQTDSsJ-GhlyW1d:b-8k6zy8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/mission/beacon/BeaconUpdate.cpp#L43)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I think it will be more readable if each condition will be separate, like:
```
if(!state.Antenna.Deployed) return false;
if(..) return false;

return true;
```

But that just my opinion ;)
</blockquote></details>

How about like this?

---

*[libs/telecommunication/include/telecommunication/FrameContentWriter.hpp, line 120 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-j-eHKVLhtZXwCxQE:-Ke-ykYvbVQJlsso6sBf:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/telecommunication/include/telecommunication/FrameContentWriter.hpp#L120)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---

*[unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp, line 78 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-lXTTPABRCef8WKtk:-Ke-ylmWUcgXKyyBj12a:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp#L78)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

One test is missing: mission time = 60min && antenna deployed = false
</blockquote></details>

Fixed

---

*[unit_tests/telecommunication/FrameContentsWriterTest.cpp, line 17 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-jlOnSVxWHQfAA-Tk:-Ke-yo4LjkjhgC0qClvL:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/telecommunication/FrameContentsWriterTest.cpp#L17)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

You can use `Writer::Capture()` and `Eq` matcher. 
</blockquote></details>

Fixed

---

*[unit_tests/mock/BeaconControllerMock.hpp, line 11 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-icvco5fA6IiIPBaX:-Ke-yqb4nNXl68V5z2Rz:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/unit_tests/mock/BeaconControllerMock.hpp#L11)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Define default ctor explicit - to speed up compilation
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by Novakov** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0-KLl3ENn0BDWNQq5:-Ke0-KLl3ENn0BDWNQq6:beutxzu) (no related file):*
Add integration test for happy path

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 43 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-kO3_S71PHX5k1xgt:-Ke-zFtaKt0RfQHECwb7:b-8pqadh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/mission/beacon/BeaconUpdate.cpp#L43)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

How about like this?
</blockquote></details>

Will do :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/state/Include/state/struct.h, line 62 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke-i2NIrJTEYXgg0NwB:-Ke0-Um7qB3UVnQc-cSM:bivgcpb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8b92f3da428b5fc960fa83093f7893261501b68a/libs/state/Include/state/struct.h#L62)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add trello task for it and link it here
</blockquote></details>

Done: https://trello.com/c/lxKYUriB/126-verify-ids-of-antennas-responsible-for-data-transmission

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by mandrek44** [comment]
Review status: 28 of 30 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 18 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0KY4xhmcPZ4cKFale:-Ke0KY4yOVRwWHw98UR-:b-4j458y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2d0f5083a7ec68904fe0158467cc266de24f08fd/libs/mission/beacon/BeaconUpdate.cpp#L18)):*
> ```cpp
>      * @brief Default beacon send interval.
>      */
>     static constexpr std::uint16_t BeaconInterval = 30;
> ```

Could we use std::chrono here?

---

*[libs/telecommunication/include/telecommunication/FrameContentWriter.hpp, line 170 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0JDKW17iVK29XW1yH:-Ke0JDKXnlOQI9_ryMuX:blpa4r9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2d0f5083a7ec68904fe0158467cc266de24f08fd/libs/telecommunication/include/telecommunication/FrameContentWriter.hpp#L170)):*
> ```cpp
>         inline bool FrameContentWriter::WriteFieldId(FieldId fieldId)
>         {
>             return writer.WriteByte(num(fieldId));
> ```

Do we need to return this value if it's ignored everywhere? (for readability sake)

---

*[unit_tests/mock/BeaconControllerMock.hpp, line 0 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0Je62AQJteBUyMDhG:-Ke0Je62AQJteBUyMDhH:b33ef6z) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93988c5e73749120a828df96cfacea3000ed19ba/unit_tests/mock/BeaconControllerMock.hpp#L0)):*
Empty file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by zaq32** [comment]
Review status: 28 of 30 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[libs/telecommunication/include/telecommunication/FrameContentWriter.hpp, line 170 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0JDKW17iVK29XW1yH:-Ke0QGNV-IwRjfe3gehD:b-hljoff) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2d0f5083a7ec68904fe0158467cc266de24f08fd/libs/telecommunication/include/telecommunication/FrameContentWriter.hpp#L170)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

Do we need to return this value if it's ignored everywhere? (for readability sake)
</blockquote></details>

Maybe I have tried to retain interface from original Writer. 

---

*[unit_tests/mock/BeaconControllerMock.hpp, line  at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0Je62AQJteBUyMDhG:-Ke0Q9-mviuxZLFV505W:b-17p0vx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/93988c5e73749120a828df96cfacea3000ed19ba/unit_tests/mock/BeaconControllerMock.hpp#L)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

Empty file?
</blockquote></details>

No it was added and subsequently removed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by Novakov** [comment]
Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0-KLl3ENn0BDWNQq5:-KfX1Fpaq0OMXIu22npD:bb7f2mf) (no related file):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add integration test for happy path
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by zaq32** [comment]
Review status: 31 of 37 files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/mission/beacon/BeaconUpdate.cpp, line 18 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97#-Ke0KY4xhmcPZ4cKFale:-KfeWSn1u2oemxLRXTHF:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2d0f5083a7ec68904fe0158467cc266de24f08fd/libs/mission/beacon/BeaconUpdate.cpp#L18)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

Could we use std::chrono here?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/97)*

**Pull request merged**
