### PR TITLE
Connect beacon & telemetry acquisition

### PR DESCRIPTION
**Pull request by zaq32**
* Separate telemetry serialization & storage
* Generate beacon using serialized form of the latest telemetry object

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/188)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 29 of 34 files at r1.
Review status: 27 of 31 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doc/HowToBuild.md, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/188#-KmfJHdbr7hAo-lo_lxx:-KmfJHdbr7hAo-lo_lxy:b-2gbmxa) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dab0cc1d5ccd00f9e74409a3bf9d6c00692fb72/doc/HowToBuild.md#L49)):*
> ```Markdown
> `ENABLE_COVERAGE`  | 0                    | Set to 1 to enable code-coverage for unit tests
> `JLINK_SN`         | _None_               | Serial number of J-Link that will be used to flash EFM
> `IPYTHON_PATH`     | _None_               | Path to folder that contains IronPython interpreter
> ```

It's `IPython`. `IronPython` is totally different thing :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/188)*

**Comment by zaq32** [comment]
Review status: 26 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/HowToBuild.md, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/188#-KmfJHdbr7hAo-lo_lxx:-Kmk1BcLKDEpMZm6r831:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1dab0cc1d5ccd00f9e74409a3bf9d6c00692fb72/doc/HowToBuild.md#L49)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's `IPython`. `IronPython` is totally different thing :)
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/188)*

**Comment by Novakov** [comment]
Reviewed 4 of 34 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/188)*

**Pull request merged**
