### PR TITLE
Telecommand: send periodic message now

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/276)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] Request periodic message](https://trello.com/c/QmJ6I5R5/252-tc-request-periodic-message)

**Comment by zaq32** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/276#-KsAe2NLvZNGyFylKZJQ:-KsAe2NLvZNGyFylKZJR:bmp3vm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a46f78ccf789226532b7fababbbb00794fc37f86/libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp#L42)):*
> ```cpp
>          * @telecommand
>          *
>          * Parameters: None
> ```

the original request was to either sent as many messages as possible (i.e. 40) or make this value configurable. As this command is supposed to be used to keep comm transmitting indefinatelly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/276)*

**Comment by Novakov** [comment]
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/276#-KsAe2NLvZNGyFylKZJQ:-KsIRmz2UgesY-i93Hs_:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a46f78ccf789226532b7fababbbb00794fc37f86/libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

the original request was to either sent as many messages as possible (i.e. 40) or make this value configurable. As this command is supposed to be used to keep comm transmitting indefinatelly
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/276)*

**Comment by zaq32** [comment]
Reviewed 8 of 13 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/276)*

**Pull request merged**
