### PR TITLE
Camera Commissioning experiment

### PR DESCRIPTION
**Pull request by tom4r**
Including upgrading Payload Commissioning Experiment to include Camera Commissioning.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/274)

### CODE REVIEW

**Comment by tom4r** [comment]
https://trello.com/c/dyRBmU6e/208-experiment-cam-commisioning

**Comment by zaq32** [comment]
Reviewed 16 of 26 files at r1.
Review status: 16 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 59 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-Ks7Jz_3z-ES3HXYlvwX:-Ks7Jz_3z-ES3HXYlvwY:b-82lmj4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/83ff3fd263deb82d9d525dffec43dd520311b313/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L59)):*
> ```cpp
>                 SupplySADSTemperature = 0x17,     // Temperature data, 4 bytes
>                 Sail = 0x18,                      // 3 bytes of data
>                 CameraSyncCount = 0x19,           // 1 byte of data
> ```

conflicting id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by tom4r** [comment]
Review status: 15 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/experiments/fs/Include/fs/ExperimentFile.hpp, line 59 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-Ks7Jz_3z-ES3HXYlvwX:-Ks7xr3UJ_wvF0Sqe4qk:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/83ff3fd263deb82d9d525dffec43dd520311b313/libs/experiments/fs/Include/fs/ExperimentFile.hpp#L59)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

conflicting id
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by zaq32** [comment]
Reviewed 6 of 26 files at r1, 1 of 1 files at r2.
Review status: 22 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by zaq32** [comment]
Reviewed 11 of 12 files at r3.
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/communication/telecommands/experiments.cpp, line 296 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsbJeOgKXKvFKvjC0JI:-KsbJeOgKXKvFKvjC0JJ:b-q5tfnz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed6e4a27061717076d340fafd6b3a4d1b4ea4201/libs/obc/communication/telecommands/experiments.cpp#L296)):*
> ```cpp
>         void PerformCameraCommisioningExperiment::Handle(devices::comm::ITransmitter& transmitter, gsl::span<const std::uint8_t> parameters)
>         {
>             char filePath[30];
> ```

this buffer is not used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by tom4r** [comment]
Review status: 18 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/experiments.cpp, line 296 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsbJeOgKXKvFKvjC0JI:-KsciaBJL9kpo1Eoo3Nh:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed6e4a27061717076d340fafd6b3a4d1b4ea4201/libs/obc/communication/telecommands/experiments.cpp#L296)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this buffer is not used.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by zaq32** [comment]
Reviewed 1 of 26 files at r1, 1 of 12 files at r3, 5 of 5 files at r4.
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by zaq32** [comment]
Reviewed 1 of 26 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/camera/camera_exp.cpp, line 22 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsnyTL9j8Mh_c8pJa1S:-KsnyTL9j8Mh_c8pJa1T:b-gb7l04) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/camera_exp.cpp#L22)):*
> ```cpp
>               _controller(_experimentFile, photoService), _currentStep(0)
>         {
>             strsafecpy(_fileName, DefaultFileName, 30);
> ```

Controller's output is left uninitialized

---

*[libs/experiments/camera/camera_exp.cpp, line 29 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsnyZ7TnXLvTAFLV4eH:-KsnyZ7UAkIsqx53R-3e:b-gb7l04) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/camera_exp.cpp#L29)):*
> ```cpp
>               _photoService(other._photoService), _controller(_experimentFile, _photoService), _currentStep(other._currentStep)
>         {
>             strsafecpy(_fileName, other._fileName, count_of(other._fileName));
> ```

Controller's output is left uninitialized

---

*[libs/experiments/camera/Include/experiment/camera/CameraExperimentController.hpp, line 14 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-Ksnxon7M-GOO2NPOuki:-Ksnxon7M-GOO2NPOukj:b-ilklbi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/Include/experiment/camera/CameraExperimentController.hpp#L14)):*
> ```cpp
>     {
>         /**
>          * @brief Class that does Camera Commisioning Experiment logic.
> ```

Commissioning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by tom4r** [comment]
Review status: 23 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/experiments/camera/camera_exp.cpp, line 22 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsnyTL9j8Mh_c8pJa1S:-KsooNR1VvLplOs6sLcd:bt2vr0b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/camera_exp.cpp#L22)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Controller's output is left uninitialized
</blockquote></details>

Fixed

---

*[libs/experiments/camera/camera_exp.cpp, line 29 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-KsnyZ7TnXLvTAFLV4eH:-KsooaaIP9aA3700mSWd:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/camera_exp.cpp#L29)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Controller's output is left uninitialized
</blockquote></details>

Fixed

---

*[libs/experiments/camera/Include/experiment/camera/CameraExperimentController.hpp, line 14 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274#-Ksnxon7M-GOO2NPOuki:-KsooIK65QrO3R7E7s0G:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3952007ab891768cd01f2e32ea13970f71c43794/libs/experiments/camera/Include/experiment/camera/CameraExperimentController.hpp#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Commissioning
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/274)*

**Pull request merged**
