### PR TITLE
Fixed PLD and Suns interrupt handlers in case of extra glitches on GPIO

### PR DESCRIPTION
**Pull request by tom4r**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/281)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[libs/drivers/payload/payload.cpp, line 71 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281#-KseMoN2DPiu-OfQb7qY:-KseMoN2DPiu-OfQb7qZ:be962ye) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/aad2840ca5ddb109e02029c972cd2c3b620a2948/libs/drivers/payload/payload.cpp#L71)):*
> ```cpp
> {
>     ErrorReporter errorContext(_error);
>     _event.Clear(InterruptFlagFinished);
> ```

This has a potential to not work correctly as by the time caller gets there the interrupt may already have happened in the past.

Consider this:

```
payload.Write(/*...*/);

eps.DoSomething();            // <- payload interrupt happens here

payload.WaitForData();     // <- and here gets erased.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281)*

**Comment by zaq32** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/suns/suns.cpp, line 145 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281#-KseNijXzUGOl94MfySB:-KseNijXzUGOl94MfySC:bi1c00i) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/aad2840ca5ddb109e02029c972cd2c3b620a2948/libs/drivers/suns/suns.cpp#L145)):*
> ```cpp
>             ErrorReporter errorContext(this->errors);
> 
>             this->event.Clear(InterruptFlagFinished);
> ```

see my comment in payload driver

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281)*

**Comment by tom4r** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/payload/payload.cpp, line 71 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281#-KseMoN2DPiu-OfQb7qY:-KseS5By2ghoFPHFUYCZ:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/aad2840ca5ddb109e02029c972cd2c3b620a2948/libs/drivers/payload/payload.cpp#L71)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This has a potential to not work correctly as by the time caller gets there the interrupt may already have happened in the past.

Consider this:

```
payload.Write(/*...*/);

eps.DoSomething();            // <- payload interrupt happens here

payload.WaitForData();     // <- and here gets erased.
```
</blockquote></details>

Fixed.

---

*[libs/drivers/suns/suns.cpp, line 145 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281#-KseNijXzUGOl94MfySB:-KseSMTQa8Fv_fKVAgaB:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/aad2840ca5ddb109e02029c972cd2c3b620a2948/libs/drivers/suns/suns.cpp#L145)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

see my comment in payload driver
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/281)*

**Pull request merged**
