### PR TITLE
Update Comm driver to support isis variant of i2c implementation

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/120)

### CODE REVIEW

**Comment by zaq32** [comment]
[[FIX] fix COMM driver to support I2C write & read](https://trello.com/c/FaxNWo2g/111-fix-fix-comm-driver-to-support-i2c-write-read)

**Comment by ggajoch** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzZti7o3NBWJbxVcu5:-KgzZti7o3NBWJbxVcu6:byzv3y3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L89)):*
> ```cpp
>     }
> 
>     System::SleepTask(2ms);
> ```

do we need this delay? We can test it tommorow if it is necessary.
Also, take note that it will be ~10 ms delay in current FreeRTOS configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by zaq32** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzZti7o3NBWJbxVcu5:-Kgz_MVUeaECvqc_7BKP:b9gxyy7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L89)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

do we need this delay? We can test it tommorow if it is necessary.
Also, take note that it will be ~10 ms delay in current FreeRTOS configuration.
</blockquote></details>

Please do test it and if possible determine if it is needed and how short it can be. 
As for the actual delay length I took 2ms from our previous tests and also in case that we decide to increase FreeRTPOS systick frequency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-Kgza-2D0-xNjQhs9-s_:-Kgza-2D0-xNjQhs9-sa:b-ita57d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L72)):*
> ```cpp
> }
> 
> bool CommObject::SendBufferWithResponse(Address address, //
> ```

It's tricky that `inputBuffer` must contain `command` as it first byte. I would expect that method with such signature will compose `command + inputBuffer` for sending - which not realy good solution for us. I would say that skipping `command` parameter and extracting command from first element of `inputBuffer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by zaq32** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/comm.cpp, line 72 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-Kgza-2D0-xNjQhs9-s_:-KgzgNG7McXAMPoaWheG:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L72)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's tricky that `inputBuffer` must contain `command` as it first byte. I would expect that method with such signature will compose `command + inputBuffer` for sending - which not realy good solution for us. I would say that skipping `command` parameter and extracting command from first element of `inputBuffer`
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 247 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzggFTPefzA2QXmBfy:-KgzggFUd9l9D83hNx4o:b-2k6cyb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/01d9b095175166201332a829bf990c7b9046dc11/libs/drivers/comm/Include/comm/CommDriver.hpp#L247)):*
> ```cpp
>      * i2c clock stretching for signaling that it is not ready with the answer.
>      * @param[in] address Address of the device which should receive the command.
>      * @param[in] command Command code of request being send. Strictly for logging purposes.
> ```

Update docs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by zaq32** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 247 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzggFTPefzA2QXmBfy:-KgzhSHRASPdJ9z6T6CT:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/01d9b095175166201332a829bf990c7b9046dc11/libs/drivers/comm/Include/comm/CommDriver.hpp#L247)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Update docs
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by zaq32** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzZti7o3NBWJbxVcu5:-Kh_tZ_fBN59FwQ7BmgP:b-y85zij) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L89)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Please do test it and if possible determine if it is needed and how short it can be. 
As for the actual delay length I took 2ms from our previous tests and also in case that we decide to increase FreeRTPOS systick frequency.
</blockquote></details>

This specific fix will be postponed until the proper delay will be empircally determined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by ggajoch** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzZti7o3NBWJbxVcu5:-KhaxLwu4jAJ30xfIx5w:bq7d50h) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L89)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This specific fix will be postponed until the proper delay will be empircally determined.
</blockquote></details>

We tried to measure it by:
 - increasing tick rate to 1000 Hz
 - removing this delay completely.

Unfortunately, removing it resulted in about 0.5ms delay between Write() and Read() and commands were executed successfully.
I don't know how to reduce the delay even more, but next time more test should be performed (e.g. sending 10k and searching for incorrect ones).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by zaq32** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120#-KgzZti7o3NBWJbxVcu5:-KhbM9xruG32f__PJYAk:bf5eqza) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/10c335db82174590fddbbbcfc2a06918f75cff40/libs/drivers/comm/comm.cpp#L89)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

We tried to measure it by:
 - increasing tick rate to 1000 Hz
 - removing this delay completely.

Unfortunately, removing it resulted in about 0.5ms delay between Write() and Read() and commands were executed successfully.
I don't know how to reduce the delay even more, but next time more test should be performed (e.g. sending 10k and searching for incorrect ones).
</blockquote></details>

Therefore lets stick with what we have ritght now and get back to this on another PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/120)*

**Pull request merged**
