### PR TITLE
SunPointing ICD

### PR DESCRIPTION
**Pull request by ggajoch**
ICD proposal for SunPointing. 
Reflects algorithm actions and interfaces for the rest of OBC.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/185)

### CODE REVIEW

**Comment by zaq32** [comment]
There are several outstanding doxygen issuses in this PR. 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/SunPointing.hpp, line 182 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185#-KmuRkNNyKxMTbyT-RGq:-KmuRkNNyKxMTbyT-RGr:b3p1dk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2568efd094066eea116d86e5207ce8d3c038b30f/libs/adcs/experimental/Include/adcs/SunPointing.hpp#L182)):*
> ```cpp
>             State() = default;
> 
>             State(const Parameters& p)
> ```

do not define constructors inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185#-:-KmuSG_fpg0vHO4LwQGM:b-a7kbfr)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Include/adcs/SunPointing.hpp, line 182 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185#-KmuRkNNyKxMTbyT-RGq:-Knb6M_6ty-A1zJhIl16:bb7f2mf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2568efd094066eea116d86e5207ce8d3c038b30f/libs/adcs/experimental/Include/adcs/SunPointing.hpp#L182)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

do not define constructors inline
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185)*

**Comment by zaq32** [comment]
Reviewed 55 of 221 files at r3, 5 of 113 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/185)*

**Pull request merged**
