### PR TITLE
Adcs integration - detumbling code

### PR DESCRIPTION
**Pull request by pwec**
Detumbling algorithm implemented and cross-validated with latest state of matlab simulation
- public interface - types and units - follows @ggajoch imtq interfaces
- cross-validation UT with test data added

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/114)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 1 of 9 files at r1, 7 of 10 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/adcs_experiments/CMakeLists.txt, line 1 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Kgymf6GPjJaFWsyw9Jq:-Kgymf6HZTVc-F9320Yr:bn76ty7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/CMakeLists.txt#L1)):*
> ```CMake
> set(NAME adcs_experiments)
> ```

It this library implementation of ADCS experiments (Detumbling/SunPointing) or implementation of algorithms? If the latter, this library should be called `adcs_experimental`

---

*[libs/adcs_experiments/detumbling.cpp, line 72 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhCuZKBklIkOnpCiJLt:-KhCuZKBklIkOnpCiJLu:b64gxq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/detumbling.cpp#L72)):*
> ```cpp
>     std::cout << "commDipoleBdot: ";
>     std::cout << commDipoleBdot << std::endl;
> #endif
> ```

To be honest - that looks terrible. Could you elaborate a bit why it is needed? Maybe it is something that should be later stored as part of experiment results?

---

*[libs/adcs_experiments/Include/adcs_experiments/detumbling.hpp, line 36 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhCuAbVY6xsC1RB0WJP:-KhCuAbVY6xsC1RB0WJQ:b-qsel0y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/Include/adcs_experiments/detumbling.hpp#L36)):*
> ```cpp
>              * @default 0.2
>              */
>             float dt = 0.2;
> ```

If this value is constant, it should be constexpr

---

*[unit_tests/adcs_experiments/CMakeLists.txt, line 10 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgynyBBLudl1wDDQsjJ:-KgynyBCDuhRCYl8bVzK:b-xa080b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/unit_tests/adcs_experiments/CMakeLists.txt#L10)):*
> ```CMake
>   )
>   
>   include_directories("${PROJECT_BINARY_DIR}")
> ```

`${CMAKE_CURRENT_SOURCE_DIR}` and `${CMAKE_CURRENT_BINARY_DIR}` are variables that you are looking for instead of path relative to project root

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/adcs_experiments/detumbling.cpp, line 72 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhCuZKBklIkOnpCiJLt:-KhDK3esp4Tk_eyag4tu:b-1g79fn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/detumbling.cpp#L72)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

To be honest - that looks terrible. Could you elaborate a bit why it is needed? Maybe it is something that should be later stored as part of experiment results?
</blockquote></details>

Do you mean block of cout's? I am not really fan of it.... Hmm I understand that's only way to debug it and if cross-validation test fail this is only way to find problem (comparing to matlab steps). Do you know better way to keep such debug code without need to re-write it? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs_experiments/CMakeLists.txt, line 1 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Kgymf6GPjJaFWsyw9Jq:-KhO6yH7EZMAvSMbOOdv:b5mirp5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/CMakeLists.txt#L1)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It this library implementation of ADCS experiments (Detumbling/SunPointing) or implementation of algorithms? If the latter, this library should be called `adcs_experimental`
</blockquote></details>

library adcs_experimental is already created in adcs/experimental so it can't be named like that or is the detumbling code should be placed under adcs/experimental? (was not aware about existence of this directory)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[unit_tests/adcs_experiments/CMakeLists.txt, line 10 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgynyBBLudl1wDDQsjJ:-KhOGMHQrX8oVInvlJl6:b7licjk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/unit_tests/adcs_experiments/CMakeLists.txt#L10)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

`${CMAKE_CURRENT_SOURCE_DIR}` and `${CMAKE_CURRENT_BINARY_DIR}` are variables that you are looking for instead of path relative to project root
</blockquote></details>

tried, variables you mentioned about are empty/not created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/adcs_experiments/CMakeLists.txt, line 1 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Kgymf6GPjJaFWsyw9Jq:-KhOYxq5NsLpU2YDfdf1:bmwsd6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/CMakeLists.txt#L1)):*
<details><summary><i>Previously, pwec (Piotr Weclewski) wrote…</i></summary><blockquote>

library adcs_experimental is already created in adcs/experimental so it can't be named like that or is the detumbling code should be placed under adcs/experimental? (was not aware about existence of this directory)
</blockquote></details>

I think it should go there - if you don't want to integrate it with rest of OBC infrastructure you can just put in that library - not nice but will keep naming consistent

---

*[libs/adcs_experiments/detumbling.cpp, line 72 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhCuZKBklIkOnpCiJLt:-KhOZLkUYBmoF61e_P7N:bybwla5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs_experiments/detumbling.cpp#L72)):*
<details><summary><i>Previously, pwec (Piotr Weclewski) wrote…</i></summary><blockquote>

Do you mean block of cout's? I am not really fan of it.... Hmm I understand that's only way to debug it and if cross-validation test fail this is only way to find problem (comparing to matlab steps). Do you know better way to keep such debug code without need to re-write it? 
</blockquote></details>

I don't know - maybe some callbacks or maybe this can be separated into few methods? @zaq32 any idea?

---

*[unit_tests/adcs_experiments/CMakeLists.txt, line 10 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgynyBBLudl1wDDQsjJ:-KhO_-PMFogQ08HuRuil:bpcqmrb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/unit_tests/adcs_experiments/CMakeLists.txt#L10)):*
<details><summary><i>Previously, pwec (Piotr Weclewski) wrote…</i></summary><blockquote>

tried, variables you mentioned about are empty/not created
</blockquote></details>

They are used in many CMakeLists through out the repository - if you have problems with them, asks anybody from OBC team on slack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[unit_tests/adcs/experimental/CMakeLists.txt, line 10 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgynyBBLudl1wDDQsjJ:-KhOzlfGxplayIDE6SyH:b-kk3ut2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/unit_tests/adcs/experimental/CMakeLists.txt#L10)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

They are used in many CMakeLists through out the repository - if you have problems with them, asks anybody from OBC team on slack
</blockquote></details>

solved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Detumbling.cpp, line 72 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhCuZKBklIkOnpCiJLt:-KhOzypiNrMhyZnZAA4o:b-hfpv0l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebbda2da2874c72c4692e3b0e86d2b8920b6488/libs/adcs/experimental/Detumbling.cpp#L72)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't know - maybe some callbacks or maybe this can be separated into few methods? @zaq32 any idea?
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by Novakov** [comment]
Reviewed 13 of 19 files at r7.
Review status: 9 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 42 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhSgEzlhHquOheRau0o:-KhSgEzlhHquOheRau0p:blwsjwc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L42)):*
> ```cpp
>              * @default 0.2
>              */
>             float wCutOff = 0.2;
> ```

If this value is constant, it should be constexpr

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 48 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhSgG1EPO6d1pDOdvDb:-KhSgG1EPO6d1pDOdvDc:b-qsel0y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L48)):*
> ```cpp
>              * @default 2.879285e-5 * 1e15 -- unit conv - original gain * convwersion
>              */
>             float bDotGain = 2.879285e-5 * 1e15; // unit conv - original gain * convwersion
> ```

If this value is constant, it should be constexpr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 42 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhSgEzlhHquOheRau0o:-KhTFwb1jrdo3hLDc7rv:b-97jrtv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L42)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

If this value is constant, it should be constexpr
</blockquote></details>

No this is not a constant, this is external parameter that could be changed from gs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 48 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhSgG1EPO6d1pDOdvDb:-KhTGFjZrKQ_S6h4oUbW:b-97jrtv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L48)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

If this value is constant, it should be constexpr
</blockquote></details>

No this is not a constant, this is external parameter that could be changed from gs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by zaq32** [comment]
Reviewed 4 of 19 files at r7.
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 29 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Khlxx9s5DFy_rHPAMx8:-Khlxx9s5DFy_rHPAMx9:b-rbejpj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L29)):*
> ```cpp
>          * @brief Set of detumbling algorithm  parameters
>          */
>         class Parameters final
> ```

Put the Parameters type separately so we do not have to include entire detumbling header when we would like to use just its parameters

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 65 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhlxF4pM5Pfd6_Ek6rq:-KhlxF4pM5Pfd6_Ek6rr:beq5vxx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L65)):*
> ```cpp
>             State() = default;
> 
>             State(const Parameters& p)
> ```

constructors should not be defined inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by ggajoch** [comment]
Reviewed 2 of 17 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[libs/adcs_experiments/detumbling.cpp, line 59 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgvBFwPS4Yce45t5Y5n:-KgvBFwPS4Yce45t5Y5o:b-5szsfy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/17c715263706058237de8d3e87db3bbda2929b41/libs/adcs_experiments/detumbling.cpp#L59)):*
> ```cpp
>     {
>         commDipoleBdot = mtmDot * (-state.params.bDotGain)
>                 / (powf((mgmt_input).norm(), 2));
> ```

redundant parentheses

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 65 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhlxF4pM5Pfd6_Ek6rq:-Ki7sZgiWABCkhlI8VfH:b96pa8v) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L65)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

constructors should not be defined inline
</blockquote></details>

I understand that this one default is ok and only  second one is to be moved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 29 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Khlxx9s5DFy_rHPAMx8:-Ki7spVhhM1iOIz-SJ1m:bjnus3w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L29)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Put the Parameters type separately so we do not have to include entire detumbling header when we would like to use just its parameters
</blockquote></details>

as you prefer... so understand to put them to completely separated file? let me know if you want to have state separated also - it is also created/stored externally... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by Novakov** [comment]
Reviewed 3 of 19 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 29 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Khlxx9s5DFy_rHPAMx8:-KiEwLMcILjF3lUqxfsa:b-m0gmji) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L29)):*
<details><summary><i>Previously, pwec (Piotr Weclewski) wrote…</i></summary><blockquote>

as you prefer... so understand to put them to completely separated file? let me know if you want to have state separated also - it is also created/stored externally... 
</blockquote></details>

The idea is to put the algorithm parameters in obc's persistent state which will allow us to modify them after the launch if need arises. Therefore the parameters type should be default constructible. Also the default constructed object should contain valid configuration that can be used to run the algorithm. Preferably this should be default algorithm configuration.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 65 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KhlxF4pM5Pfd6_Ek6rq:-KiEwHePxA27CIEsE8NC:b2nign6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L65)):*
<details><summary><i>Previously, pwec (Piotr Weclewski) wrote…</i></summary><blockquote>

I understand that this one default is ok and only  second one is to be moved?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by ggajoch** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 29 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Khlxx9s5DFy_rHPAMx8:-KiNO0BPThajkeD5gCH5:b-iwlgxu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L29)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

The idea is to put the algorithm parameters in obc's persistent state which will allow us to modify them after the launch if need arises. Therefore the parameters type should be default constructible. Also the default constructed object should contain valid configuration that can be used to run the algorithm. Preferably this should be default algorithm configuration.
</blockquote></details>

@zaq32: I don't think those parameters should be in persistent state. They should be send from earth in telecommand which will enable this detumbling mode - and there is no point for wasting persistent (FRAM/FLASH) memory for storing them as this algorithm will be never invoked "by its own". Some parameters are constant (e.g. time step) but rest has to be send in the proper TC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/adcs/experimental/Include/adcs/Detumbling.hpp, line 29 at r7](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-Khlxx9s5DFy_rHPAMx8:-KiNdLsnEvm9N8qcjA7O:b32wtd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c0c2ec66f918eea21e3e3c95bf3019289ff8fcc0/libs/adcs/experimental/Include/adcs/Detumbling.hpp#L29)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

@zaq32: I don't think those parameters should be in persistent state. They should be send from earth in telecommand which will enable this detumbling mode - and there is no point for wasting persistent (FRAM/FLASH) memory for storing them as this algorithm will be never invoked "by its own". Some parameters are constant (e.g. time step) but rest has to be send in the proper TC.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by pwec** [comment]
just spotted that after unitary test split everything on this PR must be reorganised. After changes review I am confused why adcs is now in other. Anyway I wasted today on trying to make it working but I failed - don't know why h.in mechanism is not properly including files anymore... before I start to reorganise things I need confirmation if all adcs experiments should be placed in unit_tests/others/adcs/experimental/

**Comment by Novakov** [comment]
It's under other because it does not fit elsewhere - you can create seperate executable if you like but, at least for now, it can be under `unit_tests/others/adcs/experimental`

If you have trouble building it's best to ask someone to help :)

---

Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-:-Kj3E7WB7r3S1KHca1ey:b-dv32ig)*

**Comment by pwec** [comment]
@Novakov looks lie it is done, tests are passing

**Comment by zaq32** [comment]
Reviewed 1 of 21 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by ggajoch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/adcs/experimental/Detumbling.cpp, line 59 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-KgvBFwPS4Yce45t5Y5n:-KjUKBZj_eGlZt6ejQJ9:b32w0x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/17c715263706058237de8d3e87db3bbda2929b41/libs/adcs/experimental/Detumbling.cpp#L59)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

redundant parentheses
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by kfazi** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Comment by kfazi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114#-:-KjhMQsRtu5q0WUL3n6A:bnfp4nl)*

**Comment by Novakov** [comment]
Reviewed 7 of 24 files at r7, 2 of 5 files at r8, 10 of 11 files at r9, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/114)*

**Pull request merged**
