### PR TITLE
Reintialize gyroscope if read failed

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/307)

### CODE REVIEW

**Comment by Novakov** [comment]
[Reinitialize gyro if failed to acquire telemetry](https://trello.com/c/PkBOvUkO/269-reinitialize-gyro-if-failed-to-acquire-telemetry)

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/drivers/gyro/gyroTest.cpp, line 257 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/307#-Ku0BHQ5kfutd9_h_NRm:-Ku0BHQ6-WLjvrfF_g9r:b-mf7pl1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/33fc1c3a3bc40fce750aa71446c40e951bed01c7/unit_tests/drivers/gyro/gyroTest.cpp#L257)):*
> ```cpp
>     for (int status = 0; status <= 0xFF; ++status)
>     {
>         ON_CALL(i2c, WriteRead(_addr, ElementsAre(0x1A), SpanOfSize(9))).WillByDefault(Invoke([=](uint8_t, auto, auto read) {
> ```

on_call does not have to be repeated. It sets default behaviour. 
However now driver behaviour is not enforced by the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/307)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[unit_tests/drivers/gyro/gyroTest.cpp, line 257 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/307#-Ku0BHQ5kfutd9_h_NRm:-Ku5FQcEnxdlN9qJsPCI:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/33fc1c3a3bc40fce750aa71446c40e951bed01c7/unit_tests/drivers/gyro/gyroTest.cpp#L257)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

on_call does not have to be repeated. It sets default behaviour. 
However now driver behaviour is not enforced by the test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/307)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/307)*

**Pull request merged**
