### PR TITLE
Message: Resistance is futile

### PR DESCRIPTION
**Pull request by Novakov**
You will be assimilated

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/230)

### CODE REVIEW

**Comment by Novakov** [comment]
[Resistance is futile](https://trello.com/c/x2R3YZS5/215-resistance-is-futile)

**Comment by zaq32** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/mission/comm/comm.cpp, line 116 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230#-KqMMx8XrIGU9UHCaz4I:-KqMMx8Y7iZqO2z3TXZK:b5r4kgt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2094a07319a8abf14bfc4c722a1605052523db95/libs/mission/comm/comm.cpp#L116)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         if (!This->_lastSentAt.HasValue)
>         {
>             return true;
>         }
</details>
>  
you may want to check this before accessing persistent state

---

*[libs/state/comm.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230#-KqMRuIoHB8-KAwwEG5l:-KqMRuIoHB8-KAwwEG5m:b-8pe59j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2094a07319a8abf14bfc4c722a1605052523db95/libs/state/comm.cpp#L14)):*
> ```cpp
>         "technological distinctiveness to our own. Your culture will adapt to service us. Resistance is futile.";
> 
>     MessageState::MessageState() : _interval(5min), _repeatCount(3)
> ```

we would have to think about the frequency 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230)*

**Comment by Novakov** [comment]
Review status: 17 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/mission/comm/comm.cpp, line 116 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230#-KqMMx8XrIGU9UHCaz4I:-KqxRNivv1NOKEfZCGpT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2094a07319a8abf14bfc4c722a1605052523db95/libs/mission/comm/comm.cpp#L116)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         if (!This->_lastSentAt.HasValue)
>         {
>             return true;
>         }
>  
you may want to check this before accessing persistent state
</blockquote></details>

Done.

---

*[libs/state/comm.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230#-KqMRuIoHB8-KAwwEG5l:-KqxWbqaZ6fl5222BXAX:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2094a07319a8abf14bfc4c722a1605052523db95/libs/state/comm.cpp#L14)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

we would have to think about the frequency 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230)*

**Comment by zaq32** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/230)*

**Pull request merged**
