### PR TITLE
Disable EPS overheat submode when opening sail

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/351)

### CODE REVIEW

**Comment by Novakov** [comment]
[[NCR #035] Disable EPS overheat submode when opening sail](https://trello.com/c/963V3b0E/304-ncr-035-disable-eps-overheat-submode-when-opening-sail)

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-Kw8rrTxAyVK3779YGns:-Kw8rrTxAyVK3779YGnt:bxb1noe) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/24cc369ecd6d788df3cb32581affd111bbb8360e/libs/mission/sail/sail.cpp#L10)):*
> ```cpp
> {
>     OpenSailTask::StepProc OpenSailTask::Steps[] = {
>         &IgnoreOverheat,               //
> ```

I believe that overheating submode was supposed to be disabled only in case of Time & emergemcy sail open. Regular opening (i.e. experiment is not supposed to disable this fail safe)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 10 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-Kw8rrTxAyVK3779YGns:-Kw949GFVF6SxBwWry2C:bea5l3i) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/24cc369ecd6d788df3cb32581affd111bbb8360e/libs/mission/sail/sail.cpp#L10)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I believe that overheating submode was supposed to be disabled only in case of Time & emergemcy sail open. Regular opening (i.e. experiment is not supposed to disable this fail safe)
</blockquote></details>

As discussed with @ggajoch it should be ok to disable it every time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by zaq32** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 124 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-KwGMIuTDiCtAtBbn9ID:-KwGMIuTDiCtAtBbn9IE:b-1moum8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed347207abf2ecccc85ec52c412713717aaf1871/libs/mission/sail/sail.cpp#L124)):*
> ```cpp
>                 if (state.Time >= 40 * 24h)
>                 {
>                     open();
> ```

time activation should disable overhead submode

---

*[libs/obc/communication/telecommands/sail.cpp, line 33 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-KwGLgVIFdqPPcC4Giz-:-KwGLgVIFdqPPcC4Giz0:bj7su6y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed347207abf2ecccc85ec52c412713717aaf1871/libs/obc/communication/telecommands/sail.cpp#L33)):*
> ```cpp
> 
>             response.PayloadWriter().WriteByte(0);
>             this->_openSail.OpenSail(true);
> ```

I'd say this should be telecommand argument

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 124 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-KwGMIuTDiCtAtBbn9ID:-KwGfpG3xT_HEuW3DnGz:buum250) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed347207abf2ecccc85ec52c412713717aaf1871/libs/mission/sail/sail.cpp#L124)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

time activation should disable overhead submode
</blockquote></details>

Default mode is to ignore overheat, so it will be ignored on time activation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/sail.cpp, line 33 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351#-KwGLgVIFdqPPcC4Giz-:-KwGofI96ydJ1lZ8yqsQ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ed347207abf2ecccc85ec52c412713717aaf1871/libs/obc/communication/telecommands/sail.cpp#L33)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd say this should be telecommand argument
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/351)*

**Pull request merged**
