### PR TITLE
Added Sun Sensor driver

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/228)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/drivers/suns/suns.cpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq3pawj1R-oGT_B5HKL:-Kq3pawj1R-oGT_B5HKM:b-56va3a) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e9e568493582e22f515648534ff8744719b1933/libs/drivers/suns/suns.cpp#L42)):*
> ```cpp
>             }
> 
>             System::SleepTask(4s);
> ```

suns is using interrupt to signal completed operation.

---

*[unit_tests/base/Include/mock/SunSDriverMock.hpp, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq3oja5uHCuvbvHViy2:-Kq3oja6S8Y7YXCZ4xhf:bb815et) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e9e568493582e22f515648534ff8744719b1933/unit_tests/base/Include/mock/SunSDriverMock.hpp#L8)):*
> SunSDriverMock() = default;
> ~SunSDriverMock() = default;
Define those explicitly to save a bit of linker time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by kfazi** [comment]
Review status: 13 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/suns/suns.cpp, line 42 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq3pawj1R-oGT_B5HKL:-Kq89EKUpz0KmxUyaNsv:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e9e568493582e22f515648534ff8744719b1933/libs/drivers/suns/suns.cpp#L42)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

suns is using interrupt to signal completed operation.
</blockquote></details>

Fixed

---

*[unit_tests/base/Include/mock/SunSDriverMock.hpp, line 8 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq3oja5uHCuvbvHViy2:-Kq89Hv15TGBml1NyjCl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e9e568493582e22f515648534ff8744719b1933/unit_tests/base/Include/mock/SunSDriverMock.hpp#L8)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> SunSDriverMock() = default;
> ~SunSDriverMock() = default;
Define those explicitly to save a bit of linker time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by zaq32** [comment]
Reviewed 17 of 18 files at r2.
Review status: 29 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.cpp, line 109 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq8Ep9OUwSa0A6afbk5:-Kq8Ep9OUwSa0A6afbk6:b-qgjlf8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e2db834a7191013f3f5a7f120d70f985e57da7a7/src/main.cpp#L109)):*
> ```cpp
>         Main.Hardware.PayloadDriver.IRQHandler();
>     }
>     else if (irq & Main.Hardware.SunSInterruptDriver.IRQMask())
> ```

there may be more than one interrupt reported at the same time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by kfazi** [comment]
Review status: 23 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 109 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-Kq8Ep9OUwSa0A6afbk5:-Kq95_i99DvFGXkdHvOy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e2db834a7191013f3f5a7f120d70f985e57da7a7/src/main.cpp#L109)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

there may be more than one interrupt reported at the same time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by begreeen** [comment]
Review status: 23 of 35 files reviewed at latest revision, 6 unresolved discussions.

---

*[integration_tests/system/system.py, line 51 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSThmmFUmN5G9hVe34:-KqSThmmFUmN5G9hVe35:b-7nbk2o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/integration_tests/system/system.py#L51)):*
> ```Python
>         self.i2c.add_pld_device(self.backup_antenna)
>         self.i2c.add_bus_device(self.imtq)
>         self.i2c.add_bus_device(self.suns)
> ```

the SunS is connected to pld i2c bus, so `add_pld_device` should be here

---

*[libs/drivers/suns/suns.cpp, line 85 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSU6N79_snJ7yx7ACL:-KqSU6N79_snJ7yx7ACM:b3jak68) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L85)):*
> ```cpp
>             ErrorReporter errorContext(this->errors);
> 
>             std::array<uint8_t, 536> response;
> ```

why so large array? the SunS has 67 bytes long register array.

---

*[libs/drivers/suns/suns.cpp, line 87 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSUK1q8Dgcw0c9K3B1:-KqSUK1q8Dgcw0c9K3B2:be8yn7t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L87)):*
> ```cpp
>             std::array<uint8_t, 536> response;
> 
>             auto i2cstatusRead = this->i2cbus.Read(I2CAddress, response);
> ```

to read from the SunS you have to write a byte at first - a number of the first byte from the SunS register thet you want to read. Exactly the same as it is done in payload (pld and suns I2C communication use common protocol). In this case you probably want to write just `0` to fetch whole data from sensor. 

---

*[libs/drivers/suns/suns.cpp, line 97 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqS_DVQTjDfuYL-s1JE:-KqS_DVQTjDfuYL-s1JF:b5ftfw4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L97)):*
> ```cpp
>             Reader reader{response};
> 
>             auto opCode = reader.ReadByte();
> ```

to be removed - see below

---

*[libs/drivers/suns/suns.cpp, line 98 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSVKxhL0bpCgdgmuci:-KqSVKxhL0bpCgdgmucj:b30c0vv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L98)):*
> ```cpp
> 
>             auto opCode = reader.ReadByte();
>             if (opCode != 0x80)
> ```

the first byte in the SunS registers is `WhoAmI`, `0x80` byte does not exist.

---

*[libs/obc/hardware/hardware.cpp, line 99 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqS_N0sAsCy-JevRnc-:-KqS_N0tnUyn2kALhwre:bahw307) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/obc/hardware/hardware.cpp#L99)):*
> ```cpp
>       Imtq(errorCounting, I2C.Buses.Bus),                                           //
>       SunSInterruptDriver(this->Pins.SunSInterrupt),                                //
>       SunS(errorCounting, I2C.Buses.Bus, SunSInterruptDriver),                      //
> ```

the SunS uses `I2C.Buses.Payload`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by Novakov** [comment]
Review status: 23 of 35 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[integration_tests/system/system.py, line 51 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSThmmFUmN5G9hVe34:-KqamluyKAnQomY7oopY:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/integration_tests/system/system.py#L51)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

the SunS is connected to pld i2c bus, so `add_pld_device` should be here
</blockquote></details>

Done

---

*[libs/drivers/suns/suns.cpp, line 85 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSU6N79_snJ7yx7ACL:-Kqamb0Bji9PENSRTf_D:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L85)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

why so large array? the SunS has 67 bytes long register array.
</blockquote></details>

Done

---

*[libs/drivers/suns/suns.cpp, line 87 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSUK1q8Dgcw0c9K3B1:-KqamblQFCW_GZdyAuNX:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L87)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

to read from the SunS you have to write a byte at first - a number of the first byte from the SunS register thet you want to read. Exactly the same as it is done in payload (pld and suns I2C communication use common protocol). In this case you probably want to write just `0` to fetch whole data from sensor. 
</blockquote></details>

Done

---

*[libs/drivers/suns/suns.cpp, line 97 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqS_DVQTjDfuYL-s1JE:-KqamhG7qorhpGi75ioy:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L97)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

to be removed - see below
</blockquote></details>

Done

---

*[libs/drivers/suns/suns.cpp, line 98 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqSVKxhL0bpCgdgmuci:-KqamhjYkCKAtCUJAJy4:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/drivers/suns/suns.cpp#L98)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

the first byte in the SunS registers is `WhoAmI`, `0x80` byte does not exist.
</blockquote></details>

Done

---

*[libs/obc/hardware/hardware.cpp, line 99 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228#-KqS_N0sAsCy-JevRnc-:-KqamkopTwjadtI_23Ti:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/02380cc317048323e253a747e49004775224a053/libs/obc/hardware/hardware.cpp#L99)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

the SunS uses `I2C.Buses.Payload`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by Novakov** [comment]
[[Driver] SunSensor eksperymentalny](https://trello.com/c/NwU5atkf/68-driver-sunsensor-eksperymentalny)

**Comment by begreeen** [comment]
Reviewed 1 of 15 files at r5.
Review status: 19 of 40 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by zaq32** [comment]
Reviewed 4 of 12 files at r3, 3 of 6 files at r4, 15 of 15 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/228)*

**Pull request merged**
