### PR TITLE
Update Comm driver to support comm icd issue 1.1

### PR DESCRIPTION
**Pull request by zaq32**
* Update Comm driver to support comm icd issue 1.1,
* Update comm python simulator to more closely resemble actual hardware,
* Break comm header file into several headers dedicated to specific parts of the driver interface,
* Update driver startup routine - from now on just hardware reset instead of hardware + software reset,
* Properly handle frames with invalid state.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/63)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 24 of 28 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 430 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_V9-vUivIRaLs-Akkw:-K_V9-vUivIRaLs-Akkx:bah76j7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4c52585a1735940f1ebf2fb2b31ae46907a860b3/libs/drivers/comm/comm.cpp#L430)):*
> ```cpp
>                     LOG(LOG_LEVEL_ERROR, "[comm] Unable to remove frame from receiver. ");
>                 }
>                 else if (frame.Verify())
> ```

1. Separate single iteration into dedicated function (less nesting, so it will be easier to follow)
2. Removing frame before verifing it can be dangerous - if error is introduced during I2C transfer (as there are no i2c-level error checking) we will lose valid frame. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63)*

**Comment by Novakov** [comment]
[[Driver] Comm driver update](https://trello.com/c/AsCgBIbv/89-driver-comm-driver-update)

**Comment by zaq32** [comment]
Review status: 24 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 430 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_V9-vUivIRaLs-Akkw:-K_ewSr8RK5pvw5SsnfZ:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4c52585a1735940f1ebf2fb2b31ae46907a860b3/libs/drivers/comm/comm.cpp#L430)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

1. Separate single iteration into dedicated function (less nesting, so it will be easier to follow)
2. Removing frame before verifing it can be dangerous - if error is introduced during I2C transfer (as there are no i2c-level error checking) we will lose valid frame. 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63)*

**Comment by zaq32** [comment]
Review status: 27 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 208 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_iFxSP8-qkR9RKIFUx:-K_kT5SVR_o-S2VQP_uX:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dc01010f1af7a3ffc1d4c976321ffa796dfe1e56/libs/drivers/comm/Include/comm/CommDriver.hpp#L208)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 210 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_iFx8dKlhKSiADw88o:-K_kT7JjxtULa0DgBZ2o:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dc01010f1af7a3ffc1d4c976321ffa796dfe1e56/libs/drivers/comm/Include/comm/CommDriver.hpp#L210)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 212 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_iFwqSTH5j_XwV9sgd:-K_kT7qsJxnqTrrCMlyS:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dc01010f1af7a3ffc1d4c976321ffa796dfe1e56/libs/drivers/comm/Include/comm/CommDriver.hpp#L212)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 214 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_iFwVy7O1iqC-R6tJN:-K_kT84KnU-BlwvbJiQG:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dc01010f1af7a3ffc1d4c976321ffa796dfe1e56/libs/drivers/comm/Include/comm/CommDriver.hpp#L214)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 216 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63#-K_iFuFxmtXa-SxyEwDf:-K_kT8LMvYGJcQ6zq8xG:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dc01010f1af7a3ffc1d4c976321ffa796dfe1e56/libs/drivers/comm/Include/comm/CommDriver.hpp#L216)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/63)*

**Pull request merged**
