### PR TITLE
[obc][eps] Reset lcls on obc startup.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/324)

### CODE REVIEW

**Comment by zaq32** [comment]
[[NCR #017] Reset EPS LCL state at boot](https://trello.com/c/KwIU0FKy/289-ncr-017-reset-eps-lcl-state-at-boot)

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_startup.py, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/324#-KuzXD7IcM7Gn1gtGDDV:-KuzXD7IcM7Gn1gtGDDW:b-38188f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c8923fe71dc16f8b617bcbc202d23f69394eebc3/integration_tests/tests/test_startup.py#L33)):*
> ```Python
>     def test_reset_ant_red_lcl(self):
>         self.wait_for_lcl(self.system.eps.ANTennaRed, "ANT Red LCL Should be reset on startup")
> ```

Put all asserts into single test to reduce running time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/324)*

**Comment by zaq32** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_startup.py, line 33 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/324#-KuzXD7IcM7Gn1gtGDDV:-KuzZQ-4dAfprofKthDx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/c8923fe71dc16f8b617bcbc202d23f69394eebc3/integration_tests/tests/test_startup.py#L33)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Put all asserts into single test to reduce running time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/324)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/324)*

**Pull request merged**
