### PR TITLE
SunS Telecommand

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/249)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/communication/telecommands/suns.cpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/249#-KrRDMQ0WuK2qw_8_-0U:-KrRDMQ0WuK2qw_8_-0V:b-tw7ula) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/fdf32b552f3fa708d81898c9c7868715ac5a1090/libs/obc/communication/telecommands/suns.cpp#L37)):*
> ```cpp
>             uint8_t correlationId = reader.ReadByte();
>             uint8_t gain = reader.ReadByte();
>             uint8_t itime = reader.ReadByte();
> ```

verify reader status before proceeding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/249)*

**Comment by zaq32** [comment]
[[TC] get sample from SunS](https://trello.com/c/CXHAqp4g/229-tc-get-sample-from-suns)

**Comment by mandrek44** [comment]
Review status: 7 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/suns.cpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/249#-KrRDMQ0WuK2qw_8_-0U:-KrUYllCt3e91KLZyO4Q:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/fdf32b552f3fa708d81898c9c7868715ac5a1090/libs/obc/communication/telecommands/suns.cpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

verify reader status before proceeding
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/249)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/249)*

**Pull request merged**
