### PR TITLE
Reader & writer signed implementation

### PR DESCRIPTION
**Pull request by ggajoch**
Added implementation for reader & writer to handle 2's complement little endian 16- and 32-bit values.
Added RapidCheck tests for writer -> reader loop.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/72)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/base/reader.cpp, line 64 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNREUtAXDHIT0Ed_J:-KavNREUtAXDHIT0Ed_K:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/reader.cpp#L64)):*
> ```cpp
> int16_t Reader::ReadSignedWordLE()
> {
>     return (int16_t)(this->ReadWordLE());
> ```

use c++ style cast

---

*[libs/base/reader.cpp, line 103 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNU0GoTSLsGmOttuB:-KavNU0GoTSLsGmOttuC:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/reader.cpp#L103)):*
> ```cpp
> int32_t Reader::ReadSignedDoubleWordLE()
> {
>     return (int32_t)(this->ReadDoubleWordLE());
> ```

use c++ style cast

---

*[libs/base/writer.cpp, line 57 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNUU-yLv0cN0KTaZP:-KavNUU-yLv0cN0KTaZQ:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/writer.cpp#L57)):*
> ```cpp
> bool WriterWriteSignedWordLE(Writer* writer, int16_t word)
> {
>     return WriterWriteWordLE(writer, (uint16_t)(word));
> ```

use c++ style cast

---

*[libs/base/writer.cpp, line 79 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNUuxoCroeQATUvk_:-KavNUuxoCroeQATUvka:b-qjbrhz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/writer.cpp#L79)):*
> ```cpp
> bool WriterWriteSignedDoubleWordLE(Writer* writer, int32_t dword)
> {
>     return WriterWriteDoubleWordLE(writer, (uint32_t)(dword));
> ```

use c++ style cast

---

*[libs/base/Include/base/reader.h, line 81 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNXHmeM20Kfjtrqow:-KavNXHmeM20Kfjtrqox:b-ibiqdu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/Include/base/reader.h#L81)):*
> ```objc
>      * @brief Read single 16 bit word with little-endian memory orientation from the buffer,
>      * convert it into signed value and advance the current buffer position to the next unread byte.
>      * Value is read asuuming 2's complement notation.
> ```

as**su**ming

---

*[libs/base/Include/base/reader.h, line 103 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNdwDJr2GhxuU7hnB:-KavNdwDJr2GhxuU7hnC:b-ibiqdu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/Include/base/reader.h#L103)):*
> ```objc
>      * @brief Read single 32 bit word with little-endian memory orientation from the buffer,
>      * convert it into signed value and advance the current buffer position to the next unread byte.
>      * Value is read asuuming 2's complement notation.
> ```

as**su**ming

---

*[unit_tests/base/RapidTest.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavO7lZHh7qpo9ggDqC:-KavO7lZHh7qpo9ggDqD:b-i8xm2x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/unit_tests/base/RapidTest.cpp#L65)):*
> ```cpp
> {
> 	RC_PRE(value.size() > 0u);
> 	std::unique_ptr<uint8_t[]> array(new uint8_t[value.size()]);
> ```

why not simply use local std::vector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by ggajoch** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[libs/base/reader.cpp, line 64 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNREUtAXDHIT0Ed_J:-KavaI2VCncC41qtKIE8:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/reader.cpp#L64)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use c++ style cast
</blockquote></details>

Fix'd

---

*[libs/base/reader.cpp, line 103 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNU0GoTSLsGmOttuB:-KavaTWclpsJDKuOMtre:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/reader.cpp#L103)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use c++ style cast
</blockquote></details>

Fix'd

---

*[libs/base/writer.cpp, line 57 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNUU-yLv0cN0KTaZP:-KavaUjSwYUCaSThiQS5:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/writer.cpp#L57)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use c++ style cast
</blockquote></details>

Fix'd

---

*[libs/base/writer.cpp, line 79 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNUuxoCroeQATUvk_:-KavaVmemkcSPSAh7eJa:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/writer.cpp#L79)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use c++ style cast
</blockquote></details>

Fix'd

---

*[libs/base/Include/base/reader.h, line 81 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNXHmeM20Kfjtrqow:-KavaWsucTF_wB7Cql6w:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/Include/base/reader.h#L81)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

as**su**ming
</blockquote></details>

Fix'd

---

*[libs/base/Include/base/reader.h, line 103 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavNdwDJr2GhxuU7hnB:-KavaXfvTIwl5eJ8CY_K:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/libs/base/Include/base/reader.h#L103)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

as**su**ming
</blockquote></details>

Fix'd

---

*[unit_tests/base/RapidTest.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavO7lZHh7qpo9ggDqC:-KavaZXvJqypBazmqai3:b-886iab) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/unit_tests/base/RapidTest.cpp#L65)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

why not simply use local std::vector?
</blockquote></details>

Fix'd

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by zaq32** [comment]
Reviewed 3 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavO7lZHh7qpo9ggDqC:-KavasuVOy3yG3uJ93WQ:b-p9poot) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/unit_tests/base/RapidTest.cpp#L65)):*
<details><summary><i>Previously, ggajoch (Grzegorz Gajoch) wrote…</i></summary><blockquote>

Fix'd
</blockquote></details>

is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by ggajoch** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 65 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavO7lZHh7qpo9ggDqC:-KavbuUIyePEQ2lgRu7X:b-ntkiss) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7684e9aa23855510eb03257cf27694adf985b116/unit_tests/base/RapidTest.cpp#L65)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

is it?
</blockquote></details>

Oops, did not staged this change. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by zaq32** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 1 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavjwlMdZI7Q2uSP8jP:-KavjwlMdZI7Q2uSP8jQ:b-7pzqrj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dda34e9b7b4b471ecd9a45521543117d4456c44b/unit_tests/base/RapidTest.cpp#L1)):*
> ```cpp
> #include "gtest/gtest.h"
> ```

This file is not included in the test project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by ggajoch** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 1 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KavjwlMdZI7Q2uSP8jP:-KavoUanrWrKnfVSV7GS:b-80vwjs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/dda34e9b7b4b471ecd9a45521543117d4456c44b/unit_tests/base/RapidTest.cpp#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This file is not included in the test project.
</blockquote></details>

It should be now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r4.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by Novakov** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 57 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KaxIbfDIDxlv5aDaZE9:-KaxIbfDIDxlv5aDaZEA:bq9n9d9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77b4279df7d52d463b9dc56eb233884ba361d191/unit_tests/base/RapidTest.cpp#L57)):*
> ```cpp
> }
> 
> RC_GTEST_PROP(WriteReadRapicheck, Array, (std::vector<uint8_t> value))
> ```

There's no need to put `Rapidcheck` in the name of each test ;) It's like putting `GoogleTest` in each test or `Class` in the name of every class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by ggajoch** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/base/RapidTest.cpp, line 57 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72#-KaxIbfDIDxlv5aDaZE9:-KaxPbKvVdMWWBuJ1Z9j:bcd8gdk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/77b4279df7d52d463b9dc56eb233884ba361d191/unit_tests/base/RapidTest.cpp#L57)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

There's no need to put `Rapidcheck` in the name of each test ;) It's like putting `GoogleTest` in each test or `Class` in the name of every class
</blockquote></details>

Should be better now :upside_down_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/72)*

**Pull request merged**
