### PR TITLE
Made CommObject thread-safe

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/255)

### CODE REVIEW

**Comment by zaq32** [comment]
[Make COMM driver thread-safe](https://trello.com/c/4ZqISiMY/222-make-comm-driver-thread-safe)

**Comment by Novakov** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255#-KrVlRlEwX1zTESrTQ7f:-KrVlRlEwX1zTESrTQ7g:b-k38yz9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/06a5163827be5a9e0e444ce889b095454a01e780/libs/drivers/comm/comm.cpp#L66)):*
> ```cpp
>     }
> }
> ```

Have you just created wrapper around RTOS semaphore that adapts it to `UniqueLock`? Why not plain semaphore + `Lock`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Comment by kfazi** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255#-KrVlRlEwX1zTESrTQ7f:-KrVtnqXFVKJaxvPib01:b-lm1ftw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/06a5163827be5a9e0e444ce889b095454a01e780/libs/drivers/comm/comm.cpp#L66)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Have you just created wrapper around RTOS semaphore that adapts it to `UniqueLock`? Why not plain semaphore + `Lock`?
</blockquote></details>

At first I thought there will be more places that need synchronization and implementation persisted. Do you want me to simplify this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Comment by Novakov** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/comm/comm.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255#-KrVlRlEwX1zTESrTQ7f:-KrVuzApECKKTaMxrHx_:bdudyrz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/06a5163827be5a9e0e444ce889b095454a01e780/libs/drivers/comm/comm.cpp#L66)):*
<details><summary><i>Previously, kfazi wrote…</i></summary><blockquote>

At first I thought there will be more places that need synchronization and implementation persisted. Do you want me to simplify this?
</blockquote></details>

Yes, please :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Comment by kfazi** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/comm/comm.cpp, line 66 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255#-KrVlRlEwX1zTESrTQ7f:-KrVwyXxQ4smRc1pLpGl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/06a5163827be5a9e0e444ce889b095454a01e780/libs/drivers/comm/comm.cpp#L66)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Yes, please :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/255)*

**Pull request merged**
