### PR TITLE
Fix boot counter value

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/346)

### CODE REVIEW

**Comment by zaq32** [comment]
[[NCR #028] Boot Counter always 0](https://trello.com/c/UQAF07Ez/298-ncr-028-boot-counter-always-0)

**Comment by Novakov** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/requirements.txt, line 1 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346#-KvlcohZx2vHswuG0NKx:-KvlcohZx2vHswuG0NKy:b-ncoex0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b1f74df1d77115f5d647c9b0121fe6adb1d1c8bb/integration_tests/requirements.txt#L1)):*
> ```
> ipython
> ```

We need to stick to IPython 5 as version 6 requires Python 3 which we don't support

---

*[integration_tests/requirements.txt, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346#-KvldUEoUYc7YuYO1k4B:-KvldUEoUYc7YuYO1k4C:b-ojirpq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b1f74df1d77115f5d647c9b0121fe6adb1d1c8bb/integration_tests/requirements.txt#L14)):*
> matplotlib
What is it for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346)*

**Comment by zaq32** [comment]
Review status: 14 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/requirements.txt, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346#-KvldUEoUYc7YuYO1k4B:-Kvm9QN9qgn4iJCtvO4V:b6yxhy9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5655480fab280cf99ec6639c9ac53f4f5764bd93/integration_tests/requirements.txt#L14)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

> matplotlib
What is it for?
</blockquote></details>

left over from tests.
Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346)*

**Comment by Novakov** [comment]
Reviewed 1 of 4 files at r2.
Review status: 15 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346)*

**Comment by Novakov** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/346)*

**Pull request merged**
