### PR TITLE
Open sail telecommand

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/225)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] Open Sail](https://trello.com/c/fBiLL1iL/203-tc-open-sail)

**Comment by zaq32** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/225)*

**Comment by zaq32** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/225)*

**Comment by zaq32** [comment]
Reviewed 8 of 9 files at r2.
Review status: 16 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/225)*

**Pull request merged**
