### PR TITLE
Timed scrubbing

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/193)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/base/time_counter.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnXsg22wrKev5yhoKAW:-KnXsg22wrKev5yhoKAX:b-aqax1l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85ce158c86ef4c54a95ca783923eba082eca5d36/libs/base/Include/base/time_counter.hpp#L61)):*
> ```cpp
>          * @param param Parameter that will be passed to callback
>          */
>         TimeCounter(CounterAction<Param> action, Param param);
> ```

since you are using template anyway why you are restricting this class to just function pointers? Use function objects instead.

---

*[libs/base/Include/base/time_counter.hpp, line 152 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnXtH6h3MfODGU0y-F0:-KnXtH6iq4uCJrsr1CBP:b-1hmgje) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/85ce158c86ef4c54a95ca783923eba082eca5d36/libs/base/Include/base/time_counter.hpp#L152)):*
> ```cpp
>     template <typename... Counters> std::chrono::milliseconds SleepTime(Counters&... counters)
>     {
>         std::array<std::chrono::milliseconds, sizeof...(Counters)> times{counters.TimeToZero()...};
> ```

verify that array is not empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193)*

**Comment by Novakov** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/time_counter.hpp, line 61 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnXsg22wrKev5yhoKAW:-KnnaZKBwelhgI5uexxG:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/729099f8dbaaa5b096ee2f26e9c0c739b318fc8e/libs/base/Include/base/time_counter.hpp#L61)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since you are using template anyway why you are restricting this class to just function pointers? Use function objects instead.
</blockquote></details>

Done.

---

*[libs/base/Include/base/time_counter.hpp, line 152 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnXtH6h3MfODGU0y-F0:-KnnW_pxQ8UOlwJ7VPRF:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/729099f8dbaaa5b096ee2f26e9c0c739b318fc8e/libs/base/Include/base/time_counter.hpp#L152)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

verify that array is not empty.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/time_counter.hpp, line 90 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnsNgQKjZpeo-YZ0q9N:-KnsNgQKjZpeo-YZ0q9O:b-lnl432) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/412072f07319bf8565c88b3204cb9b4227316e1f/libs/base/Include/base/time_counter.hpp#L90)):*
> _action(nullptr)
This will work as long _action is a pointer or can be initialized by pointer

---

*[libs/base/Include/base/time_counter.hpp, line 96 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnsNowWrdLrdvdLECJi:-KnsNowWrdLrdvdLECJj:bp2z96w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/412072f07319bf8565c88b3204cb9b4227316e1f/libs/base/Include/base/time_counter.hpp#L96)):*
> : _value(StartDelay::value), _action(action), _param(param)

_action(std::move(action)), _param(std::move(param))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/base/Include/base/time_counter.hpp, line 90 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnsNgQKjZpeo-YZ0q9N:-Ko1qqCdYmZCMuoIupsq:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/412072f07319bf8565c88b3204cb9b4227316e1f/libs/base/Include/base/time_counter.hpp#L90)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> _action(nullptr)
This will work as long _action is a pointer or can be initialized by pointer
</blockquote></details>

Done.

---

*[libs/base/Include/base/time_counter.hpp, line 96 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193#-KnsNowWrdLrdvdLECJi:-Ko1qqPI5BL1bobtWRbF:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/412072f07319bf8565c88b3204cb9b4227316e1f/libs/base/Include/base/time_counter.hpp#L96)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> : _value(StartDelay::value), _action(action), _param(param)

_action(std::move(action)), _param(std::move(param))
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/193)*

**Pull request merged**
