### PR TITLE
Redundant fm25w driver

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/155)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 8 of 13 files at r1.
Review status: 8 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155)*

**Comment by mandrek44** [comment]
[[TMR] FRAM](https://trello.com/c/MX5zaKLt/129-tmr-fram)

**Comment by zaq32** [comment]
Review status: 8 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/fm25w/fm25w.cpp, line 73 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-KkesvGnxAh4MXA_T8FV:-KkesvGo4mw943XjQ2I8:b-l6964f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8d351d8374c02eb975a13b13f637a00811d07c43/libs/drivers/fm25w/fm25w.cpp#L73)):*
>  auto status1 = _fm25wDrivers[0]->ReadStatus();
>             auto status2 = _fm25wDrivers[1]->ReadStatus();
>             auto status3 = _fm25wDrivers[2]->ReadStatus();
> 
>             return Vote(status1.Value, status2.Value, status3.Value);
This code ignores the fact that drivers can by itself return "None" value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155)*

**Comment by mandrek44** [comment]
Review status: 8 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/fm25w/fm25w.cpp, line 73 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-KkesvGnxAh4MXA_T8FV:-KkeuV7Nes52vWmz6nMJ:b2nhksp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/8d351d8374c02eb975a13b13f637a00811d07c43/libs/drivers/fm25w/fm25w.cpp#L73)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>  auto status1 = _fm25wDrivers[0]->ReadStatus();
>             auto status2 = _fm25wDrivers[1]->ReadStatus();
>             auto status3 = _fm25wDrivers[2]->ReadStatus();
> 
>             return Vote(status1.Value, status2.Value, status3.Value);
This code ignores the fact that drivers can by itself return "None" value
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155)*

**Comment by zaq32** [comment]
Reviewed 4 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kky_OuQiaOdcTAHV5i9:-Kky_OuQiaOdcTAHV5iA:b-gzf6zp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp#L27)):*
> ```cpp
>          * @param[in] spi Reference to spi bus controller that should be used to access the memory.
>          */
>         PersistentStorageAccess(std::array<drivers::spi::ISPIInterface*, 3> spis);
> ```

update the documentation to match the changes

---

*[src/commands/fram.cpp, line 20 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kky_ssRGfspecQG30_L:-Kky_ssRGfspecQG30_M:bvee1jg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/src/commands/fram.cpp#L20)):*
> if (fram == nullptr)
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     {
>         Main.terminal.Puts("Invalid fram\n");
>         return;
>     }
</details>
Pass argument by reference and drop this condition.

---

*[src/commands/fram.cpp, line 32 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kkya0SmQtLV5nwUDBUw:-Kkya0SmQtLV5nwUDBUx:bozq6do) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/src/commands/fram.cpp#L32)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if (fram == nullptr)
>     {
>         Main.terminal.Puts("Invalid fram\n");
>         return;
>     }
</details>
Pass argument by reference and drop this condition.

---

*[src/commands/fram.cpp, line 44 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kkya1Yb4TVj-M50TlXB:-Kkya1Yb4TVj-M50TlXC:bozq6do) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/src/commands/fram.cpp#L44)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if (fram == nullptr)
>     {
>         Main.terminal.Puts("Invalid fram\n");
>         return;
>     }
</details>
Pass argument by reference and drop this condition.

---

*[src/commands/fram.cpp, line 135 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kkyab-sdngkNGyz4R4Q:-Kkyab-sdngkNGyz4R4R:b-8vbtmg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/src/commands/fram.cpp#L135)):*
>     devices::fm25w::FM25WDriver fram1(spi1);
>     devices::fm25w::FM25WDriver fram2(spi2);
>     devices::fm25w::FM25WDriver fram3(spi3);
Are you sure that independent asynchronous access to spi bus and chip select pins will not cause problems with fram communication?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp, line 27 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155#-Kky_OuQiaOdcTAHV5i9:-Kl5amYWeC5jQWU7BSgc:b-oaq0j4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ad3c30f31ad2a33358b696675bdbb146f6ddd39/libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp#L27)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

update the documentation to match the changes
</blockquote></details>

mismatched parameter name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/155)*

**Pull request merged**
