### PR TITLE
Simple Persistent Monotonic Timer

### PR DESCRIPTION
**Pull request by zaq32**
Add simple persistent monotonic timer with some utilities for time management. The timer here is supposed to measure the mission time with millisecond resolution. The added timer is capable of following:

* Automatically saves its state once every 15 minutes (for now) in three separate files stored on the built in flash memory. 
* Automatically restore its state on startup based on the state from the files stored on built in flash memory.
* Publishing passing time notification once every 5s.
* Capable of providing current mission time in both milliseconds & version decoded into separate milliseconds, seconds, minutes, hours & days.

Additionally there are some utilities for time manipulation.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/31)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 32 of 34 files at r1.
Review status: 32 of 34 files reviewed at latest revision, 7 unresolved discussions.

---

*[integration_tests/tests/test_sail.py, line 8 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRMgyj_6ZXDAYDmcZR:-KPRMgyj_6ZXDAYDmcZS:bnytjqg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/integration_tests/tests/test_sail.py#L8)):*
> ```Python
> class Test_SailTest(BaseTest):
>     def test_pingpong(self):
>         self.system.obc.wait_to_start();
> ```

Change it to decorator (like autoCommHandling)

---

*[libs/time/CMakeLists.txt, line 12 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRjhaJKrDqmsR0ElCW:-KPRjhaJKrDqmsR0ElCX:bz95r63) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/CMakeLists.txt#L12)):*
> ```CMake
> add_library(${NAME} STATIC ${SOURCES})
> 
> target_link_libraries(${NAME} base fs logger)
> ```

Place each library in separate line - it is easier to merge changes later

---

*[libs/time/include/time/TimePoint.h, line 32 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRsZq2FrJpmGNuISc3:-KPRsZq2FrJpmGNuISc4:bemvjgc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/include/time/TimePoint.h#L32)):*
> ```objc
>     uint16_t day;        ///< Number of days.
>     uint16_t milisecond; ///< Number of milliseconds.
> } TimePoint;
> ```

I don't like the idea of non canonical state. It will force to normalize it everytime it's needed. I would prefer API similar to .NET TimeSpan (https://msdn.microsoft.com/en-US/library/system.timespan(v=vs.110).aspx): object is immutable, can be created by factory functions like `FromMinutes`. Modification is done by functions like `AddMinutes`, `AddTimeSpan` and they make sure that `TimePoint` is still valid

---

*[src/main.c, line 116 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPT9-E1ztyjbSPHz-zb:-KPT9-E1ztyjbSPHz-zc:b-v2oefu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/src/main.c#L116)):*
> ```C
>         LOG(LOG_LEVEL_ERROR, "Unable to initialize persistent timer. ");
>     }
> ```

We need to think about seperating initialization to other file(s).  Doesn't need to be done now. Leaving note just to remember

---

*[src/openSail.c, line 63 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPT7gCelhTlsfrwwqCQ:-KPT7gCelhTlsfrwwqCR:b7oel18) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/src/openSail.c#L63)):*
> ```C
>     if (span >= SAILOPENTIME)
>     {
>         if (System.GiveSemaphore(sailContext->SemaphoreHandle) != OSResultSuccess)
> ```

I don't like idea of callbacks here. This code will execute in context of other task and, for me, it's not necessary complication - it should be enough to give semaphore to release or event bit.

---

*[unit_tests/mock/FsMock.hpp, line 1 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPTB-QPjaDFjWJC3Ypo:-KPTB-QPjaDFjWJC3Ypp:br2wsvq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/unit_tests/mock/FsMock.hpp#L1)):*
> ```cpp
> #ifndef MOCK_FS_HPP
> ```

It would be nicer to have more *intelligent* FS mock that will mimic real file system. It could be dead-simple like array with file name and buffer so it test it will be possible to assert file contents without mocking individual file system functions

---

*[unit_tests/time/time.cpp, line 55 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPTB_5KIdi_djsSmAjf:-KPTB_5LczunnmVHZj_-:b5af4wu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/unit_tests/time/time.cpp#L55)):*
> ```cpp
>     ASSERT_FALSE(TimePointEqual(TimePointBuild(4501, 80, 200, 150, 12548), TimePointBuild(4501, 80, 202, 150, 12548)));
>     ASSERT_FALSE(TimePointEqual(TimePointBuild(4501, 80, 200, 150, 12548), TimePointBuild(4501, 83, 200, 150, 12548)));
>     ASSERT_FALSE(TimePointEqual(TimePointBuild(4501, 80, 200, 150, 12548), TimePointBuild(4504, 80, 200, 150, 12548)));
> ```

Maybe contraints for TimePoints allowing to write `ASSERT_THAT(TimePointBuild(...), EqTimePoint(...))`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 2 of 34 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[libs/time/timer.c, line 9 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYB7nMUguwgSp2yVmr:-KPYB7nMUguwgSp2yVms:b-hx9axl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L9)):*
> ```C
> static const char* const TimeFile0 = "TimeState.0";
> static const char* const TimeFile1 = "TimeState.1";
> static const char* const TimeFile2 = "TimeState.2";
> ```

Use full path: `/TimeState.0`

---

*[libs/time/timer.c, line 237 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYixNvNRHFKq7sBsX6:-KPYixNwxy4rsckarizx:b-61nu4o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L237)):*
> ```C
>     if (result.saveTime)
>     {
>         timeProvider->PersistanceTime = 0;
> ```

Should be PersistanceTime be cleared after saving it? The same question applies to NotificationTime

---

*[libs/time/timer.c, line 282 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYjNLZfI4Z6nnUxYOY:-KPYjNLZfI4Z6nnUxYOZ:brm8sss) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L282)):*
> ```C
>     if (!ReaderStatus(&reader))
>     {
>         LOGF(LOG_LEVEL_WARNING, "Not enough date read from file: %s. Length: 0x%08x", filePath, read);
> ```

dat**e** -> dat**a**

---

*[libs/time/timer.c, line 303 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYnupSfdHteDXsiJJB:-KPYnupSfdHteDXsiJJC:b-ntzpfs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L303)):*
> ```C
> 
>     // every value has one initial copy (its own).
>     int counters[3] = {1, 1, 1};
> ```

Maybe `votes` will be a better name?

---

*[libs/time/timer.c, line 336 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYkJxza1FguGXM88I_:-KPYkJy-kG9CSjH_ZJew:bazzslk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L336)):*
> ```C
>     {
>         selectedIndex = 2;
>     }
> ```

Move it to some helper function that returns index of max value

---

*[libs/time/timer.c, line 382 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYjsGpg9lOsUosU-3F:-KPYjsGpg9lOsUosU-3G:b-vuj8bf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L382)):*
> ```C
> 
>     fs->close(handle);
> }
> ```

`SaveToFile` & `ReadToFile` look like nice helper functions for FileSystem. It would be nice to move them to fs library

---

*[libs/time/timer.c, line 410 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYpvIZi-21hMGdMPEe:-KPYpvIZi-21hMGdMPEf:b9zmf5u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L410)):*
> ```C
>         SaveToFile(timeProvider->FileSystemObject, TimeFile1, buffer, length);
>         SaveToFile(timeProvider->FileSystemObject, TimeFile2, buffer, length);
>     }
> ```

Error while saving time requires at least some attention at this level. Even flag `timeSaved` here will be better. Now any errors are visible only in logs.

---

*[libs/time/include/time/timer.h, line 64 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYqNcCz2f_04l6vNCo:-KPYqNcCz2f_04l6vNCp:byjqdzz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/include/time/timer.h#L64)):*
> ```objc
>  * likely correct value. In case when all of the values are different the smallest one is selected as the correct one.
>  */
> struct TimeProvider
> ```

Why without `typedef`?

---

*[libs/time/include/time/timer.h, line 158 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYqWzlWhW7Rei38jz5:-KPYqWzlWhW7Rei38jz6:b-l0ak8b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/include/time/timer.h#L158)):*
> ```objc
>  * @brief This procedure can be used to move timer state forward by specified amount.
>  *
>  * Be aware that moving time forward far enough far enough may trigger timer notification &
> ```

(far enough)*2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by zaq32** [comment]
Review status: 18 of 39 files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/time/include/time/TimePoint.h, line 32 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRsZq2FrJpmGNuISc3:-KPcTGK99v376XXptqvF:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/include/time/TimePoint.h#L32)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> I don't like the idea of non canonical state. It will force to normalize it everytime it's needed. I would prefer API similar to .NET TimeSpan (https://msdn.microsoft.com/en-US/library/system.timespan(v=vs.110).aspx): object is immutable, can be created by factory functions like `FromMinutes`. Modification is done by functions like `AddMinutes`, `AddTimeSpan` and they make sure that `TimePoint` is still valid
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 8 of 20 files at r2.
Review status: 26 of 39 files reviewed at latest revision, 10 unresolved discussions.

---

*[libs/time/include/time/TimePoint.h, line 32 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRsZq2FrJpmGNuISc3:-KPcTMYthx95XYteqmq1:b2nhksp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/include/time/TimePoint.h#L32)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Fixed
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by zaq32** [comment]
Review status: 25 of 39 files reviewed at latest revision, 8 unresolved discussions.

---

*[integration_tests/tests/test_sail.py, line 8 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRMgyj_6ZXDAYDmcZR:-KPcUIC7RAoxGLutYWTx:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/integration_tests/tests/test_sail.py#L8)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Change it to decorator (like autoCommHandling)
</details>
Fixed

---

*[libs/time/CMakeLists.txt, line 12 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRjhaJKrDqmsR0ElCW:-KPcUJnNkFRZhhcA0alS:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/CMakeLists.txt#L12)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Place each library in separate line - it is easier to merge changes later
</details>
Fixed

---

*[libs/time/timer.c, line 237 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYixNvNRHFKq7sBsX6:-KPcTyr8hZJIqnN_m6Zv:b-sw61xl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L237)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Should be PersistanceTime be cleared after saving it? The same question applies to NotificationTime
</details>
Unfortunately it is not that simple.  In order to do it this way Ii would have to acquire two semaphores:
* one for notification
* one for timer state

which would be dangerous in this case.

---

*[libs/time/timer.c, line 303 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYnupSfdHteDXsiJJB:-KPcUMsidrFkqHIfGwfP:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L303)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Maybe `votes` will be a better name?
</details>
Fixed

---

*[libs/time/timer.c, line 382 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYjsGpg9lOsUosU-3F:-KPcTpl07Q_yrLsdUhtV:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L382)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> `SaveToFile` & `ReadToFile` look like nice helper functions for FileSystem. It would be nice to move them to fs library
</details>
Fixed

---

*[unit_tests/mock/FsMock.hpp, line 1 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPTB-QPjaDFjWJC3Ypo:-KPcVOnNUfVPH6qShE9X:bsufdr7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/unit_tests/mock/FsMock.hpp#L1)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> It would be nicer to have more *intelligent* FS mock that will mimic real file system. It could be dead-simple like array with file name and buffer so it test it will be possible to assert file contents without mocking individual file system functions
</details>
Moved to separate task: https://trello.com/c/EHBre8Ci/73-ut-prepare-inteligent-file-system-mock

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 13 of 20 files at r2.
Review status: 38 of 39 files reviewed at latest revision, 5 unresolved discussions.

---

*[integration_tests/tests/test_sail.py, line 8 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRMgyj_6ZXDAYDmcZR:-KPcWHTzr24cUvtUOBZY:bfiqlb6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/integration_tests/tests/test_sail.py#L8)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> Fixed
</details>
Not fixed

---

*[libs/fs/Include/fs/fs.h, line 114 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPcU70SmFLZq83mwcu1:-KPcU70SmFLZq83mwcu2:b48md44) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/270fbc7a624ce305c54b6b8d70211df41f5c555b/libs/fs/Include/fs/fs.h#L114)):*
> writing serialized state

Copy-paste?

---

*[libs/time/timer.c, line 9 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYB7nMUguwgSp2yVmr:-KPcUgXu2hcK49Cz5G3F:b32w0x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L9)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Use full path: `/TimeState.0`
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 1 of 34 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by zaq32** [comment]
Review status: 37 of 40 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration_tests/tests/test_sail.py, line 8 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRMgyj_6ZXDAYDmcZR:-KPc_rJgAxC0CFKTiJSG:b-3hg0q4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/integration_tests/tests/test_sail.py#L8)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Not fixed
</details>
try now 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_sail.py, line 8 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPRMgyj_6ZXDAYDmcZR:-KPcaCn7URi_cxnMOqsR:b2nhksp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/integration_tests/tests/test_sail.py#L8)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary>
> try now 
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by zaq32** [comment]
Review status: 37 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/fs/Include/fs/fs.h, line 114 \[r2\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPcU70SmFLZq83mwcu1:-KPxM2dy7-jKXTR3HnGd:bt2vr1b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/270fbc7a624ce305c54b6b8d70211df41f5c555b/libs/fs/Include/fs/fs.h#L114)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> > writing serialized state
> 
> Copy-paste?
</details>
Fixed.

---

*[libs/time/timer.c, line 410 \[r1\]](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31#-KPYpvIZi-21hMGdMPEe:-KPxM4vDxtd2AwhG9YSO:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a71b42e9e723ced0de35d8734bff6141386fbb49/libs/time/timer.c#L410)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary>
> Error while saving time requires at least some attention at this level. Even flag `timeSaved` here will be better. Now any errors are visible only in logs.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/31)*

**Comment by Novakov** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OzyuXbqF&#x2F;34-time-some-abstraction-of-time"> [Time] Some abstraction of time</a>

**Pull request merged**
