### PR TITLE
Telecomm stop sail

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/301)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 14 of 22 files at r1.
Review status: 14 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/tests/test_telecommands_sail.py, line 58 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtSLcDZzorUn0Gidj1m:-KtSLcD_FjbPteFhySlq:b-a7vs24) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/52e776ca98a2ad859b0f24474098cd22c8097816/integration_tests/tests/test_telecommands_sail.py#L58)):*
> ```Python
>         self.assertIsInstance(frame, SailSuccessFrame)
> 
>         self.assertFalse(sail_opening.wait_for_change(5), "Sail deployment should not be performed")
> ```

Opening sail after automatic sail opening has been disabled should reenable it again.

---

*[libs/state/Include/state/sail/SailState.hpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtSM2x39ti5aW_oyibc:-KtSM2x39ti5aW_oyibd:b6mc8xy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/52e776ca98a2ad859b0f24474098cd22c8097816/libs/state/Include/state/sail/SailState.hpp#L50)):*
> ```cpp
>          * @return True if sail deployment process is disabled, false otherwise.
>          */
>         bool IsDeploymentDisabled() const;
> ```

My initial idea was to use `CurrentState` to disable sail deployment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by kfazi** [comment]
[[TC] Stop sail deployment](https://trello.com/c/6B0wW25t/263-tc-stop-sail-deployment)

**Comment by kfazi** [comment]
Review status: 13 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/tests/test_telecommands_sail.py, line 58 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtSLcDZzorUn0Gidj1m:-KtSrltfzQqyZsH8KMXl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/52e776ca98a2ad859b0f24474098cd22c8097816/integration_tests/tests/test_telecommands_sail.py#L58)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Opening sail after automatic sail opening has been disabled should reenable it again.
</blockquote></details>

Done.

---

*[libs/state/Include/state/sail/SailState.hpp, line 50 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtSM2x39ti5aW_oyibc:-KtSrYJs0eSiO5QjikYy:b-ca5okh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/52e776ca98a2ad859b0f24474098cd22c8097816/libs/state/Include/state/sail/SailState.hpp#L50)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

My initial idea was to use `CurrentState` to disable sail deployment
</blockquote></details>

Good point. I've removed isDisabled flag and added disabled state

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by zaq32** [comment]
Reviewed 13 of 22 files at r1, 2 of 2 files at r3.
Review status: 15 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 266 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtW-ZtcTuTooUh49UxN:-KtW-ZtcTuTooUh49UxO:b-bcc5y9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef843111be0212d8bad0d3d462dab3e5b95816d5/libs/mission/sail/sail.cpp#L266)):*
> ```cpp
>     {
>         state::SailState sailState;
>         if (!state.PersistentState.Get(sailState))
> ```

what is the purpose of accessing previous sail state here?

---

*[libs/obc/communication/telecommands/sail.cpp, line 47 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtW-08tZC2Gym3ybARU:-KtW-08tZC2Gym3ybARV:bcvnvxg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef843111be0212d8bad0d3d462dab3e5b95816d5/libs/obc/communication/telecommands/sail.cpp#L47)):*
> ```cpp
>             Reader r(parameters);
> 
>             auto correlationId = r.ReadByte();
> ```

is correlation id really needed here as there response has its own unique apid anyway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by kfazi** [comment]
Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/mission/sail/sail.cpp, line 266 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtW-ZtcTuTooUh49UxN:-KtWPJI5hSDs78zrTWw0:b13bpj0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef843111be0212d8bad0d3d462dab3e5b95816d5/libs/mission/sail/sail.cpp#L266)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the purpose of accessing previous sail state here?
</blockquote></details>

None ;) I missed it during one of the refactors. Removed.

---

*[libs/obc/communication/telecommands/sail.cpp, line 47 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtW-08tZC2Gym3ybARU:-KtWOj-iv1mzoZH9IL_Q:bg082xs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/ef843111be0212d8bad0d3d462dab3e5b95816d5/libs/obc/communication/telecommands/sail.cpp#L47)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

is correlation id really needed here as there response has its own unique apid anyway?
</blockquote></details>

It's not really needed, but we might want to be able to distinguish calls of the same command (eg. we didn't received response on time and resent the command).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by Novakov** [comment]
Reviewed 2 of 22 files at r1, 1 of 6 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by zaq32** [comment]
Reviewed 3 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[libs/obc/communication/telecommands/sail.cpp, line 59 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtlgqV0aIc6dRd38Q2f:-KtlgqV0aIc6dRd38Q2g:b-48r3jw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/92a4d7878958c1bff50cd530173070cac1cf7207/libs/obc/communication/telecommands/sail.cpp#L59)):*
> ```cpp
>             }
> 
>             this->disableSailDeployment.DisableDeployment();
> ```

Persistent state is internally synchronized. is there a reason to modifying it indirectly via mission task instead of directly from here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by zaq32** [comment]
Reviewed 1 of 6 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by zaq32** [comment]
Reviewed 9 of 17 files at r6.
Review status: 13 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by kfazi** [comment]
Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/obc/communication/telecommands/sail.cpp, line 59 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301#-KtlgqV0aIc6dRd38Q2f:-KvTpNcm1P7mUi9wpnOk:b-3vzf48) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/92a4d7878958c1bff50cd530173070cac1cf7207/libs/obc/communication/telecommands/sail.cpp#L59)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Persistent state is internally synchronized. is there a reason to modifying it indirectly via mission task instead of directly from here?
</blockquote></details>

You are right. I based my code on disable antenna deploy telecommand, which must have been implemented before persistent got it's internal synchronization. I simplified my implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Comment by zaq32** [comment]
Reviewed 6 of 10 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/301)*

**Pull request merged**
