### PR TITLE
Power cycle on error limit

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/221)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toolchain.cmake, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221#-KppS-HOB1fA__OA9iVt:-KppS-HP67NUwZ52lp_V:beajpu4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/fb1f622bd4a3893e2fcac4132f85b85fe08dd289/toolchain.cmake#L37)):*
> ```CMake
> set(CMAKE_EXECUTABLE_FORMAT ELF)
> 
> if(${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles")
> ```

I am also using "Unix Makefiles"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toolchain.cmake, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221#-KppS-HOB1fA__OA9iVt:-KppZ9i4loabXk9FYvL_:b-80g1yn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/fb1f622bd4a3893e2fcac4132f85b85fe08dd289/toolchain.cmake#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I am also using "Unix Makefiles"
</blockquote></details>

And it will (should?) work. MinGW Makefiles looks for `mingw32-make.exe` as make program however our toolchain contains `make.exe`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/221)*

**Pull request merged**
