### PR TITLE
[telemetry] Query telemetry once every 30s and save it once every 5 minutes.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/175)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/mission/telemetry/telemetry.cpp, line 35 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175#-KmLUC6GZdBOt8lVM3qB:-KmLUC6GZdBOt8lVM3qC:b-p7hful) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebc2c07e5b5e0c00727653646bfc26f9c8d2e4c/libs/mission/telemetry/telemetry.cpp#L35)):*
> ```cpp
>         }
> 
>         return state.telemetry.IsModified() && This->delay++ == 0;
> ```

Just to confirm: telemetry will be saved after `This->frequency` mission iterations with modified telemetry? 

Also: It would be more readable if this will be splited into few `if`s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175)*

**Comment by zaq32** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/mission/telemetry/telemetry.cpp, line 35 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175#-KmLUC6GZdBOt8lVM3qB:-KmLvNQtnTmZCU9M3CQ6:buk1g3f) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebc2c07e5b5e0c00727653646bfc26f9c8d2e4c/libs/mission/telemetry/telemetry.cpp#L35)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Just to confirm: telemetry will be saved after `This->frequency` mission iterations with modified telemetry? 

Also: It would be more readable if this will be splited into few `if`s
</blockquote></details>

Right, it was supposed to be save telemetry once every N iterations if the telemetry has been changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/mission/telemetry/telemetry.cpp, line 35 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175#-KmLUC6GZdBOt8lVM3qB:-KmLw420gXXYTOT99k5H:b-ubaqrq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/7ebc2c07e5b5e0c00727653646bfc26f9c8d2e4c/libs/mission/telemetry/telemetry.cpp#L35)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Right, it was supposed to be save telemetry once every N iterations if the telemetry has been changed.
</blockquote></details>

1) spliting this condition into separate ifs will improve readibility
2) Changing state of task inside condition is a bad idea - move incrementing to update phase as it can be called only one during mission loop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/175)*

**Pull request merged**
