### PR TITLE
Bootloader update

### PR DESCRIPTION
**Pull request by Novakov**
* Store boot loader settings in FRAM
* TMR boot by default
* Two sets of slots: primary and failsafe
* Watchdog guarding boot process
* Fallback to failsafe slots if boot failed
* Boot table clean-up

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/171)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Bootloader] [Update] Zaimplementować logikę updatu softu + configa bootloadera + przywracanie](https://trello.com/c/nvuHE28R/176-bootloader-update-zaimplementowa%C4%87-logik%C4%99-updatu-softu--configa-bootloadera--przywracanie)

**Comment by zaq32** [comment]
Reviewed 49 of 53 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[boot/boot.cpp, line 266 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAUO6tI3dn-mNNzgoZ:-KmAUO6uDsh4QdeOel7L:b-hjqhwp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/boot.cpp#L266)):*
> ```cpp
>         BootToAddress(BOOT_APPLICATION_BASE);
>     }
>     else if (!IsBootSlotsValid(slotsMask))
> ```

Am I correct in assuming that obc will be launched with all six slots having a copy of the initial software? 

---

*[boot/xmodem.cpp, line 209 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAOpc7noqgU01RtByJ:-KmAOpc7noqgU01RtByK:b-3hga6y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/xmodem.cpp#L209)):*
> ```cpp
>             //                data = pkt->data[i];
>             //                lld_ProgramOp(base, (offset + i), data);
>             //            }
> ```

If this block is not needed remove it.

---

*[boot/commands/upload.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmBjlL24bR1kRFcQ6a-:-KmBjlL24bR1kRFcQ6a0:b-dr6go8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/commands/upload.cpp#L13)):*
> ```cpp
> 
>     // get boot index
>     auto index = USART_Rx(BSP_UART_DEBUG);
> ```

Shouldn't this function use character as boot index instead of raw byte just like the ReadBootIndex() function?

---

*[doc/boot_table.pdn, line 0 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAQ3aY0OGBJ4zT9Qdt:-KmAQ3aY0OGBJ4zT9Qdu:b-kwoddy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/doc/boot_table.pdn#L0)):*
what is the purpose of this file?

---

*[libs/boot_settings/settings.cpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAR0PgjXBYyNKIiym3:-KmAR0PgjXBYyNKIiym4:b1havlv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/settings.cpp#L15)):*
> ```cpp
>     }
> 
>     bool BootSettings::CheckMagicNumber() const
> ```

I'd suggest keeping all the offsets in one place so they can be easily tracked. And initialize them in such way that the subsequent fields will never overlap.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARaC9BtNj52BqK-4B:-KmARaCAF6QcIKF027oW:b-u6r5eq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L17)):*
> ```cpp
>      * @ingroup boot_settings
>      */
>     class BootSettings final
> ```

Add possibility to erase all settings.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 63 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARSNCTcl5qKvTqAp-:-KmARSNCTcl5qKvTqAp0:b-218zv4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L63)):*
> ```cpp
>          * @return Boot counter value
>          */
>         std::uint16_t BootCounter() const;
> ```

16bit boot counter may not be enough

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmARz_ssUx9sN7ItGvK:bbn5o9t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
> ```cpp
>          * @return Operation result
>          */
>         bool UnconfirmLastBoot();
> ```

This will work but it will not give us information how many times boot process has failed. How about storing the  boot counter of last successful boot process.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[boot/boot.cpp, line 266 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAUO6tI3dn-mNNzgoZ:-KmBl07ypqpvI3n7lDxY:bze4b9i) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/boot.cpp#L266)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Am I correct in assuming that obc will be launched with all six slots having a copy of the initial software? 
</blockquote></details>

It's reasonable approach

---

*[doc/boot_table.pdn, line  at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAQ3aY0OGBJ4zT9Qdt:-KmBkb4zKm2-HaB1Kvwh:b-l7zjgj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/doc/boot_table.pdn#L)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the purpose of this file?
</blockquote></details>

It's Paint.NET file with boot table layout

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmBkpbYHNyHwq-ymv5Q:b-2qhoa7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This will work but it will not give us information how many times boot process has failed. How about storing the  boot counter of last successful boot process.
</blockquote></details>

The main purpose is to check if last boot was successful or not and bootloader should fallback to previous set of boot slots

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[doc/boot_table.pdn, line  at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAQ3aY0OGBJ4zT9Qdt:-KmBmOJxK3hHn3xHRPi7:b-othi80) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/doc/boot_table.pdn#L)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's Paint.NET file with boot table layout
</blockquote></details>

I know that, but we also have a png version of the boot table layout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmBmadweq0KYCJPisuF:b2abj6z) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

The main purpose is to check if last boot was successful or not and bootloader should fallback to previous set of boot slots
</blockquote></details>

So one failed attempt at boot will cause boot loader to load old application version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[doc/boot_table.pdn, line  at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAQ3aY0OGBJ4zT9Qdt:-KmBn6vWi9YOd9KWePit:b-4r0368) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/doc/boot_table.pdn#L)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I know that, but we also have a png version of the boot table layout.
</blockquote></details>

PNG is included in Doxygen (raw pdn can't), this file is in repo in case we will be updating boot table layout - it's easier to edit PDN than PNG ;)

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmBnN84SwlavE5e0hMD:b-7g7nm2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

So one failed attempt at boot will cause boot loader to load old application version?
</blockquote></details>

yes, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmBng1CH-0Mavr1HPq9:bsgob7p) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

yes, 
</blockquote></details>

this will make next to impossible to reliably upload the application. as one unlucky startup will cause boot loader to switch banks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 93 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARz_ssUx9sN7ItGvJ:-KmBsSCG2ZVKsu4qwDOK:bb1ooal) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L93)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this will make next to impossible to reliably upload the application. as one unlucky startup will cause boot loader to switch banks
</blockquote></details>

Only slots will be switched, so next try will require just changing selected boot slots - no need to upload whole application again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[boot/xmodem.cpp, line 209 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAOpc7noqgU01RtByJ:-KmCb5wSpXdd1Kc73tdI:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/xmodem.cpp#L209)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

If this block is not needed remove it.
</blockquote></details>

Done.

---

*[boot/commands/upload.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmBjlL24bR1kRFcQ6a-:-KmCcLqplMU8I2iIZ5In:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/boot/commands/upload.cpp#L13)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Shouldn't this function use character as boot index instead of raw byte just like the ReadBootIndex() function?
</blockquote></details>

Done.

---

*[libs/boot_settings/settings.cpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmAR0PgjXBYyNKIiym3:-KmCpKofeweKxLJvNT6L:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/settings.cpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I'd suggest keeping all the offsets in one place so they can be easily tracked. And initialize them in such way that the subsequent fields will never overlap.
</blockquote></details>

Done.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARaC9BtNj52BqK-4B:-KmD1Dh1S-ZkDOzeY7Q3:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L17)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Add possibility to erase all settings.
</blockquote></details>

Done.

---

*[libs/boot_settings/Include/boot/settings.hpp, line 63 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171#-KmARSNCTcl5qKvTqAp-:-KmD2t_M0qDkN1R387d-:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f6e5ca90f25f2518481d120ed1bfda09d26dbb6c/libs/boot_settings/Include/boot/settings.hpp#L63)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

16bit boot counter may not be enough
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/171)*

**Pull request merged**
