### PR TITLE
Add command to request immediate beacon retransmission

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/194)

### CODE REVIEW

**Comment by zaq32** [comment]
[[TC] Send beacon immediately](https://trello.com/c/Nbt49FKi/178-tc-send-beacon-immediately)

**Comment by Novakov** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/communication/Telecommands/EnterIdleStateTelecommandTest.cpp, line 51 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/194#-KnGBlq6BS8cPl79fxdH:-KnGBlq7OSx-gL8y_l5c:bxglbv3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/2a09e671ffb73ed5d17ee7570a7e7ddd269569b0/unit_tests/communication/Telecommands/EnterIdleStateTelecommandTest.cpp#L51)):*
> ```cpp
>     TEST_F(EnterIdleStateTelecommandTest, ShouldSetIdleState)
>     {
>         System::Yield(); // TODO find out what's going on
> ```

what? yielding in unit tests does not make sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/194)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/194)*

**Comment by Novakov** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/194)*

**Pull request merged**
