### PR TITLE
Safe mode scrubbing

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/315)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Safe Mode] Scrubbing](https://trello.com/c/4FNFCDAo/275-safe-mode-scrubbing)

**Comment by Novakov** [comment]
[[Safe Mode] Reboot on interrupt](https://trello.com/c/9i1nzmYZ/276-safe-mode-reboot-on-interrupt)

**Comment by zaq32** [comment]
Reviewed 22 of 22 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[libs/drivers/program_flash/Include/program_flash/boot_table.hpp, line 240 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315#-Ku_AvErjdfQsOLnA1yR:-Ku_AvErjdfQsOLnA1yS:b5nymrh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eda29f714a88ca67910a0e0c02322570ef45f0b5/libs/drivers/program_flash/Include/program_flash/boot_table.hpp#L240)):*
> ```cpp
>          * @param index Safe mode copy index
>          */
>         SafeModeCopy(IFlashDriver& flash, std::uint8_t index) : _copy(flash, 3_MB + 5 * 64_KB + 64_KB * index)
> ```

This value should be related to the BootloaderCopies constant in the BootTable type.

---

*[libs/obc/scrubbing/scrubbing.cpp, line 64 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315#-Ku_6e2PX7kkUllnt1KJ:-Ku_6e2QvSORRTrZr_rl:b-hlnba9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eda29f714a88ca67910a0e0c02322570ef45f0b5/libs/obc/scrubbing/scrubbing.cpp#L64)):*
> ```cpp
>                 This->_secondarySlotsScrubberCounter,
>                 This->_bootloaderScrubberCounter,
>                 This->_bootSettingsScrubberCounter);
> ```

shouldn't safe mode scrubbing be included in here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315)*

**Comment by Novakov** [comment]
Review status: 24 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/program_flash/Include/program_flash/boot_table.hpp, line 240 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315#-Ku_AvErjdfQsOLnA1yR:-Kuf3WXBj0RBwELuQwWg:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eda29f714a88ca67910a0e0c02322570ef45f0b5/libs/drivers/program_flash/Include/program_flash/boot_table.hpp#L240)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This value should be related to the BootloaderCopies constant in the BootTable type.
</blockquote></details>

Done.

---

*[libs/obc/scrubbing/scrubbing.cpp, line 64 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315#-Ku_6e2PX7kkUllnt1KJ:-Kuf3W-Rkrgf0dHCw8x7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/eda29f714a88ca67910a0e0c02322570ef45f0b5/libs/obc/scrubbing/scrubbing.cpp#L64)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

shouldn't safe mode scrubbing be included in here too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/315)*

**Pull request merged**
