### PR TITLE
[TeleComm] Added SetTimeCorrectionConfig telecommand

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/165)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 17 of 21 files at r1.
Review status: 17 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 2 of 21 files at r1, 4 of 7 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[libs/base/os_base.cpp, line 31 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmczEo_8PIzkCs-g3M:-KlmczEo_8PIzkCs-g3N:b-aoc962) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L31)):*
>     System::GiveSemaphore(resourceSemaphore);
>     System::GiveSemaphore(readCountSemaphore);
>     System::GiveSemaphore(serviceSemaphore);
Unhandled error conditions

---

*[libs/base/os_base.cpp, line 41 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmePJC3vGMCVvVjLuJ:-KlmePJC3vGMCVvVjLuK:b-675900) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L41)):*
> ```cpp
>     }
> 
>     if (!OS_RESULT_SUCCEEDED(System::TakeSemaphore(readCountSemaphore, InfiniteTimeout)))
> ```

what is the exact purpose of this semaphore? As I see it it does not protect anything 

---

*[libs/base/os_base.cpp, line 87 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdwB3Af-zWlmA2saK:-KlmdwB3Af-zWlmA2saL:b-lhandq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L87)):*
> ```cpp
> bool ReaderWriterLock::ReleaseReaderLock()
> {
>     if (readCount == 0)
> ```

data race

---

*[libs/base/os_base.cpp, line 121 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmd7iyOFf4LLSvjQc5:-Klmd7iyOFf4LLSvjQc6:b-lhandq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L121)):*
> ```cpp
> bool ReaderWriterLock::IsReaderLockAcquired() const
> {
>     return readCount > 0;
> ```

data race

---

*[libs/base/os_base.cpp, line 126 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmd9S7MxWXCBZIgb-x:-Klmd9S7MxWXCBZIgb-y:b-lhandq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L126)):*
> ```cpp
> bool ReaderWriterLock::IsWriterLockAcquired() const
> {
>     return isWriterLockAcquired;
> ```

data race

---

*[libs/base/os_base.cpp, line 144 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmeax691KUkoSt_8ia:-Klmeax691KUkoSt_8ib:b-6ecrdh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L144)):*
> ```cpp
> }
> 
> bool ReaderLock::operator()()
> ```

this function should be defined inline

---

*[libs/base/os_base.cpp, line 164 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmefL9rlQJSKtoknlX:-KlmefL9rlQJSKtoknlY:b-6ecrdh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L164)):*
> ```cpp
> }
> 
> bool WriterLock::operator()()
> ```

this function should be defined inline

---

*[libs/base/Include/base/os.h, line 582 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmfW8jrpfPywRmQh3r:-KlmfW8jrpfPywRmQh3s:b-s3jzr1) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L582)):*
> ```objc
>  * @brief Reader-Writer lock state.
>  */
> struct ReaderWriterLock final : private NotCopyable, private NotMoveable
> ```

This implementation puts writers in huge disadvantage and bears a very big risk of writer starvation

---

*[libs/base/Include/base/os.h, line 593 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdGQwVqmzB1_TjbiE:-KlmdGQwVqmzB1_TjbiF:b-v52qmf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L593)):*
> ```objc
>      * @brief Acquires reader lock
>      */
>     bool AcquireReaderLock();
> ```

This operation should support timeout

---

*[libs/base/Include/base/os.h, line 598 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdIrepEtuK3HCA6oV:-KlmdIrepEtuK3HCA6oW:b-v52qmf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L598)):*
> ```objc
>      * @brief Acquires writer lock
>      */
>     bool AcquireWriterLock();
> ```

This operation should support timeout

---

*[libs/mission/time/time.cpp, line 112 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmfzMRblFb_xGICdyR:-KlmfzMRblFb_xGICdyS:b2c1s6w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/mission/time/time.cpp#L112)):*
>         }
> 
>         {
>             WriterLock lock(state.PersistentState.Lock);
Usually this is done by promoting reader to writer. Doing this way introduces a possibility of overwriting of someone else's changes that are made in between the two braces.

---

*[libs/state/Include/state/PersistentState.hpp, line 122 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmf5m_pq_kXyaHbX17:-Klmf5m_pq_kXyaHbX18:bta5trt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/state/Include/state/PersistentState.hpp#L122)):*
> ```cpp
>      * @endcode
>      */
>     template <typename StatePolicy, typename... Parts> class PersistentState
> ```

I would expect that multithreading would not part of this class and instead provided in form of wrapper type. 

---

*[libs/state/Include/state/PersistentState.hpp, line 137 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmf-q07szVtU12EpkX:-Klmf-q07szVtU12EpkY:bw8rjfd) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/state/Include/state/PersistentState.hpp#L137)):*
> ```cpp
> 
>         /** @brief Reader-Writer lock object for synchronization */
>         static ReaderWriterLock Lock;
> ```

This member should not be defined as static

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 16 of 23 files at r4.
Review status: 24 of 31 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[libs/base/CMakeLists.txt, line 22 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KmAL2g7R0UOH53XXhH1:-KmAL2g7R0UOH53XXhH2:b-pltn7s) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/423781fd78d46e2cd7c39080200a3991be96b9e0/libs/base/CMakeLists.txt#L22)):*
> ```CMake
> target_link_libraries(${NAME}
>     gsl
>     freeRTOS
> ```

this library should not be needed here.

---

*[libs/base/Include/base/os.h, line 158 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KmAM8UY5raYD9sSt9Gl:-KmAM8UY5raYD9sSt9Gm:b-tsbf7h) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/423781fd78d46e2cd7c39080200a3991be96b9e0/libs/base/Include/base/os.h#L158)):*
> ```objc
> 
> /** @brief Type definition of semaphore buffer for static allocation. */
> using OSSemaphoreBuffer = StaticSemaphore_t;
> ```

This type should be opaque struct that has the same size as the one expected by the freertos.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 2 of 23 files at r4.
Review status: 26 of 31 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 11 of 18 files at r5.
Review status: 22 of 26 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by kfazi** [comment]
Review status: 8 of 27 files reviewed at latest revision, 15 unresolved discussions.

---

*[libs/base/os_base.cpp, line 31 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmczEo_8PIzkCs-g3M:-KoN3xSIH0KBP1mbqvmD:b-2nvand) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L31)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>     System::GiveSemaphore(resourceSemaphore);
>     System::GiveSemaphore(readCountSemaphore);
>     System::GiveSemaphore(serviceSemaphore);
Unhandled error conditions
</blockquote></details>

This class has been removed

---

*[libs/base/os_base.cpp, line 41 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmePJC3vGMCVvVjLuJ:-KoN43FD6Y4O_4Noyz0P:b-3klx0s) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L41)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

what is the exact purpose of this semaphore? As I see it it does not protect anything 
</blockquote></details>

This class has been removed. This semaphore was used to protect readCount field

---

*[libs/base/os_base.cpp, line 87 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdwB3Af-zWlmA2saK:-KoN4JwXIhvduedEIGq4:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L87)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

data race
</blockquote></details>

Done.

---

*[libs/base/os_base.cpp, line 121 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmd7iyOFf4LLSvjQc5:-KoN4LEH0Bin8I_kBfw0:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L121)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

data race
</blockquote></details>

Done.

---

*[libs/base/os_base.cpp, line 126 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmd9S7MxWXCBZIgb-x:-KoN4M0c3sOOYEI3oxVL:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L126)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

data race
</blockquote></details>

Done.

---

*[libs/base/os_base.cpp, line 144 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmeax691KUkoSt_8ia:-KoN4N16Kohnx4Vxz5MI:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L144)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this function should be defined inline
</blockquote></details>

Done.

---

*[libs/base/os_base.cpp, line 164 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmefL9rlQJSKtoknlX:-KoN4Nw0AKjphGdJRm6G:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/os_base.cpp#L164)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this function should be defined inline
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 582 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmfW8jrpfPywRmQh3r:-KoN4wPkf7WAgcStmUBh:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L582)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This implementation puts writers in huge disadvantage and bears a very big risk of writer starvation
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 593 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdGQwVqmzB1_TjbiE:-KoN4yQ-k0CLnOYAUuq6:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L593)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This operation should support timeout
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 598 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmdIrepEtuK3HCA6oV:-KoN4zdguckMnEya3MJU:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/base/Include/base/os.h#L598)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This operation should support timeout
</blockquote></details>

Done.

---

*[libs/base/Include/base/os.h, line 158 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KmAM8UY5raYD9sSt9Gl:-KoN4PE2lVJU6e8YZ-10:bc8qv9b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/423781fd78d46e2cd7c39080200a3991be96b9e0/libs/base/Include/base/os.h#L158)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This type should be opaque struct that has the same size as the one expected by the freertos.
</blockquote></details>

Removed. I tried to replace all dynamic allocation with static one, but because there is no dynamic allocation of collections, there is no place where memory could leak. It is simply not worth it.

---

*[libs/mission/time/time.cpp, line 112 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KlmfzMRblFb_xGICdyR:-KoN53KNKnwjXJX3EgnG:b-m3x1uz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/mission/time/time.cpp#L112)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>         }
> 
>         {
>             WriterLock lock(state.PersistentState.Lock);
Usually this is done by promoting reader to writer. Doing this way introduces a possibility of overwriting of someone else's changes that are made in between the two braces.
</blockquote></details>

Done. I replaced PersistentState.Lock with a derived class that handles synchronization internally

---

*[libs/state/Include/state/PersistentState.hpp, line 122 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmf5m_pq_kXyaHbX17:-KoN55_DCxwc56KgySeH:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/state/Include/state/PersistentState.hpp#L122)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I would expect that multithreading would not part of this class and instead provided in form of wrapper type. 
</blockquote></details>

Done.

---

*[libs/state/Include/state/PersistentState.hpp, line 137 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Klmf-q07szVtU12EpkX:-KoN57Itxdkl27hlpMO9:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d7ebe50fd3e8735c93a5b3cc4deadf30d3aa7020/libs/state/Include/state/PersistentState.hpp#L137)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

This member should not be defined as static
</blockquote></details>

Done.

---

*[libs/base/CMakeLists.txt, line 22 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KmAL2g7R0UOH53XXhH1:-KoN58ZaO0jlyjvwpygt:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/423781fd78d46e2cd7c39080200a3991be96b9e0/libs/base/CMakeLists.txt#L22)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this library should not be needed here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 1 of 18 files at r5, 19 of 22 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 9 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomjbS3fYuH6ciGCGyL:-KomjbS3fYuH6ciGCGyM:b-5sumfi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L9)):*
> ```cpp
> namespace state
> {
>     template <typename StatePolicy, typename... Parts> class LockablePersistentState : public PersistentState<StatePolicy, Parts...>
> ```

Although correct, implementation inheritance in here seems a bit strange. Without virtual interface there is a risk that one will use unsynchronized procedure from base class instead of its replacement from derived class. Can inheritance be replaced by the composition? 

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 90 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomhHGiXMTF82uWihI4:-KomhHGjvFNmwjkVBn73:b-2zesah) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L90)):*
> ```cpp
>         }
> 
>         return Base::template Get<Object>();
> ```

Unfortunately this will not work as expected as this function does not copy the protected memory area it only returns reference (pointer) to it. Therefore by the time this function caller will try to access the object referenced by the reference returned from this function it will no longer have exclusive access to it as the lock created by this function will no longer be held.

For this to work the signature of this function has to be changed to this:
```
bool Get(Object& object)
{ 
    Lock lock(this->object);
    if(!lock)
    {
        return false;
    }

    object = Base::template Get<Object>();
    return true;
}
```

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 100 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomiU5nHlWS8D3JPw96:-KomiU5nHlWS8D3JPw97:bk270tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L100)):*
> ```cpp
>         if (!lock())
>         {
>             LOG(LOG_LEVEL_ERROR, "Unable to acquire PersistentState lock.");
> ```

When lock could not be acquired try to avoid accessing protected state.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 111 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Komia-baUtv8b9FnU6q:-Komia-baUtv8b9FnU6r:bk270tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L111)):*
> ```cpp
>         if (!lock())
>         {
>             LOG(LOG_LEVEL_ERROR, "Unable to acquire PersistentState lock.");
> ```

When lock could not be acquired try to avoid accessing protected state.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 122 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomiaXU8E6JwuGHQhjT:-KomiaXU8E6JwuGHQhjU:bk270tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L122)):*
> ```cpp
>         if (!lock())
>         {
>             LOG(LOG_LEVEL_ERROR, "Unable to acquire PersistentState lock.");
> ```

When lock could not be acquired try to avoid accessing protected state.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 133 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Komib23RV8zWAXnA6gQ:-Komib23RV8zWAXnA6gR:bk270tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L133)):*
> ```cpp
>         if (!lock())
>         {
>             LOG(LOG_LEVEL_ERROR, "Unable to acquire PersistentState lock.");
> ```

When lock could not be acquired try to avoid accessing protected state.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 144 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomibdHog49EFWj564K:-KomibdHog49EFWj564L:bk270tj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L144)):*
> ```cpp
>         if (!lock())
>         {
>             LOG(LOG_LEVEL_ERROR, "Unable to acquire PersistentState lock.");
> ```

When lock could not be acquired try to avoid accessing protected state.

---

*[libs/state/Include/state/SynchronizedPersistentState.hpp, line 1 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomjQapP7_fORfGpZyL:-KomjQapP7_fORfGpZyM:b-6ouf2k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/SynchronizedPersistentState.hpp#L1)):*
> ```cpp
> #ifndef LIBS_STATE_SYNCHRONIZED_PERSISTENT_STATE_HPP
> ```

There is some missing documentation in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by kfazi** [comment]
Review status: 15 of 34 files reviewed at latest revision, 8 unresolved discussions.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 9 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomjbS3fYuH6ciGCGyL:-KovwDUoI-WBnGym-6zw:bzarrnt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L9)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Although correct, implementation inheritance in here seems a bit strange. Without virtual interface there is a risk that one will use unsynchronized procedure from base class instead of its replacement from derived class. Can inheritance be replaced by the composition? 
</blockquote></details>

Done. Replaced by the composition

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 90 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomhHGiXMTF82uWihI4:-Kovw2O7BHQJ42kC11gX:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L90)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Unfortunately this will not work as expected as this function does not copy the protected memory area it only returns reference (pointer) to it. Therefore by the time this function caller will try to access the object referenced by the reference returned from this function it will no longer have exclusive access to it as the lock created by this function will no longer be held.

For this to work the signature of this function has to be changed to this:
```
bool Get(Object& object)
{ 
    Lock lock(this->object);
    if(!lock)
    {
        return false;
    }

    object = Base::template Get<Object>();
    return true;
}
```

</blockquote></details>

Done.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 100 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomiU5nHlWS8D3JPw96:-Kovw6sU2nlmzExEebjT:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L100)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

When lock could not be acquired try to avoid accessing protected state.
</blockquote></details>

Done.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 111 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Komia-baUtv8b9FnU6q:-Kovw7gZ0M019xhP_IkI:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L111)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

When lock could not be acquired try to avoid accessing protected state.
</blockquote></details>

Done.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 122 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomiaXU8E6JwuGHQhjT:-Kovw8PRJG5pXPJ4OY4P:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L122)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

When lock could not be acquired try to avoid accessing protected state.
</blockquote></details>

Done.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 133 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-Komib23RV8zWAXnA6gQ:-Kovw9aTgeskBaf-tY-m:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L133)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

When lock could not be acquired try to avoid accessing protected state.
</blockquote></details>

Done.

---

*[libs/state/Include/state/LockablePersistentState.hpp, line 144 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomibdHog49EFWj564K:-KovwAHCIrEm_am5wg_b:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/LockablePersistentState.hpp#L144)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

When lock could not be acquired try to avoid accessing protected state.
</blockquote></details>

Done.

---

*[libs/state/Include/state/SynchronizedPersistentState.hpp, line 1 at r6](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165#-KomjQapP7_fORfGpZyL:-KovwBhfQDuKUb2n-S-g:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/5e0108e31ca91a601b1e9f1b58fbfca2055fcb74/libs/state/Include/state/SynchronizedPersistentState.hpp#L1)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

There is some missing documentation in this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Comment by zaq32** [comment]
Reviewed 20 of 21 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/165)*

**Pull request merged**
