### PR TITLE
Antenna mission

### PR DESCRIPTION
**Pull request by zaq32**
Implementation of the 30 silent period at the beginning of the mission and the antenna deployment soon after that.

In addition cleaned up mission loop implementation from the testing logic.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/55)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/mission/antenna/antenna.cpp, line 138 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqO1DUAzkEGmTBvES9:-KXqO1DUAzkEGmTBvESA:bvim9ht) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L138)):*
> ```cpp
> 
>             {ResetDriverStep, ANTENNA_BACKUP_CHANNEL, ANTENNA_AUTO_ID, 0, false},
>             {RegularDeploymentStep, ANTENNA_BACKUP_CHANNEL, ANTENNA_AUTO_ID, 9, false},
> ```

Move these timeouts to constants

---

*[libs/mission/antenna/antenna.cpp, line 195 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqOFXW7CvZJdsHqzmD:-KXqOFXW7CvZJdsHqzmE:bnwrwgk) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L195)):*
> ```cpp
>          * @brief Number of the first step in the deployment finalization phase.
>          */
>         static constexpr uint8_t FinalizationStepIndex = count_of(deploymentSteps) - 2;
> ```

Putting static_assert checking that `FinalizationStepIndex` and `FinalizationStepIndex` are `FinishDeploymentStep` would be nice

---

*[libs/mission/antenna/antenna.cpp, line 496 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRmMXQsD1-nPZDWAR:-KXqRmMXQsD1-nPZDWAS:b-jptgj3) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L496)):*
> ```cpp
>             return descriptor;
>         }
> ```

Order of functions are making it very hard to understand. For example Action is in line 407 and Condition in 254 separated by few other functions. 

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqQ_rkWWahUtWYFb4D:-KXqQ_rlXHMXgHig2wrN:b9qc229) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L165)):*
> ```objc
>              * @brief Current antenna driver instance.
>              */
>             AntennaDriver& driver;
> ```

Private fields should begin with underscore.

I will update naming conventions with new 'types of names' in C++

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRCsBKdHL0m4JQ7yH:-KXqRCsBKdHL0m4JQ7yI:b77b145) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L215)):*
> ```objc
>          * @returns Action descriptor that runs antenna deployment process.
>          */
>         SystemActionDescriptor AntennaInitializeActionDescriptor(AntennaMissionState& stateDescriptor);
> ```

Why these functions are not methods?

---

*[libs/state/Include/state/struct.h, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXfzX7TtkgiHvFDVG-Y:-KXfzX7TtkgiHvFDVG-Z:bjiyz5w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/state/Include/state/struct.h#L48)):*
> ```objc
>         ADCSMode CurrentMode;
>     } ADCS;
> } SystemState;
> ```

Do we still need typedef and EXTERNC here?

---

*[src/main.cpp, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXfzrKOlfEthmpyxg12:-KXfzrKP31kGfJMhOO4D:b1w5qld) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/main.cpp#L48)):*
> ```cpp
> 
> OBC Main;
> MissionState Mission(Main);
> ```

I know that order of initialization of Main and Mission does not matter but I'll fill a lot better if there is a way force proper ordering. 

---

*[src/mission.cpp, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqMYqZjFjOAWeyKDbH:-KXqMYq_rat6CB2Q32kb:b-ydancn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/mission.cpp#L77)):*
> ```cpp
> {
>     UNREFERENCED_PARAMETER(missionState);
>     SystemActionDescriptor* runnableActions[COUNT_OF(NormalModeActionDescriptors)];
> ```

`std::array<SystemActionDescriptor*, count_of(NormalModeActionDescriptors)>`

---

*[src/commands/time.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg-wIb8DEGdhSh_fIZ:-KXg-wIb8DEGdhSh_fI_:bs3zdfs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/commands/time.cpp#L14)):*
> ```cpp
>         TerminalPuts(&Main.terminal, "jumpToTime <time>\n");
>     }
>     else
> ```

I prefer `if(something_is_invaliv) {return;]` instead of nesting inside `else`

---

*[unit_tests/MissionPlan/MissionPlanTest.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqCZ4V7xHl6kkWRoDv:-KXqCZ4V7xHl6kkWRoDw:b-29utvl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionPlanTest.cpp#L30)):*
> ```cpp
>     ASSERT_THAT(state.AntennaDeployed, Eq(false));
> }
> ```

If it is not needed anymore -> delete it.

---

*[unit_tests/MissionPlan/MissionTestHelpers.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg0cCbaq9O8nZ75nVu:-KXg0cCbaq9O8nZ75nVv:bhunlif) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionTestHelpers.cpp#L24)):*
> ```cpp
> SystemStateUpdateResult StateUpdater::UpdateByMock(SystemState* state, void* param)
> {
>     return ((StateUpdater*)param)->func(state);
> ```

(I known, 'not-my-code') Use C++ style cast?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by zaq32** [comment]
Review status: 34 of 52 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[libs/mission/antenna/antenna.cpp, line 138 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqO1DUAzkEGmTBvES9:-KXrDs7TVHyAWbL2NW-n:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L138)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Move these timeouts to constants
</blockquote></details>

Done

---

*[libs/mission/antenna/antenna.cpp, line 195 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqOFXW7CvZJdsHqzmD:-KXrDuveoI4SVX92zPt5:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L195)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Putting static_assert checking that `FinalizationStepIndex` and `FinalizationStepIndex` are `FinishDeploymentStep` would be nice
</blockquote></details>

Done

---

*[libs/mission/antenna/antenna.cpp, line 496 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRmMXQsD1-nPZDWAR:-KXrDxokUSxaG0aHRygd:b-iem4it) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/antenna.cpp#L496)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Order of functions are making it very hard to understand. For example Action is in line 407 and Condition in 254 separated by few other functions. 
</blockquote></details>

Should be better now

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 165 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqQ_rkWWahUtWYFb4D:-KXrE0c3zY9gm1a_u1Kx:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L165)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Private fields should begin with underscore.

I will update naming conventions with new 'types of names' in C++
</blockquote></details>

Done

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRCsBKdHL0m4JQ7yH:-KXrE26NjA4uacljOYHC:b93iasi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L215)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Why these functions are not methods?
</blockquote></details>

What type exactly these methods should belong to?

---

*[libs/state/Include/state/struct.h, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXfzX7TtkgiHvFDVG-Y:-KXrE9Heyjknhr43x6Yk:b2nhky0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/state/Include/state/struct.h#L48)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Do we still need typedef and EXTERNC here?
</blockquote></details>

No.

---

*[src/main.cpp, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXfzrKOlfEthmpyxg12:-KXrECL0On6rQzM1XxaE:b-lv8fg9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/main.cpp#L48)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I know that order of initialization of Main and Mission does not matter but I'll fill a lot better if there is a way force proper ordering. 
</blockquote></details>

It is possible but it is not pretty. As long as we do not need exact and deterministic order  of global object construction I would like to leave it as it is.

---

*[src/mission.cpp, line 77 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqMYqZjFjOAWeyKDbH:-KXrEPD8QklNyqGwjrEj:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/mission.cpp#L77)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

`std::array<SystemActionDescriptor*, count_of(NormalModeActionDescriptors)>`
</blockquote></details>

Done.

---

*[src/commands/time.cpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg-wIb8DEGdhSh_fIZ:-KXrEQkge7gUGMnkUONj:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/commands/time.cpp#L14)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I prefer `if(something_is_invaliv) {return;]` instead of nesting inside `else`
</blockquote></details>

Done.

---

*[unit_tests/MissionPlan/MissionPlanTest.cpp, line 30 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqCZ4V7xHl6kkWRoDv:-KXrETkgShofdRUDSLFW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionPlanTest.cpp#L30)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

If it is not needed anymore -> delete it.
</blockquote></details>

Done.

---

*[unit_tests/MissionPlan/MissionTestHelpers.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg0cCbaq9O8nZ75nVu:-KXrEXpd86EhqnZ2cxoN:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionTestHelpers.cpp#L24)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

(I known, 'not-my-code') Use C++ style cast?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by Novakov** [comment]
Reviewed 18 of 18 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/mission/antenna/antenna.cpp, line 202 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXrEqOq1tfu-cnraTXR:-KXrEqOq1tfu-cnraTXS:b-qdz0vz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6a86f640bd62bc26173fe10d648a02f7971f786f/libs/mission/antenna/antenna.cpp#L202)):*
> ```cpp
>             {RegularDeploymentStep, ANTENNA_BACKUP_CHANNEL, ANTENNA2_ID, EmergemcyTimeout, true},
>             {RegularDeploymentStep, ANTENNA_BACKUP_CHANNEL, ANTENNA3_ID, EmergemcyTimeout, true},
>             {RegularDeploymentStep, ANTENNA_BACKUP_CHANNEL, ANTENNA4_ID, EmergemcyTimeout, true},
> ```

Typo: Emergemcy -> Emergency

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRCsBKdHL0m4JQ7yH:-KY-uRj9AWikwbRQFzod:b-y8x0xl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L215)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

What type exactly these methods should belong to?
</blockquote></details>

Either `AntennaMissionState` or names should be changed telling more about "Deploying antennas"

---

*[src/main.cpp, line 48 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXfzrKOlfEthmpyxg12:-KXrG0jLKq-RS0qBovoR:bb6vskf) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/src/main.cpp#L48)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

It is possible but it is not pretty. As long as we do not need exact and deterministic order  of global object construction I would like to leave it as it is.
</blockquote></details>

Fine

---

*[unit_tests/MissionPlan/MissionTestHelpers.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg0cCbaq9O8nZ75nVu:-KXrGSwRdzsEUmFoyVSo:b-ze8y0x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionTestHelpers.cpp#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That was radical...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/mission/antenna/antenna.cpp, line 202 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXrEqOq1tfu-cnraTXR:-KY0WfsL38FURbF4i-0Z:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6a86f640bd62bc26173fe10d648a02f7971f786f/libs/mission/antenna/antenna.cpp#L202)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Typo: Emergemcy -> Emergency
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by zaq32** [comment]
Review status: 48 of 52 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/mission/antenna/Include/mission/antenna_state.h, line 215 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXqRCsBKdHL0m4JQ7yH:-KY0YTEYrc7Wg6ePUzEt:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/libs/mission/antenna/Include/mission/antenna_state.h#L215)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Either `AntennaMissionState` or names should be changed telling more about "Deploying antennas"
</blockquote></details>

Done

---

*[unit_tests/MissionPlan/MissionTestHelpers.cpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55#-KXg0cCbaq9O8nZ75nVu:-KY0YVMcMxgwXS59sn2I:bbbuptj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3ac7939fa6a5dcc19630dfa252fb6a9e5925d5c0/unit_tests/MissionPlan/MissionTestHelpers.cpp#L24)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

That was radical...
</blockquote></details>

I may seem like this but as a result we haven't lost anything as those mocks were replaced with much more powerfull googlemocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by Novakov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Comment by Novakov** [comment]
Reviewed 13 of 13 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/55)*

**Pull request merged**
