### PR TITLE
List files telecommand

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/161)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] List files (with sizes)](https://trello.com/c/38o900X0/179-tc-list-files-with-sizes)

**Comment by zaq32** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/fs/yaffs.cpp, line 242 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyW59hsD0abNudbsQp:-KkyW59hsD0abNudbsQq:b4gkf02) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/fs/yaffs.cpp#L242)):*
> extern "C" struct yaffs_obj* yaffsfs_FindObject(
>     struct yaffs_obj* relDir, const YCHAR* path, int symDepth, int getEquiv, struct yaffs_obj** dirOut, int* notDir, int* loop);
This declaration should be stored inside one of the yaffs  headers and not in here.

---

*[libs/fs/Include/fs/fs.h, line 239 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyWT8ANEIY9iSm7Stf:-KkyWT8ANEIY9iSm7Stg:b2o6cl7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/fs/Include/fs/fs.h#L239)):*
> ```objc
>              * @param dir Directory containing file
>              * @param file File name
>              * @return Size of file
> ```

or -1 in case of errors

---

*[libs/obc/communication/telecommands/file_system.cpp, line 174 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyYvDvDvPlQETI9XI7:-KkyYvDvDvPlQETI9XI8:b-g5yx55) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/obc/communication/telecommands/file_system.cpp#L174)):*
> ```cpp
> 
>             auto correlationid = r.ReadByte();
>             auto path = reinterpret_cast<const char*>(r.ReadToEnd().data());
> ```

verify that path is null-terminated

---

*[libs/obc/communication/telecommands/file_system.cpp, line 175 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyXxlUjhZLZaYyS7XM:-KkyXxlUjhZLZaYyS7XN:b-7krqnb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/obc/communication/telecommands/file_system.cpp#L175)):*
> ```cpp
>             auto correlationid = r.ReadByte();
>             auto path = reinterpret_cast<const char*>(r.ReadToEnd().data());
>             auto dir = this->_fs.OpenDirectory(path);
> ```

unverified reader status.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 199 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyY6djRxigqmUC-pCB:-KkyY6djRxigqmUC-pCC:bujxuis) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/obc/communication/telecommands/file_system.cpp#L199)):*
>                  DownlinkFrame response(DownlinkAPID::Operation, seq);
>                 writer.WriteByte(correlationid);
I have seen this code duplicated several times already. Perhaps it would be useful to add DownlinkFrame wrapper that takes corelation as its construction parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Comment by Novakov** [comment]
Review status: 5 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/fs/yaffs.cpp, line 242 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyW59hsD0abNudbsQp:-KlKShgVwTtm-aaBVlZm:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/fs/yaffs.cpp#L242)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> extern "C" struct yaffs_obj* yaffsfs_FindObject(
>     struct yaffs_obj* relDir, const YCHAR* path, int symDepth, int getEquiv, struct yaffs_obj** dirOut, int* notDir, int* loop);
This declaration should be stored inside one of the yaffs  headers and not in here.
</blockquote></details>

Done.

---

*[libs/fs/Include/fs/fs.h, line 239 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyWT8ANEIY9iSm7Stf:-KlKSQFx9HqfPc7EXJ9a:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/fs/Include/fs/fs.h#L239)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

or -1 in case of errors
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 174 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyYvDvDvPlQETI9XI7:-KlKS00QsYnPHbRJhmTq:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/obc/communication/telecommands/file_system.cpp#L174)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

verify that path is null-terminated
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/file_system.cpp, line 175 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161#-KkyXxlUjhZLZaYyS7XM:-KlKS0Hm2__MnGa3vxHy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/47baf2151e4b29efe009edda1ff232798f4baa91/libs/obc/communication/telecommands/file_system.cpp#L175)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

unverified reader status.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Comment by zaq32** [comment]
Reviewed 11 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Comment by zaq32** [comment]
Reviewed 3 of 4 files at r3.
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Comment by zaq32** [comment]
Reviewed 1 of 18 files at r1.
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Comment by zaq32** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/161)*

**Pull request merged**
