### PR TITLE
SRAM recovery mechanism

### PR DESCRIPTION
**Pull request by Novakov**
Implemented mechanism for handling SRAM latch-up and recovery. 

Recovery process can be invoked manually terminal command. After merging #193 recovery will be executed periodically by scrubber task

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/195)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[boot/comms.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXtX-CoXu8Vv3MvK1Q:-KnXtX-CoXu8Vv3MvK1R:bnoxgfl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/boot/comms.cpp#L38)):*
> ```cpp
> static void PrintHelp();
> 
> static std::array<Command, 18> Commands = {
> ```

consider this: 
```
static Command Commands[] = {
// list of commands
};
```

And now you do not have to fill in the size everytime command is added/removed.

---

*[integration_tests/tests/test_telecommands_boot_settings.py, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXwAbgWxgJoakOQiYM:-KnXwAbgWxgJoakOQiYN:b-7svgfm) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/integration_tests/tests/test_telecommands_boot_settings.py#L20)):*
> ```Python
>         self.system.comm.on_hardware_reset = on_reset
> 
>         self.power_on_obc(clean_state=True)
> ```

how is the obc state being reset right now?

---

*[platforms/FlightModel/Include/io_map.h, line 29 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXwLGUmqyORS_P382B:-KnXwLGUmqyORS_P382C:bs6b339) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/platforms/FlightModel/Include/io_map.h#L29)):*
> ```objc
>     using Led1 = PinLocation<gpioPortD, 2>;
> 
>     using SysClear = PinLocation<gpioPortC, 0>;
> ```

Update project documentation to reflect this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195)*

**Comment by Novakov** [comment]
Review status: 34 of 36 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[integration_tests/tests/test_telecommands_boot_settings.py, line 20 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXwAbgWxgJoakOQiYM:-KneAa0-DCmIim7WjQxg:b-8dvl3w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/integration_tests/tests/test_telecommands_boot_settings.py#L20)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

how is the obc state being reset right now?
</blockquote></details>

Our current tests do not relay on clear state - the only persistent part is time which is set to proper values as needed. However this functionality may be achived by bootloader interaction

---

*[platforms/FlightModel/Include/io_map.h, line 29 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXwLGUmqyORS_P382B:-KneDe8gmdHjQfWca2V7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/platforms/FlightModel/Include/io_map.h#L29)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Update project documentation to reflect this change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195)*

**Comment by Novakov** [comment]
Review status: 31 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[boot/comms.cpp, line 38 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195#-KnXtX-CoXu8Vv3MvK1Q:-KneVxFzqZ4apqWWUh1A:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f6a24fc74d4ffaa10bc56b8471caa6277f9a685/boot/comms.cpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

consider this: 
```
static Command Commands[] = {
// list of commands
};
```

And now you do not have to fill in the size everytime command is added/removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/195)*

**Comment by Novakov** [comment]
[[FDIR] Handle FPGA information pins (latch-up/errors)](https://trello.com/c/A5KJnq23/183-fdir-handle-fpga-information-pins-latch-up-errors)

**Pull request merged**
