### PR TITLE
Update experiment codes, changed telemetry to use 4 bits for experiment code

### PR DESCRIPTION
**Pull request by mandrek44**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/261)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/261)*

**Comment by zaq32** [comment]
Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/261)*

**Comment by mandrek44** [comment]
[[BUG][Experiments] Fix experiment code parsing in emulator](https://trello.com/c/dOIPdPF5/240-bugexperiments-fix-experiment-code-parsing-in-emulator)

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/261)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/261)*

**Pull request merged**
