### PR TITLE
Experiment detumbling

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/271)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Experiment] ADCS Detumbling](https://trello.com/c/qbtd33oS/210-experiment-adcs-detumbling)

**Comment by zaq32** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/telemetry/imtq/ImtqTelemetryCollector.cpp, line 262 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271#-KrzCWY0m3zFdfXm4lvw:-KrzCWY0m3zFdfXm4lvx:b-l2raad) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/600d76d133b11b60c61c032cb066a5f14122adc0/libs/telemetry/imtq/ImtqTelemetryCollector.cpp#L262)):*
> ```cpp
>         }
> 
>         bool ImtqTelemetryCollector::GetLastMagnetometerMeasurement(telemetry::ImtqMagnetometerMeasurements& measurements)
> ```

merge this function with the following one to remove the necessity of taking the same lock multiple times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271)*

**Comment by Novakov** [comment]
Review status: 26 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/telemetry/imtq/ImtqTelemetryCollector.cpp, line 262 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271#-KrzCWY0m3zFdfXm4lvw:-KrzJkfemQcqVM9bbdXo:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/600d76d133b11b60c61c032cb066a5f14122adc0/libs/telemetry/imtq/ImtqTelemetryCollector.cpp#L262)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

merge this function with the following one to remove the necessity of taking the same lock multiple times.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/271)*

**Pull request merged**
