### PR TITLE
Extend telemetry with state of boot reason, gpios, filesystem, time & program 

### PR DESCRIPTION
**Pull request by zaq32**
In addition there are some small fixes:
* update eps telemetry to reflect recent changes.
* bug fixes for telemetry serialization: always save entire telemetry regardless whether it has been recently modified or not

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/204)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] Add mechanism of gathering the telemetry from obc components](https://trello.com/c/Eylh5zUA/165-telemetry-add-mechanism-of-gathering-the-telemetry-from-obc-components)

**Comment by Novakov** [comment]
Reviewed 63 of 63 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/hardware/Include/obc/gpio.h, line 100 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204#-KoDLs2wm5z_obK2cfo_:-KoDLs2wm5z_obK2cfoa:b-expyxn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a9575bd379a346dd031c5b5af16cbe91e7b8c06/libs/obc/hardware/Include/obc/gpio.h#L100)):*
> ```objc
>         typename TLed1,
>         typename TSPI,
> #ifdef USE_LEUART
> ```

I think we can get rid of LEUART 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/hardware/Include/obc/gpio.h, line 100 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204#-KoDLs2wm5z_obK2cfo_:-KoJUBzw55g6I--I02Tk:bp1e6i5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a9575bd379a346dd031c5b5af16cbe91e7b8c06/libs/obc/hardware/Include/obc/gpio.h#L100)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I think we can get rid of LEUART 
</blockquote></details>

Probably, but if we are going to do it, lets do it in separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/obc/hardware/Include/obc/gpio.h, line 100 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204#-KoDLs2wm5z_obK2cfo_:-KoLX9D-Y_bEkJhSJvzZ:b-6wcbku) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/4a9575bd379a346dd031c5b5af16cbe91e7b8c06/libs/obc/hardware/Include/obc/gpio.h#L100)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Probably, but if we are going to do it, lets do it in separate PR.
</blockquote></details>

That's fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/204)*

**Pull request merged**
