### PR TITLE
Burtc time provider

### PR DESCRIPTION
**Pull request by mandrek44**
Set BURTC as a tick source to `TimeProvider`

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/84)

### CODE REVIEW

**Comment by mandrek44** [comment]
[BURTC](https://trello.com/c/P8eHwFYD/110-burtc)

**Comment by Novakov** [comment]
Reviewed 11 of 13 files at r1, 2 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[integration_tests/tests/test_time.py, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4MYT5Ht1nYyvrNQre:-Kc4MYT69LPmvoV9vjNI:bqn7erl) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/integration_tests/tests/test_time.py#L32)):*
> ```Python
> 
>         self.assertGreaterEqual(time_difference, wait_time_s - wait_time_accuracy_s)
>         self.assertLessEqual(time_difference, wait_time_s + wait_time_accuracy_s)
> ```

Use `self.assertAlmostEqual` method

---

*[libs/drivers/burtc/burtc.cpp, line 45 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4KivHNHENj5lrNu8q:-Kc4KivHNHENj5lrNu8r:b-bnauk9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/drivers/burtc/burtc.cpp#L45)):*
> ```cpp
>     burtcInterruptSemaphore = System::CreateBinarySemaphore();
> 
>     System::CreateTask(Burtc::HandleTickTask, "HandleTickTask", 512, this, TaskPriority::P1, NULL);
> ```

We've got wrapper around RTOS tasks: `Task` class in `base/os.h`

---

*[libs/drivers/burtc/burtc.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4MmdnNlKojtlAgxqT:-Kc4MmdnNlKojtlAgxqU:bccjsbs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L13)):*
> ```cpp
> void BURTC_IRQHandler(void)
> {
>     uint32_t irq = BURTC_IntGet();
> ```

In C++ it is preffered to use `std::uint32_t` from `cstdint` header

---

*[libs/drivers/burtc/Include/burtc/burtc.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4L4Xso6F55ka9HyHg:-Kc4L4Xty-oV5OK8Hhkd:b6y4ord) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/drivers/burtc/Include/burtc/burtc.hpp#L9)):*
> ```cpp
> 
> /**
>  * @defgroup burtc Backup RTC Driver
> ```

Add this group to appropriate group (perhipheral_drivers)

---

*[src/obc.cpp, line 12 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4LSUYqzjujnoDzAsa:-Kc4LSUYqzjujnoDzAsb:b-z4uqi4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/src/obc.cpp#L12)):*
> ```cpp
>       terminal(this->IO),                       //
>       burtcHandler(timeProvider),               //
>       Burtc(burtcHandler)
> ```

I think that BURTC hardware, so it can be move inside `OBCHardware`

---

*[src/obc.h, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4M7G1SgBYoVvwz5eL:-Kc4M7G1SgBYoVvwz5eM:b-vmbk88) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/src/obc.h#L49)):*
> ```objc
>      * @param[in] interval Interval that passed since last tick
>      */
>     void virtual Tick(std::chrono::milliseconds interval);
> ```

add `override`

---

*[libs/time/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4M-woCOsK8WWNDgic:-Kc4M-woCOsK8WWNDgid:b-i41lj0) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/time/CMakeLists.txt#L15)):*
> ```CMake
> 	base 
> 	fs 
> 	emlib
> ```

Time should not depend on emlib

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by zaq32** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[libs/drivers/burtc/burtc.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oPBFvuDeHSWPkF2F:-Kc7oPBFvuDeHSWPkF2G:bur2yjo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L30)):*
> ```cpp
>     while (1)
>     {
>         System::TakeSemaphore(burtcInterruptSemaphore, InfiniteTimeout);
> ```

missing error handling 

---

*[libs/drivers/burtc/burtc.cpp, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oRy5Ac15g72aSza5:-Kc7oRy6UOk2uOUiVX21:blm3lfg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L38)):*
> ```cpp
> void Burtc::Initialize()
> {
>     burtcInterruptSemaphore = System::CreateBinarySemaphore();
> ```

missing error handling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by mandrek44** [comment]
Review status: 4 of 17 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[integration_tests/tests/test_time.py, line 32 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4MYT5Ht1nYyvrNQre:-Kc94OsYZJ_EbVsJVAqy:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/integration_tests/tests/test_time.py#L32)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Use `self.assertAlmostEqual` method
</blockquote></details>

Done.

---

*[libs/drivers/burtc/burtc.cpp, line 45 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4KivHNHENj5lrNu8q:-Kc94_dxnkBf3IP8Malz:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/drivers/burtc/burtc.cpp#L45)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

We've got wrapper around RTOS tasks: `Task` class in `base/os.h`
</blockquote></details>

Done.

---

*[libs/drivers/burtc/burtc.cpp, line 13 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4MmdnNlKojtlAgxqT:-Kc94QXs3EVCzY5Dmgf7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L13)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

In C++ it is preffered to use `std::uint32_t` from `cstdint` header
</blockquote></details>

Done.

---

*[libs/drivers/burtc/burtc.cpp, line 30 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oPBFvuDeHSWPkF2F:-Kc94Ssrif1TkpEsGsYN:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L30)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing error handling 
</blockquote></details>

Done.

---

*[libs/drivers/burtc/burtc.cpp, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oRy5Ac15g72aSza5:-Kc94Unkcwjn0CATW6LB:b-9uy00b) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing error handling
</blockquote></details>

CreateBinarySemaphore logs error internally

---

*[libs/drivers/burtc/Include/burtc/burtc.hpp, line 9 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4L4Xso6F55ka9HyHg:-Kc94azCrzbn2eg0rxbl:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/drivers/burtc/Include/burtc/burtc.hpp#L9)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Add this group to appropriate group (perhipheral_drivers)
</blockquote></details>

Done.

---

*[src/obc.cpp, line 12 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4LSUYqzjujnoDzAsa:-Kc94AvvrJ98jSKrs1Yb:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/src/obc.cpp#L12)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I think that BURTC hardware, so it can be move inside `OBCHardware`
</blockquote></details>

Done.

---

*[src/obc.h, line 49 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4M7G1SgBYoVvwz5eL:-Kc94CK-jIBoQIJzvBim:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/src/obc.h#L49)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

add `override`
</blockquote></details>

Done.

---

*[libs/time/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc4M-woCOsK8WWNDgic:-Kc94G1M7dx1mi1Y7K7G:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/96c15b0914f61dd2ad747bc3d1450faca5986521/libs/time/CMakeLists.txt#L15)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Time should not depend on emlib
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by Novakov** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/burtc/burtc.cpp, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oRy5Ac15g72aSza5:-KcWU-MnFSMsXfKUoiFw:btr7fo5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L38)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

CreateBinarySemaphore logs error internally
</blockquote></details>

so it would be nice to propagate this error up the call stack

---

*[libs/drivers/burtc/burtc.cpp, line 39 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-KcWTt8PlKizUApiyklP:-KcWTt8PlKizUApiyklQ:bl3zef8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/177fd147e8b11ca9fca7d2a29b74516dcfb4c24b/libs/drivers/burtc/burtc.cpp#L39)):*
> ```cpp
>         }
> 
>         burtcObject->_tickCallback.Invoke(burtcObject->_timeDelta);
> ```

this function should not be called in case of errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by mandrek44** [comment]
Review status: 10 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/burtc/burtc.cpp, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-Kc7oRy5Ac15g72aSza5:-KcXwrD8cmB4_oe_9MWW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/093fc76405a088f9e6bede254850864bc8ebbb88/libs/drivers/burtc/burtc.cpp#L38)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

so it would be nice to propagate this error up the call stack
</blockquote></details>

Done.

---

*[libs/drivers/burtc/burtc.cpp, line 39 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-KcWTt8PlKizUApiyklP:-KcXwqS3aTJYzt34ccc8:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/177fd147e8b11ca9fca7d2a29b74516dcfb4c24b/libs/drivers/burtc/burtc.cpp#L39)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

this function should not be called in case of errors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by zaq32** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/burtc/burtc.cpp, line 48 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-KcXz9jtDo2rOdGLL97F:-KcXz9jtDo2rOdGLL97G:b-mgqfqy) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6c731386488f642de38705d4482180a61e84825b/libs/drivers/burtc/burtc.cpp#L48)):*
> ```cpp
> {
>     burtcInterruptSemaphore = System::CreateBinarySemaphore();
>     if (burtcInterruptSemaphore == 0)
> ```

since semaphore handle is a pointer you should use nullptr instead of zero constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by mandrek44** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/burtc/burtc.cpp, line 48 at r5](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84#-KcXz9jtDo2rOdGLL97F:-KcYBymH0-_bhHD3pSKx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6c731386488f642de38705d4482180a61e84825b/libs/drivers/burtc/burtc.cpp#L48)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since semaphore handle is a pointer you should use nullptr instead of zero constant.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/84)*

**Pull request merged**
