### PR TITLE
Implemented time retrieval from RTC

### PR DESCRIPTION
**Pull request by mandrek44**
RTC integration - just the driver, without a mock and tests. "`rtc`" terminal command for testing the hardware. `mktime` used to convert RTC time to seconds for comparing.

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/88)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[libs/drivers/rtc/rtc.cpp, line 39 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnrrot1im8TXxMXdma:-Kcnrrot1im8TXxMXdmb:b4nyg9l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L39)):*
> ```cpp
>     rtcTime.days = ConvertFromBCD(outBuffer[3], DaysNibbleMask);
>     rtcTime.months = ConvertFromBCD(outBuffer[5], MonthsNibbleMask);
>     rtcTime.years = ConvertFromBCD(outBuffer[6], YearsNibbleMask);
> ```

It would be better to move this method (`ConvertFromBCD`) to `Reader` class and use it here

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnm8YwxkrgMcMgz8iF:-Kcnm8YwxkrgMcMgz8iG:bfgg7ae) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/Include/rtc/rtc.hpp#L14)):*
> perhipheral_drivers
Perhipheral drivers are used to control something that is built in into MCU (like timers, BURTC, I2C, etc). External RTC falls into `device_drviers` category

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-KcnpEr-DlUPaKB0JBwS:-KcnpEr-DlUPaKB0JBwT:bl459wi) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/Include/rtc/rtc.hpp#L89)):*
> ```cpp
>                 t.tm_isdst = -1;
> 
>                 return static_cast<std::uint32_t>(mktime(&t));
> ```

How about returning chrono duration from here? 

---

*[src/commands/rtc.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcns5Vr5wU-g5nWFTAu:-Kcns5Vr5wU-g5nWFTAv:bgx0wk2) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/src/commands/rtc.cpp#L28)):*
> ```cpp
>     else
>         Main.terminal.Printf("FAIL\r\n");
> }
> ```

What's the purpose of this function?

---

*[src/commands/rtc.cpp, line 67 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-KcnsAslMxr1znxy12TK:-KcnsAslMxr1znxy12TL:b-ngxonw) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/src/commands/rtc.cpp#L67)):*
> ```cpp
>     }
> 
>     if (command == 0)
> ```

Using `strcmp` directly in if is fine in case of commands - it will be easier to see what is supported

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/drivers/rtc/rtc.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnxl9llhUPTx8sVElY:-Kcnxl9llhUPTx8sVElZ:bccfw3k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L31)):*
> ```cpp
>     {
>         LOG(LOG_LEVEL_ERROR, "Unable read time from RTC");
>         return;
> ```

how RTC user is expected to detect failure?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Comment by mandrek44** [comment]
Review status: 5 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[libs/drivers/rtc/rtc.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnxl9llhUPTx8sVElY:-KctNr9duyyYVOkoSJGS:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L31)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

how RTC user is expected to detect failure?
</blockquote></details>

Done.

---

*[libs/drivers/rtc/rtc.cpp, line 39 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnrrot1im8TXxMXdma:-KctNmRiRkiP9AyFEuhW:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L39)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be better to move this method (`ConvertFromBCD`) to `Reader` class and use it here
</blockquote></details>

Done.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 14 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnm8YwxkrgMcMgz8iF:-KctNoTrJU6vkqnRkTGB:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/Include/rtc/rtc.hpp#L14)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

> perhipheral_drivers
Perhipheral drivers are used to control something that is built in into MCU (like timers, BURTC, I2C, etc). External RTC falls into `device_drviers` category
</blockquote></details>

Done.

---

*[libs/drivers/rtc/Include/rtc/rtc.hpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-KcnpEr-DlUPaKB0JBwS:-KctNpB4avEyZ0jBY7Eb:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/Include/rtc/rtc.hpp#L89)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

How about returning chrono duration from here? 
</blockquote></details>

Done.

---

*[src/commands/rtc.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcns5Vr5wU-g5nWFTAu:-KctJNVR338VTHo0Yu5C:bxgt062) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/src/commands/rtc.cpp#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

What's the purpose of this function?
</blockquote></details>

To easily spot error in data returned from RTC - kind of healthcheck function. Should I remove it?

---

*[src/commands/rtc.cpp, line 67 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-KcnsAslMxr1znxy12TK:-KctNpuVlGEusDFpSbNz:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/src/commands/rtc.cpp#L67)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Using `strcmp` directly in if is fine in case of commands - it will be easier to see what is supported
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libs/drivers/rtc/rtc.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnxl9llhUPTx8sVElY:-KcvMh5L9CCQ4maispSM:bq7lyi5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L31)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think that I2CResult is proper result type... OSResult/bool would be better

---

*[src/commands/rtc.cpp, line 28 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcns5Vr5wU-g5nWFTAu:-KcvMuYcQrfTyp0olQwh:bgcj8ql) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/src/commands/rtc.cpp#L28)):*
<details><summary><i>Previously, mandrek44 (Mandro) wrote…</i></summary><blockquote>

To easily spot error in data returned from RTC - kind of healthcheck function. Should I remove it?
</blockquote></details>

As you said - ranges of some values are different from those stated in datasheet, so let's leave this method here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Comment by mandrek44** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/drivers/rtc/rtc.cpp, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88#-Kcnxl9llhUPTx8sVElY:-KdFI1plS6lm-OVMmMlq:bcf8u5t) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/6f770ba81521b4f32985a98f94c476dcdc1a3cdc/libs/drivers/rtc/rtc.cpp#L31)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

I don't think that I2CResult is proper result type... OSResult/bool would be better
</blockquote></details>

I don't like bools - changed to `OSResult`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Comment by Novakov** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/88)*

**Pull request merged**
