### PR TITLE
[TeleComm] Added raw I2C telecommand

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/224)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/obc/communication/telecommands/i2c.cpp, line 26 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq71wDcXT2yB9tfAEk:-Kpq71wDcXT2yB9tfAEl:b-lqiji7) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/i2c.cpp#L26)):*
> ```cpp
>             auto correlationId = r.ReadByte();
>             auto address = r.ReadByte();
>             auto data = r.ReadToEnd();
> ```

verify reader status.

---

*[libs/obc/communication/telecommands/i2c.cpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq7Jr0cCSV4qhSuJHL:-Kpq7Jr0cCSV4qhSuJHM:bez97tp) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/i2c.cpp#L37)):*
> ```cpp
>             std::fill(responseBuf.begin(), responseBuf.end(), 0);
> 
>             auto result = this->i2cBus.WriteRead(address, data, responseBuf);
> ```

since some of the devices do not work with combined write/read transaction it would be better to use separated read/write operations with some delay in between (preferably parametrized)

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/i2c.hpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq6oPma7A_HvL0MFdV:-Kpq6oPma7A_HvL0MFdW:b-2nur6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/Include/obc/telecommands/i2c.hpp#L24)):*
> ```cpp
>          *  - Array of 8-bit - Data to send to I2C bus
>          */
>         class RawI2CTelecommand final : public telecommunication::uplink::Telecommand<0x80>
> ```

ideally we would like to be able to access selected i2c bus - either bus or payload depending on the telecommand parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224)*

**Comment by kfazi** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/obc/communication/telecommands/i2c.cpp, line 26 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq71wDcXT2yB9tfAEk:-KrGBPqQLZlTMm6u_tVZ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/i2c.cpp#L26)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

verify reader status.
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/i2c.cpp, line 37 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq7Jr0cCSV4qhSuJHL:-KrGBQPH7bpnIANxrRiE:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/i2c.cpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

since some of the devices do not work with combined write/read transaction it would be better to use separated read/write operations with some delay in between (preferably parametrized)
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/Include/obc/telecommands/i2c.hpp, line 24 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224#-Kpq6oPma7A_HvL0MFdV:-KrGBP69dNVhLjzXnAg7:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/a460e984514904ee95dc540f11fd5f939d319a35/libs/obc/communication/telecommands/Include/obc/telecommands/i2c.hpp#L24)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

ideally we would like to be able to access selected i2c bus - either bus or payload depending on the telecommand parameter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224)*

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224)*

**Comment by zaq32** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/224)*

**Comment by zaq32** [comment]
[[TC] RAW I2C Interface to GS](https://trello.com/c/OxHWZGvF/107-tc-raw-i2c-interface-to-gs)

**Pull request merged**
