### PR TITLE
[APID Cleanup] Replaced Operation by command specific apids.

### PR DESCRIPTION
**Pull request by tom4r**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/293)

### CODE REVIEW

**Comment by tom4r** [comment]
[APIDy odpowiedzi](https://trello.com/c/Ykj7BA69/255-apidy-odpowiedzi)

**Comment by Novakov** [comment]
Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by zaq32** [comment]
Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 55 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293#-KtCcKC1uhkwXrWKVCkq:-KtCcKC2VqUFkWyHm05K:b5mfz6u) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cfaa7adad9100270da5973ed28c48ee38d61d11e/libs/telecommunication/include/telecommunication/downlink.h#L55)):*
> ```objc
>             Comm = 0x17,                        //!< Commands for Comm subsystem
>             I2C = 0x1A,                         //!< I2C Raw
>             Forbidden = (BeaconMarker & 0x3ff), //!< Reserved apid due to beacon collision
> ```

incorrect APID is 6 bit long therefore mask should also be 6 bits long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by tom4r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[libs/telecommunication/include/telecommunication/downlink.h, line 55 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293#-KtCcKC1uhkwXrWKVCkq:-KtCpQ41znQRpdXWghnj:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/cfaa7adad9100270da5973ed28c48ee38d61d11e/libs/telecommunication/include/telecommunication/downlink.h#L55)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

incorrect APID is 6 bit long therefore mask should also be 6 bits long.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by zaq32** [comment]
Reviewed 2 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by zaq32** [comment]
Reviewed 1 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/293)*

**Pull request merged**
