### PR TITLE
Upload application

### PR DESCRIPTION
**Pull request by Novakov**
Uploading new application using telecommands

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/152)

### CODE REVIEW

**Comment by Novakov** [comment]
[[TC] Uploading new version of application](https://trello.com/c/pr4LsSoU/166-tc-uploading-new-version-of-application)

**Comment by kfazi** [comment]
Reviewed 55 of 55 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Reviewed 28 of 55 files at r1, 1 of 7 files at r3.
Review status: 50 of 57 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/drivers/program_flash/boot_table.cpp, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-Kke5dC2WOOM3LB5c6G3:-Kke5dC2WOOM3LB5c6G4:bj0lzzh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f3b90ce009126471c0c799d30e677d6c8a315f14/libs/drivers/program_flash/boot_table.cpp#L18)):*
> ```cpp
>         this->_bootConfig = this->_flash.BootConfig();
> 
>         while (this->_deviceId != 0x00530000 || this->_bootConfig != 0x00000002)
> ```

Is this supposed to be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Reviewed 20 of 55 files at r1, 1 of 1 files at r2, 1 of 7 files at r3.
Review status: 52 of 57 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/utils.h, line 318 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI3UuCS3LMyKVYbCf3:-KlI3UuCS3LMyKVYbCf4:bb7jepx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/base/Include/utils.h#L318)):*
> TSuccess _success;
>     /** @brief Error value */
>     TError _error;
consider using an union

---

*[libs/obc/hardware/hardware.cpp, line 76 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI2jSYkvZ6chaMc-uy:-KlI2jSZcgwzTkNr8CZK:bej244e) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/obc/hardware/hardware.cpp#L76)):*
> ```cpp
>     error_counter::ErrorCounting& errorCounting, services::power::IPowerControl& powerControl, TimeAction& burtcTickHandler)
>     : I2C(powerControl),                                               //
>       FlashDriver(reinterpret_cast<std::uint8_t*>(0x84000000)),        //
> ```

where this value came from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by Novakov** [comment]
Review status: 52 of 57 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[libs/base/Include/utils.h, line 318 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI3UuCS3LMyKVYbCf3:-KlK-r6_1wmzN-P_fvbU:bnmkd35) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/base/Include/utils.h#L318)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

> TSuccess _success;
>     /** @brief Error value */
>     TError _error;
consider using an union
</blockquote></details>

It would be nice but union is messing with copy-ctor. I don't want to invest more time in it (at least now)

---

*[libs/drivers/program_flash/boot_table.cpp, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-Kke5dC2WOOM3LB5c6G3:-KlJuPBLQgWUUUfmHhlL:b-rhlckb) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f3b90ce009126471c0c799d30e677d6c8a315f14/libs/drivers/program_flash/boot_table.cpp#L18)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Is this supposed to be here?
</blockquote></details>

Yes - these are expected ID's of the flash device. 

---

*[libs/obc/hardware/hardware.cpp, line 76 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI2jSYkvZ6chaMc-uy:-KlJuX-2cljhEWq0sh8a:bz7thil) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/obc/hardware/hardware.cpp#L76)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

where this value came from?
</blockquote></details>

It's a base address for EBI-mapped flash device (BANK1) .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Review status: 50 of 58 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/base/Include/utils.h, line 318 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI3UuCS3LMyKVYbCf3:-KlK869O6jX2k6VP9S8Q:b-dnqgmt) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/base/Include/utils.h#L318)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It would be nice but union is messing with copy-ctor. I don't want to invest more time in it (at least now)
</blockquote></details>

Not as much as messing as you would have to provide your own constructors, destructor, assignment operators. Right now this type introduces unnecessary overhead of keeping/copying unused half of its state.

---

*[libs/drivers/program_flash/boot_table.cpp, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-Kke5dC2WOOM3LB5c6G3:-KlK8SZwTFpxlzpz_U0r:bg79n4y) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f3b90ce009126471c0c799d30e677d6c8a315f14/libs/drivers/program_flash/boot_table.cpp#L18)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Yes - these are expected ID's of the flash device. 
</blockquote></details>

I don't like the idea of hardcoding the devices ids for no obvious reason.

---

*[libs/obc/hardware/hardware.cpp, line 76 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI2jSYkvZ6chaMc-uy:-KlK78WNwoZdcSuPRZoK:b-pam95k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/obc/hardware/hardware.cpp#L76)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

It's a base address for EBI-mapped flash device (BANK1) .
</blockquote></details>

Isn't platform supposed to provide things like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Reviewed 1 of 4 files at r4.
Review status: 51 of 58 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by Novakov** [comment]
Review status: 51 of 58 files reviewed at latest revision, 3 unresolved discussions.

---

*[libs/base/Include/utils.h, line 318 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI3UuCS3LMyKVYbCf3:-KlKAp1MG4BRiCmjxbCj:b-4bglq4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/base/Include/utils.h#L318)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Not as much as messing as you would have to provide your own constructors, destructor, assignment operators. Right now this type introduces unnecessary overhead of keeping/copying unused half of its state.
</blockquote></details>

Let's just wait for `std::variant` ;)

---

*[libs/drivers/program_flash/boot_table.cpp, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-Kke5dC2WOOM3LB5c6G3:-KlK9QTYu7OUgOaCplxk:b70fqco) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/f3b90ce009126471c0c799d30e677d6c8a315f14/libs/drivers/program_flash/boot_table.cpp#L18)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

I don't like the idea of hardcoding the devices ids for no obvious reason.
</blockquote></details>

It is just for checking if the device is really there (useful for debugging)

---

*[libs/obc/hardware/hardware.cpp, line 76 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlI2jSYkvZ6chaMc-uy:-KlK9XqdFoGF086xw6OY:b-d3wwjs) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/234e71b3ba6352383f377dce8ea7aa0ce22675f6/libs/obc/hardware/hardware.cpp#L76)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

Isn't platform supposed to provide things like that?
</blockquote></details>

As you can see I moved it to `io_map`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Reviewed 4 of 7 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/drivers/program_flash/flash_driver.cpp, line 20 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlK9E9BNOBFxkCUQN9n:-KlK9E9BNOBFxkCUQN9o:b-pepn4w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b2f3df7b2e3203603e09b450ed125101dbc136a5/libs/drivers/program_flash/flash_driver.cpp#L20)):*
> ```cpp
>         System::GiveSemaphore(this->_sync);
> 
>         Lock lock(this->_sync, InfiniteTimeout);
> ```

As we do not use exceptions status of the lock has to be verified after construction.

---

*[libs/drivers/program_flash/flash_driver.cpp, line 29 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlK9KQ26wGXbp498Glg:-KlK9KQ26wGXbp498Glh:b-pepn4w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b2f3df7b2e3203603e09b450ed125101dbc136a5/libs/drivers/program_flash/flash_driver.cpp#L29)):*
> ```cpp
>     FlashStatus FlashDriver::EraseSector(std::size_t sectorOfffset)
>     {
>         Lock lock(this->_sync, InfiniteTimeout);
> ```

As we do not use exceptions status of the lock has to be verified after construction.

---

*[libs/drivers/program_flash/flash_driver.cpp, line 43 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlK9L6r0nyWk3lGTJZF:-KlK9L6r0nyWk3lGTJZG:b-pepn4w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b2f3df7b2e3203603e09b450ed125101dbc136a5/libs/drivers/program_flash/flash_driver.cpp#L43)):*
> ```cpp
>     FlashStatus FlashDriver::Program(std::size_t offset, std::uint8_t value)
>     {
>         Lock lock(this->_sync, InfiniteTimeout);
> ```

As we do not use exceptions status of the lock has to be verified after construction.

---

*[libs/drivers/program_flash/flash_driver.cpp, line 55 at r4](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152#-KlK9LaqcgUd_itiz3N5:-KlK9LaqcgUd_itiz3N6:b-pepn4w) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/b2f3df7b2e3203603e09b450ed125101dbc136a5/libs/drivers/program_flash/flash_driver.cpp#L55)):*
> ```cpp
>     FlashStatus FlashDriver::Program(std::size_t offset, gsl::span<const std::uint8_t> value)
>     {
>         Lock lock(this->_sync, InfiniteTimeout);
> ```

As we do not use exceptions status of the lock has to be verified after construction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Comment by zaq32** [comment]
Reviewed 1 of 55 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/152)*

**Pull request merged**
