### PR TITLE
Antenna procedure update

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/345)

### CODE REVIEW

**Comment by Novakov** [comment]
[Antenna - ignore deployment in progress flag](https://trello.com/c/sXaVgAAJ/293-antenna-ignore-deployment-in-progress-flag)

**Comment by zaq32** [comment]
Reviewed 12 of 21 files at r1, 1 of 2 files at r2.
Review status: 13 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Comment by zaq32** [comment]
Reviewed 1 of 21 files at r1.
Review status: 14 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/mission/antenna/antenna.cpp, line 41 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvlemIRprQ7ljDls_Ka:-KvlemIRprQ7ljDls_Kb:b4yeheh) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L41)):*
> ```cpp
>         {
>             /** @brief Power on controller */
>             static constexpr AntennaTask::StepDescriptor PowerOn = {AntennaTask::PowerOn, Channel, AntennaId::ANTENNA_AUTO_ID, 0s, 10s};
> ```

use value that is slightly less then 10s or it will always be effectively two mission iterations. This applies to all wait times

---

*[libs/mission/antenna/antenna.cpp, line 44 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvle8wxeUWBSY5XG75X:-Kvle8wxeUWBSY5XG75Y:b-z9vc8l) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L44)):*
> ```cpp
> 
>             /** @brief Reset controller */
>             static constexpr AntennaTask::StepDescriptor Reset = {AntennaTask::Reset, Channel, AntennaId::ANTENNA_AUTO_ID, 0s, 60s};
> ```

This is insane, resetting the controller does not take 60s. 

---

*[libs/mission/antenna/antenna.cpp, line 47 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvle9UOWxMPh-bTsQCJ:-Kvle9UOWxMPh-bTsQCK:bz9xja4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L47)):*
> ```cpp
> 
>             /** @brief Arm controller */
>             static constexpr AntennaTask::StepDescriptor Arm = {AntennaTask::Arm, Channel, AntennaId::ANTENNA_AUTO_ID, 0s, 60s};
> ```

This is insane, Arming deployment system does not take 60s. If it takes more then 60ms something is wrong.

---

*[libs/mission/antenna/antenna.cpp, line 55 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvldyAWD9F9hQfujr7W:-KvldyAWD9F9hQfujr7X:b-7jeq35) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L55)):*
> ```cpp
>             /** @brief Perform manual deployment */
>             template <AntennaId Antenna>
>             static constexpr AntennaTask::StepDescriptor ManualDeploy = {AntennaTask::Deploy, Channel, Antenna, 30s, 90s};
> ```

This is insane, why wait time is three times bigger than burn time?

---

*[libs/mission/antenna/antenna.cpp, line 64 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvlf1SGVVcPprilFH_Q:-Kvlf1SGVVcPprilFH_R:b-clgtjj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L64)):*
> ```cpp
> 
>             /** @brief Perform full sequence of auto deployment */
>             static constexpr auto FullSequenceAuto = std::make_tuple(PowerOn, Reset, Arm, AutoDeploy, Disarm, PowerOff);
> ```

If I am counting this right this single sequence takes at least 7m 10s to run.

---

*[libs/mission/antenna/antenna.cpp, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvlfDiAsBcFjX11ZZw9:-KvlfDiAsBcFjX11ZZwA:b-clgtjj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L68)):*
> ```cpp
>             /** @brief Perform full sequence of manual deployment on single antenna */
>             template <AntennaId Antenna>
>             static constexpr auto FullSequenceManual = std::make_tuple(PowerOn, Reset, Arm, ManualDeploy<Antenna>, Disarm, PowerOff);
> ```

If I am counting this right this single sequence takes at least 7m 10s to run.

---

*[libs/mission/antenna/antenna.cpp, line 68 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvlfRcHeuntAOv1gGL9:-KvlfRcHeuntAOv1gGLA:b8n7k4d) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L68)):*
> ```cpp
>             /** @brief Perform full sequence of manual deployment on single antenna */
>             template <AntennaId Antenna>
>             static constexpr auto FullSequenceManual = std::make_tuple(PowerOn, Reset, Arm, ManualDeploy<Antenna>, Disarm, PowerOff);
> ```

Powering off & on controller in the middle of the sequence effectively erases its state. Which effectively invalidates the purpose of collecting antenna telemetry

---

*[libs/mission/antenna/antenna.cpp, line 71 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvlfHvfkSlM3_pMvW8O:-KvlfHvfkSlM3_pMvW8P:b-1vexnz) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L71)):*
> ```cpp
>         };
> 
>         std::array<AntennaTask::StepDescriptor, 60> AntennaTask::Steps = Join( //
> ```

execution of the entire array will take over 70 minutes. Is that intended?

---

*[libs/mission/antenna/antenna.cpp, line 85 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvldivoHWVTkxs-bU5u:-KvldivoHWVTkxs-bU5v:b-t5ruxu) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L85)):*
> ```cpp
>         AntennaTask::AntennaTask(std::tuple<IAntennaDriver&, services::power::IPowerControl&> args)
>             : _powerControl(std::get<services::power::IPowerControl&>(args)), _antenna(std::get<IAntennaDriver&>(args)), _step(0),
>               _nextStepAt(0), _retryCounter(StepRetries), _controllerPoweredOn(false)
> ```

uninitialized: _sync

---

*[libs/mission/antenna/antenna.cpp, line 100 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvld9mxBn56Df4REPXz:-Kvld9mxBn56Df4REPY-:bvw93jc) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L100)):*
> ```cpp
>             auto This = reinterpret_cast<AntennaTask*>(param);
> 
>             if (state.Time < 40min)
> ```

use IsInitialSilentPeriodFinished procedure instead of manually checking time

---

*[libs/mission/antenna/antenna.cpp, line 122 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvlfsh-u_9hO1korrPA:-Kvlfsh-u_9hO1korrPB:bjoxd7k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L122)):*
>                 if (cfg.IsDeploymentDisabled())
>  
>                 {
>                     return false;
>                 }

consider:
```
return !cfg.IsDeploymentDisabled();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Comment by zaq32** [comment]
Reviewed 6 of 21 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Comment by Novakov** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[libs/mission/antenna/antenna.cpp, line 41 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvlemIRprQ7ljDls_Ka:-KvlnnKEN23jwUAOwkcR:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L41)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use value that is slightly less then 10s or it will always be effectively two mission iterations. This applies to all wait times
</blockquote></details>

Done.

---

*[libs/mission/antenna/antenna.cpp, line 85 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-KvldivoHWVTkxs-bU5u:-KvlkHc6jpk5OUYLAx5y:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L85)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

uninitialized: _sync
</blockquote></details>

Done.

---

*[libs/mission/antenna/antenna.cpp, line 100 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvld9mxBn56Df4REPXz:-KvlkXZ_OdSxIj9BdAaJ:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L100)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

use IsInitialSilentPeriodFinished procedure instead of manually checking time
</blockquote></details>

Done.

---

*[libs/mission/antenna/antenna.cpp, line 122 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345#-Kvlfsh-u_9hO1korrPA:-KvlkxoSPIJTVTT_tXWc:btd9g49) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1534ab702235a3f473d81eb5bcba09bc37474886/libs/mission/antenna/antenna.cpp#L122)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

>                 if (cfg.IsDeploymentDisabled())
>  
>                 {
>                     return false;
>                 }

consider:
```
return !cfg.IsDeploymentDisabled();
```
</blockquote></details>

I prefer explicit checks for all negative conditions, than just returning true. That way every condition is single statement (a bit easier for read).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r4.
Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Comment by zaq32** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/345)*

**Pull request merged**
