### PR TITLE
[platforms] Move FlightModel platform to EngModel, add platform for true FlightModel.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/198)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by begreeen** [comment]
*[platforms/FlightModel/Include/io_map.h, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-Ko8Ga73OMpaflCxhbPn:-Ko8Ga73OMpaflCxhbPo:b1x51sj) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23ca67413e8f66b226819fed4c1744988d595b2f/platforms/FlightModel/Include/io_map.h#L18)):*
> ```objc
> namespace io_map
> {
>     using SlaveSelectFlash1 = PinLocation<gpioPortA, 13>;
> ```

should be PB12 since PA13 and PB12 are swapped on OBC FM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by begreeen** [comment]
*[platforms/FlightModel/Include/io_map.h, line 27 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-Ko8FvxOfKrn_Kwf3oVt:-Ko8FvxOfKrn_Kwf3oVu:b-es7sad) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23ca67413e8f66b226819fed4c1744988d595b2f/platforms/FlightModel/Include/io_map.h#L27)):*
> ```objc
> 
>     using Led0 = PinLocation<gpioPortD, 1>;
>     using Led1 = PinLocation<gpioPortD, 2>;
> ```

do these leds exist on FM?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by Novakov** [comment]
Reviewed 80 of 80 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[platforms/mcu/EngModel/Include/mcu/io_map.h, line 18 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-KoWj1yROIHlVGNdfb2q:-KoWj1yROIHlVGNdfb2r:bfv98vx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d8d773af957c3fd6822ab1ca1ccdb363cc53dd70/platforms/mcu/EngModel/Include/mcu/io_map.h#L18)):*
> ```objc
> namespace io_map
> {
>     using VirtualPA13 = PinLocation<gpioPortA, 13>;
> ```

Remapping MCU pins to other pins is confusing - you can use `Piggyback42` (don't remember the exact number) instead 

---

*[platforms/payload/Mock/Include/payload/io_map.h, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-KoWdkAnnGit_v7dq-Yp:-KoWdkAolb6jtG6i50Ta:b-loijw4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d8d773af957c3fd6822ab1ca1ccdb363cc53dd70/platforms/payload/Mock/Include/payload/io_map.h#L28)):*
> ```objc
> /** @endcond */
> 
> #endif
> ```

Don't reinvent the names - we call it PLD DM, so name should be DM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by zaq32** [comment]
Review status: 52 of 59 files reviewed at latest revision, 4 unresolved discussions.

---

*[platforms/mcu/EngModel/Include/mcu/io_map.h, line 18 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-Ko8Ga73OMpaflCxhbPn:-KoXwMmH9F5een9FXVfr:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23ca67413e8f66b226819fed4c1744988d595b2f/platforms/mcu/EngModel/Include/mcu/io_map.h#L18)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

should be PB12 since PA13 and PB12 are swapped on OBC FM
</blockquote></details>

Done

---

*[platforms/mcu/EngModel/Include/mcu/io_map.h, line 27 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-Ko8FvxOfKrn_Kwf3oVt:-KoXwC9-xJjoLB1MrZyo:b-y13f70) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/23ca67413e8f66b226819fed4c1744988d595b2f/platforms/mcu/EngModel/Include/mcu/io_map.h#L27)):*
<details><summary><i>Previously, begreeen wrote…</i></summary><blockquote>

do these leds exist on FM?
</blockquote></details>

No but it easier to keep them instead of try to build platform specific functionality.

---

*[platforms/mcu/EngModel/Include/mcu/io_map.h, line 18 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-KoWj1yROIHlVGNdfb2q:-KoXw7tHxNq2KV9NlvnB:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d8d773af957c3fd6822ab1ca1ccdb363cc53dd70/platforms/mcu/EngModel/Include/mcu/io_map.h#L18)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Remapping MCU pins to other pins is confusing - you can use `Piggyback42` (don't remember the exact number) instead 
</blockquote></details>

Done

---

*[platforms/payload/DM/Include/payload/io_map.h, line 28 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198#-KoWdkAnnGit_v7dq-Yp:-KoXwAbvAbNALkU7iOeI:bb6un1j) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d8d773af957c3fd6822ab1ca1ccdb363cc53dd70/platforms/payload/DM/Include/payload/io_map.h#L28)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Don't reinvent the names - we call it PLD DM, so name should be DM
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by Novakov** [comment]
Reviewed 2 of 82 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Comment by Novakov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/198)*

**Pull request merged**
