### PR TITLE
Test commands

### PR DESCRIPTION
**Pull request by zaq32**
Terminal commands for testing comm & antenna hardware/drivers.

* New commands:
   * antenna_get_telemetry
   * antenna_reset [primary|backup]
   * comm_get_telemetry [transmitter|receiver]
   * comm_set_bitrate [1200|2400|4800|9600]
* Some integration tests for new commands
* Extended integration tests documentation

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/73)

### CODE REVIEW

**Comment by Novakov** [comment]
Reviewed 12 of 14 files at r1.
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/devices/antenna.py, line 109 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KaxKM68IleSSLteerSR:-KaxKM68IleSSLteerSS:btk9tg5) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f5cf53acc6c9245ebd8943e5f953676fdd00eb4/integration_tests/devices/antenna.py#L109)):*
> ```Python
>     def reset(self):
>         self.log.debug("Resetting antenna controller")
>         if(call(self.on_reset, True)):
> ```

No need for parentheses around condition

---

*[src/commands/commands.h, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KaxLLVXwizXb-HhwBqM:-KaxLLVXwizXb-HhwBqN:b-u3xm1o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f5cf53acc6c9245ebd8943e5f953676fdd00eb4/src/commands/commands.h#L34)):*
> ```objc
> void AntennaGetDeploymentStatus(std::uint16_t argc, char* argv[]);
> void AntennaGetTelemetry(uint16_t argc, char* argv[]);
> void AntennaReset(uint16_t argc, char* argv[]);
> ```

`std::uint16_t`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73)*

**Comment by zaq32** [comment]
Review status: 10 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration_tests/devices/antenna.py, line 109 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KaxKM68IleSSLteerSR:-KaxNhl7kicx5iquSsXT:bj7jlso) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f5cf53acc6c9245ebd8943e5f953676fdd00eb4/integration_tests/devices/antenna.py#L109)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

No need for parentheses around condition
</blockquote></details>

eh. c++ habbits....

---

*[src/commands/commands.h, line 34 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KaxLLVXwizXb-HhwBqM:-KaxNd8Hm3cFqE6JYGmV:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/3f5cf53acc6c9245ebd8943e5f953676fdd00eb4/src/commands/commands.h#L34)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

`std::uint16_t`
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73)*

**Comment by Novakov** [comment]
Reviewed 1 of 14 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/commands/antenna.cpp, line 188 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KbC23bznCaNSGiL8KkG:-KbC23bznCaNSGiL8KkH:b-zahdyn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d7716d1a4da0950e449616e0b43b3f575e72e15/src/commands/antenna.cpp#L188)):*
> ```cpp
>     else
>     {
>         Main.terminal.Printf("Unable to reset antenna. Status: '%d'", result);
> ```

`num(result)`

---

*[src/commands/comm.cpp, line 145 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KbC2CBxlE2QlNWCZSHu:-KbC2CBxlE2QlNWCZSHv:b-5j5eik) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d7716d1a4da0950e449616e0b43b3f575e72e15/src/commands/comm.cpp#L145)):*
> ```cpp
>             static_cast<int>(telemetry.AmplifierTemperature),
>             static_cast<int>(telemetry.RFForwardPower),
>             static_cast<int>(telemetry.TransmitterCurrentConsumption));
> ```

I prefer using `int<size>_t` types

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73)*

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/commands/antenna.cpp, line 188 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73#-KbC23bznCaNSGiL8KkG:-KbEOKOA3jX9rcEdF8rZ:b32w0x) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/0d7716d1a4da0950e449616e0b43b3f575e72e15/src/commands/antenna.cpp#L188)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

`num(result)`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/73)*

**Pull request merged**
