### PR TITLE
FM25W256 driver

### PR DESCRIPTION
**Pull request by Novakov**
Driver for FM25W256 FRAM

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/101)

### CODE REVIEW

**Comment by Novakov** [comment]
[[Driver] FRAM](https://trello.com/c/sgJoSh0z/127-driver-fram)

**Comment by zaq32** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/101)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/101)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/101)*

**Pull request merged**
