### PR TITLE
[telecommand][take_photo] Add delay parameter to take photo command.

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/268)

### CODE REVIEW

**Comment by zaq32** [comment]
[[TC] Add photo delay parameter](https://trello.com/c/VUWkKXdo/242-tc-add-photo-delay-parameter)

**Comment by Novakov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration_tests/tests/test_telecommands_photo.py, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/268#-KrqSy3xJAleD0JbYxTC:-KrqSy3xJAleD0JbYxTD:b-otujr6) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/95a687840cf66fd5e7be99f79fbacccdcd4c3995/integration_tests/tests/test_telecommands_photo.py#L31)):*
> ```Python
>         sail_opening = TestEvent()
> 
>         self.system.comm.put_frame(TakePhotoTelecommand(10, CameraLocation.Wing, PhotoResolution.p128, 30, 0, "photo.jpg"))
> ```

Use `timedelta` parameters, not raw numbers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/268)*

**Comment by zaq32** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/tests/test_telecommands_photo.py, line 31 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/268#-KrqSy3xJAleD0JbYxTC:-KrysQZbzKDl5aVsTJDh:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/57f6887a588156b70d9cf72695f5ab2d8fabc285/integration_tests/tests/test_telecommands_photo.py#L31)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Use `timedelta` parameters, not raw numbers
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/268)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/268)*

**Pull request merged**
