### PR TITLE
Photo service

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/245)

### CODE REVIEW

**Comment by Novakov** [comment]
[Photo taking task](https://trello.com/c/uPyjxGgl/217-photo-taking-task)

**Comment by zaq32** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[libs/base/Include/base/os.h, line 603 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFaiV2klfOrGoPvIRQ:-KrFaiV2klfOrGoPvIRR:b-iz5jct) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/base/Include/base/os.h#L603)):*
> ```objc
> template <typename Element, std::size_t Capacity> class Queue final
> {
>     static_assert(std::is_standard_layout<Element>::value, "Queue works only for standard layout types");
> ```

free rtoses queues are only compatible with pods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245)*

**Comment by zaq32** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[libs/photo/Include/photo/photo_service.hpp, line 60 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFb0cE7SafOln5PeeT:-KrFb0cE7SafOln5PeeU:b-x1m71o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L60)):*
> ```cpp
>         {
>           public:
>             DisableCamera() = default;
> ```

uninitialized field: _which

---

*[libs/photo/Include/photo/photo_service.hpp, line 89 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFb6-Vaj9W8-c49Yft:-KrFb6-Vaj9W8-c49Yfu:b-x1m71o) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L89)):*
> ```cpp
>         {
>           public:
>             EnableCamera() = default;
> ```

uninitialized field: _which

---

*[libs/photo/Include/photo/photo_service.hpp, line 118 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFb6qsrKNFhjTltVq2:-KrFb6qsrKNFhjTltVq3:b-y046eo) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L118)):*
> ```cpp
>         {
>           public:
>             TakePhoto() = default;
> ```

uninitialized fields: _which, _resolution

---

*[libs/photo/Include/photo/photo_service.hpp, line 161 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFbB9SHNmuCctjcO8f:-KrFbB9SHNmuCctjcO8g:b-1z5bkv) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L161)):*
> ```cpp
>         {
>           public:
>             DownloadPhoto() = default;
> ```

uninitialized fields: _which _bufferId

---

*[libs/photo/Include/photo/photo_service.hpp, line 204 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFbG0ktM9k48YZsx_d:-KrFbG0ktM9k48YZsx_e:b-ddkfac) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L204)):*
> ```cpp
>         {
>           public:
>             SavePhoto() = default;
> ```

default constructor is not sufficient for this type

---

*[libs/photo/Include/photo/photo_service.hpp, line 245 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFbKBDxsDZJ7YWAhPG:-KrFbKBDxsDZJ7YWAhPH:b-ku4ozn) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/photo/Include/photo/photo_service.hpp#L245)):*
> ```cpp
>         {
>           public:
>             Sleep() = default;
> ```

uninitialized field: _duration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245)*

**Comment by Novakov** [comment]
Review status: 24 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[libs/base/Include/base/os.h, line 603 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245#-KrFaiV2klfOrGoPvIRQ:-KrGFB8mgaAfhTPEUo9B:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/d87e1a40a9ed57e27199e663a7e045f6dd77f00d/libs/base/Include/base/os.h#L603)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

free rtoses queues are only compatible with pods
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/245)*

**Pull request merged**
