### PR TITLE
No response frames

### PR DESCRIPTION
**Pull request by Novakov**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/365)

### CODE REVIEW

**Comment by Novakov** [comment]
[Missing responses from telecommands](https://trello.com/c/KEwAYZp5/311-missing-responses-from-telecommands)

**Comment by zaq32** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/response_frames/comm.py, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/365#-KwpyD2OcxM9Y36FHev6:-KwpyD2OcxM9Y36FHev7:b3xrypq) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e04a073120982aa939f5563402bfbe886ef94ca9/integration_tests/response_frames/comm.py#L5)):*
> ```Python
> 
> @response_frame(0x22)
> class OperationSuccessFrame(ResponseFrame):
> ```

shouldn't this be BeaconErrorFrame?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/365)*

**Comment by Novakov** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration_tests/response_frames/comm.py, line 5 at r1](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/365#-KwpyD2OcxM9Y36FHev6:-Kwq-TuuEViQFGnFeN0M:b-89cf64) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/e04a073120982aa939f5563402bfbe886ef94ca9/integration_tests/response_frames/comm.py#L5)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

shouldn't this be BeaconErrorFrame?
</blockquote></details>

My copy-fu failed me today....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/365)*

**Comment by zaq32** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/365)*

**Pull request merged**
