### PR TITLE
Telemetry uptime

### PR DESCRIPTION
**Pull request by zaq32**
Extend telemetry with 22bit obc uptime in seconds

---
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/297)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Telemetry] OBC Uptime](https://trello.com/c/oRLBouDU/267-telemetry-obc-uptime)

**Comment by Novakov** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/297)*

**Comment by Novakov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/297)*

**Comment by Novakov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/297)*

**Pull request merged**
