### PR TITLE
[NCR #024] Fixed overflow in detumbling calculations

### PR DESCRIPTION
**Pull request by tom4r**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/362)

### CODE REVIEW

**Comment by tom4r** [comment]
[[NCR #024] Detumbling experiment works incorrectly](https://trello.com/c/mg1kaWNR/295-ncr-024-detumbling-experiment-works-incorrectly)

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/362)*

**Comment by zaq32** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/362)*

**Comment by zaq32** [comment]
Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/362)*

**Comment by tom4r** [comment]
Moved back to development as still there are some issues

**Comment by tom4r** [comment]
Issues fixed, can CR-ed again.

**Comment by Novakov** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/362)*

**Pull request merged**
