### PR TITLE
[TeleComm] Added Idle telecommand

### PR DESCRIPTION
**Pull request by kfazi**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/141)

### CODE REVIEW

**Comment by zaq32** [comment]
Reviewed 43 of 44 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 151 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTtsHMyuQ53jc5wKNW:-KjTtsHMyuQ53jc5wKNX:bmqad75) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/drivers/comm/Include/comm/CommDriver.hpp#L151)):*
> ```cpp
>      * @return Operation status, true in case of success, false otherwise.
>      */
>     bool SetTransmitterStateWhenIdle(IdleState requestedState);
> ```

missing specifier: override

---

*[libs/mission/comm/Include/mission/idle_state_controller.hpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTuL-UDuFg-nbYWXkN:-KjTuL-UDuFg-nbYWXkO:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/mission/comm/Include/mission/idle_state_controller.hpp#L15)):*
> ```cpp
>     struct IIdleStateController
>     {
>         virtual bool EnterTransmitterStateWhenIdle(std::chrono::milliseconds turnOffTime) = 0;
> ```

undocumented

---

*[libs/mission/comm/Include/mission/idle_state_controller.hpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTuMwWWcyB3sogqQsQ:-KjTuMwWWcyB3sogqQsR:b-kje888) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/mission/comm/Include/mission/idle_state_controller.hpp#L17)):*
> ```cpp
>         virtual bool EnterTransmitterStateWhenIdle(std::chrono::milliseconds turnOffTime) = 0;
> 
>         virtual bool LeaveTransmitterStateWhenIdle() = 0;
> ```

undocumented

---

*[libs/obc/communication/telecommands/comm.cpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTucisPsecb_uKbEdV:-KjTucisPsecb_uKbEdW:bxfuyvg) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/obc/communication/telecommands/comm.cpp#L37)):*
> ```cpp
>             auto disableTime = now + std::chrono::seconds(duration);
> 
>             const auto status = _idleStateController.EnterTransmitterStateWhenIdle(disableTime);
> ```

telecommands are executed in different task than mission therefore this function call should be synchronized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by kfazi** [comment]
Review status: 30 of 44 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[libs/drivers/comm/Include/comm/CommDriver.hpp, line 151 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTtsHMyuQ53jc5wKNW:-KjUYm_tT8WaR8emDXwx:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/drivers/comm/Include/comm/CommDriver.hpp#L151)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

missing specifier: override
</blockquote></details>

Done.

---

*[libs/mission/comm/Include/mission/idle_state_controller.hpp, line 15 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTuL-UDuFg-nbYWXkN:-KjUYp7IeauRf03T9dul:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/mission/comm/Include/mission/idle_state_controller.hpp#L15)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/mission/comm/Include/mission/idle_state_controller.hpp, line 17 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTuMwWWcyB3sogqQsQ:-KjUYq-f5AtGQ5XLOd3a:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/mission/comm/Include/mission/idle_state_controller.hpp#L17)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

undocumented
</blockquote></details>

Done.

---

*[libs/obc/communication/telecommands/comm.cpp, line 37 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141#-KjTucisPsecb_uKbEdV:-KjUYrbNhbYXivuh2y3V:b-896fix) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/59ab5fcea7453cd2dee67d55d8bddebf903a779d/libs/obc/communication/telecommands/comm.cpp#L37)):*
<details><summary><i>Previously, zaq32 (Łukasz Żak) wrote…</i></summary><blockquote>

telecommands are executed in different task than mission therefore this function call should be synchronized.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by zaq32** [comment]
Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by zaq32** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by zaq32** [comment]
Reviewed 9 of 9 files at r5, 7 of 9 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by Novakov** [comment]
Reviewed 1 of 44 files at r1, 1 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by zaq32** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/141)*

**Comment by Novakov** [comment]
[[TC] COMM - Komenda - włączenie nośnej na określony czas](https://trello.com/c/h2YTLGXh/124-tc-comm-komenda-w-aczenie-nosnej-na-okreslony-czas)

**Pull request merged**
