### PR TITLE
Add Sail Experiment

### PR DESCRIPTION
**Pull request by zaq32**
This change is [Reviewable](https://reviewable.io/reviews/pw-sat2/pwsat2obc/251)

### CODE REVIEW

**Comment by zaq32** [comment]
[[Experiment] SAIL](https://trello.com/c/xbXvfM9L/205-experiment-sail)

**Comment by Novakov** [comment]
Reviewed 35 of 46 files at r1, 1 of 1 files at r2.
Review status: 36 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[unit_tests/communication/CMakeLists.txt, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrUlfk5YCYwWE9OSeFT:-KrUlfk5YCYwWE9OSeFU:b-o8vu7k) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/unit_tests/communication/CMakeLists.txt#L38)):*
> ```CMake
>     obc_telecommands
>     boot_settings
>     experiments
> ```

Never not too much experiments ;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Comment by zaq32** [comment]
Review status: 24 of 47 files reviewed at latest revision, 1 unresolved discussion.

---

*[unit_tests/communication/CMakeLists.txt, line 38 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrUlfk5YCYwWE9OSeFT:-KrV4I5tz8P18V_sPo3J:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/unit_tests/communication/CMakeLists.txt#L38)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Never not too much experiments ;
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Comment by Novakov** [comment]
Reviewed 11 of 46 files at r1.
Review status: 33 of 47 files reviewed at latest revision, 4 unresolved discussions.

---

*[integration_tests/tests/test_experiment_sail.py, line 29 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrVAx8lRWC_nZg6PAAT:-KrVAx8lRWC_nZg6PAAU:bcjvaq9) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/integration_tests/tests/test_experiment_sail.py#L29)):*
> ```Python
>         self.assertEqual(frame.correlation_id, 10);
> 
>     def test_experiment_startup(self):
> ```

join `test_experiment_start` and `test_experiment_startup`  

---

*[libs/experiments/sail/sail.cpp, line 316 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrV8rOBP-v5GplR_t3Z:-KrV8rOBP-v5GplR_t3_:b-fykiq4) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e6d418cbf22af400de2ca6399aa44d2a7d3a27a/libs/experiments/sail/sail.cpp#L316)):*
> ```cpp
>         void SailExperiment::SavePhotos()
>         {
>             for (std::uint8_t index = 0; !this->_photoService.IsEmpty(index); ++index)
> ```

Do not abort after first empty buffer

---

*[unit_tests/others/photos/PhotoServiceTest.cpp, line 88 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrVAhvFAq05AEG_xgcM:-KrVAhvFAq05AEG_xgcN:b-62r3w8) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/unit_tests/others/photos/PhotoServiceTest.cpp#L88)):*
> ```cpp
>     }
> 
>     TEST_F(PhotoServiceTest, AllBuffersAreEmptBeyondLimit)
> ```

Empt**y**

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Comment by Novakov** [comment]
Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Comment by zaq32** [comment]
Review status: 44 of 48 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration_tests/tests/test_experiment_sail.py, line 29 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrVAx8lRWC_nZg6PAAT:-KrVMZIm_-4qNdU1UL9U:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/integration_tests/tests/test_experiment_sail.py#L29)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

join `test_experiment_start` and `test_experiment_startup`  
</blockquote></details>

Fixed

---

*[libs/experiments/sail/sail.cpp, line 316 at r3](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrV8rOBP-v5GplR_t3Z:-KrVM_owwFfUQmQwpijG:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/1e6d418cbf22af400de2ca6399aa44d2a7d3a27a/libs/experiments/sail/sail.cpp#L316)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Do not abort after first empty buffer
</blockquote></details>

Fixed

---

*[unit_tests/others/photos/PhotoServiceTest.cpp, line 88 at r2](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251#-KrVAhvFAq05AEG_xgcM:-KrVMbM8LexnKcXkPu_T:b-886gsx) ([raw file](https://github.com/pw-sat2/pwsat2obc/blob/72e8a06e9493bed2e608de128bdf6595c1769dc8/unit_tests/others/photos/PhotoServiceTest.cpp#L88)):*
<details><summary><i>Previously, Novakov (Maciej T. Nowak) wrote…</i></summary><blockquote>

Empt**y**
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Comment by Novakov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pw-sat2/pwsat2obc/251)*

**Pull request merged**
